import csv

def create_womens_swimming_dataset(filename="womens_swimming_dataset.csv"):
    """
    Creates a CSV file containing 30 women's swimmers, each with 40+ stats.
    Stats are approximations, intended for demonstration and for building
    a 'Women's Swimming Index Score' later.
    """

    # Define the header (41 columns total)
    headers = [
        "player_name",
        "country",
        "years_active",
        "main_stroke",
        "total_olympic_medals",
        "olympic_gold_medals",
        "olympic_silver_medals",
        "olympic_bronze_medals",
        "total_world_champ_medals",
        "world_champ_gold",
        "world_champ_silver",
        "world_champ_bronze",
        "world_record_count",
        "personal_best_50_free",
        "personal_best_100_free",
        "personal_best_200_free",
        "personal_best_400_free",
        "personal_best_800_free",
        "personal_best_1500_free",
        "personal_best_100_butterfly",
        "personal_best_200_butterfly",
        "personal_best_100_back",
        "personal_best_200_back",
        "personal_best_100_breast",
        "personal_best_200_breast",
        "personal_best_200_im",
        "personal_best_400_im",
        "doping_tests_passed",
        "doping_tests_failed",
        "total_meet_points",
        "fina_swimmer_of_year",
        "career_races_swum",
        "career_races_won",
        "career_win_percentage",
        "main_event_olympic_titles",
        "pan_pac_medals",
        "commonwealth_medals",
        "total_prize_money_million_usd",
        "retirement_year",
        "hall_of_fame_inducted"
    ]

    # List of 30 swimmers with their data. Each dict must have exactly 41 keys.
    players_data = [
        {
            "player_name": "Katie Ledecky",
            "country": "USA",
            "years_active": 10,
            "main_stroke": "Freestyle",
            "total_olympic_medals": 10,
            "olympic_gold_medals": 7,
            "olympic_silver_medals": 3,
            "olympic_bronze_medals": 0,
            "total_world_champ_medals": 22,
            "world_champ_gold": 19,
            "world_champ_silver": 3,
            "world_champ_bronze": 0,
            "world_record_count": 16,
            "personal_best_50_free": 24.9,
            "personal_best_100_free": 52.6,
            "personal_best_200_free": 1.53,
            "personal_best_400_free": 3.56,
            "personal_best_800_free": 8.04,
            "personal_best_1500_free": 15.20,
            "personal_best_100_butterfly": 57.3,
            "personal_best_200_butterfly": 2.05,
            "personal_best_100_back": 59.7,
            "personal_best_200_back": 2.07,
            "personal_best_100_breast": 1.08,
            "personal_best_200_breast": 2.24,
            "personal_best_200_im": 2.10,
            "personal_best_400_im": 4.28,
            "doping_tests_passed": 200,
            "doping_tests_failed": 0,
            "total_meet_points": 1500,
            "fina_swimmer_of_year": 6,
            "career_races_swum": 350,
            "career_races_won": 300,
            "career_win_percentage": 85.7,
            "main_event_olympic_titles": 3,
            "pan_pac_medals": 14,
            "commonwealth_medals": 0,
            "total_prize_money_million_usd": 2.5,
            "retirement_year": 0,
            "hall_of_fame_inducted": 0
        },
        {
            "player_name": "Sarah Sjostrom",
            "country": "Sweden",
            "years_active": 13,
            "main_stroke": "Freestyle/Butterfly",
            "total_olympic_medals": 4,
            "olympic_gold_medals": 1,
            "olympic_silver_medals": 2,
            "olympic_bronze_medals": 1,
            "total_world_champ_medals": 16,
            "world_champ_gold": 8,
            "world_champ_silver": 6,
            "world_champ_bronze": 2,
            "world_record_count": 9,
            "personal_best_50_free": 23.6,
            "personal_best_100_free": 51.7,
            "personal_best_200_free": 1.54,
            "personal_best_400_free": 4.01,
            "personal_best_800_free": 8.20,
            "personal_best_1500_free": 16.10,
            "personal_best_100_butterfly": 55.4,
            "personal_best_200_butterfly": 2.03,
            "personal_best_100_back": 58.7,
            "personal_best_200_back": 2.09,
            "personal_best_100_breast": 1.07,
            "personal_best_200_breast": 2.25,
            "personal_best_200_im": 2.08,
            "personal_best_400_im": 4.35,
            "doping_tests_passed": 180,
            "doping_tests_failed": 0,
            "total_meet_points": 1200,
            "fina_swimmer_of_year": 2,
            "career_races_swum": 270,
            "career_races_won": 145,
            "career_win_percentage": 53.7,
            "main_event_olympic_titles": 1,
            "pan_pac_medals": 0,
            "commonwealth_medals": 0,
            "total_prize_money_million_usd": 1.3,
            "retirement_year": 0,
            "hall_of_fame_inducted": 0
        },
        {
            "player_name": "Federica Pellegrini",
            "country": "Italy",
            "years_active": 17,
            "main_stroke": "Freestyle",
            "total_olympic_medals": 2,
            "olympic_gold_medals": 0,
            "olympic_silver_medals": 1,
            "olympic_bronze_medals": 1,
            "total_world_champ_medals": 11,
            "world_champ_gold": 7,
            "world_champ_silver": 2,
            "world_champ_bronze": 2,
            "world_record_count": 4,
            "personal_best_50_free": 24.8,
            "personal_best_100_free": 52.9,
            "personal_best_200_free": 1.52,
            "personal_best_400_free": 3.59,
            "personal_best_800_free": 8.24,
            "personal_best_1500_free": 16.20,
            "personal_best_100_butterfly": 58.0,
            "personal_best_200_butterfly": 2.06,
            "personal_best_100_back": 1.00,
            "personal_best_200_back": 2.10,
            "personal_best_100_breast": 1.10,
            "personal_best_200_breast": 2.28,
            "personal_best_200_im": 2.11,
            "personal_best_400_im": 4.39,
            "doping_tests_passed": 150,
            "doping_tests_failed": 0,
            "total_meet_points": 1100,
            "fina_swimmer_of_year": 1,
            "career_races_swum": 300,
            "career_races_won": 180,
            "career_win_percentage": 60.0,
            "main_event_olympic_titles": 0,
            "pan_pac_medals": 0,
            "commonwealth_medals": 0,
            "total_prize_money_million_usd": 1.8,
            "retirement_year": 2021,
            "hall_of_fame_inducted": 0
        },
        {
            "player_name": "Missy Franklin",
            "country": "USA",
            "years_active": 7,
            "main_stroke": "Backstroke/Freestyle",
            "total_olympic_medals": 6,
            "olympic_gold_medals": 5,
            "olympic_silver_medals": 0,
            "olympic_bronze_medals": 1,
            "total_world_champ_medals": 11,
            "world_champ_gold": 9,
            "world_champ_silver": 2,
            "world_champ_bronze": 0,
            "world_record_count": 3,
            "personal_best_50_free": 25.2,
            "personal_best_100_free": 52.9,
            "personal_best_200_free": 1.54,
            "personal_best_400_free": 4.03,
            "personal_best_800_free": 8.15,
            "personal_best_1500_free": 16.30,
            "personal_best_100_butterfly": 57.6,
            "personal_best_200_butterfly": 2.07,
            "personal_best_100_back": 58.3,
            "personal_best_200_back": 2.04,
            "personal_best_100_breast": 1.08,
            "personal_best_200_breast": 2.26,
            "personal_best_200_im": 2.08,
            "personal_best_400_im": 4.34,
            "doping_tests_passed": 100,
            "doping_tests_failed": 0,
            "total_meet_points": 900,
            "fina_swimmer_of_year": 1,
            "career_races_swum": 180,
            "career_races_won": 120,
            "career_win_percentage": 66.7,
            "main_event_olympic_titles": 2,
            "pan_pac_medals": 6,
            "commonwealth_medals": 0,
            "total_prize_money_million_usd": 1.2,
            "retirement_year": 2018,
            "hall_of_fame_inducted": 0
        },
        {
            "player_name": "Katinka Hosszu",
            "country": "Hungary",
            "years_active": 14,
            "main_stroke": "Medley/Back/Fly",
            "total_olympic_medals": 3,
            "olympic_gold_medals": 3,
            "olympic_silver_medals": 0,
            "olympic_bronze_medals": 0,
            "total_world_champ_medals": 15,
            "world_champ_gold": 9,
            "world_champ_silver": 3,
            "world_champ_bronze": 3,
            "world_record_count": 11,
            "personal_best_50_free": 25.1,
            "personal_best_100_free": 53.1,
            "personal_best_200_free": 1.54,
            "personal_best_400_free": 4.02,
            "personal_best_800_free": 8.16,
            "personal_best_1500_free": 16.09,
            "personal_best_100_butterfly": 56.9,
            "personal_best_200_butterfly": 2.05,
            "personal_best_100_back": 58.5,
            "personal_best_200_back": 2.03,
            "personal_best_100_breast": 1.06,
            "personal_best_200_breast": 2.23,
            "personal_best_200_im": 2.06,
            "personal_best_400_im": 4.25,
            "doping_tests_passed": 180,
            "doping_tests_failed": 0,
            "total_meet_points": 1400,
            "fina_swimmer_of_year": 3,
            "career_races_swum": 320,
            "career_races_won": 210,
            "career_win_percentage": 65.6,
            "main_event_olympic_titles": 2,
            "pan_pac_medals": 0,
            "commonwealth_medals": 0,
            "total_prize_money_million_usd": 2.4,
            "retirement_year": 0,
            "hall_of_fame_inducted": 0
        },
        {
            "player_name": "Ragnhild Hveger",
            "country": "Denmark",
            "years_active": 12,
            "main_stroke": "Freestyle",
            "total_olympic_medals": 1,
            "olympic_gold_medals": 0,
            "olympic_silver_medals": 1,
            "olympic_bronze_medals": 0,
            "total_world_champ_medals": 0,
            "world_champ_gold": 0,
            "world_champ_silver": 0,
            "world_champ_bronze": 0,
            "world_record_count": 42,
            "personal_best_50_free": 27.0,
            "personal_best_100_free": 59.8,
            "personal_best_200_free": 2.10,
            "personal_best_400_free": 4.40,
            "personal_best_800_free": 9.40,
            "personal_best_1500_free": 19.20,
            "personal_best_100_butterfly": 0.0,
            "personal_best_200_butterfly": 0.0,
            "personal_best_100_back": 1.10,
            "personal_best_200_back": 2.25,
            "personal_best_100_breast": 1.20,
            "personal_best_200_breast": 2.50,
            "personal_best_200_im": 0.0,
            "personal_best_400_im": 0.0,
            "doping_tests_passed": 0,
            "doping_tests_failed": 0,
            "total_meet_points": 400,
            "fina_swimmer_of_year": 0,
            "career_races_swum": 80,
            "career_races_won": 60,
            "career_win_percentage": 75.0,
            "main_event_olympic_titles": 0,
            "pan_pac_medals": 0,
            "commonwealth_medals": 0,
            "total_prize_money_million_usd": 0.0,
            "retirement_year": 1945,
            "hall_of_fame_inducted": 1
        },
        {
            "player_name": "Shane Gould",
            "country": "Australia",
            "years_active": 3,
            "main_stroke": "Freestyle",
            "total_olympic_medals": 5,
            "olympic_gold_medals": 3,
            "olympic_silver_medals": 1,
            "olympic_bronze_medals": 1,
            "total_world_champ_medals": 0,
            "world_champ_gold": 0,
            "world_champ_silver": 0,
            "world_champ_bronze": 0,
            "world_record_count": 11,
            "personal_best_50_free": 26.5,
            "personal_best_100_free": 57.3,
            "personal_best_200_free": 2.03,
            "personal_best_400_free": 4.19,
            "personal_best_800_free": 8.52,
            "personal_best_1500_free": 0.0,
            "personal_best_100_butterfly": 1.05,
            "personal_best_200_butterfly": 2.16,
            "personal_best_100_back": 1.07,
            "personal_best_200_back": 2.24,
            "personal_best_100_breast": 1.20,
            "personal_best_200_breast": 2.45,
            "personal_best_200_im": 2.24,
            "personal_best_400_im": 0.0,
            "doping_tests_passed": 10,
            "doping_tests_failed": 0,
            "total_meet_points": 300,
            "fina_swimmer_of_year": 0,
            "career_races_swum": 40,
            "career_races_won": 30,
            "career_win_percentage": 75.0,
            "main_event_olympic_titles": 2,
            "pan_pac_medals": 0,
            "commonwealth_medals": 2,
            "total_prize_money_million_usd": 0.0,
            "retirement_year": 1973,
            "hall_of_fame_inducted": 1
        },
        {
            "player_name": "Dawn Fraser",
            "country": "Australia",
            "years_active": 8,
            "main_stroke": "Freestyle",
            "total_olympic_medals": 6,
            "olympic_gold_medals": 4,
            "olympic_silver_medals": 2,
            "olympic_bronze_medals": 0,
            "total_world_champ_medals": 0,
            "world_champ_gold": 0,
            "world_champ_silver": 0,
            "world_champ_bronze": 0,
            "world_record_count": 27,
            "personal_best_50_free": 27.2,
            "personal_best_100_free": 58.9,
            "personal_best_200_free": 2.06,
            "personal_best_400_free": 4.30,
            "personal_best_800_free": 9.20,
            "personal_best_1500_free": 0.0,
            "personal_best_100_butterfly": 0.0,
            "personal_best_200_butterfly": 0.0,
            "personal_best_100_back": 1.10,
            "personal_best_200_back": 2.20,
            "personal_best_100_breast": 1.22,
            "personal_best_200_breast": 2.50,
            "personal_best_200_im": 0.0,
            "personal_best_400_im": 0.0,
            "doping_tests_passed": 0,
            "doping_tests_failed": 0,
            "total_meet_points": 350,
            "fina_swimmer_of_year": 0,
            "career_races_swum": 70,
            "career_races_won": 60,
            "career_win_percentage": 85.7,
            "main_event_olympic_titles": 3,
            "pan_pac_medals": 0,
            "commonwealth_medals": 4,
            "total_prize_money_million_usd": 0.0,
            "retirement_year": 1964,
            "hall_of_fame_inducted": 1
        },
        {
            "player_name": "Kristin Otto",
            "country": "East Germany",
            "years_active": 5,
            "main_stroke": "Freestyle/Backstroke",
            "total_olympic_medals": 6,
            "olympic_gold_medals": 6,
            "olympic_silver_medals": 0,
            "olympic_bronze_medals": 0,
            "total_world_champ_medals": 7,
            "world_champ_gold": 2,
            "world_champ_silver": 3,
            "world_champ_bronze": 2,
            "world_record_count": 5,
            "personal_best_50_free": 25.5,
            "personal_best_100_free": 54.7,
            "personal_best_200_free": 1.58,
            "personal_best_400_free": 4.10,
            "personal_best_800_free": 0.0,
            "personal_best_1500_free": 0.0,
            "personal_best_100_butterfly": 58.9,
            "personal_best_200_butterfly": 2.10,
            "personal_best_100_back": 59.6,
            "personal_best_200_back": 2.08,
            "personal_best_100_breast": 1.10,
            "personal_best_200_breast": 2.30,
            "personal_best_200_im": 2.12,
            "personal_best_400_im": 0.0,
            "doping_tests_passed": 15,
            "doping_tests_failed": 0, 
            "total_meet_points": 400,
            "fina_swimmer_of_year": 0,
            "career_races_swum": 50,
            "career_races_won": 40,
            "career_win_percentage": 80.0,
            "main_event_olympic_titles": 2,
            "pan_pac_medals": 0,
            "commonwealth_medals": 0,
            "total_prize_money_million_usd": 0.0,
            "retirement_year": 1989,
            "hall_of_fame_inducted": 1
        },
        {
            "player_name": "Rebecca Adlington",
            "country": "Great Britain",
            "years_active": 6,
            "main_stroke": "Freestyle",
            "total_olympic_medals": 4,
            "olympic_gold_medals": 2,
            "olympic_silver_medals": 0,
            "olympic_bronze_medals": 2,
            "total_world_champ_medals": 3,
            "world_champ_gold": 0,
            "world_champ_silver": 2,
            "world_champ_bronze": 1,
            "world_record_count": 1,
            "personal_best_50_free": 26.9,
            "personal_best_100_free": 55.2,
            "personal_best_200_free": 1.56,
            "personal_best_400_free": 4.02,
            "personal_best_800_free": 8.14,
            "personal_best_1500_free": 15.38,
            "personal_best_100_butterfly": 0.0,
            "personal_best_200_butterfly": 0.0,
            "personal_best_100_back": 1.05,
            "personal_best_200_back": 2.19,
            "personal_best_100_breast": 1.12,
            "personal_best_200_breast": 2.30,
            "personal_best_200_im": 2.15,
            "personal_best_400_im": 4.35,
            "doping_tests_passed": 50,
            "doping_tests_failed": 0,
            "total_meet_points": 320,
            "fina_swimmer_of_year": 0,
            "career_races_swum": 90,
            "career_races_won": 46,
            "career_win_percentage": 51.1,
            "main_event_olympic_titles": 2,
            "pan_pac_medals": 0,
            "commonwealth_medals": 2,
            "total_prize_money_million_usd": 0.8,
            "retirement_year": 2013,
            "hall_of_fame_inducted": 0
        },
        {
            "player_name": "Penny Oleksiak",
            "country": "Canada",
            "years_active": 7,
            "main_stroke": "Freestyle/Butterfly",
            "total_olympic_medals": 7,
            "olympic_gold_medals": 1,
            "olympic_silver_medals": 3,
            "olympic_bronze_medals": 3,
            "total_world_champ_medals": 6,
            "world_champ_gold": 0,
            "world_champ_silver": 4,
            "world_champ_bronze": 2,
            "world_record_count": 0,
            "personal_best_50_free": 24.5,
            "personal_best_100_free": 52.7,
            "personal_best_200_free": 1.56,
            "personal_best_400_free": 4.07,
            "personal_best_800_free": 8.25,
            "personal_best_1500_free": 16.33,
            "personal_best_100_butterfly": 56.4,
            "personal_best_200_butterfly": 2.08,
            "personal_best_100_back": 59.3,
            "personal_best_200_back": 2.10,
            "personal_best_100_breast": 1.08,
            "personal_best_200_breast": 2.28,
            "personal_best_200_im": 2.13,
            "personal_best_400_im": 4.38,
            "doping_tests_passed": 40,
            "doping_tests_failed": 0,
            "total_meet_points": 500,
            "fina_swimmer_of_year": 0,
            "career_races_swum": 110,
            "career_races_won": 35,
            "career_win_percentage": 31.8,
            "main_event_olympic_titles": 1,
            "pan_pac_medals": 4,
            "commonwealth_medals": 3,
            "total_prize_money_million_usd": 0.5,
            "retirement_year": 0,
            "hall_of_fame_inducted": 0
        },
        # ----- Additional swimmers 12 to 30, each with 41 fields -----
        {
            "player_name": "Amy Van Dyken",
            "country": "USA",
            "years_active": 8,
            "main_stroke": "Freestyle",
            "total_olympic_medals": 6,
            "olympic_gold_medals": 6,
            "olympic_silver_medals": 0,
            "olympic_bronze_medals": 0,
            "total_world_champ_medals": 4,
            "world_champ_gold": 2,
            "world_champ_silver": 2,
            "world_champ_bronze": 0,
            "world_record_count": 3,
            "personal_best_50_free": 24.7,
            "personal_best_100_free": 54.5,
            "personal_best_200_free": 2.00,
            "personal_best_400_free": 4.13,
            "personal_best_800_free": 0.0,
            "personal_best_1500_free": 0.0,
            "personal_best_100_butterfly": 58.2,
            "personal_best_200_butterfly": 0.0,
            "personal_best_100_back": 1.01,
            "personal_best_200_back": 2.14,
            "personal_best_100_breast": 1.11,
            "personal_best_200_breast": 2.33,
            "personal_best_200_im": 2.17,
            "personal_best_400_im": 0.0,
            "doping_tests_passed": 40,
            "doping_tests_failed": 0,
            "total_meet_points": 250,
            "fina_swimmer_of_year": 0,
            "career_races_swum": 70,
            "career_races_won": 35,
            "career_win_percentage": 50.0,
            "main_event_olympic_titles": 2,
            "pan_pac_medals": 3,
            "commonwealth_medals": 0,
            "total_prize_money_million_usd": 0.5,
            "retirement_year": 2000,
            "hall_of_fame_inducted": 1
        },
        {
            "player_name": "Summer Sanders",
            "country": "USA",
            "years_active": 5,
            "main_stroke": "Butterfly/IM",
            "total_olympic_medals": 4,
            "olympic_gold_medals": 2,
            "olympic_silver_medals": 1,
            "olympic_bronze_medals": 1,
            "total_world_champ_medals": 5,
            "world_champ_gold": 3,
            "world_champ_silver": 2,
            "world_champ_bronze": 0,
            "world_record_count": 1,
            "personal_best_50_free": 25.8,
            "personal_best_100_free": 55.8,
            "personal_best_200_free": 1.58,
            "personal_best_400_free": 4.12,
            "personal_best_800_free": 8.30,
            "personal_best_1500_free": 16.40,
            "personal_best_100_butterfly": 57.9,
            "personal_best_200_butterfly": 2.07,
            "personal_best_100_back": 1.03,
            "personal_best_200_back": 2.12,
            "personal_best_100_breast": 1.12,
            "personal_best_200_breast": 2.35,
            "personal_best_200_im": 2.10,
            "personal_best_400_im": 4.36,
            "doping_tests_passed": 25,
            "doping_tests_failed": 0,
            "total_meet_points": 240,
            "fina_swimmer_of_year": 0,
            "career_races_swum": 60,
            "career_races_won": 28,
            "career_win_percentage": 46.7,
            "main_event_olympic_titles": 1,
            "pan_pac_medals": 3,
            "commonwealth_medals": 0,
            "total_prize_money_million_usd": 0.2,
            "retirement_year": 1994,
            "hall_of_fame_inducted": 1
        },
        {
            "player_name": "Jenny Thompson",
            "country": "USA",
            "years_active": 10,
            "main_stroke": "Freestyle/Butterfly",
            "total_olympic_medals": 12,
            "olympic_gold_medals": 8,
            "olympic_silver_medals": 3,
            "olympic_bronze_medals": 1,
            "total_world_champ_medals": 15,
            "world_champ_gold": 10,
            "world_champ_silver": 4,
            "world_champ_bronze": 1,
            "world_record_count": 6,
            "personal_best_50_free": 24.8,
            "personal_best_100_free": 54.0,
            "personal_best_200_free": 1.58,
            "personal_best_400_free": 4.09,
            "personal_best_800_free": 8.30,
            "personal_best_1500_free": 0.0,
            "personal_best_100_butterfly": 57.0,
            "personal_best_200_butterfly": 2.09,
            "personal_best_100_back": 1.01,
            "personal_best_200_back": 2.14,
            "personal_best_100_breast": 1.10,
            "personal_best_200_breast": 2.32,
            "personal_best_200_im": 2.15,
            "personal_best_400_im": 0.0,
            "doping_tests_passed": 60,
            "doping_tests_failed": 0,
            "total_meet_points": 420,
            "fina_swimmer_of_year": 0,
            "career_races_swum": 100,
            "career_races_won": 55,
            "career_win_percentage": 55.0,
            "main_event_olympic_titles": 3,
            "pan_pac_medals": 5,
            "commonwealth_medals": 0,
            "total_prize_money_million_usd": 0.3,
            "retirement_year": 2004,
            "hall_of_fame_inducted": 1
        },
        {
            "player_name": "Natalie Coughlin",
            "country": "USA",
            "years_active": 12,
            "main_stroke": "Backstroke/Freestyle",
            "total_olympic_medals": 12,
            "olympic_gold_medals": 3,
            "olympic_silver_medals": 4,
            "olympic_bronze_medals": 5,
            "total_world_champ_medals": 19,
            "world_champ_gold": 8,
            "world_champ_silver": 7,
            "world_champ_bronze": 4,
            "world_record_count": 5,
            "personal_best_50_free": 24.9,
            "personal_best_100_free": 53.8,
            "personal_best_200_free": 1.57,
            "personal_best_400_free": 4.08,
            "personal_best_800_free": 8.22,
            "personal_best_1500_free": 16.20,
            "personal_best_100_butterfly": 57.3,
            "personal_best_200_butterfly": 2.08,
            "personal_best_100_back": 58.9,
            "personal_best_200_back": 2.03,
            "personal_best_100_breast": 1.09,
            "personal_best_200_breast": 2.29,
            "personal_best_200_im": 2.10,
            "personal_best_400_im": 4.37,
            "doping_tests_passed": 80,
            "doping_tests_failed": 0,
            "total_meet_points": 600,
            "fina_swimmer_of_year": 1,
            "career_races_swum": 160,
            "career_races_won": 90,
            "career_win_percentage": 56.2,
            "main_event_olympic_titles": 2,
            "pan_pac_medals": 7,
            "commonwealth_medals": 0,
            "total_prize_money_million_usd": 1.0,
            "retirement_year": 2016,
            "hall_of_fame_inducted": 1
        },
        {
            "player_name": "Dara Torres",
            "country": "USA",
            "years_active": 24,
            "main_stroke": "Freestyle",
            "total_olympic_medals": 12,
            "olympic_gold_medals": 4,
            "olympic_silver_medals": 4,
            "olympic_bronze_medals": 4,
            "total_world_champ_medals": 8,
            "world_champ_gold": 4,
            "world_champ_silver": 3,
            "world_champ_bronze": 1,
            "world_record_count": 3,
            "personal_best_50_free": 24.7,
            "personal_best_100_free": 53.5,
            "personal_best_200_free": 1.58,
            "personal_best_400_free": 4.12,
            "personal_best_800_free": 8.28,
            "personal_best_1500_free": 16.50,
            "personal_best_100_butterfly": 58.0,
            "personal_best_200_butterfly": 2.10,
            "personal_best_100_back": 1.01,
            "personal_best_200_back": 2.15,
            "personal_best_100_breast": 1.12,
            "personal_best_200_breast": 2.33,
            "personal_best_200_im": 2.18,
            "personal_best_400_im": 0.0,
            "doping_tests_passed": 100,
            "doping_tests_failed": 0,
            "total_meet_points": 570,
            "fina_swimmer_of_year": 0,
            "career_races_swum": 140,
            "career_races_won": 60,
            "career_win_percentage": 42.9,
            "main_event_olympic_titles": 2,
            "pan_pac_medals": 4,
            "commonwealth_medals": 0,
            "total_prize_money_million_usd": 1.5,
            "retirement_year": 2012,
            "hall_of_fame_inducted": 1
        },
        {
            "player_name": "Janet Evans",
            "country": "USA",
            "years_active": 9,
            "main_stroke": "Freestyle",
            "total_olympic_medals": 4,
            "olympic_gold_medals": 4,
            "olympic_silver_medals": 0,
            "olympic_bronze_medals": 0,
            "total_world_champ_medals": 5,
            "world_champ_gold": 3,
            "world_champ_silver": 2,
            "world_champ_bronze": 0,
            "world_record_count": 7,
            "personal_best_50_free": 27.8,
            "personal_best_100_free": 58.5,
            "personal_best_200_free": 1.58,
            "personal_best_400_free": 4.03,
            "personal_best_800_free": 8.16,
            "personal_best_1500_free": 15.52,
            "personal_best_100_butterfly": 0.0,
            "personal_best_200_butterfly": 2.15,
            "personal_best_100_back": 1.05,
            "personal_best_200_back": 2.15,
            "personal_best_100_breast": 1.15,
            "personal_best_200_breast": 2.38,
            "personal_best_200_im": 2.20,
            "personal_best_400_im": 4.45,
            "doping_tests_passed": 20,
            "doping_tests_failed": 0,
            "total_meet_points": 320,
            "fina_swimmer_of_year": 0,
            "career_races_swum": 80,
            "career_races_won": 50,
            "career_win_percentage": 62.5,
            "main_event_olympic_titles": 3,
            "pan_pac_medals": 6,
            "commonwealth_medals": 0,
            "total_prize_money_million_usd": 0.2,
            "retirement_year": 1996,
            "hall_of_fame_inducted": 1
        },
        {
            "player_name": "Yuliya Yefimova",
            "country": "Russia",
            "years_active": 12,
            "main_stroke": "Breaststroke",
            "total_olympic_medals": 3,
            "olympic_gold_medals": 0,
            "olympic_silver_medals": 2,
            "olympic_bronze_medals": 1,
            "total_world_champ_medals": 9,
            "world_champ_gold": 4,
            "world_champ_silver": 4,
            "world_champ_bronze": 1,
            "world_record_count": 2,
            "personal_best_50_free": 25.9,
            "personal_best_100_free": 56.5,
            "personal_best_200_free": 2.02,
            "personal_best_400_free": 4.10,
            "personal_best_800_free": 8.40,
            "personal_best_1500_free": 0.0,
            "personal_best_100_butterfly": 58.5,
            "personal_best_200_butterfly": 2.09,
            "personal_best_100_back": 1.02,
            "personal_best_200_back": 2.14,
            "personal_best_100_breast": 1.04,
            "personal_best_200_breast": 2.19,
            "personal_best_200_im": 2.12,
            "personal_best_400_im": 4.39,
            "doping_tests_passed": 80,
            "doping_tests_failed": 1,  # doping controversy
            "total_meet_points": 500,
            "fina_swimmer_of_year": 0,
            "career_races_swum": 140,
            "career_races_won": 70,
            "career_win_percentage": 50.0,
            "main_event_olympic_titles": 0,
            "pan_pac_medals": 0,
            "commonwealth_medals": 0,
            "total_prize_money_million_usd": 1.1,
            "retirement_year": 0,
            "hall_of_fame_inducted": 0
        },
        {
            "player_name": "Lilly King",
            "country": "USA",
            "years_active": 8,
            "main_stroke": "Breaststroke",
            "total_olympic_medals": 4,
            "olympic_gold_medals": 3,
            "olympic_silver_medals": 0,
            "olympic_bronze_medals": 1,
            "total_world_champ_medals": 10,
            "world_champ_gold": 8,
            "world_champ_silver": 2,
            "world_champ_bronze": 0,
            "world_record_count": 4,
            "personal_best_50_free": 25.6,
            "personal_best_100_free": 55.0,
            "personal_best_200_free": 1.58,
            "personal_best_400_free": 4.15,
            "personal_best_800_free": 0.0,
            "personal_best_1500_free": 0.0,
            "personal_best_100_butterfly": 58.4,
            "personal_best_200_butterfly": 2.11,
            "personal_best_100_back": 1.01,
            "personal_best_200_back": 2.16,
            "personal_best_100_breast": 1.04,
            "personal_best_200_breast": 2.19,
            "personal_best_200_im": 2.15,
            "personal_best_400_im": 4.38,
            "doping_tests_passed": 90,
            "doping_tests_failed": 0,
            "total_meet_points": 650,
            "fina_swimmer_of_year": 1,
            "career_races_swum": 130,
            "career_races_won": 72,
            "career_win_percentage": 55.4,
            "main_event_olympic_titles": 2,
            "pan_pac_medals": 3,
            "commonwealth_medals": 0,
            "total_prize_money_million_usd": 1.0,
            "retirement_year": 0,
            "hall_of_fame_inducted": 0
        },
        {
            "player_name": "Ariarne Titmus",
            "country": "Australia",
            "years_active": 6,
            "main_stroke": "Freestyle",
            "total_olympic_medals": 3,
            "olympic_gold_medals": 2,
            "olympic_silver_medals": 1,
            "olympic_bronze_medals": 0,
            "total_world_champ_medals": 6,
            "world_champ_gold": 4,
            "world_champ_silver": 2,
            "world_champ_bronze": 0,
            "world_record_count": 1,
            "personal_best_50_free": 24.7,
            "personal_best_100_free": 52.9,
            "personal_best_200_free": 1.53,
            "personal_best_400_free": 3.56,
            "personal_best_800_free": 8.13,
            "personal_best_1500_free": 15.50,
            "personal_best_100_butterfly": 58.0,
            "personal_best_200_butterfly": 2.10,
            "personal_best_100_back": 1.00,
            "personal_best_200_back": 2.11,
            "personal_best_100_breast": 1.12,
            "personal_best_200_breast": 2.30,
            "personal_best_200_im": 2.15,
            "personal_best_400_im": 4.38,
            "doping_tests_passed": 50,
            "doping_tests_failed": 0,
            "total_meet_points": 700,
            "fina_swimmer_of_year": 1,
            "career_races_swum": 120,
            "career_races_won": 75,
            "career_win_percentage": 62.5,
            "main_event_olympic_titles": 1,  # 400 free
            "pan_pac_medals": 4,
            "commonwealth_medals": 4,
            "total_prize_money_million_usd": 0.8,
            "retirement_year": 0,
            "hall_of_fame_inducted": 0
        },
        {
            "player_name": "Mireia Belmonte",
            "country": "Spain",
            "years_active": 12,
            "main_stroke": "Freestyle/Butterfly/IM",
            "total_olympic_medals": 4,
            "olympic_gold_medals": 1,
            "olympic_silver_medals": 2,
            "olympic_bronze_medals": 1,
            "total_world_champ_medals": 10,
            "world_champ_gold": 2,
            "world_champ_silver": 4,
            "world_champ_bronze": 4,
            "world_record_count": 3,
            "personal_best_50_free": 25.5,
            "personal_best_100_free": 54.2,
            "personal_best_200_free": 1.55,
            "personal_best_400_free": 4.02,
            "personal_best_800_free": 8.11,
            "personal_best_1500_free": 15.50,
            "personal_best_100_butterfly": 56.8,
            "personal_best_200_butterfly": 2.04,
            "personal_best_100_back": 1.00,
            "personal_best_200_back": 2.09,
            "personal_best_100_breast": 1.08,
            "personal_best_200_breast": 2.22,
            "personal_best_200_im": 2.06,
            "personal_best_400_im": 4.25,
            "doping_tests_passed": 70,
            "doping_tests_failed": 0,
            "total_meet_points": 820,
            "fina_swimmer_of_year": 0,
            "career_races_swum": 170,
            "career_races_won": 95,
            "career_win_percentage": 55.9,
            "main_event_olympic_titles": 1,  # 200 fly
            "pan_pac_medals": 0,
            "commonwealth_medals": 0,
            "total_prize_money_million_usd": 0.7,
            "retirement_year": 0,
            "hall_of_fame_inducted": 0
        },
        {
            "player_name": "Ye Shiwen",
            "country": "China",
            "years_active": 8,
            "main_stroke": "Medley",
            "total_olympic_medals": 2,
            "olympic_gold_medals": 2,
            "olympic_silver_medals": 0,
            "olympic_bronze_medals": 0,
            "total_world_champ_medals": 5,
            "world_champ_gold": 2,
            "world_champ_silver": 2,
            "world_champ_bronze": 1,
            "world_record_count": 1,
            "personal_best_50_free": 26.0,
            "personal_best_100_free": 55.5,
            "personal_best_200_free": 1.57,
            "personal_best_400_free": 4.08,
            "personal_best_800_free": 8.25,
            "personal_best_1500_free": 0.0,
            "personal_best_100_butterfly": 59.0,
            "personal_best_200_butterfly": 2.08,
            "personal_best_100_back": 1.00,
            "personal_best_200_back": 2.07,
            "personal_best_100_breast": 1.07,
            "personal_best_200_breast": 2.22,
            "personal_best_200_im": 2.07,
            "personal_best_400_im": 4.28,
            "doping_tests_passed": 60,
            "doping_tests_failed": 0,
            "total_meet_points": 500,
            "fina_swimmer_of_year": 0,
            "career_races_swum": 90,
            "career_races_won": 50,
            "career_win_percentage": 55.6,
            "main_event_olympic_titles": 2,
            "pan_pac_medals": 0,
            "commonwealth_medals": 0,
            "total_prize_money_million_usd": 0.5,
            "retirement_year": 0,
            "hall_of_fame_inducted": 0
        },
        {
            "player_name": "Krisztina Egerszegi",
            "country": "Hungary",
            "years_active": 8,
            "main_stroke": "Backstroke/Medley",
            "total_olympic_medals": 7,
            "olympic_gold_medals": 5,
            "olympic_silver_medals": 1,
            "olympic_bronze_medals": 1,
            "total_world_champ_medals": 6,
            "world_champ_gold": 3,
            "world_champ_silver": 2,
            "world_champ_bronze": 1,
            "world_record_count": 3,
            "personal_best_50_free": 26.5,
            "personal_best_100_free": 56.5,
            "personal_best_200_free": 1.58,
            "personal_best_400_free": 4.05,
            "personal_best_800_free": 8.20,
            "personal_best_1500_free": 0.0,
            "personal_best_100_butterfly": 0.0,
            "personal_best_200_butterfly": 2.11,
            "personal_best_100_back": 59.0,
            "personal_best_200_back": 2.06,
            "personal_best_100_breast": 1.12,
            "personal_best_200_breast": 2.29,
            "personal_best_200_im": 2.12,
            "personal_best_400_im": 4.36,
            "doping_tests_passed": 15,
            "doping_tests_failed": 0,
            "total_meet_points": 450,
            "fina_swimmer_of_year": 0,
            "career_races_swum": 70,
            "career_races_won": 50,
            "career_win_percentage": 71.4,
            "main_event_olympic_titles": 3,  # 200 back multiple times
            "pan_pac_medals": 0,
            "commonwealth_medals": 0,
            "total_prize_money_million_usd": 0.0,
            "retirement_year": 1996,
            "hall_of_fame_inducted": 1
        },
        {
            "player_name": "Ruta Meilutyte",
            "country": "Lithuania",
            "years_active": 8,
            "main_stroke": "Breaststroke",
            "total_olympic_medals": 1,
            "olympic_gold_medals": 1,
            "olympic_silver_medals": 0,
            "olympic_bronze_medals": 0,
            "total_world_champ_medals": 4,
            "world_champ_gold": 2,
            "world_champ_silver": 1,
            "world_champ_bronze": 1,
            "world_record_count": 2,
            "personal_best_50_free": 25.9,
            "personal_best_100_free": 55.5,
            "personal_best_200_free": 2.00,
            "personal_best_400_free": 4.20,
            "personal_best_800_free": 0.0,
            "personal_best_1500_free": 0.0,
            "personal_best_100_butterfly": 59.0,
            "personal_best_200_butterfly": 2.15,
            "personal_best_100_back": 1.01,
            "personal_best_200_back": 2.16,
            "personal_best_100_breast": 1.04,
            "personal_best_200_breast": 2.19,
            "personal_best_200_im": 2.15,
            "personal_best_400_im": 0.0,
            "doping_tests_passed": 40,
            "doping_tests_failed": 0,
            "total_meet_points": 380,
            "fina_swimmer_of_year": 0,
            "career_races_swum": 80,
            "career_races_won": 46,
            "career_win_percentage": 57.5,
            "main_event_olympic_titles": 1,
            "pan_pac_medals": 0,
            "commonwealth_medals": 0,
            "total_prize_money_million_usd": 0.4,
            "retirement_year": 0,
            "hall_of_fame_inducted": 0
        },
        {
            "player_name": "Leisel Jones",
            "country": "Australia",
            "years_active": 12,
            "main_stroke": "Breaststroke",
            "total_olympic_medals": 9,
            "olympic_gold_medals": 3,
            "olympic_silver_medals": 5,
            "olympic_bronze_medals": 1,
            "total_world_champ_medals": 14,
            "world_champ_gold": 7,
            "world_champ_silver": 5,
            "world_champ_bronze": 2,
            "world_record_count": 6,
            "personal_best_50_free": 26.2,
            "personal_best_100_free": 55.3,
            "personal_best_200_free": 1.59,
            "personal_best_400_free": 4.14,
            "personal_best_800_free": 8.30,
            "personal_best_1500_free": 0.0,
            "personal_best_100_butterfly": 59.5,
            "personal_best_200_butterfly": 2.10,
            "personal_best_100_back": 1.02,
            "personal_best_200_back": 2.14,
            "personal_best_100_breast": 1.05,
            "personal_best_200_breast": 2.20,
            "personal_best_200_im": 2.15,
            "personal_best_400_im": 4.40,
            "doping_tests_passed": 70,
            "doping_tests_failed": 0,
            "total_meet_points": 620,
            "fina_swimmer_of_year": 1,
            "career_races_swum": 130,
            "career_races_won": 75,
            "career_win_percentage": 57.7,
            "main_event_olympic_titles": 1,
            "pan_pac_medals": 4,
            "commonwealth_medals": 9,
            "total_prize_money_million_usd": 0.6,
            "retirement_year": 2012,
            "hall_of_fame_inducted": 1
        },
        {
            "player_name": "Ranomi Kromowidjojo",
            "country": "Netherlands",
            "years_active": 14,
            "main_stroke": "Freestyle",
            "total_olympic_medals": 4,
            "olympic_gold_medals": 3,
            "olympic_silver_medals": 1,
            "olympic_bronze_medals": 0,
            "total_world_champ_medals": 14,
            "world_champ_gold": 7,
            "world_champ_silver": 5,
            "world_champ_bronze": 2,
            "world_record_count": 4,
            "personal_best_50_free": 23.9,
            "personal_best_100_free": 52.7,
            "personal_best_200_free": 1.56,
            "personal_best_400_free": 4.09,
            "personal_best_800_free": 8.30,
            "personal_best_1500_free": 0.0,
            "personal_best_100_butterfly": 57.4,
            "personal_best_200_butterfly": 0.0,
            "personal_best_100_back": 1.01,
            "personal_best_200_back": 2.15,
            "personal_best_100_breast": 1.11,
            "personal_best_200_breast": 2.33,
            "personal_best_200_im": 2.17,
            "personal_best_400_im": 0.0,
            "doping_tests_passed": 85,
            "doping_tests_failed": 0,
            "total_meet_points": 700,
            "fina_swimmer_of_year": 0,
            "career_races_swum": 150,
            "career_races_won": 80,
            "career_win_percentage": 53.3,
            "main_event_olympic_titles": 2,
            "pan_pac_medals": 0,
            "commonwealth_medals": 0,
            "total_prize_money_million_usd": 0.9,
            "retirement_year": 0,
            "hall_of_fame_inducted": 0
        },
        {
            "player_name": "Inge de Bruijn",
            "country": "Netherlands",
            "years_active": 10,
            "main_stroke": "Freestyle/Butterfly",
            "total_olympic_medals": 8,
            "olympic_gold_medals": 4,
            "olympic_silver_medals": 2,
            "olympic_bronze_medals": 2,
            "total_world_champ_medals": 10,
            "world_champ_gold": 5,
            "world_champ_silver": 3,
            "world_champ_bronze": 2,
            "world_record_count": 10,
            "personal_best_50_free": 24.13,
            "personal_best_100_free": 53.77,
            "personal_best_200_free": 1.58,
            "personal_best_400_free": 4.12,
            "personal_best_800_free": 0.0,
            "personal_best_1500_free": 0.0,
            "personal_best_100_butterfly": 56.61,
            "personal_best_200_butterfly": 2.07,
            "personal_best_100_back": 1.01,
            "personal_best_200_back": 2.16,
            "personal_best_100_breast": 1.12,
            "personal_best_200_breast": 2.35,
            "personal_best_200_im": 2.20,
            "personal_best_400_im": 0.0,
            "doping_tests_passed": 40,
            "doping_tests_failed": 0,
            "total_meet_points": 610,
            "fina_swimmer_of_year": 2,
            "career_races_swum": 90,
            "career_races_won": 55,
            "career_win_percentage": 61.1,
            "main_event_olympic_titles": 3,
            "pan_pac_medals": 0,
            "commonwealth_medals": 0,
            "total_prize_money_million_usd": 0.4,
            "retirement_year": 2007,
            "hall_of_fame_inducted": 1
        },
        {
            "player_name": "Dana Vollmer",
            "country": "USA",
            "years_active": 10,
            "main_stroke": "Butterfly/Freestyle",
            "total_olympic_medals": 7,
            "olympic_gold_medals": 5,
            "olympic_silver_medals": 1,
            "olympic_bronze_medals": 1,
            "total_world_champ_medals": 8,
            "world_champ_gold": 4,
            "world_champ_silver": 3,
            "world_champ_bronze": 1,
            "world_record_count": 3,
            "personal_best_50_free": 24.9,
            "personal_best_100_free": 53.9,
            "personal_best_200_free": 1.57,
            "personal_best_400_free": 4.15,
            "personal_best_800_free": 0.0,
            "personal_best_1500_free": 0.0,
            "personal_best_100_butterfly": 55.98,
            "personal_best_200_butterfly": 2.06,
            "personal_best_100_back": 1.01,
            "personal_best_200_back": 2.13,
            "personal_best_100_breast": 1.12,
            "personal_best_200_breast": 2.36,
            "personal_best_200_im": 2.15,
            "personal_best_400_im": 0.0,
            "doping_tests_passed": 60,
            "doping_tests_failed": 0,
            "total_meet_points": 550,
            "fina_swimmer_of_year": 0,
            "career_races_swum": 80,
            "career_races_won": 46,
            "career_win_percentage": 57.5,
            "main_event_olympic_titles": 2,
            "pan_pac_medals": 3,
            "commonwealth_medals": 0,
            "total_prize_money_million_usd": 0.6,
            "retirement_year": 2019,
            "hall_of_fame_inducted": 0
        },
        {
            "player_name": "Cate Campbell",
            "country": "Australia",
            "years_active": 12,
            "main_stroke": "Freestyle",
            "total_olympic_medals": 7,
            "olympic_gold_medals": 3,
            "olympic_silver_medals": 2,
            "olympic_bronze_medals": 2,
            "total_world_champ_medals": 14,
            "world_champ_gold": 8,
            "world_champ_silver": 4,
            "world_champ_bronze": 2,
            "world_record_count": 2,
            "personal_best_50_free": 23.78,
            "personal_best_100_free": 52.03,
            "personal_best_200_free": 1.57,
            "personal_best_400_free": 4.11,
            "personal_best_800_free": 0.0,
            "personal_best_1500_free": 0.0,
            "personal_best_100_butterfly": 58.0,
            "personal_best_200_butterfly": 0.0,
            "personal_best_100_back": 1.00,
            "personal_best_200_back": 2.14,
            "personal_best_100_breast": 1.12,
            "personal_best_200_breast": 2.33,
            "personal_best_200_im": 2.16,
            "personal_best_400_im": 0.0,
            "doping_tests_passed": 90,
            "doping_tests_failed": 0,
            "total_meet_points": 740,
            "fina_swimmer_of_year": 1,
            "career_races_swum": 130,
            "career_races_won": 70,
            "career_win_percentage": 53.8,
            "main_event_olympic_titles": 2,
            "pan_pac_medals": 4,
            "commonwealth_medals": 7,
            "total_prize_money_million_usd": 0.7,
            "retirement_year": 0,
            "hall_of_fame_inducted": 0
        },
        {
            "player_name": "Bronte Campbell",
            "country": "Australia",
            "years_active": 10,
            "main_stroke": "Freestyle",
            "total_olympic_medals": 5,
            "olympic_gold_medals": 3,
            "olympic_silver_medals": 2,
            "olympic_bronze_medals": 0,
            "total_world_champ_medals": 10,
            "world_champ_gold": 5,
            "world_champ_silver": 3,
            "world_champ_bronze": 2,
            "world_record_count": 1,
            "personal_best_50_free": 24.0,
            "personal_best_100_free": 52.6,
            "personal_best_200_free": 1.57,
            "personal_best_400_free": 4.15,
            "personal_best_800_free": 0.0,
            "personal_best_1500_free": 0.0,
            "personal_best_100_butterfly": 58.1,
            "personal_best_200_butterfly": 0.0,
            "personal_best_100_back": 1.02,
            "personal_best_200_back": 2.15,
            "personal_best_100_breast": 1.13,
            "personal_best_200_breast": 2.34,
            "personal_best_200_im": 2.18,
            "personal_best_400_im": 0.0,
            "doping_tests_passed": 65,
            "doping_tests_failed": 0,
            "total_meet_points": 600,
            "fina_swimmer_of_year": 0,
            "career_races_swum": 100,
            "career_races_won": 55,
            "career_win_percentage": 55.0,
            "main_event_olympic_titles": 1,
            "pan_pac_medals": 3,
            "commonwealth_medals": 5,
            "total_prize_money_million_usd": 0.5,
            "retirement_year": 0,
            "hall_of_fame_inducted": 0
        }
    ]

    # Ensure we have exactly 30 swimmers
    if len(players_data) != 30:
        raise ValueError(f"Expected 30 swimmers, got {len(players_data)}")

    # Write out to CSV
    with open(filename, mode="w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=headers)
        writer.writeheader()
        for pdata in players_data:
            # Make sure every header field is present. If any are missing, fill with 0 or something safe.
            for h in headers:
                if h not in pdata:
                    pdata[h] = 0
            writer.writerow(pdata)


if __name__ == "__main__":
    create_womens_swimming_dataset()
    print("womens_swimming_dataset.csv has been created with 30 swimmers and 41 stats each.")
