import csv

def create_wnba_dataset(filename="wnba_dataset.csv"):
    """
    Creates a CSV file containing 30 WNBA players and 40 stats each.
    Stats are approximations, intended for demonstration and for building
    a 'WNBA Index Score' later in Step 2.
    """
    # Define the header (player_name + 39 more stats = 40 total)
    headers = [
        "player_name",
        "seasons_played",
        "games_played",
        "minutes_played",
        "points",
        "rebounds",
        "assists",
        "steals",
        "blocks",
        "field_goals_made",
        "field_goal_attempts",
        "field_goal_percentage",
        "three_pointers_made",
        "three_pointer_attempts",
        "three_pointer_percentage",
        "free_throws_made",
        "free_throw_attempts",
        "free_throw_percentage",
        "usage_rate",
        "turnover_percentage",
        "true_shooting_percentage",
        "effective_fg_percentage",
        "player_efficiency_rating",  # PER
        "win_shares",
        "plus_minus",                # BPM (approx)
        "off_bpm",
        "def_bpm",
        "vorp",
        "triple_doubles",
        "double_doubles",
        "finals_mvp_awards",
        "championships",
        "mvp_awards",
        "dpoy_awards",              # Defensive Player of the Year
        "all_star_appearances",
        "all_wnba_teams",
        "scoring_titles",
        "game_high_points",
        "career_high_points",
        "total_playoff_points"
    ]

    # Each dict represents one player's "career" data (approx or representative)
    players_data = [
        {
            "player_name": "Diana Taurasi",
            "seasons_played": 18,
            "games_played": 508,
            "minutes_played": 16000,
            "points": 9400,
            "rebounds": 2000,
            "assists": 2100,
            "steals": 650,
            "blocks": 200,
            "field_goals_made": 3000,
            "field_goal_attempts": 7000,
            "field_goal_percentage": 42.9,
            "three_pointers_made": 1212,
            "three_pointer_attempts": 3300,
            "three_pointer_percentage": 36.7,
            "free_throws_made": 2200,
            "free_throw_attempts": 2600,
            "free_throw_percentage": 84.6,
            "usage_rate": 30.5,
            "turnover_percentage": 13.1,
            "true_shooting_percentage": 58.4,
            "effective_fg_percentage": 50.5,
            "player_efficiency_rating": 25.0,
            "win_shares": 70.1,
            "plus_minus": 6.0,
            "off_bpm": 5.0,
            "def_bpm": 1.0,
            "vorp": 45.0,
            "triple_doubles": 1,
            "double_doubles": 50,
            "finals_mvp_awards": 2,
            "championships": 3,
            "mvp_awards": 1,
            "dpoy_awards": 0,
            "all_star_appearances": 10,
            "all_wnba_teams": 14,
            "scoring_titles": 5,
            "game_high_points": 47,
            "career_high_points": 47,
            "total_playoff_points": 1000
        },
        {
            "player_name": "Sue Bird",
            "seasons_played": 19,
            "games_played": 580,
            "minutes_played": 17500,
            "points": 7000,
            "rebounds": 2500,
            "assists": 3300,
            "steals": 700,
            "blocks": 70,
            "field_goals_made": 2500,
            "field_goal_attempts": 6000,
            "field_goal_percentage": 41.7,
            "three_pointers_made": 1000,
            "three_pointer_attempts": 2800,
            "three_pointer_percentage": 35.7,
            "free_throws_made": 1200,
            "free_throw_attempts": 1450,
            "free_throw_percentage": 82.8,
            "usage_rate": 25.5,
            "turnover_percentage": 14.0,
            "true_shooting_percentage": 56.2,
            "effective_fg_percentage": 50.1,
            "player_efficiency_rating": 20.1,
            "win_shares": 65.0,
            "plus_minus": 5.0,
            "off_bpm": 4.0,
            "def_bpm": 1.0,
            "vorp": 40.0,
            "triple_doubles": 3,
            "double_doubles": 80,
            "finals_mvp_awards": 0,
            "championships": 4,
            "mvp_awards": 0,
            "dpoy_awards": 0,
            "all_star_appearances": 13,
            "all_wnba_teams": 8,
            "scoring_titles": 0,
            "game_high_points": 33,
            "career_high_points": 33,
            "total_playoff_points": 900
        },
        {
            "player_name": "Tamika Catchings",
            "seasons_played": 15,
            "games_played": 457,
            "minutes_played": 15000,
            "points": 7380,
            "rebounds": 3200,
            "assists": 1600,
            "steals": 1100,
            "blocks": 350,
            "field_goals_made": 2500,
            "field_goal_attempts": 6000,
            "field_goal_percentage": 41.6,
            "three_pointers_made": 600,
            "three_pointer_attempts": 1900,
            "three_pointer_percentage": 31.6,
            "free_throws_made": 1800,
            "free_throw_attempts": 2200,
            "free_throw_percentage": 82.0,
            "usage_rate": 27.0,
            "turnover_percentage": 15.5,
            "true_shooting_percentage": 54.0,
            "effective_fg_percentage": 46.0,
            "player_efficiency_rating": 24.5,
            "win_shares": 78.1,
            "plus_minus": 6.5,
            "off_bpm": 3.0,
            "def_bpm": 3.5,
            "vorp": 42.0,
            "triple_doubles": 2,
            "double_doubles": 120,
            "finals_mvp_awards": 1,
            "championships": 1,
            "mvp_awards": 1,
            "dpoy_awards": 5,
            "all_star_appearances": 10,
            "all_wnba_teams": 12,
            "scoring_titles": 0,
            "game_high_points": 32,
            "career_high_points": 32,
            "total_playoff_points": 800
        },
        {
            "player_name": "Lisa Leslie",
            "seasons_played": 12,
            "games_played": 363,
            "minutes_played": 11500,
            "points": 6263,
            "rebounds": 3307,
            "assists": 822,
            "steals": 310,
            "blocks": 822,
            "field_goals_made": 2400,
            "field_goal_attempts": 4600,
            "field_goal_percentage": 52.0,
            "three_pointers_made": 22,
            "three_pointer_attempts": 105,
            "three_pointer_percentage": 21.0,
            "free_throws_made": 1500,
            "free_throw_attempts": 1800,
            "free_throw_percentage": 83.0,
            "usage_rate": 28.5,
            "turnover_percentage": 14.0,
            "true_shooting_percentage": 58.0,
            "effective_fg_percentage": 52.5,
            "player_efficiency_rating": 28.0,
            "win_shares": 60.2,
            "plus_minus": 7.0,
            "off_bpm": 3.5,
            "def_bpm": 3.5,
            "vorp": 38.0,
            "triple_doubles": 0,
            "double_doubles": 135,
            "finals_mvp_awards": 2,
            "championships": 2,
            "mvp_awards": 3,
            "dpoy_awards": 2,
            "all_star_appearances": 8,
            "all_wnba_teams": 8,
            "scoring_titles": 0,
            "game_high_points": 41,
            "career_high_points": 41,
            "total_playoff_points": 600
        },
        {
            "player_name": "Candace Parker",
            "seasons_played": 15,
            "games_played": 400,
            "minutes_played": 12600,
            "points": 6100,
            "rebounds": 3000,
            "assists": 1600,
            "steals": 500,
            "blocks": 550,
            "field_goals_made": 2200,
            "field_goal_attempts": 4500,
            "field_goal_percentage": 48.9,
            "three_pointers_made": 350,
            "three_pointer_attempts": 1000,
            "three_pointer_percentage": 35.0,
            "free_throws_made": 1300,
            "free_throw_attempts": 1600,
            "free_throw_percentage": 81.5,
            "usage_rate": 26.5,
            "turnover_percentage": 13.5,
            "true_shooting_percentage": 57.5,
            "effective_fg_percentage": 53.0,
            "player_efficiency_rating": 26.0,
            "win_shares": 58.0,
            "plus_minus": 5.0,
            "off_bpm": 3.0,
            "def_bpm": 2.0,
            "vorp": 35.0,
            "triple_doubles": 11,
            "double_doubles": 130,
            "finals_mvp_awards": 1,
            "championships": 2,
            "mvp_awards": 2,
            "dpoy_awards": 0,
            "all_star_appearances": 7,
            "all_wnba_teams": 10,
            "scoring_titles": 0,
            "game_high_points": 40,
            "career_high_points": 40,
            "total_playoff_points": 700
        },
        {
            "player_name": "Cynthia Cooper",
            "seasons_played": 5,
            "games_played": 120,
            "minutes_played": 3900,
            "points": 2541,
            "rebounds": 421,
            "assists": 602,
            "steals": 220,
            "blocks": 50,
            "field_goals_made": 900,
            "field_goal_attempts": 1800,
            "field_goal_percentage": 50.0,
            "three_pointers_made": 170,
            "three_pointer_attempts": 500,
            "three_pointer_percentage": 34.0,
            "free_throws_made": 571,
            "free_throw_attempts": 660,
            "free_throw_percentage": 86.5,
            "usage_rate": 29.0,
            "turnover_percentage": 14.5,
            "true_shooting_percentage": 58.0,
            "effective_fg_percentage": 54.0,
            "player_efficiency_rating": 29.5,
            "win_shares": 25.0,
            "plus_minus": 7.0,
            "off_bpm": 5.0,
            "def_bpm": 2.0,
            "vorp": 15.0,
            "triple_doubles": 0,
            "double_doubles": 15,
            "finals_mvp_awards": 4,
            "championships": 4,
            "mvp_awards": 2,
            "dpoy_awards": 0,
            "all_star_appearances": 3,
            "all_wnba_teams": 4,
            "scoring_titles": 3,
            "game_high_points": 44,
            "career_high_points": 44,
            "total_playoff_points": 400
        },
        {
            "player_name": "Maya Moore",
            "seasons_played": 8,
            "games_played": 271,
            "minutes_played": 9200,
            "points": 4500,
            "rebounds": 1400,
            "assists": 900,
            "steals": 450,
            "blocks": 150,
            "field_goals_made": 1600,
            "field_goal_attempts": 3300,
            "field_goal_percentage": 48.5,
            "three_pointers_made": 500,
            "three_pointer_attempts": 1300,
            "three_pointer_percentage": 38.5,
            "free_throws_made": 800,
            "free_throw_attempts": 950,
            "free_throw_percentage": 84.2,
            "usage_rate": 28.0,
            "turnover_percentage": 12.5,
            "true_shooting_percentage": 59.0,
            "effective_fg_percentage": 55.0,
            "player_efficiency_rating": 26.5,
            "win_shares": 40.0,
            "plus_minus": 6.0,
            "off_bpm": 4.0,
            "def_bpm": 2.0,
            "vorp": 25.0,
            "triple_doubles": 1,
            "double_doubles": 40,
            "finals_mvp_awards": 1,
            "championships": 4,
            "mvp_awards": 1,
            "dpoy_awards": 0,
            "all_star_appearances": 6,
            "all_wnba_teams": 7,
            "scoring_titles": 1,
            "game_high_points": 48,
            "career_high_points": 48,
            "total_playoff_points": 550
        },
        {
            "player_name": "Breanna Stewart",
            "seasons_played": 7,
            "games_played": 220,
            "minutes_played": 6800,
            "points": 4200,
            "rebounds": 1900,
            "assists": 700,
            "steals": 300,
            "blocks": 350,
            "field_goals_made": 1500,
            "field_goal_attempts": 3100,
            "field_goal_percentage": 48.4,
            "three_pointers_made": 375,
            "three_pointer_attempts": 1000,
            "three_pointer_percentage": 37.5,
            "free_throws_made": 900,
            "free_throw_attempts": 1100,
            "free_throw_percentage": 81.5,
            "usage_rate": 26.0,
            "turnover_percentage": 12.0,
            "true_shooting_percentage": 58.2,
            "effective_fg_percentage": 53.0,
            "player_efficiency_rating": 27.0,
            "win_shares": 36.0,
            "plus_minus": 6.0,
            "off_bpm": 4.0,
            "def_bpm": 2.0,
            "vorp": 20.0,
            "triple_doubles": 0,
            "double_doubles": 60,
            "finals_mvp_awards": 2,
            "championships": 2,
            "mvp_awards": 2,
            "dpoy_awards": 0,
            "all_star_appearances": 5,
            "all_wnba_teams": 5,
            "scoring_titles": 0,
            "game_high_points": 45,
            "career_high_points": 45,
            "total_playoff_points": 550
        },
        {
            "player_name": "Sheryl Swoopes",
            "seasons_played": 12,
            "games_played": 324,
            "minutes_played": 10500,
            "points": 4816,
            "rebounds": 1600,
            "assists": 1000,
            "steals": 700,
            "blocks": 280,
            "field_goals_made": 1800,
            "field_goal_attempts": 3900,
            "field_goal_percentage": 46.1,
            "three_pointers_made": 300,
            "three_pointer_attempts": 900,
            "three_pointer_percentage": 33.3,
            "free_throws_made": 1000,
            "free_throw_attempts": 1250,
            "free_throw_percentage": 80.0,
            "usage_rate": 25.5,
            "turnover_percentage": 13.0,
            "true_shooting_percentage": 55.0,
            "effective_fg_percentage": 50.0,
            "player_efficiency_rating": 23.0,
            "win_shares": 45.0,
            "plus_minus": 5.5,
            "off_bpm": 3.5,
            "def_bpm": 2.0,
            "vorp": 30.0,
            "triple_doubles": 2,
            "double_doubles": 55,
            "finals_mvp_awards": 0,
            "championships": 4,
            "mvp_awards": 3,
            "dpoy_awards": 3,
            "all_star_appearances": 6,
            "all_wnba_teams": 8,
            "scoring_titles": 2,
            "game_high_points": 34,
            "career_high_points": 34,
            "total_playoff_points": 400
        },
        {
            "player_name": "Sylvia Fowles",
            "seasons_played": 15,
            "games_played": 408,
            "minutes_played": 12300,
            "points": 6000,
            "rebounds": 3500,
            "assists": 500,
            "steals": 350,
            "blocks": 650,
            "field_goals_made": 2400,
            "field_goal_attempts": 3800,
            "field_goal_percentage": 63.0,
            "three_pointers_made": 5,
            "three_pointer_attempts": 25,
            "three_pointer_percentage": 20.0,
            "free_throws_made": 1200,
            "free_throw_attempts": 1700,
            "free_throw_percentage": 70.6,
            "usage_rate": 24.5,
            "turnover_percentage": 15.0,
            "true_shooting_percentage": 60.0,
            "effective_fg_percentage": 63.6,
            "player_efficiency_rating": 28.0,
            "win_shares": 55.0,
            "plus_minus": 5.0,
            "off_bpm": 2.0,
            "def_bpm": 3.0,
            "vorp": 32.0,
            "triple_doubles": 0,
            "double_doubles": 150,
            "finals_mvp_awards": 2,
            "championships": 2,
            "mvp_awards": 1,
            "dpoy_awards": 4,
            "all_star_appearances": 8,
            "all_wnba_teams": 7,
            "scoring_titles": 0,
            "game_high_points": 33,
            "career_high_points": 33,
            "total_playoff_points": 550
        },
        {
            "player_name": "Lauren Jackson",
            "seasons_played": 12,
            "games_played": 317,
            "minutes_played": 10200,
            "points": 6005,
            "rebounds": 2700,
            "assists": 490,
            "steals": 250,
            "blocks": 586,
            "field_goals_made": 2100,
            "field_goal_attempts": 4200,
            "field_goal_percentage": 50.0,
            "three_pointers_made": 400,
            "three_pointer_attempts": 1050,
            "three_pointer_percentage": 38.1,
            "free_throws_made": 1400,
            "free_throw_attempts": 1650,
            "free_throw_percentage": 84.8,
            "usage_rate": 28.0,
            "turnover_percentage": 14.0,
            "true_shooting_percentage": 59.5,
            "effective_fg_percentage": 54.8,
            "player_efficiency_rating": 29.4,
            "win_shares": 52.0,
            "plus_minus": 6.5,
            "off_bpm": 4.0,
            "def_bpm": 2.5,
            "vorp": 28.0,
            "triple_doubles": 0,
            "double_doubles": 120,
            "finals_mvp_awards": 1,
            "championships": 2,
            "mvp_awards": 3,
            "dpoy_awards": 1,
            "all_star_appearances": 7,
            "all_wnba_teams": 8,
            "scoring_titles": 3,
            "game_high_points": 47,
            "career_high_points": 47,
            "total_playoff_points": 450
        },
        {
            "player_name": "Tina Charles",
            "seasons_played": 13,
            "games_played": 375,
            "minutes_played": 12000,
            "points": 6200,
            "rebounds": 3000,
            "assists": 700,
            "steals": 300,
            "blocks": 280,
            "field_goals_made": 2400,
            "field_goal_attempts": 5000,
            "field_goal_percentage": 48.0,
            "three_pointers_made": 150,
            "three_pointer_attempts": 450,
            "three_pointer_percentage": 33.3,
            "free_throws_made": 1200,
            "free_throw_attempts": 1500,
            "free_throw_percentage": 80.0,
            "usage_rate": 27.0,
            "turnover_percentage": 13.5,
            "true_shooting_percentage": 54.5,
            "effective_fg_percentage": 50.0,
            "player_efficiency_rating": 23.0,
            "win_shares": 40.0,
            "plus_minus": 3.0,
            "off_bpm": 2.0,
            "def_bpm": 1.0,
            "vorp": 20.0,
            "triple_doubles": 0,
            "double_doubles": 160,
            "finals_mvp_awards": 0,
            "championships": 0,
            "mvp_awards": 1,
            "dpoy_awards": 0,
            "all_star_appearances": 8,
            "all_wnba_teams": 7,
            "scoring_titles": 1,
            "game_high_points": 36,
            "career_high_points": 36,
            "total_playoff_points": 300
        },
        {
            "player_name": "Becky Hammon",
            "seasons_played": 16,
            "games_played": 450,
            "minutes_played": 13400,
            "points": 5800,
            "rebounds": 900,
            "assists": 1600,
            "steals": 400,
            "blocks": 50,
            "field_goals_made": 2100,
            "field_goal_attempts": 4900,
            "field_goal_percentage": 42.9,
            "three_pointers_made": 800,
            "three_pointer_attempts": 2150,
            "three_pointer_percentage": 37.2,
            "free_throws_made": 800,
            "free_throw_attempts": 950,
            "free_throw_percentage": 84.7,
            "usage_rate": 24.0,
            "turnover_percentage": 14.0,
            "true_shooting_percentage": 57.0,
            "effective_fg_percentage": 49.5,
            "player_efficiency_rating": 20.5,
            "win_shares": 34.0,
            "plus_minus": 4.0,
            "off_bpm": 3.0,
            "def_bpm": 1.0,
            "vorp": 18.0,
            "triple_doubles": 2,
            "double_doubles": 30,
            "finals_mvp_awards": 0,
            "championships": 0,
            "mvp_awards": 0,
            "dpoy_awards": 0,
            "all_star_appearances": 6,
            "all_wnba_teams": 4,
            "scoring_titles": 0,
            "game_high_points": 38,
            "career_high_points": 38,
            "total_playoff_points": 350
        },
        # --------------- Add more players to reach 30 total ---------------
        {
            "player_name": "Elena Delle Donne",
            "seasons_played": 10,
            "games_played": 260,
            "minutes_played": 8100,
            "points": 4900,
            "rebounds": 1800,
            "assists": 600,
            "steals": 300,
            "blocks": 350,
            "field_goals_made": 1600,
            "field_goal_attempts": 3400,
            "field_goal_percentage": 47.1,
            "three_pointers_made": 370,
            "three_pointer_attempts": 900,
            "three_pointer_percentage": 41.1,
            "free_throws_made": 1300,
            "free_throw_attempts": 1400,
            "free_throw_percentage": 92.1,
            "usage_rate": 27.5,
            "turnover_percentage": 12.0,
            "true_shooting_percentage": 60.2,
            "effective_fg_percentage": 53.0,
            "player_efficiency_rating": 27.5,
            "win_shares": 32.0,
            "plus_minus": 5.0,
            "off_bpm": 3.0,
            "def_bpm": 2.0,
            "vorp": 15.0,
            "triple_doubles": 0,
            "double_doubles": 55,
            "finals_mvp_awards": 1,
            "championships": 1,
            "mvp_awards": 2,
            "dpoy_awards": 0,
            "all_star_appearances": 6,
            "all_wnba_teams": 5,
            "scoring_titles": 1,
            "game_high_points": 45,
            "career_high_points": 45,
            "total_playoff_points": 400
        },
        {
            "player_name": "Angel McCoughtry",
            "seasons_played": 13,
            "games_played": 360,
            "minutes_played": 11000,
            "points": 6400,
            "rebounds": 1800,
            "assists": 900,
            "steals": 800,
            "blocks": 180,
            "field_goals_made": 2200,
            "field_goal_attempts": 5300,
            "field_goal_percentage": 41.5,
            "three_pointers_made": 300,
            "three_pointer_attempts": 950,
            "three_pointer_percentage": 31.6,
            "free_throws_made": 1700,
            "free_throw_attempts": 2100,
            "free_throw_percentage": 81.0,
            "usage_rate": 30.0,
            "turnover_percentage": 15.5,
            "true_shooting_percentage": 53.0,
            "effective_fg_percentage": 45.0,
            "player_efficiency_rating": 23.5,
            "win_shares": 35.0,
            "plus_minus": 3.0,
            "off_bpm": 2.0,
            "def_bpm": 1.0,
            "vorp": 22.0,
            "triple_doubles": 1,
            "double_doubles": 40,
            "finals_mvp_awards": 0,
            "championships": 0,
            "mvp_awards": 0,
            "dpoy_awards": 0,
            "all_star_appearances": 5,
            "all_wnba_teams": 6,
            "scoring_titles": 2,
            "game_high_points": 42,
            "career_high_points": 42,
            "total_playoff_points": 410
        },
        {
            "player_name": "Brittney Griner",
            "seasons_played": 10,
            "games_played": 282,
            "minutes_played": 8500,
            "points": 5200,
            "rebounds": 2000,
            "assists": 300,
            "steals": 200,
            "blocks": 800,
            "field_goals_made": 2100,
            "field_goal_attempts": 3800,
            "field_goal_percentage": 55.3,
            "three_pointers_made": 15,
            "three_pointer_attempts": 45,
            "three_pointer_percentage": 33.3,
            "free_throws_made": 1000,
            "free_throw_attempts": 1300,
            "free_throw_percentage": 76.9,
            "usage_rate": 26.0,
            "turnover_percentage": 14.5,
            "true_shooting_percentage": 58.0,
            "effective_fg_percentage": 55.5,
            "player_efficiency_rating": 25.5,
            "win_shares": 28.0,
            "plus_minus": 4.0,
            "off_bpm": 2.0,
            "def_bpm": 2.0,
            "vorp": 17.0,
            "triple_doubles": 0,
            "double_doubles": 90,
            "finals_mvp_awards": 1,
            "championships": 1,
            "mvp_awards": 0,
            "dpoy_awards": 2,
            "all_star_appearances": 8,
            "all_wnba_teams": 6,
            "scoring_titles": 0,
            "game_high_points": 38,
            "career_high_points": 38,
            "total_playoff_points": 300
        },
        {
            "player_name": "Nneka Ogwumike",
            "seasons_played": 11,
            "games_played": 330,
            "minutes_played": 10000,
            "points": 4800,
            "rebounds": 2400,
            "assists": 600,
            "steals": 300,
            "blocks": 270,
            "field_goals_made": 1900,
            "field_goal_attempts": 3200,
            "field_goal_percentage": 59.3,
            "three_pointers_made": 180,
            "three_pointer_attempts": 500,
            "three_pointer_percentage": 36.0,
            "free_throws_made": 800,
            "free_throw_attempts": 1000,
            "free_throw_percentage": 80.0,
            "usage_rate": 23.5,
            "turnover_percentage": 12.5,
            "true_shooting_percentage": 62.0,
            "effective_fg_percentage": 61.0,
            "player_efficiency_rating": 24.0,
            "win_shares": 30.0,
            "plus_minus": 3.5,
            "off_bpm": 2.0,
            "def_bpm": 1.5,
            "vorp": 14.0,
            "triple_doubles": 0,
            "double_doubles": 90,
            "finals_mvp_awards": 1,
            "championships": 1,
            "mvp_awards": 1,
            "dpoy_awards": 0,
            "all_star_appearances": 7,
            "all_wnba_teams": 5,
            "scoring_titles": 0,
            "game_high_points": 38,
            "career_high_points": 38,
            "total_playoff_points": 290
        },
        {
            "player_name": "Ticha Penicheiro",
            "seasons_played": 15,
            "games_played": 454,
            "minutes_played": 12900,
            "points": 3600,
            "rebounds": 1400,
            "assists": 2600,
            "steals": 700,
            "blocks": 70,
            "field_goals_made": 1300,
            "field_goal_attempts": 3300,
            "field_goal_percentage": 39.4,
            "three_pointers_made": 100,
            "three_pointer_attempts": 350,
            "three_pointer_percentage": 28.6,
            "free_throws_made": 900,
            "free_throw_attempts": 1200,
            "free_throw_percentage": 75.0,
            "usage_rate": 22.0,
            "turnover_percentage": 17.0,
            "true_shooting_percentage": 50.0,
            "effective_fg_percentage": 42.4,
            "player_efficiency_rating": 16.5,
            "win_shares": 28.0,
            "plus_minus": 2.0,
            "off_bpm": 1.5,
            "def_bpm": 0.5,
            "vorp": 10.0,
            "triple_doubles": 8,
            "double_doubles": 45,
            "finals_mvp_awards": 0,
            "championships": 1,
            "mvp_awards": 0,
            "dpoy_awards": 0,
            "all_star_appearances": 4,
            "all_wnba_teams": 2,
            "scoring_titles": 0,
            "game_high_points": 27,
            "career_high_points": 27,
            "total_playoff_points": 300
        },
        {
            "player_name": "Penny Taylor",
            "seasons_played": 13,
            "games_played": 326,
            "minutes_played": 9800,
            "points": 4300,
            "rebounds": 1300,
            "assists": 800,
            "steals": 400,
            "blocks": 150,
            "field_goals_made": 1500,
            "field_goal_attempts": 3100,
            "field_goal_percentage": 48.5,
            "three_pointers_made": 300,
            "three_pointer_attempts": 800,
            "three_pointer_percentage": 37.5,
            "free_throws_made": 1000,
            "free_throw_attempts": 1200,
            "free_throw_percentage": 83.3,
            "usage_rate": 25.0,
            "turnover_percentage": 14.0,
            "true_shooting_percentage": 57.7,
            "effective_fg_percentage": 53.2,
            "player_efficiency_rating": 19.5,
            "win_shares": 25.0,
            "plus_minus": 3.0,
            "off_bpm": 2.0,
            "def_bpm": 1.0,
            "vorp": 12.0,
            "triple_doubles": 0,
            "double_doubles": 30,
            "finals_mvp_awards": 0,
            "championships": 3,
            "mvp_awards": 0,
            "dpoy_awards": 0,
            "all_star_appearances": 3,
            "all_wnba_teams": 2,
            "scoring_titles": 0,
            "game_high_points": 30,
            "career_high_points": 30,
            "total_playoff_points": 320
        },
        {
            "player_name": "Skylar Diggins-Smith",
            "seasons_played": 10,
            "games_played": 280,
            "minutes_played": 9000,
            "points": 4900,
            "rebounds": 950,
            "assists": 1400,
            "steals": 400,
            "blocks": 60,
            "field_goals_made": 1700,
            "field_goal_attempts": 4100,
            "field_goal_percentage": 41.5,
            "three_pointers_made": 400,
            "three_pointer_attempts": 1200,
            "three_pointer_percentage": 33.3,
            "free_throws_made": 1100,
            "free_throw_attempts": 1300,
            "free_throw_percentage": 84.6,
            "usage_rate": 27.0,
            "turnover_percentage": 13.5,
            "true_shooting_percentage": 54.0,
            "effective_fg_percentage": 47.5,
            "player_efficiency_rating": 21.5,
            "win_shares": 20.0,
            "plus_minus": 2.0,
            "off_bpm": 1.5,
            "def_bpm": 0.5,
            "vorp": 10.0,
            "triple_doubles": 1,
            "double_doubles": 25,
            "finals_mvp_awards": 0,
            "championships": 0,
            "mvp_awards": 0,
            "dpoy_awards": 0,
            "all_star_appearances": 6,
            "all_wnba_teams": 4,
            "scoring_titles": 0,
            "game_high_points": 35,
            "career_high_points": 35,
            "total_playoff_points": 200
        },
        {
            "player_name": "DeWanna Bonner",
            "seasons_played": 13,
            "games_played": 370,
            "minutes_played": 11500,
            "points": 5500,
            "rebounds": 2200,
            "assists": 800,
            "steals": 400,
            "blocks": 200,
            "field_goals_made": 1800,
            "field_goal_attempts": 4400,
            "field_goal_percentage": 40.9,
            "three_pointers_made": 400,
            "three_pointer_attempts": 1300,
            "three_pointer_percentage": 30.7,
            "free_throws_made": 1500,
            "free_throw_attempts": 1800,
            "free_throw_percentage": 83.3,
            "usage_rate": 28.0,
            "turnover_percentage": 15.0,
            "true_shooting_percentage": 52.0,
            "effective_fg_percentage": 45.5,
            "player_efficiency_rating": 19.0,
            "win_shares": 22.0,
            "plus_minus": 1.5,
            "off_bpm": 1.0,
            "def_bpm": 0.5,
            "vorp": 8.0,
            "triple_doubles": 1,
            "double_doubles": 55,
            "finals_mvp_awards": 0,
            "championships": 2,
            "mvp_awards": 0,
            "dpoy_awards": 0,
            "all_star_appearances": 4,
            "all_wnba_teams": 3,
            "scoring_titles": 0,
            "game_high_points": 38,
            "career_high_points": 38,
            "total_playoff_points": 250
        },
        {
            "player_name": "A'ja Wilson",
            "seasons_played": 5,
            "games_played": 150,
            "minutes_played": 4800,
            "points": 3000,
            "rebounds": 1300,
            "assists": 400,
            "steals": 150,
            "blocks": 220,
            "field_goals_made": 1100,
            "field_goal_attempts": 2200,
            "field_goal_percentage": 50.0,
            "three_pointers_made": 50,
            "three_pointer_attempts": 170,
            "three_pointer_percentage": 29.4,
            "free_throws_made": 750,
            "free_throw_attempts": 900,
            "free_throw_percentage": 83.3,
            "usage_rate": 28.0,
            "turnover_percentage": 14.0,
            "true_shooting_percentage": 56.5,
            "effective_fg_percentage": 51.0,
            "player_efficiency_rating": 25.5,
            "win_shares": 14.0,
            "plus_minus": 4.0,
            "off_bpm": 2.0,
            "def_bpm": 2.0,
            "vorp": 8.0,
            "triple_doubles": 0,
            "double_doubles": 50,
            "finals_mvp_awards": 1,
            "championships": 1,
            "mvp_awards": 2,
            "dpoy_awards": 1,
            "all_star_appearances": 4,
            "all_wnba_teams": 3,
            "scoring_titles": 0,
            "game_high_points": 38,
            "career_high_points": 38,
            "total_playoff_points": 210
        },
        {
            "player_name": "Kelsey Plum",
            "seasons_played": 6,
            "games_played": 170,
            "minutes_played": 4800,
            "points": 2200,
            "rebounds": 400,
            "assists": 600,
            "steals": 150,
            "blocks": 25,
            "field_goals_made": 750,
            "field_goal_attempts": 1900,
            "field_goal_percentage": 39.5,
            "three_pointers_made": 350,
            "three_pointer_attempts": 1000,
            "three_pointer_percentage": 35.0,
            "free_throws_made": 350,
            "free_throw_attempts": 400,
            "free_throw_percentage": 87.5,
            "usage_rate": 22.0,
            "turnover_percentage": 12.0,
            "true_shooting_percentage": 53.0,
            "effective_fg_percentage": 48.0,
            "player_efficiency_rating": 16.5,
            "win_shares": 10.0,
            "plus_minus": 2.0,
            "off_bpm": 1.5,
            "def_bpm": 0.5,
            "vorp": 5.0,
            "triple_doubles": 0,
            "double_doubles": 10,
            "finals_mvp_awards": 0,
            "championships": 1,
            "mvp_awards": 0,
            "dpoy_awards": 0,
            "all_star_appearances": 2,
            "all_wnba_teams": 1,
            "scoring_titles": 0,
            "game_high_points": 32,
            "career_high_points": 32,
            "total_playoff_points": 150
        },
        {
            "player_name": "Cheryl Ford",
            "seasons_played": 6,
            "games_played": 195,
            "minutes_played": 5200,
            "points": 2000,
            "rebounds": 1900,
            "assists": 400,
            "steals": 220,
            "blocks": 130,
            "field_goals_made": 700,
            "field_goal_attempts": 1500,
            "field_goal_percentage": 46.7,
            "three_pointers_made": 0,
            "three_pointer_attempts": 10,
            "three_pointer_percentage": 0.0,
            "free_throws_made": 600,
            "free_throw_attempts": 860,
            "free_throw_percentage": 69.8,
            "usage_rate": 20.0,
            "turnover_percentage": 16.0,
            "true_shooting_percentage": 50.0,
            "effective_fg_percentage": 46.7,
            "player_efficiency_rating": 18.5,
            "win_shares": 12.0,
            "plus_minus": 2.0,
            "off_bpm": 1.0,
            "def_bpm": 1.0,
            "vorp": 5.0,
            "triple_doubles": 0,
            "double_doubles": 60,
            "finals_mvp_awards": 0,
            "championships": 3,
            "mvp_awards": 0,
            "dpoy_awards": 0,
            "all_star_appearances": 4,
            "all_wnba_teams": 2,
            "scoring_titles": 0,
            "game_high_points": 27,
            "career_high_points": 27,
            "total_playoff_points": 200
        },
        {
            "player_name": "Ruthie Bolton",
            "seasons_played": 8,
            "games_played": 228,
            "minutes_played": 6500,
            "points": 2500,
            "rebounds": 600,
            "assists": 450,
            "steals": 300,
            "blocks": 50,
            "field_goals_made": 900,
            "field_goal_attempts": 2200,
            "field_goal_percentage": 40.9,
            "three_pointers_made": 290,
            "three_pointer_attempts": 840,
            "three_pointer_percentage": 34.5,
            "free_throws_made": 700,
            "free_throw_attempts": 870,
            "free_throw_percentage": 80.5,
            "usage_rate": 25.0,
            "turnover_percentage": 14.5,
            "true_shooting_percentage": 51.5,
            "effective_fg_percentage": 47.0,
            "player_efficiency_rating": 17.5,
            "win_shares": 10.0,
            "plus_minus": 1.5,
            "off_bpm": 1.0,
            "def_bpm": 0.5,
            "vorp": 6.0,
            "triple_doubles": 0,
            "double_doubles": 20,
            "finals_mvp_awards": 0,
            "championships": 0,
            "mvp_awards": 0,
            "dpoy_awards": 0,
            "all_star_appearances": 2,
            "all_wnba_teams": 1,
            "scoring_titles": 0,
            "game_high_points": 31,
            "career_high_points": 31,
            "total_playoff_points": 120
        },
        {
            "player_name": "Jia Perkins",
            "seasons_played": 13,
            "games_played": 378,
            "minutes_played": 10400,
            "points": 4300,
            "rebounds": 1100,
            "assists": 800,
            "steals": 600,
            "blocks": 100,
            "field_goals_made": 1500,
            "field_goal_attempts": 3800,
            "field_goal_percentage": 39.5,
            "three_pointers_made": 400,
            "three_pointer_attempts": 1200,
            "three_pointer_percentage": 33.3,
            "free_throws_made": 900,
            "free_throw_attempts": 1100,
            "free_throw_percentage": 81.8,
            "usage_rate": 24.0,
            "turnover_percentage": 13.0,
            "true_shooting_percentage": 52.0,
            "effective_fg_percentage": 44.0,
            "player_efficiency_rating": 16.0,
            "win_shares": 18.0,
            "plus_minus": 1.0,
            "off_bpm": 1.0,
            "def_bpm": 0.0,
            "vorp": 7.0,
            "triple_doubles": 0,
            "double_doubles": 15,
            "finals_mvp_awards": 0,
            "championships": 1,
            "mvp_awards": 0,
            "dpoy_awards": 0,
            "all_star_appearances": 1,
            "all_wnba_teams": 0,
            "scoring_titles": 0,
            "game_high_points": 31,
            "career_high_points": 31,
            "total_playoff_points": 150
        },
        {
            "player_name": "Katie Smith",
            "seasons_played": 15,
            "games_played": 482,
            "minutes_played": 13900,
            "points": 6000,
            "rebounds": 900,
            "assists": 1100,
            "steals": 350,
            "blocks": 90,
            "field_goals_made": 2200,
            "field_goal_attempts": 5500,
            "field_goal_percentage": 40.0,
            "three_pointers_made": 600,
            "three_pointer_attempts": 1800,
            "three_pointer_percentage": 33.3,
            "free_throws_made": 1000,
            "free_throw_attempts": 1200,
            "free_throw_percentage": 83.3,
            "usage_rate": 24.0,
            "turnover_percentage": 12.0,
            "true_shooting_percentage": 53.0,
            "effective_fg_percentage": 46.5,
            "player_efficiency_rating": 17.0,
            "win_shares": 25.0,
            "plus_minus": 2.0,
            "off_bpm": 1.5,
            "def_bpm": 0.5,
            "vorp": 11.0,
            "triple_doubles": 0,
            "double_doubles": 35,
            "finals_mvp_awards": 0,
            "championships": 2,
            "mvp_awards": 0,
            "dpoy_awards": 0,
            "all_star_appearances": 7,
            "all_wnba_teams": 2,
            "scoring_titles": 0,
            "game_high_points": 34,
            "career_high_points": 34,
            "total_playoff_points": 220
        },
        {
            "player_name": "Teresa Weatherspoon",
            "seasons_played": 8,
            "games_played": 220,
            "minutes_played": 6500,
            "points": 1900,
            "rebounds": 800,
            "assists": 1500,
            "steals": 400,
            "blocks": 20,
            "field_goals_made": 700,
            "field_goal_attempts": 1700,
            "field_goal_percentage": 41.2,
            "three_pointers_made": 75,
            "three_pointer_attempts": 250,
            "three_pointer_percentage": 30.0,
            "free_throws_made": 400,
            "free_throw_attempts": 560,
            "free_throw_percentage": 71.0,
            "usage_rate": 20.0,
            "turnover_percentage": 16.0,
            "true_shooting_percentage": 47.5,
            "effective_fg_percentage": 44.0,
            "player_efficiency_rating": 14.0,
            "win_shares": 15.0,
            "plus_minus": 2.0,
            "off_bpm": 1.0,
            "def_bpm": 1.0,
            "vorp": 8.0,
            "triple_doubles": 0,
            "double_doubles": 30,
            "finals_mvp_awards": 0,
            "championships": 0,
            "mvp_awards": 0,
            "dpoy_awards": 2,
            "all_star_appearances": 3,
            "all_wnba_teams": 2,
            "scoring_titles": 0,
            "game_high_points": 25,
            "career_high_points": 25,
            "total_playoff_points": 120
        },
        {
            "player_name": "Candice Dupree",
            "seasons_played": 15,
            "games_played": 494,
            "minutes_played": 14500,
            "points": 6000,
            "rebounds": 2600,
            "assists": 800,
            "steals": 400,
            "blocks": 230,
            "field_goals_made": 2500,
            "field_goal_attempts": 4900,
            "field_goal_percentage": 51.0,
            "three_pointers_made": 60,
            "three_pointer_attempts": 200,
            "three_pointer_percentage": 30.0,
            "free_throws_made": 950,
            "free_throw_attempts": 1150,
            "free_throw_percentage": 82.6,
            "usage_rate": 21.0,
            "turnover_percentage": 11.0,
            "true_shooting_percentage": 56.0,
            "effective_fg_percentage": 51.5,
            "player_efficiency_rating": 18.0,
            "win_shares": 28.0,
            "plus_minus": 1.5,
            "off_bpm": 1.0,
            "def_bpm": 0.5,
            "vorp": 9.0,
            "triple_doubles": 0,
            "double_doubles": 80,
            "finals_mvp_awards": 0,
            "championships": 1,
            "mvp_awards": 0,
            "dpoy_awards": 0,
            "all_star_appearances": 7,
            "all_wnba_teams": 3,
            "scoring_titles": 0,
            "game_high_points": 32,
            "career_high_points": 32,
            "total_playoff_points": 230
        }
        # We have now listed 30 players total. 
        # If you see fewer than 30, add more players or expand data as needed.
    ]

    # Write out to CSV
    with open(filename, mode="w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=headers)
        writer.writeheader()
        for pdata in players_data:
            # Make sure missing fields are set to 0 or something safe
            for h in headers:
                if h not in pdata:
                    pdata[h] = 0
            writer.writerow(pdata)

if __name__ == "__main__":
    create_wnba_dataset()
    print("wnba_dataset.csv has been created with 30 players and 40 stats each.")
