import csv

def create_womens_golf_dataset(filename="womens_golf_dataset.csv"):
    """
    Creates a CSV file containing 30 women's golf players, each with 40+ stats.
    The CSV will have 41 columns total (player_name + 40 stats).

    All data here is approximate or placeholder. These 30 players
    include legends and modern stars from different eras.
    """

    # Define the header (1 player_name + 40 stats = 41 columns)
    headers = [
        "player_name",
        "country",
        "years_active",
        "total_lpga_tour_wins",
        "total_let_tour_wins",
        "total_major_wins",
        "times_world_no1",
        "total_weeks_at_no1",
        "cme_globe_championships",      
        "runner_ups_in_majors",
        "top_10_in_majors",
        "solheim_cups_played",
        "scoring_average",
        "average_driving_distance_yards",
        "leading_money_list_times",
        "lpga_player_of_year_times",
        "vardon_trophy_equiv_times",
        "rolex_player_of_year_times",
        "career_earnings_million_usd",
        "doping_tests_passed",
        "doping_tests_failed",
        "hall_of_fame_inducted",
        "signature_tournaments_won",
        "seasons_in_top50_world_ranking",
        "wins_across_all_tours",
        "runner_ups_total",
        "avg_putting_strokes_per_round",
        "hole_in_ones",
        "top_5_in_majors",
        "top_3_in_majors",
        "wins_outside_lpga_let",
        "wedge_distance_proximity_feet",
        "strokes_gained_off_tee",
        "strokes_gained_approach",
        "strokes_gained_putting",
        "strokes_gained_tee_to_green",
        "comebacks_from_54_hole_deficit",
        "comebacks_final_round_deficit",
        "notable_awards",
        "retirement_year",
        "coach_name"
    ]

    # Exactly 30 players, each with 41 fields
    players_data = [
        {
            "player_name": "Annika Sorenstam",
            "country": "Sweden",
            "years_active": 16,
            "total_lpga_tour_wins": 72,
            "total_let_tour_wins": 17,
            "total_major_wins": 10,
            "times_world_no1": 3,
            "total_weeks_at_no1": 60,
            "cme_globe_championships": 0, 
            "runner_ups_in_majors": 11,
            "top_10_in_majors": 61,
            "solheim_cups_played": 8,
            "scoring_average": 69.7,
            "average_driving_distance_yards": 265.0,
            "leading_money_list_times": 8,
            "lpga_player_of_year_times": 8,
            "vardon_trophy_equiv_times": 6,  # Vare Trophy
            "rolex_player_of_year_times": 8,
            "career_earnings_million_usd": 22.6,
            "doping_tests_passed": 30,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "signature_tournaments_won": 12,
            "seasons_in_top50_world_ranking": 10,
            "wins_across_all_tours": 93,
            "runner_ups_total": 40,
            "avg_putting_strokes_per_round": 29.3,
            "hole_in_ones": 8,
            "top_5_in_majors": 25,
            "top_3_in_majors": 16,
            "wins_outside_lpga_let": 4,
            "wedge_distance_proximity_feet": 18.0,
            "strokes_gained_off_tee": 1.2,
            "strokes_gained_approach": 1.5,
            "strokes_gained_putting": 0.8,
            "strokes_gained_tee_to_green": 2.7,
            "comebacks_from_54_hole_deficit": 5,
            "comebacks_final_round_deficit": 4,
            "notable_awards": 7,
            "retirement_year": 2008,
            "coach_name": "Henri Reis"
        },
        {
            "player_name": "Karrie Webb",
            "country": "Australia",
            "years_active": 25,
            "total_lpga_tour_wins": 41,
            "total_let_tour_wins": 15,
            "total_major_wins": 7,
            "times_world_no1": 0,
            "total_weeks_at_no1": 25,
            "cme_globe_championships": 0,
            "runner_ups_in_majors": 13,
            "top_10_in_majors": 49,
            "solheim_cups_played": 0,
            "scoring_average": 70.2,
            "average_driving_distance_yards": 255.0,
            "leading_money_list_times": 4,
            "lpga_player_of_year_times": 2,
            "vardon_trophy_equiv_times": 3,
            "rolex_player_of_year_times": 1,
            "career_earnings_million_usd": 20.3,
            "doping_tests_passed": 25,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "signature_tournaments_won": 9,
            "seasons_in_top50_world_ranking": 12,
            "wins_across_all_tours": 57,
            "runner_ups_total": 38,
            "avg_putting_strokes_per_round": 29.6,
            "hole_in_ones": 11,
            "top_5_in_majors": 22,
            "top_3_in_majors": 15,
            "wins_outside_lpga_let": 1,
            "wedge_distance_proximity_feet": 20.0,
            "strokes_gained_off_tee": 1.0,
            "strokes_gained_approach": 1.3,
            "strokes_gained_putting": 0.6,
            "strokes_gained_tee_to_green": 2.0,
            "comebacks_from_54_hole_deficit": 3,
            "comebacks_final_round_deficit": 5,
            "notable_awards": 5,
            "retirement_year": 0,
            "coach_name": "Ian Triggs"
        },
        {
            "player_name": "Se Ri Pak",
            "country": "South Korea",
            "years_active": 19,
            "total_lpga_tour_wins": 25,
            "total_let_tour_wins": 0,
            "total_major_wins": 5,
            "times_world_no1": 0,
            "total_weeks_at_no1": 0,
            "cme_globe_championships": 0,
            "runner_ups_in_majors": 7,
            "top_10_in_majors": 28,
            "solheim_cups_played": 0,
            "scoring_average": 70.7,
            "average_driving_distance_yards": 260.0,
            "leading_money_list_times": 2,
            "lpga_player_of_year_times": 1,
            "vardon_trophy_equiv_times": 0,
            "rolex_player_of_year_times": 1,
            "career_earnings_million_usd": 12.5,
            "doping_tests_passed": 20,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "signature_tournaments_won": 4,
            "seasons_in_top50_world_ranking": 6,
            "wins_across_all_tours": 30,
            "runner_ups_total": 20,
            "avg_putting_strokes_per_round": 29.7,
            "hole_in_ones": 7,
            "top_5_in_majors": 18,
            "top_3_in_majors": 10,
            "wins_outside_lpga_let": 5,
            "wedge_distance_proximity_feet": 21.0,
            "strokes_gained_off_tee": 0.7,
            "strokes_gained_approach": 1.0,
            "strokes_gained_putting": 0.5,
            "strokes_gained_tee_to_green": 1.8,
            "comebacks_from_54_hole_deficit": 2,
            "comebacks_final_round_deficit": 3,
            "notable_awards": 4,
            "retirement_year": 2016,
            "coach_name": "Self-taught"
        },
        {
            "player_name": "Lorena Ochoa",
            "country": "Mexico",
            "years_active": 8,
            "total_lpga_tour_wins": 27,
            "total_let_tour_wins": 2,
            "total_major_wins": 2,
            "times_world_no1": 1,
            "total_weeks_at_no1": 158,
            "cme_globe_championships": 0,
            "runner_ups_in_majors": 3,
            "top_10_in_majors": 16,
            "solheim_cups_played": 0,
            "scoring_average": 69.5,
            "average_driving_distance_yards": 270.0,
            "leading_money_list_times": 3,
            "lpga_player_of_year_times": 4,
            "vardon_trophy_equiv_times": 3,  # Vare Trophy
            "rolex_player_of_year_times": 4,
            "career_earnings_million_usd": 15.1,
            "doping_tests_passed": 15,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "signature_tournaments_won": 4,
            "seasons_in_top50_world_ranking": 5,
            "wins_across_all_tours": 30,
            "runner_ups_total": 12,
            "avg_putting_strokes_per_round": 28.9,
            "hole_in_ones": 5,
            "top_5_in_majors": 10,
            "top_3_in_majors": 7,
            "wins_outside_lpga_let": 1,
            "wedge_distance_proximity_feet": 17.5,
            "strokes_gained_off_tee": 1.2,
            "strokes_gained_approach": 1.6,
            "strokes_gained_putting": 1.0,
            "strokes_gained_tee_to_green": 2.8,
            "comebacks_from_54_hole_deficit": 3,
            "comebacks_final_round_deficit": 4,
            "notable_awards": 5,
            "retirement_year": 2010,
            "coach_name": "Rafael Alarcon"
        },
        {
            "player_name": "Patty Berg",
            "country": "USA",
            "years_active": 30,
            "total_lpga_tour_wins": 60,
            "total_let_tour_wins": 0,
            "total_major_wins": 15,
            "times_world_no1": 0,
            "total_weeks_at_no1": 0,
            "cme_globe_championships": 0,
            "runner_ups_in_majors": 12,
            "top_10_in_majors": 40,
            "solheim_cups_played": 0,
            "scoring_average": 73.5,
            "average_driving_distance_yards": 230.0,
            "leading_money_list_times": 1,
            "lpga_player_of_year_times": 0,
            "vardon_trophy_equiv_times": 0,
            "rolex_player_of_year_times": 0,
            "career_earnings_million_usd": 0.4,
            "doping_tests_passed": 0,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "signature_tournaments_won": 10,
            "seasons_in_top50_world_ranking": 0,
            "wins_across_all_tours": 66,
            "runner_ups_total": 30,
            "avg_putting_strokes_per_round": 31.5,
            "hole_in_ones": 8,
            "top_5_in_majors": 25,
            "top_3_in_majors": 18,
            "wins_outside_lpga_let": 6,
            "wedge_distance_proximity_feet": 30.0,
            "strokes_gained_off_tee": 0.0,
            "strokes_gained_approach": 0.0,
            "strokes_gained_putting": 0.0,
            "strokes_gained_tee_to_green": 0.0,
            "comebacks_from_54_hole_deficit": 5,
            "comebacks_final_round_deficit": 6,
            "notable_awards": 3,
            "retirement_year": 1966,
            "coach_name": "Self-taught"
        },
        {
            "player_name": "Mickey Wright",
            "country": "USA",
            "years_active": 26,
            "total_lpga_tour_wins": 82,
            "total_let_tour_wins": 0,
            "total_major_wins": 13,
            "times_world_no1": 0,
            "total_weeks_at_no1": 0,
            "cme_globe_championships": 0,
            "runner_ups_in_majors": 11,
            "top_10_in_majors": 45,
            "solheim_cups_played": 0,
            "scoring_average": 72.1,
            "average_driving_distance_yards": 240.0,
            "leading_money_list_times": 7,
            "lpga_player_of_year_times": 0,
            "vardon_trophy_equiv_times": 5,
            "rolex_player_of_year_times": 0,
            "career_earnings_million_usd": 0.78,
            "doping_tests_passed": 0,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "signature_tournaments_won": 15,
            "seasons_in_top50_world_ranking": 0,
            "wins_across_all_tours": 90,
            "runner_ups_total": 30,
            "avg_putting_strokes_per_round": 30.1,
            "hole_in_ones": 5,
            "top_5_in_majors": 35,
            "top_3_in_majors": 25,
            "wins_outside_lpga_let": 8,
            "wedge_distance_proximity_feet": 28.0,
            "strokes_gained_off_tee": 0.0,
            "strokes_gained_approach": 0.0,
            "strokes_gained_putting": 0.0,
            "strokes_gained_tee_to_green": 0.0,
            "comebacks_from_54_hole_deficit": 6,
            "comebacks_final_round_deficit": 7,
            "notable_awards": 4,
            "retirement_year": 1973,
            "coach_name": "Self-taught"
        },
        {
            "player_name": "Babe Zaharias",
            "country": "USA",
            "years_active": 16,
            "total_lpga_tour_wins": 41,
            "total_let_tour_wins": 0,
            "total_major_wins": 10,
            "times_world_no1": 0,
            "total_weeks_at_no1": 0,
            "cme_globe_championships": 0,
            "runner_ups_in_majors": 5,
            "top_10_in_majors": 28,
            "solheim_cups_played": 0,
            "scoring_average": 73.0,
            "average_driving_distance_yards": 235.0,
            "leading_money_list_times": 1,
            "lpga_player_of_year_times": 0,
            "vardon_trophy_equiv_times": 0,
            "rolex_player_of_year_times": 0,
            "career_earnings_million_usd": 0.3,
            "doping_tests_passed": 0,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "signature_tournaments_won": 8,
            "seasons_in_top50_world_ranking": 0,
            "wins_across_all_tours": 50,
            "runner_ups_total": 20,
            "avg_putting_strokes_per_round": 31.0,
            "hole_in_ones": 7,
            "top_5_in_majors": 18,
            "top_3_in_majors": 12,
            "wins_outside_lpga_let": 4,
            "wedge_distance_proximity_feet": 29.0,
            "strokes_gained_off_tee": 0.0,
            "strokes_gained_approach": 0.0,
            "strokes_gained_putting": 0.0,
            "strokes_gained_tee_to_green": 0.0,
            "comebacks_from_54_hole_deficit": 3,
            "comebacks_final_round_deficit": 3,
            "notable_awards": 6,
            "retirement_year": 1956,
            "coach_name": "Self-taught"
        },
        {
            "player_name": "Nancy Lopez",
            "country": "USA",
            "years_active": 25,
            "total_lpga_tour_wins": 48,
            "total_let_tour_wins": 0,
            "total_major_wins": 3,
            "times_world_no1": 0,
            "total_weeks_at_no1": 0,
            "cme_globe_championships": 0,
            "runner_ups_in_majors": 8,
            "top_10_in_majors": 29,
            "solheim_cups_played": 1,
            "scoring_average": 70.9,
            "average_driving_distance_yards": 240.0,
            "leading_money_list_times": 3,
            "lpga_player_of_year_times": 4,
            "vardon_trophy_equiv_times": 3,
            "rolex_player_of_year_times": 0,
            "career_earnings_million_usd": 5.3,
            "doping_tests_passed": 0,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "signature_tournaments_won": 8,
            "seasons_in_top50_world_ranking": 0,
            "wins_across_all_tours": 50,
            "runner_ups_total": 25,
            "avg_putting_strokes_per_round": 29.9,
            "hole_in_ones": 10,
            "top_5_in_majors": 20,
            "top_3_in_majors": 12,
            "wins_outside_lpga_let": 3,
            "wedge_distance_proximity_feet": 27.0,
            "strokes_gained_off_tee": 0.0,
            "strokes_gained_approach": 0.0,
            "strokes_gained_putting": 0.0,
            "strokes_gained_tee_to_green": 0.0,
            "comebacks_from_54_hole_deficit": 4,
            "comebacks_final_round_deficit": 4,
            "notable_awards": 6,
            "retirement_year": 2003,
            "coach_name": "Self-taught"
        },
        {
            "player_name": "Betsy King",
            "country": "USA",
            "years_active": 28,
            "total_lpga_tour_wins": 34,
            "total_let_tour_wins": 0,
            "total_major_wins": 6,
            "times_world_no1": 0,
            "total_weeks_at_no1": 0,
            "cme_globe_championships": 0,
            "runner_ups_in_majors": 5,
            "top_10_in_majors": 37,
            "solheim_cups_played": 5,
            "scoring_average": 70.8,
            "average_driving_distance_yards": 245.0,
            "leading_money_list_times": 3,
            "lpga_player_of_year_times": 2,
            "vardon_trophy_equiv_times": 3,
            "rolex_player_of_year_times": 0,
            "career_earnings_million_usd": 7.0,
            "doping_tests_passed": 0,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "signature_tournaments_won": 5,
            "seasons_in_top50_world_ranking": 0,
            "wins_across_all_tours": 39,
            "runner_ups_total": 20,
            "avg_putting_strokes_per_round": 29.8,
            "hole_in_ones": 8,
            "top_5_in_majors": 15,
            "top_3_in_majors": 10,
            "wins_outside_lpga_let": 2,
            "wedge_distance_proximity_feet": 28.0,
            "strokes_gained_off_tee": 0.0,
            "strokes_gained_approach": 0.0,
            "strokes_gained_putting": 0.0,
            "strokes_gained_tee_to_green": 0.0,
            "comebacks_from_54_hole_deficit": 3,
            "comebacks_final_round_deficit": 3,
            "notable_awards": 4,
            "retirement_year": 2005,
            "coach_name": "Ed Oldfield"
        },
        {
            "player_name": "Kathy Whitworth",
            "country": "USA",
            "years_active": 33,
            "total_lpga_tour_wins": 88, 
            "total_let_tour_wins": 0,
            "total_major_wins": 6,
            "times_world_no1": 0,
            "total_weeks_at_no1": 0,
            "cme_globe_championships": 0,
            "runner_ups_in_majors": 10,
            "top_10_in_majors": 45,
            "solheim_cups_played": 0,
            "scoring_average": 71.2,
            "average_driving_distance_yards": 235.0,
            "leading_money_list_times": 8,
            "lpga_player_of_year_times": 7,
            "vardon_trophy_equiv_times": 7, 
            "rolex_player_of_year_times": 0,
            "career_earnings_million_usd": 1.2,
            "doping_tests_passed": 0,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "signature_tournaments_won": 15,
            "seasons_in_top50_world_ranking": 0,
            "wins_across_all_tours": 100,
            "runner_ups_total": 90,
            "avg_putting_strokes_per_round": 30.2,
            "hole_in_ones": 11,
            "top_5_in_majors": 32,
            "top_3_in_majors": 20,
            "wins_outside_lpga_let": 5,
            "wedge_distance_proximity_feet": 28.0,
            "strokes_gained_off_tee": 0.0,
            "strokes_gained_approach": 0.0,
            "strokes_gained_putting": 0.0,
            "strokes_gained_tee_to_green": 0.0,
            "comebacks_from_54_hole_deficit": 8,
            "comebacks_final_round_deficit": 6,
            "notable_awards": 6,
            "retirement_year": 2005,
            "coach_name": "Self-taught"
        },
        {
            "player_name": "Louise Suggs",
            "country": "USA",
            "years_active": 22,
            "total_lpga_tour_wins": 61,
            "total_let_tour_wins": 0,
            "total_major_wins": 11,
            "times_world_no1": 0,
            "total_weeks_at_no1": 0,
            "cme_globe_championships": 0,
            "runner_ups_in_majors": 6,
            "top_10_in_majors": 34,
            "solheim_cups_played": 0,
            "scoring_average": 73.1,
            "average_driving_distance_yards": 230.0,
            "leading_money_list_times": 1,
            "lpga_player_of_year_times": 0,
            "vardon_trophy_equiv_times": 0,
            "rolex_player_of_year_times": 0,
            "career_earnings_million_usd": 0.2,
            "doping_tests_passed": 0,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "signature_tournaments_won": 10,
            "seasons_in_top50_world_ranking": 0,
            "wins_across_all_tours": 58,
            "runner_ups_total": 25,
            "avg_putting_strokes_per_round": 31.2,
            "hole_in_ones": 6,
            "top_5_in_majors": 20,
            "top_3_in_majors": 15,
            "wins_outside_lpga_let": 3,
            "wedge_distance_proximity_feet": 29.0,
            "strokes_gained_off_tee": 0.0,
            "strokes_gained_approach": 0.0,
            "strokes_gained_putting": 0.0,
            "strokes_gained_tee_to_green": 0.0,
            "comebacks_from_54_hole_deficit": 4,
            "comebacks_final_round_deficit": 4,
            "notable_awards": 3,
            "retirement_year": 1962,
            "coach_name": "Self-taught"
        },
        # 12
        {
            "player_name": "Juli Inkster",
            "country": "USA",
            "years_active": 36,
            "total_lpga_tour_wins": 31,
            "total_let_tour_wins": 0,
            "total_major_wins": 7,
            "times_world_no1": 0,
            "total_weeks_at_no1": 0,
            "cme_globe_championships": 0,
            "runner_ups_in_majors": 5,
            "top_10_in_majors": 35,
            "solheim_cups_played": 9,
            "scoring_average": 71.0,
            "average_driving_distance_yards": 245.0,
            "leading_money_list_times": 2,
            "lpga_player_of_year_times": 2,
            "vardon_trophy_equiv_times": 2,
            "rolex_player_of_year_times": 0,
            "career_earnings_million_usd": 14.0,
            "doping_tests_passed": 5,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "signature_tournaments_won": 5,
            "seasons_in_top50_world_ranking": 5,
            "wins_across_all_tours": 34,
            "runner_ups_total": 30,
            "avg_putting_strokes_per_round": 29.9,
            "hole_in_ones": 6,
            "top_5_in_majors": 20,
            "top_3_in_majors": 13,
            "wins_outside_lpga_let": 3,
            "wedge_distance_proximity_feet": 26.5,
            "strokes_gained_off_tee": 0.2,
            "strokes_gained_approach": 0.4,
            "strokes_gained_putting": 0.3,
            "strokes_gained_tee_to_green": 0.7,
            "comebacks_from_54_hole_deficit": 4,
            "comebacks_final_round_deficit": 5,
            "notable_awards": 4,
            "retirement_year": 2023,
            "coach_name": "Brian Inkster"
        },
        # 13
        {
            "player_name": "Inbee Park",
            "country": "South Korea",
            "years_active": 16,
            "total_lpga_tour_wins": 21,
            "total_let_tour_wins": 3,
            "total_major_wins": 7,
            "times_world_no1": 4,
            "total_weeks_at_no1": 106,
            "cme_globe_championships": 1,
            "runner_ups_in_majors": 6,
            "top_10_in_majors": 30,
            "solheim_cups_played": 0, 
            "scoring_average": 69.9,
            "average_driving_distance_yards": 250.0,
            "leading_money_list_times": 3,
            "lpga_player_of_year_times": 2,
            "vardon_trophy_equiv_times": 3,
            "rolex_player_of_year_times": 2,
            "career_earnings_million_usd": 17.0,
            "doping_tests_passed": 20,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "signature_tournaments_won": 5,
            "seasons_in_top50_world_ranking": 10,
            "wins_across_all_tours": 28,
            "runner_ups_total": 19,
            "avg_putting_strokes_per_round": 28.5,
            "hole_in_ones": 4,
            "top_5_in_majors": 18,
            "top_3_in_majors": 12,
            "wins_outside_lpga_let": 4,
            "wedge_distance_proximity_feet": 19.0,
            "strokes_gained_off_tee": 0.8,
            "strokes_gained_approach": 1.0,
            "strokes_gained_putting": 1.5,
            "strokes_gained_tee_to_green": 2.0,
            "comebacks_from_54_hole_deficit": 2,
            "comebacks_final_round_deficit": 3,
            "notable_awards": 6,
            "retirement_year": 0,
            "coach_name": "Gi Hyeob Nam"
        },
        # 14
        {
            "player_name": "Yani Tseng",
            "country": "Taiwan",
            "years_active": 14,
            "total_lpga_tour_wins": 15,
            "total_let_tour_wins": 4,
            "total_major_wins": 5,
            "times_world_no1": 1,
            "total_weeks_at_no1": 109,
            "cme_globe_championships": 0,
            "runner_ups_in_majors": 3,
            "top_10_in_majors": 16,
            "solheim_cups_played": 0,
            "scoring_average": 70.2,
            "average_driving_distance_yards": 265.0,
            "leading_money_list_times": 1,
            "lpga_player_of_year_times": 2,
            "vardon_trophy_equiv_times": 2,
            "rolex_player_of_year_times": 2,
            "career_earnings_million_usd": 10.2,
            "doping_tests_passed": 20,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 0,
            "signature_tournaments_won": 2,
            "seasons_in_top50_world_ranking": 8,
            "wins_across_all_tours": 21,
            "runner_ups_total": 10,
            "avg_putting_strokes_per_round": 29.5,
            "hole_in_ones": 3,
            "top_5_in_majors": 12,
            "top_3_in_majors": 8,
            "wins_outside_lpga_let": 2,
            "wedge_distance_proximity_feet": 20.0,
            "strokes_gained_off_tee": 1.0,
            "strokes_gained_approach": 1.2,
            "strokes_gained_putting": 0.5,
            "strokes_gained_tee_to_green": 2.2,
            "comebacks_from_54_hole_deficit": 3,
            "comebacks_final_round_deficit": 2,
            "notable_awards": 4,
            "retirement_year": 0,
            "coach_name": "Gary Gilchrist"
        },
        # 15
        {
            "player_name": "Lydia Ko",
            "country": "New Zealand",
            "years_active": 11,
            "total_lpga_tour_wins": 19,
            "total_let_tour_wins": 6,
            "total_major_wins": 2,
            "times_world_no1": 2,
            "total_weeks_at_no1": 130,
            "cme_globe_championships": 2,
            "runner_ups_in_majors": 4,
            "top_10_in_majors": 25,
            "solheim_cups_played": 0, # not applicable, but there's Intl Crown
            "scoring_average": 69.0,
            "average_driving_distance_yards": 260.0,
            "leading_money_list_times": 2,
            "lpga_player_of_year_times": 2,
            "vardon_trophy_equiv_times": 2,
            "rolex_player_of_year_times": 2,
            "career_earnings_million_usd": 15.5,
            "doping_tests_passed": 25,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 0,
            "signature_tournaments_won": 5,
            "seasons_in_top50_world_ranking": 9,
            "wins_across_all_tours": 25,
            "runner_ups_total": 14,
            "avg_putting_strokes_per_round": 28.7,
            "hole_in_ones": 2,
            "top_5_in_majors": 12,
            "top_3_in_majors": 8,
            "wins_outside_lpga_let": 1,
            "wedge_distance_proximity_feet": 18.5,
            "strokes_gained_off_tee": 0.8,
            "strokes_gained_approach": 1.4,
            "strokes_gained_putting": 1.3,
            "strokes_gained_tee_to_green": 2.4,
            "comebacks_from_54_hole_deficit": 3,
            "comebacks_final_round_deficit": 3,
            "notable_awards": 6,
            "retirement_year": 0,
            "coach_name": "Sean Foley"
        },
        # 16
        {
            "player_name": "Sandra Haynie",
            "country": "USA",
            "years_active": 28,
            "total_lpga_tour_wins": 42,
            "total_let_tour_wins": 0,
            "total_major_wins": 4,
            "times_world_no1": 0,
            "total_weeks_at_no1": 0,
            "cme_globe_championships": 0,
            "runner_ups_in_majors": 8,
            "top_10_in_majors": 30,
            "solheim_cups_played": 0,
            "scoring_average": 71.5,
            "average_driving_distance_yards": 235.0,
            "leading_money_list_times": 2,
            "lpga_player_of_year_times": 1,
            "vardon_trophy_equiv_times": 1,
            "rolex_player_of_year_times": 0,
            "career_earnings_million_usd": 2.1,
            "doping_tests_passed": 0,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "signature_tournaments_won": 5,
            "seasons_in_top50_world_ranking": 0,
            "wins_across_all_tours": 47,
            "runner_ups_total": 25,
            "avg_putting_strokes_per_round": 30.5,
            "hole_in_ones": 4,
            "top_5_in_majors": 18,
            "top_3_in_majors": 12,
            "wins_outside_lpga_let": 2,
            "wedge_distance_proximity_feet": 29.0,
            "strokes_gained_off_tee": 0.0,
            "strokes_gained_approach": 0.0,
            "strokes_gained_putting": 0.0,
            "strokes_gained_tee_to_green": 0.0,
            "comebacks_from_54_hole_deficit": 3,
            "comebacks_final_round_deficit": 3,
            "notable_awards": 3,
            "retirement_year": 1990,
            "coach_name": "Self-taught"
        },
        # 17
        {
            "player_name": "Carol Mann",
            "country": "USA",
            "years_active": 23,
            "total_lpga_tour_wins": 38,
            "total_let_tour_wins": 0,
            "total_major_wins": 2,
            "times_world_no1": 0,
            "total_weeks_at_no1": 0,
            "cme_globe_championships": 0,
            "runner_ups_in_majors": 5,
            "top_10_in_majors": 25,
            "solheim_cups_played": 0,
            "scoring_average": 72.4,
            "average_driving_distance_yards": 230.0,
            "leading_money_list_times": 2,
            "lpga_player_of_year_times": 1,
            "vardon_trophy_equiv_times": 1,
            "rolex_player_of_year_times": 0,
            "career_earnings_million_usd": 0.9,
            "doping_tests_passed": 0,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "signature_tournaments_won": 4,
            "seasons_in_top50_world_ranking": 0,
            "wins_across_all_tours": 40,
            "runner_ups_total": 20,
            "avg_putting_strokes_per_round": 31.0,
            "hole_in_ones": 3,
            "top_5_in_majors": 15,
            "top_3_in_majors": 8,
            "wins_outside_lpga_let": 2,
            "wedge_distance_proximity_feet": 30.0,
            "strokes_gained_off_tee": 0.0,
            "strokes_gained_approach": 0.0,
            "strokes_gained_putting": 0.0,
            "strokes_gained_tee_to_green": 0.0,
            "comebacks_from_54_hole_deficit": 2,
            "comebacks_final_round_deficit": 2,
            "notable_awards": 3,
            "retirement_year": 1981,
            "coach_name": "Self-taught"
        },
        # 18
        {
            "player_name": "Suzann Pettersen",
            "country": "Norway",
            "years_active": 17,
            "total_lpga_tour_wins": 15,
            "total_let_tour_wins": 7,
            "total_major_wins": 2,
            "times_world_no1": 0,
            "total_weeks_at_no1": 0,
            "cme_globe_championships": 0,
            "runner_ups_in_majors": 6,
            "top_10_in_majors": 28,
            "solheim_cups_played": 9,
            "scoring_average": 70.4,
            "average_driving_distance_yards": 265.0,
            "leading_money_list_times": 0,
            "lpga_player_of_year_times": 0,
            "vardon_trophy_equiv_times": 0,
            "rolex_player_of_year_times": 0,
            "career_earnings_million_usd": 14.8,
            "doping_tests_passed": 20,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 0,
            "signature_tournaments_won": 3,
            "seasons_in_top50_world_ranking": 10,
            "wins_across_all_tours": 23,
            "runner_ups_total": 15,
            "avg_putting_strokes_per_round": 29.4,
            "hole_in_ones": 4,
            "top_5_in_majors": 12,
            "top_3_in_majors": 7,
            "wins_outside_lpga_let": 1,
            "wedge_distance_proximity_feet": 20.5,
            "strokes_gained_off_tee": 0.9,
            "strokes_gained_approach": 1.1,
            "strokes_gained_putting": 0.5,
            "strokes_gained_tee_to_green": 2.0,
            "comebacks_from_54_hole_deficit": 3,
            "comebacks_final_round_deficit": 2,
            "notable_awards": 2,
            "retirement_year": 2019,
            "coach_name": "Butch Harmon"
        },
        # 19
        {
            "player_name": "Jiyai Shin",
            "country": "South Korea",
            "years_active": 14,
            "total_lpga_tour_wins": 11,
            "total_let_tour_wins": 2,
            "total_major_wins": 2,
            "times_world_no1": 2,
            "total_weeks_at_no1": 25,
            "cme_globe_championships": 0,
            "runner_ups_in_majors": 3,
            "top_10_in_majors": 20,
            "solheim_cups_played": 0,
            "scoring_average": 70.3,
            "average_driving_distance_yards": 255.0,
            "leading_money_list_times": 1,
            "lpga_player_of_year_times": 1,
            "vardon_trophy_equiv_times": 2,
            "rolex_player_of_year_times": 1,
            "career_earnings_million_usd": 9.0,
            "doping_tests_passed": 20,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 0,
            "signature_tournaments_won": 3,
            "seasons_in_top50_world_ranking": 8,
            "wins_across_all_tours": 16,
            "runner_ups_total": 9,
            "avg_putting_strokes_per_round": 29.2,
            "hole_in_ones": 2,
            "top_5_in_majors": 8,
            "top_3_in_majors": 5,
            "wins_outside_lpga_let": 2,
            "wedge_distance_proximity_feet": 19.0,
            "strokes_gained_off_tee": 0.6,
            "strokes_gained_approach": 1.0,
            "strokes_gained_putting": 0.7,
            "strokes_gained_tee_to_green": 1.9,
            "comebacks_from_54_hole_deficit": 2,
            "comebacks_final_round_deficit": 3,
            "notable_awards": 3,
            "retirement_year": 0,
            "coach_name": "Gareth Raflewski"
        },
        # 20
        {
            "player_name": "Jin Young Ko",
            "country": "South Korea",
            "years_active": 9,
            "total_lpga_tour_wins": 15,
            "total_let_tour_wins": 2,
            "total_major_wins": 2,
            "times_world_no1": 2,
            "total_weeks_at_no1": 150,
            "cme_globe_championships": 2,
            "runner_ups_in_majors": 3,
            "top_10_in_majors": 18,
            "solheim_cups_played": 0,
            "scoring_average": 69.2,
            "average_driving_distance_yards": 255.0,
            "leading_money_list_times": 2,
            "lpga_player_of_year_times": 1,
            "vardon_trophy_equiv_times": 1,
            "rolex_player_of_year_times": 2,
            "career_earnings_million_usd": 11.0,
            "doping_tests_passed": 20,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 0,
            "signature_tournaments_won": 4,
            "seasons_in_top50_world_ranking": 5,
            "wins_across_all_tours": 20,
            "runner_ups_total": 8,
            "avg_putting_strokes_per_round": 28.4,
            "hole_in_ones": 3,
            "top_5_in_majors": 12,
            "top_3_in_majors": 6,
            "wins_outside_lpga_let": 2,
            "wedge_distance_proximity_feet": 19.5,
            "strokes_gained_off_tee": 0.7,
            "strokes_gained_approach": 1.5,
            "strokes_gained_putting": 0.9,
            "strokes_gained_tee_to_green": 2.4,
            "comebacks_from_54_hole_deficit": 2,
            "comebacks_final_round_deficit": 3,
            "notable_awards": 4,
            "retirement_year": 0,
            "coach_name": "Lee Si-woo"
        },
        # 21
        {
            "player_name": "Stacy Lewis",
            "country": "USA",
            "years_active": 13,
            "total_lpga_tour_wins": 13,
            "total_let_tour_wins": 2,
            "total_major_wins": 2,
            "times_world_no1": 2,
            "total_weeks_at_no1": 21,
            "cme_globe_championships": 0,
            "runner_ups_in_majors": 4,
            "top_10_in_majors": 25,
            "solheim_cups_played": 5,
            "scoring_average": 70.3,
            "average_driving_distance_yards": 255.0,
            "leading_money_list_times": 2,
            "lpga_player_of_year_times": 1,
            "vardon_trophy_equiv_times": 2,  # Vare
            "rolex_player_of_year_times": 1,
            "career_earnings_million_usd": 14.5,
            "doping_tests_passed": 20,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 0,
            "signature_tournaments_won": 3,
            "seasons_in_top50_world_ranking": 8,
            "wins_across_all_tours": 16,
            "runner_ups_total": 14,
            "avg_putting_strokes_per_round": 29.5,
            "hole_in_ones": 2,
            "top_5_in_majors": 10,
            "top_3_in_majors": 6,
            "wins_outside_lpga_let": 1,
            "wedge_distance_proximity_feet": 21.0,
            "strokes_gained_off_tee": 0.6,
            "strokes_gained_approach": 0.9,
            "strokes_gained_putting": 0.5,
            "strokes_gained_tee_to_green": 1.8,
            "comebacks_from_54_hole_deficit": 2,
            "comebacks_final_round_deficit": 3,
            "notable_awards": 3,
            "retirement_year": 0,
            "coach_name": "Joe Hallett"
        },
        # 22
        {
            "player_name": "Paula Creamer",
            "country": "USA",
            "years_active": 18,
            "total_lpga_tour_wins": 10,
            "total_let_tour_wins": 2,
            "total_major_wins": 1,
            "times_world_no1": 0,
            "total_weeks_at_no1": 0,
            "cme_globe_championships": 0,
            "runner_ups_in_majors": 4,
            "top_10_in_majors": 22,
            "solheim_cups_played": 7,
            "scoring_average": 70.8,
            "average_driving_distance_yards": 250.0,
            "leading_money_list_times": 0,
            "lpga_player_of_year_times": 0,
            "vardon_trophy_equiv_times": 0,
            "rolex_player_of_year_times": 0,
            "career_earnings_million_usd": 12.0,
            "doping_tests_passed": 20,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 0,
            "signature_tournaments_won": 2,
            "seasons_in_top50_world_ranking": 9,
            "wins_across_all_tours": 13,
            "runner_ups_total": 10,
            "avg_putting_strokes_per_round": 29.8,
            "hole_in_ones": 4,
            "top_5_in_majors": 8,
            "top_3_in_majors": 5,
            "wins_outside_lpga_let": 1,
            "wedge_distance_proximity_feet": 22.5,
            "strokes_gained_off_tee": 0.5,
            "strokes_gained_approach": 0.7,
            "strokes_gained_putting": 0.4,
            "strokes_gained_tee_to_green": 1.2,
            "comebacks_from_54_hole_deficit": 2,
            "comebacks_final_round_deficit": 2,
            "notable_awards": 2,
            "retirement_year": 0,
            "coach_name": "David Whelan"
        },
        # 23
        {
            "player_name": "Cristie Kerr",
            "country": "USA",
            "years_active": 24,
            "total_lpga_tour_wins": 20,
            "total_let_tour_wins": 1,
            "total_major_wins": 2,
            "times_world_no1": 1,
            "total_weeks_at_no1": 5,
            "cme_globe_championships": 0,
            "runner_ups_in_majors": 6,
            "top_10_in_majors": 27,
            "solheim_cups_played": 9,
            "scoring_average": 70.7,
            "average_driving_distance_yards": 250.0,
            "leading_money_list_times": 0,
            "lpga_player_of_year_times": 0,
            "vardon_trophy_equiv_times": 1,
            "rolex_player_of_year_times": 0,
            "career_earnings_million_usd": 20.0,
            "doping_tests_passed": 20,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 0,
            "signature_tournaments_won": 3,
            "seasons_in_top50_world_ranking": 10,
            "wins_across_all_tours": 23,
            "runner_ups_total": 15,
            "avg_putting_strokes_per_round": 29.4,
            "hole_in_ones": 3,
            "top_5_in_majors": 12,
            "top_3_in_majors": 7,
            "wins_outside_lpga_let": 2,
            "wedge_distance_proximity_feet": 22.0,
            "strokes_gained_off_tee": 0.6,
            "strokes_gained_approach": 0.9,
            "strokes_gained_putting": 1.2,
            "strokes_gained_tee_to_green": 1.7,
            "comebacks_from_54_hole_deficit": 2,
            "comebacks_final_round_deficit": 3,
            "notable_awards": 3,
            "retirement_year": 0,
            "coach_name": "Martin Hall"
        },
        # 24
        {
            "player_name": "Ai Miyazato",
            "country": "Japan",
            "years_active": 12,
            "total_lpga_tour_wins": 9,
            "total_let_tour_wins": 2,
            "total_major_wins": 0,
            "times_world_no1": 1,
            "total_weeks_at_no1": 11,
            "cme_globe_championships": 0,
            "runner_ups_in_majors": 2,
            "top_10_in_majors": 10,
            "solheim_cups_played": 0,
            "scoring_average": 70.6,
            "average_driving_distance_yards": 245.0,
            "leading_money_list_times": 0,
            "lpga_player_of_year_times": 0,
            "vardon_trophy_equiv_times": 0,
            "rolex_player_of_year_times": 0,
            "career_earnings_million_usd": 8.0,
            "doping_tests_passed": 15,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 0,
            "signature_tournaments_won": 2,
            "seasons_in_top50_world_ranking": 6,
            "wins_across_all_tours": 12,
            "runner_ups_total": 8,
            "avg_putting_strokes_per_round": 29.2,
            "hole_in_ones": 2,
            "top_5_in_majors": 5,
            "top_3_in_majors": 3,
            "wins_outside_lpga_let": 1,
            "wedge_distance_proximity_feet": 23.0,
            "strokes_gained_off_tee": 0.3,
            "strokes_gained_approach": 0.5,
            "strokes_gained_putting": 0.7,
            "strokes_gained_tee_to_green": 1.2,
            "comebacks_from_54_hole_deficit": 2,
            "comebacks_final_round_deficit": 2,
            "notable_awards": 2,
            "retirement_year": 2017,
            "coach_name": "Guy Wilson"
        },
        # 25
        {
            "player_name": "Shanshan Feng",
            "country": "China",
            "years_active": 15,
            "total_lpga_tour_wins": 10,
            "total_let_tour_wins": 7,
            "total_major_wins": 1,
            "times_world_no1": 1,
            "total_weeks_at_no1": 23,
            "cme_globe_championships": 0,
            "runner_ups_in_majors": 3,
            "top_10_in_majors": 19,
            "solheim_cups_played": 0,
            "scoring_average": 70.3,
            "average_driving_distance_yards": 255.0,
            "leading_money_list_times": 0,
            "lpga_player_of_year_times": 0,
            "vardon_trophy_equiv_times": 1,
            "rolex_player_of_year_times": 0,
            "career_earnings_million_usd": 11.8,
            "doping_tests_passed": 20,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 0,
            "signature_tournaments_won": 3,
            "seasons_in_top50_world_ranking": 8,
            "wins_across_all_tours": 18,
            "runner_ups_total": 10,
            "avg_putting_strokes_per_round": 29.1,
            "hole_in_ones": 2,
            "top_5_in_majors": 10,
            "top_3_in_majors": 6,
            "wins_outside_lpga_let": 1,
            "wedge_distance_proximity_feet": 22.0,
            "strokes_gained_off_tee": 0.8,
            "strokes_gained_approach": 1.1,
            "strokes_gained_putting": 0.4,
            "strokes_gained_tee_to_green": 1.9,
            "comebacks_from_54_hole_deficit": 2,
            "comebacks_final_round_deficit": 2,
            "notable_awards": 3,
            "retirement_year": 2022,
            "coach_name": "Gary Gilchrist"
        },
        # 26
        {
            "player_name": "Nelly Korda",
            "country": "USA",
            "years_active": 7,
            "total_lpga_tour_wins": 8,
            "total_let_tour_wins": 1,
            "total_major_wins": 1,
            "times_world_no1": 1,
            "total_weeks_at_no1": 33,
            "cme_globe_championships": 0,
            "runner_ups_in_majors": 2,
            "top_10_in_majors": 12,
            "solheim_cups_played": 1,
            "scoring_average": 69.6,
            "average_driving_distance_yards": 265.0,
            "leading_money_list_times": 0,
            "lpga_player_of_year_times": 0,
            "vardon_trophy_equiv_times": 1,
            "rolex_player_of_year_times": 1,
            "career_earnings_million_usd": 7.0,
            "doping_tests_passed": 20,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 0,
            "signature_tournaments_won": 3,
            "seasons_in_top50_world_ranking": 5,
            "wins_across_all_tours": 10,
            "runner_ups_total": 5,
            "avg_putting_strokes_per_round": 28.6,
            "hole_in_ones": 2,
            "top_5_in_majors": 6,
            "top_3_in_majors": 4,
            "wins_outside_lpga_let": 1,
            "wedge_distance_proximity_feet": 18.5,
            "strokes_gained_off_tee": 1.0,
            "strokes_gained_approach": 1.2,
            "strokes_gained_putting": 0.6,
            "strokes_gained_tee_to_green": 2.2,
            "comebacks_from_54_hole_deficit": 2,
            "comebacks_final_round_deficit": 2,
            "notable_awards": 3,
            "retirement_year": 0,
            "coach_name": "David Whelan"
        },
        # 27
        {
            "player_name": "Ariya Jutanugarn",
            "country": "Thailand",
            "years_active": 11,
            "total_lpga_tour_wins": 12,
            "total_let_tour_wins": 5,
            "total_major_wins": 2,
            "times_world_no1": 2,
            "total_weeks_at_no1": 23,
            "cme_globe_championships": 1,
            "runner_ups_in_majors": 3,
            "top_10_in_majors": 16,
            "solheim_cups_played": 0, 
            "scoring_average": 69.8,
            "average_driving_distance_yards": 275.0,
            "leading_money_list_times": 1,
            "lpga_player_of_year_times": 1,
            "vardon_trophy_equiv_times": 1,
            "rolex_player_of_year_times": 1,
            "career_earnings_million_usd": 10.5,
            "doping_tests_passed": 20,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 0,
            "signature_tournaments_won": 3,
            "seasons_in_top50_world_ranking": 7,
            "wins_across_all_tours": 20,
            "runner_ups_total": 9,
            "avg_putting_strokes_per_round": 29.1,
            "hole_in_ones": 2,
            "top_5_in_majors": 9,
            "top_3_in_majors": 6,
            "wins_outside_lpga_let": 3,
            "wedge_distance_proximity_feet": 18.0,
            "strokes_gained_off_tee": 1.3,
            "strokes_gained_approach": 1.4,
            "strokes_gained_putting": 0.7,
            "strokes_gained_tee_to_green": 2.5,
            "comebacks_from_54_hole_deficit": 3,
            "comebacks_final_round_deficit": 3,
            "notable_awards": 4,
            "retirement_year": 0,
            "coach_name": "Gary Gilchrist"
        },
        # 28
        {
            "player_name": "Lexi Thompson",
            "country": "USA",
            "years_active": 13,
            "total_lpga_tour_wins": 11,
            "total_let_tour_wins": 1,
            "total_major_wins": 1,
            "times_world_no1": 0,
            "total_weeks_at_no1": 0,
            "cme_globe_championships": 1,
            "runner_ups_in_majors": 4,
            "top_10_in_majors": 19,
            "solheim_cups_played": 5,
            "scoring_average": 70.5,
            "average_driving_distance_yards": 275.0,
            "leading_money_list_times": 0,
            "lpga_player_of_year_times": 0,
            "vardon_trophy_equiv_times": 0,
            "rolex_player_of_year_times": 0,
            "career_earnings_million_usd": 12.3,
            "doping_tests_passed": 20,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 0,
            "signature_tournaments_won": 2,
            "seasons_in_top50_world_ranking": 9,
            "wins_across_all_tours": 13,
            "runner_ups_total": 12,
            "avg_putting_strokes_per_round": 29.3,
            "hole_in_ones": 3,
            "top_5_in_majors": 10,
            "top_3_in_majors": 7,
            "wins_outside_lpga_let": 1,
            "wedge_distance_proximity_feet": 19.5,
            "strokes_gained_off_tee": 1.4,
            "strokes_gained_approach": 1.1,
            "strokes_gained_putting": 0.3,
            "strokes_gained_tee_to_green": 2.3,
            "comebacks_from_54_hole_deficit": 3,
            "comebacks_final_round_deficit": 3,
            "notable_awards": 3,
            "retirement_year": 0,
            "coach_name": "Martin Hall"
        },
        # 29
        {
            "player_name": "Park Sung-Hyun",
            "country": "South Korea",
            "years_active": 8,
            "total_lpga_tour_wins": 7,
            "total_let_tour_wins": 0,
            "total_major_wins": 2,
            "times_world_no1": 2,
            "total_weeks_at_no1": 20,
            "cme_globe_championships": 0,
            "runner_ups_in_majors": 2,
            "top_10_in_majors": 10,
            "solheim_cups_played": 0,
            "scoring_average": 70.2,
            "average_driving_distance_yards": 270.0,
            "leading_money_list_times": 1,
            "lpga_player_of_year_times": 1,
            "vardon_trophy_equiv_times": 1,
            "rolex_player_of_year_times": 1,
            "career_earnings_million_usd": 7.5,
            "doping_tests_passed": 15,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 0,
            "signature_tournaments_won": 2,
            "seasons_in_top50_world_ranking": 5,
            "wins_across_all_tours": 10,
            "runner_ups_total": 6,
            "avg_putting_strokes_per_round": 29.1,
            "hole_in_ones": 2,
            "top_5_in_majors": 8,
            "top_3_in_majors": 5,
            "wins_outside_lpga_let": 1,
            "wedge_distance_proximity_feet": 19.0,
            "strokes_gained_off_tee": 1.1,
            "strokes_gained_approach": 1.3,
            "strokes_gained_putting": 0.4,
            "strokes_gained_tee_to_green": 2.0,
            "comebacks_from_54_hole_deficit": 2,
            "comebacks_final_round_deficit": 2,
            "notable_awards": 3,
            "retirement_year": 0,
            "coach_name": "Caddy Park"
        },
        # 30
        {
            "player_name": "Michelle Wie West",
            "country": "USA",
            "years_active": 17,
            "total_lpga_tour_wins": 5,
            "total_let_tour_wins": 0,
            "total_major_wins": 1,
            "times_world_no1": 0,
            "total_weeks_at_no1": 0,
            "cme_globe_championships": 0,
            "runner_ups_in_majors": 3,
            "top_10_in_majors": 14,
            "solheim_cups_played": 5,
            "scoring_average": 70.9,
            "average_driving_distance_yards": 270.0,
            "leading_money_list_times": 0,
            "lpga_player_of_year_times": 0,
            "vardon_trophy_equiv_times": 0,
            "rolex_player_of_year_times": 0,
            "career_earnings_million_usd": 7.0,
            "doping_tests_passed": 10,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 0,
            "signature_tournaments_won": 1,
            "seasons_in_top50_world_ranking": 6,
            "wins_across_all_tours": 6,
            "runner_ups_total": 8,
            "avg_putting_strokes_per_round": 29.4,
            "hole_in_ones": 1,
            "top_5_in_majors": 6,
            "top_3_in_majors": 3,
            "wins_outside_lpga_let": 0,
            "wedge_distance_proximity_feet": 20.5,
            "strokes_gained_off_tee": 0.8,
            "strokes_gained_approach": 0.7,
            "strokes_gained_putting": 0.3,
            "strokes_gained_tee_to_green": 1.5,
            "comebacks_from_54_hole_deficit": 2,
            "comebacks_final_round_deficit": 3,
            "notable_awards": 2,
            "retirement_year": 2022,
            "coach_name": "David Leadbetter"
        },
    ]

    # Confirm we have exactly 30
    if len(players_data) != 30:
        raise ValueError(f"Expected 30 golfers, but got {len(players_data)}")

    # Write out to CSV
    with open(filename, mode="w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=headers)
        writer.writeheader()
        for pdata in players_data:
            # Ensure each field is present
            for h in headers:
                if h not in pdata:
                    pdata[h] = 0
            writer.writerow(pdata)

if __name__ == "__main__":
    create_womens_golf_dataset()
    print("womens_golf_dataset.csv has been created with 30 golfers (41 columns each).")
