import csv

def create_mens_tennis_dataset(filename="mens_tennis_dataset.csv"):
    """
    Creates a CSV file containing 30 men's tennis players and 40 stats each.
    Stats are approximations or representative figures, intended for
    demonstration and for building a 'Men's Tennis Index Score' later.
    """

    # Define the header (player_name + 39 more stats = 40 total)
    headers = [
        "player_name",
        "country",
        "years_active",
        "career_singles_titles",
        "career_doubles_titles",
        "grand_slam_singles_titles",
        "grand_slam_doubles_titles",
        "weeks_at_no1",
        "year_end_no1_finishes",
        "olympic_gold_medals",
        "davis_cup_titles",
        "masters_1000_titles",
        "atp_finals_titles",
        "career_match_wins",
        "career_match_losses",
        "career_win_percentage",
        "aces",
        "double_faults",
        "first_serve_percentage",
        "first_serve_points_won_percentage",
        "second_serve_points_won_percentage",
        "break_points_saved_percentage",
        "service_games_won_percentage",
        "return_games_won_percentage",
        "tie_breaks_won_percentage",
        "hard_court_titles",
        "clay_court_titles",
        "grass_court_titles",
        "indoor_court_titles",
        "career_prize_money_million_usd",
        "head_to_head_vs_top10_wins",
        "best_calendar_year_match_record",
        "most_consecutive_matches_won",
        "career_points_ranking_peak",   # e.g. best points total in one ranking period
        "big_titles_count",             # GS + ATP Finals + M1000
        "career_fifth_set_record",
        "five_setters_played",
        "longest_match_hours",
        "career_retirement_year",       # 0 if still active
        "hall_of_fame_inducted"         # 1 if inducted, 0 if not / not yet
    ]

    # Each dict represents one player's approximate or representative data
    players_data = [
        {
            "player_name": "Roger Federer",
            "country": "Switzerland",
            "years_active": 24,
            "career_singles_titles": 103,
            "career_doubles_titles": 8,
            "grand_slam_singles_titles": 20,
            "grand_slam_doubles_titles": 0,
            "weeks_at_no1": 310,
            "year_end_no1_finishes": 5,
            "olympic_gold_medals": 1,   # 2008 doubles
            "davis_cup_titles": 1,
            "masters_1000_titles": 28,
            "atp_finals_titles": 6,
            "career_match_wins": 1251,
            "career_match_losses": 275,
            "career_win_percentage": 82.0,
            "aces": 11678,
            "double_faults": 1368,
            "first_serve_percentage": 62.0,
            "first_serve_points_won_percentage": 77.0,
            "second_serve_points_won_percentage": 57.0,
            "break_points_saved_percentage": 67.0,
            "service_games_won_percentage": 88.0,
            "return_games_won_percentage": 27.0,
            "tie_breaks_won_percentage": 65.0,
            "hard_court_titles": 71,
            "clay_court_titles": 11,
            "grass_court_titles": 19,
            "indoor_court_titles": 15,
            "career_prize_money_million_usd": 130.0,
            "head_to_head_vs_top10_wins": 223,
            "best_calendar_year_match_record": 92,  # e.g. 92-5 in 2006
            "most_consecutive_matches_won": 41,
            "career_points_ranking_peak": 16700,  # approx peak
            "big_titles_count": 54,  # (20 Slams + 6 Finals + 28 M1000)
            "career_fifth_set_record": 32,
            "five_setters_played": 54,
            "longest_match_hours": 4.57,
            "career_retirement_year": 2022,
            "hall_of_fame_inducted": 0   # Not yet, but presumably in the future
        },
        {
            "player_name": "Rafael Nadal",
            "country": "Spain",
            "years_active": 20,
            "career_singles_titles": 92,
            "career_doubles_titles": 11,
            "grand_slam_singles_titles": 22,
            "grand_slam_doubles_titles": 0,
            "weeks_at_no1": 209,
            "year_end_no1_finishes": 5,
            "olympic_gold_medals": 2,  # 1 singles (2008), 1 doubles (2016)
            "davis_cup_titles": 5,
            "masters_1000_titles": 36,
            "atp_finals_titles": 0,
            "career_match_wins": 1068,
            "career_match_losses": 220,
            "career_win_percentage": 83.0,
            "aces": 3682,
            "double_faults": 1217,
            "first_serve_percentage": 68.0,
            "first_serve_points_won_percentage": 71.0,
            "second_serve_points_won_percentage": 57.0,
            "break_points_saved_percentage": 66.0,
            "service_games_won_percentage": 84.0,
            "return_games_won_percentage": 33.0,
            "tie_breaks_won_percentage": 60.0,
            "hard_court_titles": 25,
            "clay_court_titles": 63,
            "grass_court_titles": 4,
            "indoor_court_titles": 0,
            "career_prize_money_million_usd": 135.0,
            "head_to_head_vs_top10_wins": 185,
            "best_calendar_year_match_record": 82,
            "most_consecutive_matches_won": 32,
            "career_points_ranking_peak": 15000,
            "big_titles_count": 58,  # 22 Slams + 36 M1000
            "career_fifth_set_record": 23,
            "five_setters_played": 34,
            "longest_match_hours": 5.53,
            "career_retirement_year": 0,  # still active
            "hall_of_fame_inducted": 0
        },
        {
            "player_name": "Novak Djokovic",
            "country": "Serbia",
            "years_active": 18,
            "career_singles_titles": 93,
            "career_doubles_titles": 1,
            "grand_slam_singles_titles": 24,
            "grand_slam_doubles_titles": 0,
            "weeks_at_no1": 390,
            "year_end_no1_finishes": 7,
            "olympic_gold_medals": 0,
            "davis_cup_titles": 1,
            "masters_1000_titles": 39,
            "atp_finals_titles": 6,
            "career_match_wins": 1075,
            "career_match_losses": 223,
            "career_win_percentage": 82.8,
            "aces": 6600,
            "double_faults": 1360,
            "first_serve_percentage": 65.0,
            "first_serve_points_won_percentage": 74.0,
            "second_serve_points_won_percentage": 57.0,
            "break_points_saved_percentage": 68.0,
            "service_games_won_percentage": 86.0,
            "return_games_won_percentage": 33.0,
            "tie_breaks_won_percentage": 64.0,
            "hard_court_titles": 52,
            "clay_court_titles": 19,
            "grass_court_titles": 10,
            "indoor_court_titles": 12,
            "career_prize_money_million_usd": 175.0,
            "head_to_head_vs_top10_wins": 243,
            "best_calendar_year_match_record": 82,
            "most_consecutive_matches_won": 43,
            "career_points_ranking_peak": 16950,
            "big_titles_count": 65,  # 24 Slams + 6 Finals + 39 M1000
            "career_fifth_set_record": 36,
            "five_setters_played": 50,
            "longest_match_hours": 5.53,
            "career_retirement_year": 0,
            "hall_of_fame_inducted": 0
        },
        {
            "player_name": "Pete Sampras",
            "country": "USA",
            "years_active": 15,
            "career_singles_titles": 64,
            "career_doubles_titles": 2,
            "grand_slam_singles_titles": 14,
            "grand_slam_doubles_titles": 0,
            "weeks_at_no1": 286,
            "year_end_no1_finishes": 6,
            "olympic_gold_medals": 0,
            "davis_cup_titles": 2,
            "masters_1000_titles": 11,
            "atp_finals_titles": 5,
            "career_match_wins": 762,
            "career_match_losses": 222,
            "career_win_percentage": 77.4,
            "aces": 8858,
            "double_faults": 1245,
            "first_serve_percentage": 58.0,
            "first_serve_points_won_percentage": 79.0,
            "second_serve_points_won_percentage": 57.0,
            "break_points_saved_percentage": 66.0,
            "service_games_won_percentage": 90.0,
            "return_games_won_percentage": 23.0,
            "tie_breaks_won_percentage": 63.0,
            "hard_court_titles": 36,
            "clay_court_titles": 3,
            "grass_court_titles": 10,
            "indoor_court_titles": 15,
            "career_prize_money_million_usd": 43.0,
            "head_to_head_vs_top10_wins": 124,
            "best_calendar_year_match_record": 84,
            "most_consecutive_matches_won": 29,
            "career_points_ranking_peak": 5450,  # older system
            "big_titles_count": 30,  # 14 Slams + 5 Finals + 11 M1000
            "career_fifth_set_record": 21,
            "five_setters_played": 32,
            "longest_match_hours": 3.92,
            "career_retirement_year": 2002,
            "hall_of_fame_inducted": 1
        },
        {
            "player_name": "Bjorn Borg",
            "country": "Sweden",
            "years_active": 10,
            "career_singles_titles": 66,
            "career_doubles_titles": 4,
            "grand_slam_singles_titles": 11,
            "grand_slam_doubles_titles": 0,
            "weeks_at_no1": 109,
            "year_end_no1_finishes": 2,
            "olympic_gold_medals": 0,
            "davis_cup_titles": 1,
            "masters_1000_titles": 15,  # was different era
            "atp_finals_titles": 2,
            "career_match_wins": 654,
            "career_match_losses": 140,
            "career_win_percentage": 82.4,
            "aces": 1200,
            "double_faults": 500,
            "first_serve_percentage": 64.0,
            "first_serve_points_won_percentage": 72.0,
            "second_serve_points_won_percentage": 55.0,
            "break_points_saved_percentage": 66.0,
            "service_games_won_percentage": 84.0,
            "return_games_won_percentage": 33.0,
            "tie_breaks_won_percentage": 60.0,
            "hard_court_titles": 8,
            "clay_court_titles": 30,
            "grass_court_titles": 5,
            "indoor_court_titles": 23,
            "career_prize_money_million_usd": 3.6,
            "head_to_head_vs_top10_wins": 100,
            "best_calendar_year_match_record": 84,
            "most_consecutive_matches_won": 35,
            "career_points_ranking_peak": 3400,
            "big_titles_count": 28,
            "career_fifth_set_record": 24,
            "five_setters_played": 30,
            "longest_match_hours": 3.88,
            "career_retirement_year": 1983,
            "hall_of_fame_inducted": 1
        },
        {
            "player_name": "Rod Laver",
            "country": "Australia",
            "years_active": 20,
            "career_singles_titles": 200, # counting pre-Open era, approx
            "career_doubles_titles": 28,
            "grand_slam_singles_titles": 11,
            "grand_slam_doubles_titles": 6,
            "weeks_at_no1": 0,  # no official system pre-1973
            "year_end_no1_finishes": 4, # approximate
            "olympic_gold_medals": 0,
            "davis_cup_titles": 5,
            "masters_1000_titles": 0,
            "atp_finals_titles": 0,
            "career_match_wins": 840,
            "career_match_losses": 183,
            "career_win_percentage": 82.1,
            "aces": 2000, # rough
            "double_faults": 800,
            "first_serve_percentage": 66.0,
            "first_serve_points_won_percentage": 70.0,
            "second_serve_points_won_percentage": 58.0,
            "break_points_saved_percentage": 65.0,
            "service_games_won_percentage": 83.0,
            "return_games_won_percentage": 34.0,
            "tie_breaks_won_percentage": 0.0, # didn't exist in early era
            "hard_court_titles": 10,
            "clay_court_titles": 34,
            "grass_court_titles": 150, # many pre-Open events
            "indoor_court_titles": 6,
            "career_prize_money_million_usd": 1.6,
            "head_to_head_vs_top10_wins": 0, # incomplete records
            "best_calendar_year_match_record": 102,
            "most_consecutive_matches_won": 29,
            "career_points_ranking_peak": 0,
            "big_titles_count": 11, # just counting Slams
            "career_fifth_set_record": 15,
            "five_setters_played": 22,
            "longest_match_hours": 3.50,
            "career_retirement_year": 1979,
            "hall_of_fame_inducted": 1
        },
        {
            "player_name": "Jimmy Connors",
            "country": "USA",
            "years_active": 24,
            "career_singles_titles": 109,
            "career_doubles_titles": 16,
            "grand_slam_singles_titles": 8,
            "grand_slam_doubles_titles": 2,
            "weeks_at_no1": 268,
            "year_end_no1_finishes": 5,
            "olympic_gold_medals": 0,
            "davis_cup_titles": 1,
            "masters_1000_titles": 17, # older era
            "atp_finals_titles": 1,
            "career_match_wins": 1274,
            "career_match_losses": 283,
            "career_win_percentage": 81.8,
            "aces": 2700,
            "double_faults": 1000,
            "first_serve_percentage": 70.0,
            "first_serve_points_won_percentage": 68.0,
            "second_serve_points_won_percentage": 56.0,
            "break_points_saved_percentage": 65.0,
            "service_games_won_percentage": 80.0,
            "return_games_won_percentage": 33.0,
            "tie_breaks_won_percentage": 58.0,
            "hard_court_titles": 40,
            "clay_court_titles": 12,
            "grass_court_titles": 12,
            "indoor_court_titles": 45,
            "career_prize_money_million_usd": 8.6,
            "head_to_head_vs_top10_wins": 160,
            "best_calendar_year_match_record": 93,
            "most_consecutive_matches_won": 37,
            "career_points_ranking_peak": 4200,
            "big_titles_count": 26,
            "career_fifth_set_record": 20,
            "five_setters_played": 30,
            "longest_match_hours": 3.77,
            "career_retirement_year": 1996,
            "hall_of_fame_inducted": 1
        },
        {
            "player_name": "Ivan Lendl",
            "country": "Czechoslovakia/USA",
            "years_active": 16,
            "career_singles_titles": 94,
            "career_doubles_titles": 6,
            "grand_slam_singles_titles": 8,
            "grand_slam_doubles_titles": 0,
            "weeks_at_no1": 270,
            "year_end_no1_finishes": 4,
            "olympic_gold_medals": 0,
            "davis_cup_titles": 1,
            "masters_1000_titles": 22,
            "atp_finals_titles": 5,
            "career_match_wins": 1068,
            "career_match_losses": 242,
            "career_win_percentage": 81.5,
            "aces": 5900,
            "double_faults": 1300,
            "first_serve_percentage": 60.0,
            "first_serve_points_won_percentage": 75.0,
            "second_serve_points_won_percentage": 55.0,
            "break_points_saved_percentage": 65.0,
            "service_games_won_percentage": 85.0,
            "return_games_won_percentage": 31.0,
            "tie_breaks_won_percentage": 57.0,
            "hard_court_titles": 52,
            "clay_court_titles": 28,
            "grass_court_titles": 2,
            "indoor_court_titles": 12,
            "career_prize_money_million_usd": 21.2,
            "head_to_head_vs_top10_wins": 167,
            "best_calendar_year_match_record": 90,
            "most_consecutive_matches_won": 44,
            "career_points_ranking_peak": 5290,
            "big_titles_count": 35,
            "career_fifth_set_record": 22,
            "five_setters_played": 34,
            "longest_match_hours": 4.33,
            "career_retirement_year": 1994,
            "hall_of_fame_inducted": 1
        },
        {
            "player_name": "John McEnroe",
            "country": "USA",
            "years_active": 16,
            "career_singles_titles": 77,
            "career_doubles_titles": 78,
            "grand_slam_singles_titles": 7,
            "grand_slam_doubles_titles": 9,
            "weeks_at_no1": 170,
            "year_end_no1_finishes": 4,
            "olympic_gold_medals": 0,
            "davis_cup_titles": 5,
            "masters_1000_titles": 19,
            "atp_finals_titles": 3,
            "career_match_wins": 875,
            "career_match_losses": 198,
            "career_win_percentage": 81.5,
            "aces": 3500,
            "double_faults": 950,
            "first_serve_percentage": 65.0,
            "first_serve_points_won_percentage": 73.0,
            "second_serve_points_won_percentage": 58.0,
            "break_points_saved_percentage": 64.0,
            "service_games_won_percentage": 84.0,
            "return_games_won_percentage": 32.0,
            "tie_breaks_won_percentage": 60.0,
            "hard_court_titles": 32,
            "clay_court_titles": 4,
            "grass_court_titles": 8,
            "indoor_court_titles": 33,
            "career_prize_money_million_usd": 12.5,
            "head_to_head_vs_top10_wins": 119,
            "best_calendar_year_match_record": 82,
            "most_consecutive_matches_won": 42,
            "career_points_ranking_peak": 4200,
            "big_titles_count": 29,
            "career_fifth_set_record": 18,
            "five_setters_played": 27,
            "longest_match_hours": 4.10,
            "career_retirement_year": 1992,
            "hall_of_fame_inducted": 1
        },
        {
            "player_name": "Andre Agassi",
            "country": "USA",
            "years_active": 20,
            "career_singles_titles": 60,
            "career_doubles_titles": 1,
            "grand_slam_singles_titles": 8,
            "grand_slam_doubles_titles": 0,
            "weeks_at_no1": 101,
            "year_end_no1_finishes": 1,
            "olympic_gold_medals": 1,
            "davis_cup_titles": 3,
            "masters_1000_titles": 17,
            "atp_finals_titles": 1,
            "career_match_wins": 870,
            "career_match_losses": 274,
            "career_win_percentage": 76.0,
            "aces": 6182,
            "double_faults": 1303,
            "first_serve_percentage": 63.0,
            "first_serve_points_won_percentage": 71.0,
            "second_serve_points_won_percentage": 53.0,
            "break_points_saved_percentage": 65.0,
            "service_games_won_percentage": 83.0,
            "return_games_won_percentage": 31.0,
            "tie_breaks_won_percentage": 59.0,
            "hard_court_titles": 46,
            "clay_court_titles": 5,
            "grass_court_titles": 1,
            "indoor_court_titles": 8,
            "career_prize_money_million_usd": 31.2,
            "head_to_head_vs_top10_wins": 109,
            "best_calendar_year_match_record": 74,
            "most_consecutive_matches_won": 26,
            "career_points_ranking_peak": 5500,
            "big_titles_count": 26,
            "career_fifth_set_record": 20,
            "five_setters_played": 29,
            "longest_match_hours": 4.33,
            "career_retirement_year": 2006,
            "hall_of_fame_inducted": 1
        },
        # --------------- Add more players to reach 30 total ---------------
        {
            "player_name": "Roy Emerson",
            "country": "Australia",
            "years_active": 15,
            "career_singles_titles": 55,
            "career_doubles_titles": 50,
            "grand_slam_singles_titles": 12,
            "grand_slam_doubles_titles": 16,
            "weeks_at_no1": 0,  # pre-official ranking
            "year_end_no1_finishes": 0,
            "olympic_gold_medals": 0,
            "davis_cup_titles": 8,
            "masters_1000_titles": 0,
            "atp_finals_titles": 0,
            "career_match_wins": 700,
            "career_match_losses": 120,
            "career_win_percentage": 85.3,
            "aces": 1000,
            "double_faults": 500,
            "first_serve_percentage": 67.0,
            "first_serve_points_won_percentage": 70.0,
            "second_serve_points_won_percentage": 55.0,
            "break_points_saved_percentage": 64.0,
            "service_games_won_percentage": 82.0,
            "return_games_won_percentage": 32.0,
            "tie_breaks_won_percentage": 0.0,
            "hard_court_titles": 0,
            "clay_court_titles": 20,
            "grass_court_titles": 35,
            "indoor_court_titles": 0,
            "career_prize_money_million_usd": 0.3,
            "head_to_head_vs_top10_wins": 0,
            "best_calendar_year_match_record": 64,
            "most_consecutive_matches_won": 22,
            "career_points_ranking_peak": 0,
            "big_titles_count": 12,
            "career_fifth_set_record": 12,
            "five_setters_played": 18,
            "longest_match_hours": 3.2,
            "career_retirement_year": 1971,
            "hall_of_fame_inducted": 1
        },
        {
            "player_name": "Bill Tilden",
            "country": "USA",
            "years_active": 18,
            "career_singles_titles": 138, 
            "career_doubles_titles": 0,
            "grand_slam_singles_titles": 10,
            "grand_slam_doubles_titles": 5,
            "weeks_at_no1": 0,
            "year_end_no1_finishes": 7,
            "olympic_gold_medals": 0,
            "davis_cup_titles": 7,
            "masters_1000_titles": 0,
            "atp_finals_titles": 0,
            "career_match_wins": 695,
            "career_match_losses": 100,
            "career_win_percentage": 87.4,
            "aces": 500,
            "double_faults": 300,
            "first_serve_percentage": 65.0,
            "first_serve_points_won_percentage": 70.0,
            "second_serve_points_won_percentage": 55.0,
            "break_points_saved_percentage": 64.0,
            "service_games_won_percentage": 83.0,
            "return_games_won_percentage": 32.0,
            "tie_breaks_won_percentage": 0.0,
            "hard_court_titles": 0,
            "clay_court_titles": 15,
            "grass_court_titles": 120,
            "indoor_court_titles": 3,
            "career_prize_money_million_usd": 0.1,
            "head_to_head_vs_top10_wins": 0,
            "best_calendar_year_match_record": 60,
            "most_consecutive_matches_won": 28,
            "career_points_ranking_peak": 0,
            "big_titles_count": 10,
            "career_fifth_set_record": 10,
            "five_setters_played": 15,
            "longest_match_hours": 2.9,
            "career_retirement_year": 1946,
            "hall_of_fame_inducted": 1
        },
        {
            "player_name": "Ken Rosewall",
            "country": "Australia",
            "years_active": 25,
            "career_singles_titles": 133,
            "career_doubles_titles": 18,
            "grand_slam_singles_titles": 8,
            "grand_slam_doubles_titles": 9,
            "weeks_at_no1": 0,
            "year_end_no1_finishes": 2,
            "olympic_gold_medals": 0,
            "davis_cup_titles": 4,
            "masters_1000_titles": 0, # pre Open
            "atp_finals_titles": 0,
            "career_match_wins": 800,
            "career_match_losses": 230,
            "career_win_percentage": 77.7,
            "aces": 1500,
            "double_faults": 600,
            "first_serve_percentage": 66.0,
            "first_serve_points_won_percentage": 68.0,
            "second_serve_points_won_percentage": 55.0,
            "break_points_saved_percentage": 64.0,
            "service_games_won_percentage": 80.0,
            "return_games_won_percentage": 31.0,
            "tie_breaks_won_percentage": 0.0,
            "hard_court_titles": 8,
            "clay_court_titles": 22,
            "grass_court_titles": 90,
            "indoor_court_titles": 13,
            "career_prize_money_million_usd": 1.6,
            "head_to_head_vs_top10_wins": 0,
            "best_calendar_year_match_record": 78,
            "most_consecutive_matches_won": 24,
            "career_points_ranking_peak": 0,
            "big_titles_count": 8,
            "career_fifth_set_record": 18,
            "five_setters_played": 25,
            "longest_match_hours": 3.6,
            "career_retirement_year": 1980,
            "hall_of_fame_inducted": 1
        },
        {
            "player_name": "Guillermo Vilas",
            "country": "Argentina",
            "years_active": 18,
            "career_singles_titles": 62,
            "career_doubles_titles": 16,
            "grand_slam_singles_titles": 4,
            "grand_slam_doubles_titles": 0,
            "weeks_at_no1": 0,  
            "year_end_no1_finishes": 0,
            "olympic_gold_medals": 0,
            "davis_cup_titles": 0,
            "masters_1000_titles": 0,
            "atp_finals_titles": 1,
            "career_match_wins": 951,
            "career_match_losses": 297,
            "career_win_percentage": 76.2,
            "aces": 2000,
            "double_faults": 900,
            "first_serve_percentage": 65.0,
            "first_serve_points_won_percentage": 69.0,
            "second_serve_points_won_percentage": 55.0,
            "break_points_saved_percentage": 64.0,
            "service_games_won_percentage": 81.0,
            "return_games_won_percentage": 32.0,
            "tie_breaks_won_percentage": 58.0,
            "hard_court_titles": 5,
            "clay_court_titles": 46,
            "grass_court_titles": 1,
            "indoor_court_titles": 10,
            "career_prize_money_million_usd": 4.9,
            "head_to_head_vs_top10_wins": 95,
            "best_calendar_year_match_record": 130, # 1977
            "most_consecutive_matches_won": 46,
            "career_points_ranking_peak": 2600,
            "big_titles_count": 5,
            "career_fifth_set_record": 15,
            "five_setters_played": 23,
            "longest_match_hours": 4.15,
            "career_retirement_year": 1989,
            "hall_of_fame_inducted": 1
        },
        {
            "player_name": "Boris Becker",
            "country": "Germany",
            "years_active": 15,
            "career_singles_titles": 49,
            "career_doubles_titles": 15,
            "grand_slam_singles_titles": 6,
            "grand_slam_doubles_titles": 0,
            "weeks_at_no1": 12,
            "year_end_no1_finishes": 0,
            "olympic_gold_medals": 1, # doubles
            "davis_cup_titles": 2,
            "masters_1000_titles": 13,
            "atp_finals_titles": 3,
            "career_match_wins": 713,
            "career_match_losses": 214,
            "career_win_percentage": 76.9,
            "aces": 9000,
            "double_faults": 1900,
            "first_serve_percentage": 58.0,
            "first_serve_points_won_percentage": 77.0,
            "second_serve_points_won_percentage": 54.0,
            "break_points_saved_percentage": 65.0,
            "service_games_won_percentage": 87.0,
            "return_games_won_percentage": 24.0,
            "tie_breaks_won_percentage": 62.0,
            "hard_court_titles": 15,
            "clay_court_titles": 3,
            "grass_court_titles": 7,
            "indoor_court_titles": 24,
            "career_prize_money_million_usd": 25.0,
            "head_to_head_vs_top10_wins": 121,
            "best_calendar_year_match_record": 71,
            "most_consecutive_matches_won": 25,
            "career_points_ranking_peak": 4300,
            "big_titles_count": 22,
            "career_fifth_set_record": 23,
            "five_setters_played": 39,
            "longest_match_hours": 4.10,
            "career_retirement_year": 1999,
            "hall_of_fame_inducted": 1
        },
        {
            "player_name": "Stefan Edberg",
            "country": "Sweden",
            "years_active": 14,
            "career_singles_titles": 42,
            "career_doubles_titles": 18,
            "grand_slam_singles_titles": 6,
            "grand_slam_doubles_titles": 3,
            "weeks_at_no1": 72,
            "year_end_no1_finishes": 2,
            "olympic_gold_medals": 2, # 1984 demonstration, etc. 
            "davis_cup_titles": 4,
            "masters_1000_titles": 9,
            "atp_finals_titles": 1,
            "career_match_wins": 801,
            "career_match_losses": 270,
            "career_win_percentage": 74.8,
            "aces": 3900,
            "double_faults": 1100,
            "first_serve_percentage": 60.0,
            "first_serve_points_won_percentage": 73.0,
            "second_serve_points_won_percentage": 54.0,
            "break_points_saved_percentage": 63.0,
            "service_games_won_percentage": 82.0,
            "return_games_won_percentage": 29.0,
            "tie_breaks_won_percentage": 58.0,
            "hard_court_titles": 15,
            "clay_court_titles": 3,
            "grass_court_titles": 10,
            "indoor_court_titles": 14,
            "career_prize_money_million_usd": 20.6,
            "head_to_head_vs_top10_wins": 96,
            "best_calendar_year_match_record": 67,
            "most_consecutive_matches_won": 23,
            "career_points_ranking_peak": 4300,
            "big_titles_count": 16,
            "career_fifth_set_record": 17,
            "five_setters_played": 30,
            "longest_match_hours": 4.33,
            "career_retirement_year": 1996,
            "hall_of_fame_inducted": 1
        },
        {
            "player_name": "Mats Wilander",
            "country": "Sweden",
            "years_active": 16,
            "career_singles_titles": 33,
            "career_doubles_titles": 7,
            "grand_slam_singles_titles": 7,
            "grand_slam_doubles_titles": 1,
            "weeks_at_no1": 20,
            "year_end_no1_finishes": 1,
            "olympic_gold_medals": 0,
            "davis_cup_titles": 3,
            "masters_1000_titles": 8,
            "atp_finals_titles": 0,
            "career_match_wins": 571,
            "career_match_losses": 222,
            "career_win_percentage": 72.0,
            "aces": 2200,
            "double_faults": 700,
            "first_serve_percentage": 68.0,
            "first_serve_points_won_percentage": 69.0,
            "second_serve_points_won_percentage": 54.0,
            "break_points_saved_percentage": 63.0,
            "service_games_won_percentage": 80.0,
            "return_games_won_percentage": 30.0,
            "tie_breaks_won_percentage": 55.0,
            "hard_court_titles": 9,
            "clay_court_titles": 14,
            "grass_court_titles": 1,
            "indoor_court_titles": 9,
            "career_prize_money_million_usd": 7.9,
            "head_to_head_vs_top10_wins": 80,
            "best_calendar_year_match_record": 70,
            "most_consecutive_matches_won": 22,
            "career_points_ranking_peak": 3900,
            "big_titles_count": 15,
            "career_fifth_set_record": 16,
            "five_setters_played": 24,
            "longest_match_hours": 4.05,
            "career_retirement_year": 1996,
            "hall_of_fame_inducted": 1
        },
        {
            "player_name": "Stan Wawrinka",
            "country": "Switzerland",
            "years_active": 18,
            "career_singles_titles": 16,
            "career_doubles_titles": 2,
            "grand_slam_singles_titles": 3,
            "grand_slam_doubles_titles": 0,
            "weeks_at_no1": 0,
            "year_end_no1_finishes": 0,
            "olympic_gold_medals": 1, # 2008 doubles with Federer
            "davis_cup_titles": 1,
            "masters_1000_titles": 1,
            "atp_finals_titles": 0,
            "career_match_wins": 550,
            "career_match_losses": 315,
            "career_win_percentage": 63.6,
            "aces": 5200,
            "double_faults": 1900,
            "first_serve_percentage": 57.0,
            "first_serve_points_won_percentage": 76.0,
            "second_serve_points_won_percentage": 52.0,
            "break_points_saved_percentage": 63.0,
            "service_games_won_percentage": 83.0,
            "return_games_won_percentage": 23.0,
            "tie_breaks_won_percentage": 58.0,
            "hard_court_titles": 8,
            "clay_court_titles": 5,
            "grass_court_titles": 0,
            "indoor_court_titles": 3,
            "career_prize_money_million_usd": 35.0,
            "head_to_head_vs_top10_wins": 62,
            "best_calendar_year_match_record": 54,
            "most_consecutive_matches_won": 13,
            "career_points_ranking_peak": 6380,
            "big_titles_count": 4,
            "career_fifth_set_record": 10,
            "five_setters_played": 16,
            "longest_match_hours": 5.0,
            "career_retirement_year": 0,
            "hall_of_fame_inducted": 0
        },
        {
            "player_name": "Andy Murray",
            "country": "Great Britain",
            "years_active": 17,
            "career_singles_titles": 46,
            "career_doubles_titles": 3,
            "grand_slam_singles_titles": 3,
            "grand_slam_doubles_titles": 0,
            "weeks_at_no1": 41,
            "year_end_no1_finishes": 1,
            "olympic_gold_medals": 2,
            "davis_cup_titles": 1,
            "masters_1000_titles": 14,
            "atp_finals_titles": 1,
            "career_match_wins": 730,
            "career_match_losses": 250,
            "career_win_percentage": 74.5,
            "aces": 4000,
            "double_faults": 1400,
            "first_serve_percentage": 59.0,
            "first_serve_points_won_percentage": 73.0,
            "second_serve_points_won_percentage": 52.0,
            "break_points_saved_percentage": 65.0,
            "service_games_won_percentage": 83.0,
            "return_games_won_percentage": 30.0,
            "tie_breaks_won_percentage": 55.0,
            "hard_court_titles": 20,
            "clay_court_titles": 3,
            "grass_court_titles": 8,
            "indoor_court_titles": 15,
            "career_prize_money_million_usd": 63.0,
            "head_to_head_vs_top10_wins": 102,
            "best_calendar_year_match_record": 78,
            "most_consecutive_matches_won": 24,
            "career_points_ranking_peak": 12360,
            "big_titles_count": 18,
            "career_fifth_set_record": 23,
            "five_setters_played": 32,
            "longest_match_hours": 4.09,
            "career_retirement_year": 0,
            "hall_of_fame_inducted": 0
        },
        {
            "player_name": "Lleyton Hewitt",
            "country": "Australia",
            "years_active": 18,
            "career_singles_titles": 30,
            "career_doubles_titles": 3,
            "grand_slam_singles_titles": 2,
            "grand_slam_doubles_titles": 0,
            "weeks_at_no1": 80,
            "year_end_no1_finishes": 2,
            "olympic_gold_medals": 0,
            "davis_cup_titles": 2,
            "masters_1000_titles": 2,
            "atp_finals_titles": 2,
            "career_match_wins": 616,
            "career_match_losses": 262,
            "career_win_percentage": 70.2,
            "aces": 2500,
            "double_faults": 1100,
            "first_serve_percentage": 60.0,
            "first_serve_points_won_percentage": 69.0,
            "second_serve_points_won_percentage": 51.0,
            "break_points_saved_percentage": 60.0,
            "service_games_won_percentage": 79.0,
            "return_games_won_percentage": 31.0,
            "tie_breaks_won_percentage": 52.0,
            "hard_court_titles": 14,
            "clay_court_titles": 1,
            "grass_court_titles": 8,
            "indoor_court_titles": 7,
            "career_prize_money_million_usd": 20.7,
            "head_to_head_vs_top10_wins": 80,
            "best_calendar_year_match_record": 80,
            "most_consecutive_matches_won": 15,
            "career_points_ranking_peak": 5000,
            "big_titles_count": 6,
            "career_fifth_set_record": 21,
            "five_setters_played": 30,
            "longest_match_hours": 4.20,
            "career_retirement_year": 2016,
            "hall_of_fame_inducted": 1
        },
        {
            "player_name": "Ilie Nastase",
            "country": "Romania",
            "years_active": 18,
            "career_singles_titles": 58,
            "career_doubles_titles": 45,
            "grand_slam_singles_titles": 2,
            "grand_slam_doubles_titles": 3,
            "weeks_at_no1": 40,
            "year_end_no1_finishes": 2,
            "olympic_gold_medals": 0,
            "davis_cup_titles": 0,
            "masters_1000_titles": 8,   # approximate
            "atp_finals_titles": 4,
            "career_match_wins": 780,
            "career_match_losses": 280,
            "career_win_percentage": 73.6,
            "aces": 1500,
            "double_faults": 700,
            "first_serve_percentage": 66.0,
            "first_serve_points_won_percentage": 70.0,
            "second_serve_points_won_percentage": 54.0,
            "break_points_saved_percentage": 63.0,
            "service_games_won_percentage": 80.0,
            "return_games_won_percentage": 32.0,
            "tie_breaks_won_percentage": 55.0,
            "hard_court_titles": 15,
            "clay_court_titles": 25,
            "grass_court_titles": 5,
            "indoor_court_titles": 13,
            "career_prize_money_million_usd": 2.1,
            "head_to_head_vs_top10_wins": 72,
            "best_calendar_year_match_record": 71,
            "most_consecutive_matches_won": 23,
            "career_points_ranking_peak": 0,
            "big_titles_count": 10,
            "career_fifth_set_record": 15,
            "five_setters_played": 23,
            "longest_match_hours": 3.7,
            "career_retirement_year": 1985,
            "hall_of_fame_inducted": 1
        },
        {
            "player_name": "Andy Roddick",
            "country": "USA",
            "years_active": 13,
            "career_singles_titles": 32,
            "career_doubles_titles": 4,
            "grand_slam_singles_titles": 1,
            "grand_slam_doubles_titles": 0,
            "weeks_at_no1": 13,
            "year_end_no1_finishes": 1,
            "olympic_gold_medals": 0,
            "davis_cup_titles": 1,
            "masters_1000_titles": 5,
            "atp_finals_titles": 0,
            "career_match_wins": 612,
            "career_match_losses": 213,
            "career_win_percentage": 74.2,
            "aces": 9074,
            "double_faults": 1800,
            "first_serve_percentage": 63.0,
            "first_serve_points_won_percentage": 76.0,
            "second_serve_points_won_percentage": 50.0,
            "break_points_saved_percentage": 62.0,
            "service_games_won_percentage": 87.0,
            "return_games_won_percentage": 20.0,
            "tie_breaks_won_percentage": 60.0,
            "hard_court_titles": 21,
            "clay_court_titles": 3,
            "grass_court_titles": 5,
            "indoor_court_titles": 3,
            "career_prize_money_million_usd": 20.6,
            "head_to_head_vs_top10_wins": 78,
            "best_calendar_year_match_record": 74,
            "most_consecutive_matches_won": 17,
            "career_points_ranking_peak": 5055,
            "big_titles_count": 6,
            "career_fifth_set_record": 15,
            "five_setters_played": 24,
            "longest_match_hours": 5.14,
            "career_retirement_year": 2012,
            "hall_of_fame_inducted": 1
        },
        {
            "player_name": "Marat Safin",
            "country": "Russia",
            "years_active": 12,
            "career_singles_titles": 15,
            "career_doubles_titles": 2,
            "grand_slam_singles_titles": 2,
            "grand_slam_doubles_titles": 0,
            "weeks_at_no1": 9,
            "year_end_no1_finishes": 0,
            "olympic_gold_medals": 0,
            "davis_cup_titles": 2,
            "masters_1000_titles": 5,
            "atp_finals_titles": 0,
            "career_match_wins": 422,
            "career_match_losses": 267,
            "career_win_percentage": 61.3,
            "aces": 4063,
            "double_faults": 1400,
            "first_serve_percentage": 57.0,
            "first_serve_points_won_percentage": 74.0,
            "second_serve_points_won_percentage": 49.0,
            "break_points_saved_percentage": 60.0,
            "service_games_won_percentage": 82.0,
            "return_games_won_percentage": 24.0,
            "tie_breaks_won_percentage": 55.0,
            "hard_court_titles": 8,
            "clay_court_titles": 2,
            "grass_court_titles": 0,
            "indoor_court_titles": 5,
            "career_prize_money_million_usd": 14.4,
            "head_to_head_vs_top10_wins": 60,
            "best_calendar_year_match_record": 70,
            "most_consecutive_matches_won": 14,
            "career_points_ranking_peak": 7280,
            "big_titles_count": 7,
            "career_fifth_set_record": 12,
            "five_setters_played": 20,
            "longest_match_hours": 5.28,
            "career_retirement_year": 2009,
            "hall_of_fame_inducted": 1
        },
        {
            "player_name": "Goran Ivanisevic",
            "country": "Croatia",
            "years_active": 14,
            "career_singles_titles": 22,
            "career_doubles_titles": 9,
            "grand_slam_singles_titles": 1,
            "grand_slam_doubles_titles": 0,
            "weeks_at_no1": 0,
            "year_end_no1_finishes": 0,
            "olympic_gold_medals": 0,
            "davis_cup_titles": 0,
            "masters_1000_titles": 2,
            "atp_finals_titles": 0,
            "career_match_wins": 599,
            "career_match_losses": 333,
            "career_win_percentage": 64.3,
            "aces": 10183,
            "double_faults": 2100,
            "first_serve_percentage": 55.0,
            "first_serve_points_won_percentage": 77.0,
            "second_serve_points_won_percentage": 47.0,
            "break_points_saved_percentage": 61.0,
            "service_games_won_percentage": 88.0,
            "return_games_won_percentage": 18.0,
            "tie_breaks_won_percentage": 58.0,
            "hard_court_titles": 10,
            "clay_court_titles": 3,
            "grass_court_titles": 2,
            "indoor_court_titles": 7,
            "career_prize_money_million_usd": 19.9,
            "head_to_head_vs_top10_wins": 52,
            "best_calendar_year_match_record": 59,
            "most_consecutive_matches_won": 10,
            "career_points_ranking_peak": 3500,
            "big_titles_count": 3,
            "career_fifth_set_record": 9,
            "five_setters_played": 19,
            "longest_match_hours": 3.98,
            "career_retirement_year": 2004,
            "hall_of_fame_inducted": 1
        },
        {
            "player_name": "Arthur Ashe",
            "country": "USA",
            "years_active": 11,
            "career_singles_titles": 33,
            "career_doubles_titles": 18,
            "grand_slam_singles_titles": 3,
            "grand_slam_doubles_titles": 2,
            "weeks_at_no1": 0,
            "year_end_no1_finishes": 0,
            "olympic_gold_medals": 0,
            "davis_cup_titles": 4,
            "masters_1000_titles": 0,
            "atp_finals_titles": 0,
            "career_match_wins": 760,
            "career_match_losses": 315,
            "career_win_percentage": 70.7,
            "aces": 2200,
            "double_faults": 750,
            "first_serve_percentage": 61.0,
            "first_serve_points_won_percentage": 72.0,
            "second_serve_points_won_percentage": 50.0,
            "break_points_saved_percentage": 62.0,
            "service_games_won_percentage": 81.0,
            "return_games_won_percentage": 26.0,
            "tie_breaks_won_percentage": 0.0, # earlier era
            "hard_court_titles": 7,
            "clay_court_titles": 3,
            "grass_court_titles": 18,
            "indoor_court_titles": 5,
            "career_prize_money_million_usd": 1.6,
            "head_to_head_vs_top10_wins": 60,
            "best_calendar_year_match_record": 60,
            "most_consecutive_matches_won": 15,
            "career_points_ranking_peak": 0,
            "big_titles_count": 3,
            "career_fifth_set_record": 14,
            "five_setters_played": 20,
            "longest_match_hours": 3.5,
            "career_retirement_year": 1980,
            "hall_of_fame_inducted": 1
        },
        {
            "player_name": "Michael Chang",
            "country": "USA",
            "years_active": 16,
            "career_singles_titles": 34,
            "career_doubles_titles": 3,
            "grand_slam_singles_titles": 1,
            "grand_slam_doubles_titles": 0,
            "weeks_at_no1": 0,
            "year_end_no1_finishes": 0,
            "olympic_gold_medals": 0,
            "davis_cup_titles": 1,
            "masters_1000_titles": 7,
            "atp_finals_titles": 0,
            "career_match_wins": 662,
            "career_match_losses": 312,
            "career_win_percentage": 68.0,
            "aces": 2100,
            "double_faults": 900,
            "first_serve_percentage": 67.0,
            "first_serve_points_won_percentage": 69.0,
            "second_serve_points_won_percentage": 50.0,
            "break_points_saved_percentage": 61.0,
            "service_games_won_percentage": 78.0,
            "return_games_won_percentage": 31.0,
            "tie_breaks_won_percentage": 53.0,
            "hard_court_titles": 24,
            "clay_court_titles": 7,
            "grass_court_titles": 0,
            "indoor_court_titles": 3,
            "career_prize_money_million_usd": 19.1,
            "head_to_head_vs_top10_wins": 56,
            "best_calendar_year_match_record": 57,
            "most_consecutive_matches_won": 14,
            "career_points_ranking_peak": 3800,
            "big_titles_count": 8,
            "career_fifth_set_record": 15,
            "five_setters_played": 23,
            "longest_match_hours": 4.18,
            "career_retirement_year": 2003,
            "hall_of_fame_inducted": 1
        },
        {
            "player_name": "Gustavo Kuerten",
            "country": "Brazil",
            "years_active": 10,
            "career_singles_titles": 20,
            "career_doubles_titles": 8,
            "grand_slam_singles_titles": 3,
            "grand_slam_doubles_titles": 0,
            "weeks_at_no1": 43,
            "year_end_no1_finishes": 1,
            "olympic_gold_medals": 0,
            "davis_cup_titles": 0,
            "masters_1000_titles": 5,
            "atp_finals_titles": 1,
            "career_match_wins": 358,
            "career_match_losses": 195,
            "career_win_percentage": 64.7,
            "aces": 1900,
            "double_faults": 800,
            "first_serve_percentage": 58.0,
            "first_serve_points_won_percentage": 72.0,
            "second_serve_points_won_percentage": 49.0,
            "break_points_saved_percentage": 61.0,
            "service_games_won_percentage": 80.0,
            "return_games_won_percentage": 26.0,
            "tie_breaks_won_percentage": 55.0,
            "hard_court_titles": 2,
            "clay_court_titles": 17,
            "grass_court_titles": 0,
            "indoor_court_titles": 1,
            "career_prize_money_million_usd": 14.8,
            "head_to_head_vs_top10_wins": 50,
            "best_calendar_year_match_record": 63,
            "most_consecutive_matches_won": 12,
            "career_points_ranking_peak": 5700,
            "big_titles_count": 9,
            "career_fifth_set_record": 8,
            "five_setters_played": 16,
            "longest_match_hours": 4.1,
            "career_retirement_year": 2008,
            "hall_of_fame_inducted": 1
        }
    ]

    # Write out to CSV
    with open(filename, mode="w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=headers)
        writer.writeheader()
        for pdata in players_data:
            # Ensure every header field is present
            for h in headers:
                if h not in pdata:
                    pdata[h] = 0
            writer.writerow(pdata)


if __name__ == "__main__":
    create_mens_tennis_dataset()
    print("mens_tennis_dataset.csv has been created with 30 players and 40 stats each.")
