import csv

def create_basketball_dataset(filename="basketball_dataset.csv"):
    """
    Creates a CSV file containing 30 NBA players with 32 'basic' stats +
    8 additional advanced stats (total 40 columns).
    Stats are approximate, intended for demonstration and for building an
    advanced 'Basketball Index Score' later.
    """

    # Define the header (40 stats: 32 old + 8 new + player_name)
    headers = [
        "player_name",
        "seasons_played",
        "games_played",
        "minutes_played",
        "field_goals_made",
        "field_goal_attempts",
        "field_goal_percentage",
        "three_pointers_made",
        "three_pointer_attempts",
        "three_pointer_percentage",
        "two_pointers_made",
        "two_pointer_attempts",
        "two_pointer_percentage",
        "free_throws_made",
        "free_throw_attempts",
        "free_throw_percentage",
        "offensive_rebounds",
        "defensive_rebounds",
        "total_rebounds",
        "assists",
        "steals",
        "blocks",
        "turnovers",
        "points",
        "all_star_appearances",
        "all_nba_teams",
        "mvp_awards",
        "finals_mvp_awards",
        "championships",
        "career_per",
        "career_ws",
        "career_bpm",
        # --- New Stats ---
        "true_shooting_percentage",   # TS%
        "effective_fg_percentage",    # eFG%
        "offensive_bpm",             # OBPM
        "defensive_bpm",             # DBPM
        "vorp",                      # Value Over Replacement
        "career_def_rtg",            # Defensive Rating
        "triple_doubles",
        "forty_plus_point_games"
    ]

    # Each dict represents one player's career data (approx.)
    players_data = [
        {
            "player_name": "Michael Jordan",
            "seasons_played": 15,
            "games_played": 1072,
            "minutes_played": 41011,
            "field_goals_made": 12192,
            "field_goal_attempts": 24537,
            "field_goal_percentage": 49.7,
            "three_pointers_made": 581,
            "three_pointer_attempts": 1778,
            "three_pointer_percentage": 32.7,
            "two_pointers_made": 11611,
            "two_pointer_attempts": 22759,
            "two_pointer_percentage": 51.0,
            "free_throws_made": 7327,
            "free_throw_attempts": 8772,
            "free_throw_percentage": 83.5,
            "offensive_rebounds": 877,
            "defensive_rebounds": 4095,
            "total_rebounds": 4972,
            "assists": 5633,
            "steals": 2514,
            "blocks": 893,
            "turnovers": 2924,
            "points": 32292,
            "all_star_appearances": 14,
            "all_nba_teams": 11,
            "mvp_awards": 5,
            "finals_mvp_awards": 6,
            "championships": 6,
            "career_per": 27.9,
            "career_ws": 214.0,
            "career_bpm": 9.2,
            # New Stats
            "true_shooting_percentage": 56.9,
            "effective_fg_percentage": 51.0,
            "offensive_bpm": 7.9,
            "defensive_bpm": 1.3,
            "vorp": 116.1,
            "career_def_rtg": 103,
            "triple_doubles": 28,
            "forty_plus_point_games": 173
        },
        {
            "player_name": "LeBron James",
            "seasons_played": 20,
            "games_played": 1568,
            "minutes_played": 62914,
            "field_goals_made": 14261,
            "field_goal_attempts": 27709,
            "field_goal_percentage": 51.4,
            "three_pointers_made": 2337,
            "three_pointer_attempts": 6538,
            "three_pointer_percentage": 35.7,
            "two_pointers_made": 11924,
            "two_pointer_attempts": 21171,
            "two_pointer_percentage": 56.3,
            "free_throws_made": 8369,
            "free_throw_attempts": 11100,
            "free_throw_percentage": 75.4,
            "offensive_rebounds": 1652,
            "defensive_rebounds": 9080,
            "total_rebounds": 10732,
            "assists": 10667,
            "steals": 2212,
            "blocks": 1074,
            "turnovers": 4937,
            "points": 38652,
            "all_star_appearances": 19,
            "all_nba_teams": 18,
            "mvp_awards": 4,
            "finals_mvp_awards": 4,
            "championships": 4,
            "career_per": 27.4,
            "career_ws": 257.0,
            "career_bpm": 8.8,
            # New Stats
            "true_shooting_percentage": 58.8,
            "effective_fg_percentage": 54.5,
            "offensive_bpm": 7.1,
            "defensive_bpm": 1.7,
            "vorp": 143.0,
            "career_def_rtg": 106,
            "triple_doubles": 107,
            "forty_plus_point_games": 72
        },
        {
            "player_name": "Kareem Abdul-Jabbar",
            "seasons_played": 20,
            "games_played": 1560,
            "minutes_played": 57446,
            "field_goals_made": 15837,
            "field_goal_attempts": 28307,
            "field_goal_percentage": 55.9,
            "three_pointers_made": 1,
            "three_pointer_attempts": 18,
            "three_pointer_percentage": 5.6,
            "two_pointers_made": 15836,
            "two_pointer_attempts": 28289,
            "two_pointer_percentage": 55.9,
            "free_throws_made": 6712,
            "free_throw_attempts": 9304,
            "free_throw_percentage": 72.1,
            "offensive_rebounds": 2731,
            "defensive_rebounds": 9224,
            "total_rebounds": 11954,
            "assists": 5660,
            "steals": 1160,
            "blocks": 3189,
            "turnovers": 4100,
            "points": 38387,
            "all_star_appearances": 19,
            "all_nba_teams": 15,
            "mvp_awards": 6,
            "finals_mvp_awards": 2,
            "championships": 6,
            "career_per": 24.6,
            "career_ws": 273.4,
            "career_bpm": 7.0,
            # New Stats
            "true_shooting_percentage": 59.2,
            "effective_fg_percentage": 55.0,
            "offensive_bpm": 4.1,
            "defensive_bpm": 2.6,
            "vorp": 104.4,
            "career_def_rtg": 99,
            "triple_doubles": 21,
            "forty_plus_point_games": 70
        },
        {
            "player_name": "Magic Johnson",
            "seasons_played": 13,
            "games_played": 906,
            "minutes_played": 33183,
            "field_goals_made": 7065,
            "field_goal_attempts": 13245,
            "field_goal_percentage": 53.0,
            "three_pointers_made": 325,
            "three_pointer_attempts": 1000,
            "three_pointer_percentage": 32.6,
            "two_pointers_made": 6740,
            "two_pointer_attempts": 12245,
            "two_pointer_percentage": 55.1,
            "free_throws_made": 4857,
            "free_throw_attempts": 5692,
            "free_throw_percentage": 85.4,
            "offensive_rebounds": 1180,
            "defensive_rebounds": 4831,
            "total_rebounds": 6011,
            "assists": 10141,
            "steals": 1724,
            "blocks": 374,
            "turnovers": 3595,
            "points": 17707,
            "all_star_appearances": 12,
            "all_nba_teams": 10,
            "mvp_awards": 3,
            "finals_mvp_awards": 3,
            "championships": 5,
            "career_per": 24.1,
            "career_ws": 155.8,
            "career_bpm": 7.5,
            # New Stats
            "true_shooting_percentage": 61.0,
            "effective_fg_percentage": 55.0,
            "offensive_bpm": 7.5,
            "defensive_bpm": 1.4,
            "vorp": 80.7,
            "career_def_rtg": 105,
            "triple_doubles": 138,
            "forty_plus_point_games": 20
        },
        {
            "player_name": "Larry Bird",
            "seasons_played": 13,
            "games_played": 897,
            "minutes_played": 34143,
            "field_goals_made": 8974,
            "field_goal_attempts": 17734,
            "field_goal_percentage": 50.0,
            "three_pointers_made": 649,
            "three_pointer_attempts": 1727,
            "three_pointer_percentage": 37.6,
            "two_pointers_made": 8325,
            "two_pointer_attempts": 16007,
            "two_pointer_percentage": 52.0,
            "free_throws_made": 3760,
            "free_throw_attempts": 4257,
            "free_throw_percentage": 89.0,
            "offensive_rebounds": 1117,
            "defensive_rebounds": 7117,
            "total_rebounds": 8234,
            "assists": 5695,
            "steals": 1556,
            "blocks": 755,
            "turnovers": 2947,
            "points": 21791,
            "all_star_appearances": 12,
            "all_nba_teams": 10,
            "mvp_awards": 3,
            "finals_mvp_awards": 2,
            "championships": 3,
            "career_per": 23.5,
            "career_ws": 145.8,
            "career_bpm": 7.6,
            # New Stats
            "true_shooting_percentage": 56.4,
            "effective_fg_percentage": 50.8,
            "offensive_bpm": 6.5,
            "defensive_bpm": 1.3,
            "vorp": 80.9,
            "career_def_rtg": 103,
            "triple_doubles": 59,
            "forty_plus_point_games": 47
        },
        {
            "player_name": "Bill Russell",
            "seasons_played": 13,
            "games_played": 963,
            "minutes_played": 40326,
            "field_goals_made": 5637,
            "field_goal_attempts": 13497,
            "field_goal_percentage": 41.9,
            "three_pointers_made": 0,
            "three_pointer_attempts": 0,
            "three_pointer_percentage": 0.0,
            "two_pointers_made": 5637,
            "two_pointer_attempts": 13497,
            "two_pointer_percentage": 41.9,
            "free_throws_made": 3337,
            "free_throw_attempts": 6262,
            "free_throw_percentage": 53.0,
            "offensive_rebounds": 0,
            "defensive_rebounds": 0,
            "total_rebounds": 21620,
            "assists": 4100,
            "steals": 0,
            "blocks": 0,
            "turnovers": 0,
            "points": 14522,
            "all_star_appearances": 12,
            "all_nba_teams": 11,
            "mvp_awards": 5,
            "finals_mvp_awards": 0,
            "championships": 11,
            "career_per": 18.9,
            "career_ws": 163.5,
            "career_bpm": 0.0,
            # New Stats
            "true_shooting_percentage": 47.0,
            "effective_fg_percentage": 44.0,
            "offensive_bpm": 1.0,
            "defensive_bpm": 5.0,
            "vorp": 50.0,
            "career_def_rtg": 95,
            "triple_doubles": 12,
            "forty_plus_point_games": 1
        },
        {
            "player_name": "Wilt Chamberlain",
            "seasons_played": 14,
            "games_played": 1045,
            "minutes_played": 47859,
            "field_goals_made": 12681,
            "field_goal_attempts": 23297,
            "field_goal_percentage": 54.0,
            "three_pointers_made": 0,
            "three_pointer_attempts": 0,
            "three_pointer_percentage": 0.0,
            "two_pointers_made": 12681,
            "two_pointer_attempts": 23297,
            "two_pointer_percentage": 54.0,
            "free_throws_made": 6057,
            "free_throw_attempts": 11862,
            "free_throw_percentage": 51.1,
            "offensive_rebounds": 0,
            "defensive_rebounds": 0,
            "total_rebounds": 23924,
            "assists": 4643,
            "steals": 0,
            "blocks": 0,
            "turnovers": 0,
            "points": 31419,
            "all_star_appearances": 13,
            "all_nba_teams": 10,
            "mvp_awards": 4,
            "finals_mvp_awards": 1,
            "championships": 2,
            "career_per": 26.2,
            "career_ws": 247.3,
            "career_bpm": 0.0,
            # New Stats
            "true_shooting_percentage": 54.0,
            "effective_fg_percentage": 54.0,
            "offensive_bpm": 3.0,
            "defensive_bpm": 2.0,
            "vorp": 70.0,
            "career_def_rtg": 100,
            "triple_doubles": 78,
            "forty_plus_point_games": 271
        },
        {
            "player_name": "Shaquille O'Neal",
            "seasons_played": 19,
            "games_played": 1207,
            "minutes_played": 41159,
            "field_goals_made": 11830,
            "field_goal_attempts": 19457,
            "field_goal_percentage": 60.0,
            "three_pointers_made": 1,
            "three_pointer_attempts": 22,
            "three_pointer_percentage": 4.5,
            "two_pointers_made": 11829,
            "two_pointer_attempts": 19435,
            "two_pointer_percentage": 60.9,
            "free_throws_made": 5935,
            "free_throw_attempts": 11252,
            "free_throw_percentage": 52.7,
            "offensive_rebounds": 4732,
            "defensive_rebounds": 8130,
            "total_rebounds": 12862,
            "assists": 3026,
            "steals": 739,
            "blocks": 2732,
            "turnovers": 3766,
            "points": 28596,
            "all_star_appearances": 15,
            "all_nba_teams": 14,
            "mvp_awards": 1,
            "finals_mvp_awards": 3,
            "championships": 4,
            "career_per": 26.4,
            "career_ws": 181.7,
            "career_bpm": 5.1,
            # New Stats
            "true_shooting_percentage": 58.6,
            "effective_fg_percentage": 58.2,
            "offensive_bpm": 5.5,
            "defensive_bpm": 1.5,
            "vorp": 79.2,
            "career_def_rtg": 100,
            "triple_doubles": 2,
            "forty_plus_point_games": 49
        },
        {
            "player_name": "Tim Duncan",
            "seasons_played": 19,
            "games_played": 1392,
            "minutes_played": 47368,
            "field_goals_made": 10485,
            "field_goal_attempts": 20334,
            "field_goal_percentage": 51.6,
            "three_pointers_made": 30,
            "three_pointer_attempts": 168,
            "three_pointer_percentage": 17.9,
            "two_pointers_made": 10455,
            "two_pointer_attempts": 20166,
            "two_pointer_percentage": 51.8,
            "free_throws_made": 5796,
            "free_throw_attempts": 8321,
            "free_throw_percentage": 69.6,
            "offensive_rebounds": 3857,
            "defensive_rebounds": 10491,
            "total_rebounds": 14348,
            "assists": 4225,
            "steals": 1014,
            "blocks": 3020,
            "turnovers": 3505,
            "points": 26496,
            "all_star_appearances": 15,
            "all_nba_teams": 15,
            "mvp_awards": 2,
            "finals_mvp_awards": 3,
            "championships": 5,
            "career_per": 24.2,
            "career_ws": 206.4,
            "career_bpm": 7.6,
            # New Stats
            "true_shooting_percentage": 55.1,
            "effective_fg_percentage": 50.7,
            "offensive_bpm": 4.1,
            "defensive_bpm": 2.9,
            "vorp": 89.6,
            "career_def_rtg": 96,
            "triple_doubles": 4,
            "forty_plus_point_games": 14
        },
        {
            "player_name": "Kobe Bryant",
            "seasons_played": 20,
            "games_played": 1346,
            "minutes_played": 48637,
            "field_goals_made": 11719,
            "field_goal_attempts": 26200,
            "field_goal_percentage": 44.7,
            "three_pointers_made": 1827,
            "three_pointer_attempts": 5546,
            "three_pointer_percentage": 32.9,
            "two_pointers_made": 9889,
            "two_pointer_attempts": 20654,
            "two_pointer_percentage": 47.9,
            "free_throws_made": 8378,
            "free_throw_attempts": 10011,
            "free_throw_percentage": 83.7,
            "offensive_rebounds": 1731,
            "defensive_rebounds": 5140,
            "total_rebounds": 6871,
            "assists": 6306,
            "steals": 1944,
            "blocks": 640,
            "turnovers": 4010,
            "points": 33643,
            "all_star_appearances": 18,
            "all_nba_teams": 15,
            "mvp_awards": 1,
            "finals_mvp_awards": 2,
            "championships": 5,
            "career_per": 22.9,
            "career_ws": 172.7,
            "career_bpm": 4.7,
            # New Stats
            "true_shooting_percentage": 55.0,
            "effective_fg_percentage": 48.2,
            "offensive_bpm": 4.7,
            "defensive_bpm": 0.3,
            "vorp": 76.6,
            "career_def_rtg": 105,
            "triple_doubles": 21,
            "forty_plus_point_games": 122
        },
        {
            "player_name": "Hakeem Olajuwon",
            "seasons_played": 18,
            "games_played": 1238,
            "minutes_played": 44222,
            "field_goals_made": 10949,
            "field_goal_attempts": 21186,
            "field_goal_percentage": 51.7,
            "three_pointers_made": 25,
            "three_pointer_attempts": 124,
            "three_pointer_percentage": 20.2,
            "two_pointers_made": 10924,
            "two_pointer_attempts": 21062,
            "two_pointer_percentage": 51.9,
            "free_throws_made": 5135,
            "free_throw_attempts": 6791,
            "free_throw_percentage": 75.1,
            "offensive_rebounds": 4261,
            "defensive_rebounds": 9063,
            "total_rebounds": 13324,
            "assists": 3058,
            "steals": 2162,
            "blocks": 3830,
            "turnovers": 3667,
            "points": 26946,
            "all_star_appearances": 12,
            "all_nba_teams": 12,
            "mvp_awards": 1,
            "finals_mvp_awards": 2,
            "championships": 2,
            "career_per": 23.6,
            "career_ws": 162.8,
            "career_bpm": 4.3,
            # New Stats
            "true_shooting_percentage": 55.3,
            "effective_fg_percentage": 51.2,
            "offensive_bpm": 1.5,
            "defensive_bpm": 3.3,
            "vorp": 75.0,
            "career_def_rtg": 99,
            "triple_doubles": 14,
            "forty_plus_point_games": 55
        },
        {
            "player_name": "Oscar Robertson",
            "seasons_played": 14,
            "games_played": 1040,
            "minutes_played": 0,  # Not fully tracked in older era
            "field_goals_made": 9887,
            "field_goal_attempts": 0,
            "field_goal_percentage": 48.5,
            "three_pointers_made": 0,
            "three_pointer_attempts": 0,
            "three_pointer_percentage": 0.0,
            "two_pointers_made": 9887,
            "two_pointer_attempts": 20399,
            "two_pointer_percentage": 48.5,
            "free_throws_made": 7694,
            "free_throw_attempts": 9905,
            "free_throw_percentage": 77.0,
            "offensive_rebounds": 0,
            "defensive_rebounds": 0,
            "total_rebounds": 7804,
            "assists": 9887,
            "steals": 0,
            "blocks": 0,
            "turnovers": 0,
            "points": 26710,
            "all_star_appearances": 12,
            "all_nba_teams": 11,
            "mvp_awards": 1,
            "finals_mvp_awards": 0,
            "championships": 1,
            "career_per": 23.2,
            "career_ws": 189.2,
            "career_bpm": 0.0,
            # New Stats
            "true_shooting_percentage": 56.0,
            "effective_fg_percentage": 47.8,
            "offensive_bpm": 5.0,
            "defensive_bpm": 0.0,
            "vorp": 80.0,
            "career_def_rtg": 105,
            "triple_doubles": 181,
            "forty_plus_point_games": 40
        },
        {
            "player_name": "Jerry West",
            "seasons_played": 14,
            "games_played": 932,
            "minutes_played": 0,
            "field_goals_made": 9000,
            "field_goal_attempts": 0,
            "field_goal_percentage": 47.4,
            "three_pointers_made": 0,
            "three_pointer_attempts": 0,
            "three_pointer_percentage": 0.0,
            "two_pointers_made": 9000,
            "two_pointer_attempts": 19000,
            "two_pointer_percentage": 47.4,
            "free_throws_made": 7000,
            "free_throw_attempts": 8400,
            "free_throw_percentage": 83.0,
            "offensive_rebounds": 0,
            "defensive_rebounds": 0,
            "total_rebounds": 5366,
            "assists": 6238,
            "steals": 0,
            "blocks": 0,
            "turnovers": 0,
            "points": 25192,
            "all_star_appearances": 14,
            "all_nba_teams": 12,
            "mvp_awards": 0,
            "finals_mvp_awards": 1,
            "championships": 1,
            "career_per": 22.9,
            "career_ws": 162.6,
            "career_bpm": 0.0,
            # New Stats
            "true_shooting_percentage": 54.9,
            "effective_fg_percentage": 47.4,
            "offensive_bpm": 4.5,
            "defensive_bpm": 1.0,
            "vorp": 70.0,
            "career_def_rtg": 104,
            "triple_doubles": 12,
            "forty_plus_point_games": 66
        },
        {
            "player_name": "Julius Erving",
            "seasons_played": 16,
            "games_played": 1243,
            "minutes_played": 0,
            "field_goals_made": 10792,
            "field_goal_attempts": 0,
            "field_goal_percentage": 50.6,
            "three_pointers_made": 160,
            "three_pointer_attempts": 592,
            "three_pointer_percentage": 27.0,
            "two_pointers_made": 10632,
            "two_pointer_attempts": 21000,
            "two_pointer_percentage": 50.6,
            "free_throws_made": 5140,
            "free_throw_attempts": 6940,
            "free_throw_percentage": 74.0,
            "offensive_rebounds": 0,
            "defensive_rebounds": 0,
            "total_rebounds": 10125,
            "assists": 5541,
            "steals": 2272,
            "blocks": 1941,
            "turnovers": 3500,
            "points": 30026,
            "all_star_appearances": 16,
            "all_nba_teams": 7,  # Strictly NBA
            "mvp_awards": 1,
            "finals_mvp_awards": 0,
            "championships": 1,
            "career_per": 22.0,
            "career_ws": 158.0,
            "career_bpm": 0.0,
            # New Stats
            "true_shooting_percentage": 54.9,
            "effective_fg_percentage": 50.2,
            "offensive_bpm": 3.5,
            "defensive_bpm": 1.0,
            "vorp": 60.0,
            "career_def_rtg": 100,
            "triple_doubles": 33,
            "forty_plus_point_games": 32
        },
        {
            "player_name": "Moses Malone",
            "seasons_played": 21,
            "games_played": 1455,
            "minutes_played": 0,
            "field_goals_made": 10079,
            "field_goal_attempts": 20555,
            "field_goal_percentage": 49.0,
            "three_pointers_made": 8,
            "three_pointer_attempts": 83,
            "three_pointer_percentage": 9.6,
            "two_pointers_made": 10071,
            "two_pointer_attempts": 20472,
            "two_pointer_percentage": 49.2,
            "free_throws_made": 8531,
            "free_throw_attempts": 11464,
            "free_throw_percentage": 74.3,
            "offensive_rebounds": 6731,
            "defensive_rebounds": 9052,
            "total_rebounds": 15783,
            "assists": 1796,
            "steals": 1155,
            "blocks": 1733,
            "turnovers": 3120,
            "points": 27409,
            "all_star_appearances": 12,
            "all_nba_teams": 8,
            "mvp_awards": 3,
            "finals_mvp_awards": 1,
            "championships": 1,
            "career_per": 22.0,
            "career_ws": 174.7,
            "career_bpm": 0.0,
            # New Stats
            "true_shooting_percentage": 56.9,
            "effective_fg_percentage": 50.0,
            "offensive_bpm": 2.5,
            "defensive_bpm": 1.5,
            "vorp": 55.0,
            "career_def_rtg": 100,
            "triple_doubles": 10,
            "forty_plus_point_games": 35
        },
        {
            "player_name": "Kevin Durant",
            "seasons_played": 15,
            "games_played": 986,
            "minutes_played": 35992,
            "field_goals_made": 10938,
            "field_goal_attempts": 21406,
            "field_goal_percentage": 51.1,
            "three_pointers_made": 1772,
            "three_pointer_attempts": 4578,
            "three_pointer_percentage": 38.7,
            "two_pointers_made": 9166,
            "two_pointer_attempts": 16828,
            "two_pointer_percentage": 54.4,
            "free_throws_made": 6708,
            "free_throw_attempts": 7550,
            "free_throw_percentage": 88.8,
            "offensive_rebounds": 887,
            "defensive_rebounds": 5199,
            "total_rebounds": 6086,
            "assists": 4436,
            "steals": 1014,
            "blocks": 1057,
            "turnovers": 3016,
            "points": 30403,
            "all_star_appearances": 13,
            "all_nba_teams": 10,
            "mvp_awards": 1,
            "finals_mvp_awards": 2,
            "championships": 2,
            "career_per": 25.4,
            "career_ws": 157.7,
            "career_bpm": 6.3,
            # New Stats
            "true_shooting_percentage": 61.6,
            "effective_fg_percentage": 54.6,
            "offensive_bpm": 6.0,
            "defensive_bpm": 1.0,
            "vorp": 75.0,
            "career_def_rtg": 107,
            "triple_doubles": 16,
            "forty_plus_point_games": 60
        },
        {
            "player_name": "Stephen Curry",
            "seasons_played": 14,
            "games_played": 882,
            "minutes_played": 28936,
            "field_goals_made": 7984,
            "field_goal_attempts": 16500,
            "field_goal_percentage": 48.4,
            "three_pointers_made": 3548,
            "three_pointer_attempts": 8147,
            "three_pointer_percentage": 43.5,
            "two_pointers_made": 4436,
            "two_pointer_attempts": 8353,
            "two_pointer_percentage": 53.1,
            "free_throws_made": 3461,
            "free_throw_attempts": 3780,
            "free_throw_percentage": 91.0,
            "offensive_rebounds": 722,
            "defensive_rebounds": 3382,
            "total_rebounds": 4104,
            "assists": 5822,
            "steals": 1398,
            "blocks": 200,
            "turnovers": 2597,
            "points": 23970,
            "all_star_appearances": 9,
            "all_nba_teams": 9,
            "mvp_awards": 2,
            "finals_mvp_awards": 1,
            "championships": 4,
            "career_per": 24.3,
            "career_ws": 130.0,
            "career_bpm": 6.8,
            # New Stats
            "true_shooting_percentage": 62.6,
            "effective_fg_percentage": 58.1,
            "offensive_bpm": 7.0,
            "defensive_bpm": 0.5,
            "vorp": 57.0,
            "career_def_rtg": 108,
            "triple_doubles": 12,
            "forty_plus_point_games": 56
        },
        {
            "player_name": "Giannis Antetokounmpo",
            "seasons_played": 10,
            "games_played": 719,
            "minutes_played": 23800,
            "field_goals_made": 5844,
            "field_goal_attempts": 10888,
            "field_goal_percentage": 53.7,
            "three_pointers_made": 586,
            "three_pointer_attempts": 1976,
            "three_pointer_percentage": 29.7,
            "two_pointers_made": 5258,
            "two_pointer_attempts": 8912,
            "two_pointer_percentage": 59.0,
            "free_throws_made": 3923,
            "free_throw_attempts": 5724,
            "free_throw_percentage": 68.6,
            "offensive_rebounds": 1488,
            "defensive_rebounds": 4501,
            "total_rebounds": 5989,
            "assists": 3109,
            "steals": 754,
            "blocks": 859,
            "turnovers": 1859,
            "points": 16197,
            "all_star_appearances": 7,
            "all_nba_teams": 6,
            "mvp_awards": 2,
            "finals_mvp_awards": 1,
            "championships": 1,
            "career_per": 23.9,
            "career_ws": 96.8,
            "career_bpm": 6.7,
            # New Stats
            "true_shooting_percentage": 60.4,
            "effective_fg_percentage": 55.0,
            "offensive_bpm": 5.9,
            "defensive_bpm": 2.2,
            "vorp": 41.0,
            "career_def_rtg": 105,
            "triple_doubles": 31,
            "forty_plus_point_games": 23
        },
        {
            "player_name": "Dirk Nowitzki",
            "seasons_played": 21,
            "games_played": 1522,
            "minutes_played": 51368,
            "field_goals_made": 11568,
            "field_goal_attempts": 22720,
            "field_goal_percentage": 47.1,
            "three_pointers_made": 1982,
            "three_pointer_attempts": 5210,
            "three_pointer_percentage": 38.0,
            "two_pointers_made": 9586,
            "two_pointer_attempts": 17510,
            "two_pointer_percentage": 54.7,
            "free_throws_made": 7240,
            "free_throw_attempts": 8373,
            "free_throw_percentage": 86.9,
            "offensive_rebounds": 1721,
            "defensive_rebounds": 8762,
            "total_rebounds": 10483,
            "assists": 3651,
            "steals": 1210,
            "blocks": 1261,
            "turnovers": 2551,
            "points": 31560,
            "all_star_appearances": 14,
            "all_nba_teams": 12,
            "mvp_awards": 1,
            "finals_mvp_awards": 1,
            "championships": 1,
            "career_per": 22.4,
            "career_ws": 206.3,
            "career_bpm": 3.6,
            # New Stats
            "true_shooting_percentage": 58.6,
            "effective_fg_percentage": 51.2,
            "offensive_bpm": 3.2,
            "defensive_bpm": 1.0,
            "vorp": 73.0,
            "career_def_rtg": 105,
            "triple_doubles": 1,
            "forty_plus_point_games": 20
        },
        {
            "player_name": "Karl Malone",
            "seasons_played": 19,
            "games_played": 1476,
            "minutes_played": 54852,
            "field_goals_made": 13528,
            "field_goal_attempts": 26210,
            "field_goal_percentage": 51.6,
            "three_pointers_made": 85,
            "three_pointer_attempts": 310,
            "three_pointer_percentage": 27.4,
            "two_pointers_made": 13443,
            "two_pointer_attempts": 25899,
            "two_pointer_percentage": 51.9,
            "free_throws_made": 9787,
            "free_throw_attempts": 13188,
            "free_throw_percentage": 74.2,
            "offensive_rebounds": 2382,
            "defensive_rebounds": 10410,
            "total_rebounds": 12792,
            "assists": 5248,
            "steals": 2085,
            "blocks": 1145,
            "turnovers": 4524,
            "points": 36928,
            "all_star_appearances": 14,
            "all_nba_teams": 14,
            "mvp_awards": 2,
            "finals_mvp_awards": 0,
            "championships": 0,
            "career_per": 23.9,
            "career_ws": 234.6,
            "career_bpm": 5.6,
            # New Stats
            "true_shooting_percentage": 57.7,
            "effective_fg_percentage": 51.8,
            "offensive_bpm": 3.5,
            "defensive_bpm": 1.0,
            "vorp": 90.0,
            "career_def_rtg": 102,
            "triple_doubles": 4,
            "forty_plus_point_games": 35
        },
        {
            "player_name": "Charles Barkley",
            "seasons_played": 16,
            "games_played": 1073,
            "minutes_played": 39330,
            "field_goals_made": 8865,
            "field_goal_attempts": 16232,
            "field_goal_percentage": 54.1,
            "three_pointers_made": 538,
            "three_pointer_attempts": 2020,
            "three_pointer_percentage": 26.6,
            "two_pointers_made": 8327,
            "two_pointer_attempts": 14212,
            "two_pointer_percentage": 58.6,
            "free_throws_made": 6010,
            "free_throw_attempts": 7986,
            "free_throw_percentage": 75.7,
            "offensive_rebounds": 4215,
            "defensive_rebounds": 7565,
            "total_rebounds": 11780,
            "assists": 4215,
            "steals": 1686,
            "blocks": 888,
            "turnovers": 3676,
            "points": 23757,
            "all_star_appearances": 11,
            "all_nba_teams": 11,
            "mvp_awards": 1,
            "finals_mvp_awards": 0,
            "championships": 0,
            "career_per": 24.6,
            "career_ws": 177.2,
            "career_bpm": 5.8,
            # New Stats
            "true_shooting_percentage": 60.0,
            "effective_fg_percentage": 55.0,
            "offensive_bpm": 4.5,
            "defensive_bpm": 1.0,
            "vorp": 80.0,
            "career_def_rtg": 103,
            "triple_doubles": 20,
            "forty_plus_point_games": 23
        },
        {
            "player_name": "John Havlicek",
            "seasons_played": 16,
            "games_played": 1270,
            "minutes_played": 46371,
            "field_goals_made": 10413,
            "field_goal_attempts": 0,
            "field_goal_percentage": 43.9,
            "three_pointers_made": 0,
            "three_pointer_attempts": 0,
            "three_pointer_percentage": 0.0,
            "two_pointers_made": 10413,
            "two_pointer_attempts": 23716,
            "two_pointer_percentage": 43.9,
            "free_throws_made": 5169,
            "free_throw_attempts": 6513,
            "free_throw_percentage": 79.0,
            "offensive_rebounds": 0,
            "defensive_rebounds": 0,
            "total_rebounds": 8007,
            "assists": 6114,
            "steals": 0,
            "blocks": 0,
            "turnovers": 0,
            "points": 26395,
            "all_star_appearances": 13,
            "all_nba_teams": 11,
            "mvp_awards": 0,
            "finals_mvp_awards": 0,
            "championships": 8,
            "career_per": 17.5,
            "career_ws": 131.7,
            "career_bpm": 0.0,
            # New Stats
            "true_shooting_percentage": 50.9,
            "effective_fg_percentage": 44.9,
            "offensive_bpm": 2.0,
            "defensive_bpm": 1.0,
            "vorp": 46.0,
            "career_def_rtg": 101,
            "triple_doubles": 31,
            "forty_plus_point_games": 7
        },
        {
            "player_name": "Scottie Pippen",
            "seasons_played": 17,
            "games_played": 1178,
            "minutes_played": 41069,
            "field_goals_made": 8512,
            "field_goal_attempts": 17940,
            "field_goal_percentage": 47.5,
            "three_pointers_made": 978,
            "three_pointer_attempts": 2903,
            "three_pointer_percentage": 33.7,
            "two_pointers_made": 7534,
            "two_pointer_attempts": 15037,
            "two_pointer_percentage": 50.1,
            "free_throws_made": 4494,
            "free_throw_attempts": 6229,
            "free_throw_percentage": 72.6,
            "offensive_rebounds": 1762,
            "defensive_rebounds": 5755,
            "total_rebounds": 7517,
            "assists": 6135,
            "steals": 2307,
            "blocks": 947,
            "turnovers": 3341,
            "points": 18940,
            "all_star_appearances": 7,
            "all_nba_teams": 10,
            "mvp_awards": 0,
            "finals_mvp_awards": 0,
            "championships": 6,
            "career_per": 18.6,
            "career_ws": 125.1,
            "career_bpm": 4.1,
            # New Stats
            "true_shooting_percentage": 53.6,
            "effective_fg_percentage": 50.4,
            "offensive_bpm": 2.5,
            "defensive_bpm": 2.5,
            "vorp": 80.0,
            "career_def_rtg": 99,
            "triple_doubles": 21,
            "forty_plus_point_games": 4
        },
        {
            "player_name": "Dwyane Wade",
            "seasons_played": 16,
            "games_played": 1054,
            "minutes_played": 36726,
            "field_goals_made": 8869,
            "field_goal_attempts": 18686,
            "field_goal_percentage": 47.5,
            "three_pointers_made": 570,
            "three_pointer_attempts": 1858,
            "three_pointer_percentage": 30.7,
            "two_pointers_made": 8299,
            "two_pointer_attempts": 16828,
            "two_pointer_percentage": 49.3,
            "free_throws_made": 6549,
            "free_throw_attempts": 8348,
            "free_throw_percentage": 78.0,
            "offensive_rebounds": 1087,
            "defensive_rebounds": 3439,
            "total_rebounds": 4526,
            "assists": 5701,
            "steals": 1620,
            "blocks": 885,
            "turnovers": 2995,
            "points": 23165,
            "all_star_appearances": 13,
            "all_nba_teams": 8,
            "mvp_awards": 0,
            "finals_mvp_awards": 1,
            "championships": 3,
            "career_per": 23.5,
            "career_ws": 120.7,
            "career_bpm": 4.6,
            # New Stats
            "true_shooting_percentage": 55.4,
            "effective_fg_percentage": 49.5,
            "offensive_bpm": 4.0,
            "defensive_bpm": 1.5,
            "vorp": 75.0,
            "career_def_rtg": 105,
            "triple_doubles": 5,
            "forty_plus_point_games": 37
        },
        {
            "player_name": "Kevin Garnett",
            "seasons_played": 21,
            "games_played": 1462,
            "minutes_played": 50617,
            "field_goals_made": 10418,
            "field_goal_attempts": 20523,
            "field_goal_percentage": 50.8,
            "three_pointers_made": 174,
            "three_pointer_attempts": 528,
            "three_pointer_percentage": 33.0,
            "two_pointers_made": 10244,
            "two_pointer_attempts": 19995,
            "two_pointer_percentage": 51.2,
            "free_throws_made": 5012,
            "free_throw_attempts": 6817,
            "free_throw_percentage": 73.5,
            "offensive_rebounds": 3107,
            "defensive_rebounds": 11353,
            "total_rebounds": 14460,
            "assists": 5015,
            "steals": 1859,
            "blocks": 2037,
            "turnovers": 3300,
            "points": 26071,
            "all_star_appearances": 15,
            "all_nba_teams": 9,
            "mvp_awards": 1,
            "finals_mvp_awards": 0,
            "championships": 1,
            "career_per": 22.7,
            "career_ws": 191.4,
            "career_bpm": 5.4,
            # New Stats
            "true_shooting_percentage": 54.7,
            "effective_fg_percentage": 49.8,
            "offensive_bpm": 3.5,
            "defensive_bpm": 3.0,
            "vorp": 96.0,
            "career_def_rtg": 99,
            "triple_doubles": 19,
            "forty_plus_point_games": 16
        },
        {
            "player_name": "David Robinson",
            "seasons_played": 14,
            "games_played": 987,
            "minutes_played": 34496,
            "field_goals_made": 7289,
            "field_goal_attempts": 13011,
            "field_goal_percentage": 56.0,
            "three_pointers_made": 25,
            "three_pointer_attempts": 100,
            "three_pointer_percentage": 25.0,
            "two_pointers_made": 7264,
            "two_pointer_attempts": 12911,
            "two_pointer_percentage": 56.3,
            "free_throws_made": 6654,
            "free_throw_attempts": 9304,
            "free_throw_percentage": 71.5,
            "offensive_rebounds": 2664,
            "defensive_rebounds": 7314,
            "total_rebounds": 9978,
            "assists": 2500,
            "steals": 1388,
            "blocks": 2954,
            "turnovers": 2201,
            "points": 20790,
            "all_star_appearances": 10,
            "all_nba_teams": 10,
            "mvp_awards": 1,
            "finals_mvp_awards": 0,
            "championships": 2,
            "career_per": 26.2,
            "career_ws": 178.7,
            "career_bpm": 6.1,
            # New Stats
            "true_shooting_percentage": 58.3,
            "effective_fg_percentage": 55.0,
            "offensive_bpm": 4.7,
            "defensive_bpm": 4.0,
            "vorp": 80.0,
            "career_def_rtg": 95,
            "triple_doubles": 14,
            "forty_plus_point_games": 19
        },
        {
            "player_name": "Elgin Baylor",
            "seasons_played": 14,
            "games_played": 846,
            "minutes_played": 0,
            "field_goals_made": 0,
            "field_goal_attempts": 0,
            "field_goal_percentage": 43.1,
            "three_pointers_made": 0,
            "three_pointer_attempts": 0,
            "three_pointer_percentage": 0.0,
            "two_pointers_made": 0,
            "two_pointer_attempts": 0,
            "two_pointer_percentage": 0.0,
            "free_throws_made": 0,
            "free_throw_attempts": 0,
            "free_throw_percentage": 0.0,
            "offensive_rebounds": 0,
            "defensive_rebounds": 0,
            "total_rebounds": 11463,
            "assists": 3650,
            "steals": 0,
            "blocks": 0,
            "turnovers": 0,
            "points": 23149,
            "all_star_appearances": 11,
            "all_nba_teams": 10,
            "mvp_awards": 0,
            "finals_mvp_awards": 0,
            "championships": 0,
            "career_per": 22.7,
            "career_ws": 104.2,
            "career_bpm": 0.0,
            # New Stats
            "true_shooting_percentage": 51.6,
            "effective_fg_percentage": 43.1,
            "offensive_bpm": 0.0,
            "defensive_bpm": 0.0,
            "vorp": 50.0,
            "career_def_rtg": 105,
            "triple_doubles": 24,
            "forty_plus_point_games": 88
        },
        {
            "player_name": "John Stockton",
            "seasons_played": 19,
            "games_played": 1504,
            "minutes_played": 47764,
            "field_goals_made": 8252,
            "field_goal_attempts": 15115,
            "field_goal_percentage": 54.1,
            "three_pointers_made": 845,
            "three_pointer_attempts": 2345,
            "three_pointer_percentage": 36.0,
            "two_pointers_made": 7407,
            "two_pointer_attempts": 12770,
            "two_pointer_percentage": 58.0,
            "free_throws_made": 3787,
            "free_throw_attempts": 4560,
            "free_throw_percentage": 83.2,
            "offensive_rebounds": 848,
            "defensive_rebounds": 3681,
            "total_rebounds": 4529,
            "assists": 15806,
            "steals": 3265,
            "blocks": 315,
            "turnovers": 4244,
            "points": 19711,
            "all_star_appearances": 10,
            "all_nba_teams": 11,
            "mvp_awards": 0,
            "finals_mvp_awards": 0,
            "championships": 0,
            "career_per": 21.8,
            "career_ws": 207.7,
            "career_bpm": 4.2,
            # New Stats
            "true_shooting_percentage": 60.8,
            "effective_fg_percentage": 58.5,
            "offensive_bpm": 3.7,
            "defensive_bpm": 2.0,
            "vorp": 90.0,
            "career_def_rtg": 104,
            "triple_doubles": 31,
            "forty_plus_point_games": 5
        },
        {
            "player_name": "Isiah Thomas",
            "seasons_played": 13,
            "games_played": 979,
            "minutes_played": 35516,
            "field_goals_made": 9061,
            "field_goal_attempts": 19620,
            "field_goal_percentage": 46.2,
            "three_pointers_made": 398,
            "three_pointer_attempts": 1211,
            "three_pointer_percentage": 32.9,
            "two_pointers_made": 8663,
            "two_pointer_attempts": 18409,
            "two_pointer_percentage": 47.0,
            "free_throws_made": 4492,
            "free_throw_attempts": 5585,
            "free_throw_percentage": 80.3,
            "offensive_rebounds": 698,
            "defensive_rebounds": 2331,
            "total_rebounds": 3029,
            "assists": 9061,
            "steals": 1861,
            "blocks": 200,
            "turnovers": 3862,
            "points": 18822,
            "all_star_appearances": 12,
            "all_nba_teams": 5,
            "mvp_awards": 0,
            "finals_mvp_awards": 1,
            "championships": 2,
            "career_per": 18.1,
            "career_ws": 80.7,
            "career_bpm": 2.6,
            # New Stats
            "true_shooting_percentage": 51.6,
            "effective_fg_percentage": 46.5,
            "offensive_bpm": 2.0,
            "defensive_bpm": 0.5,
            "vorp": 35.0,
            "career_def_rtg": 108,
            "triple_doubles": 6,
            "forty_plus_point_games": 22
        },
        {
            "player_name": "Allen Iverson",
            "seasons_played": 14,
            "games_played": 914,
            "minutes_played": 37864,
            "field_goals_made": 8186,
            "field_goal_attempts": 19606,
            "field_goal_percentage": 41.1,
            "three_pointers_made": 1783,
            "three_pointer_attempts": 5605,
            "three_pointer_percentage": 31.8,
            "two_pointers_made": 6403,
            "two_pointer_attempts": 14001,
            "two_pointer_percentage": 45.7,
            "free_throws_made": 6090,
            "free_throw_attempts": 7513,
            "free_throw_percentage": 81.8,
            "offensive_rebounds": 781,
            "defensive_rebounds": 1775,
            "total_rebounds": 2556,
            "assists": 6248,
            "steals": 1983,
            "blocks": 164,
            "turnovers": 3662,
            "points": 24368,
            "all_star_appearances": 11,
            "all_nba_teams": 7,
            "mvp_awards": 1,
            "finals_mvp_awards": 0,
            "championships": 0,
            "career_per": 20.9,
            "career_ws": 99.0,
            "career_bpm": 2.3,
            # New Stats
            "true_shooting_percentage": 51.8,
            "effective_fg_percentage": 45.2,
            "offensive_bpm": 3.0,
            "defensive_bpm": -0.5,
            "vorp": 40.0,
            "career_def_rtg": 106,
            "triple_doubles": 5,
            "forty_plus_point_games": 79
        },
        {
            "player_name": "Chris Paul",
            "seasons_played": 18,
            "games_played": 1214,
            "minutes_played": 41664,
            "field_goals_made": 9324,
            "field_goal_attempts": 18702,
            "field_goal_percentage": 49.9,
            "three_pointers_made": 1540,
            "three_pointer_attempts": 4164,
            "three_pointer_percentage": 37.0,
            "two_pointers_made": 7784,
            "two_pointer_attempts": 14538,
            "two_pointer_percentage": 53.5,
            "free_throws_made": 4135,
            "free_throw_attempts": 4792,
            "free_throw_percentage": 86.3,
            "offensive_rebounds": 704,
            "defensive_rebounds": 4473,
            "total_rebounds": 5177,
            "assists": 12061,
            "steals": 2678,
            "blocks": 155,
            "turnovers": 2909,
            "points": 24385,
            "all_star_appearances": 12,
            "all_nba_teams": 11,
            "mvp_awards": 0,
            "finals_mvp_awards": 0,
            "championships": 0,
            "career_per": 24.0,
            "career_ws": 214.4,
            "career_bpm": 7.2,
            # New Stats
            "true_shooting_percentage": 58.1,
            "effective_fg_percentage": 52.8,
            "offensive_bpm": 6.0,
            "defensive_bpm": 2.3,
            "vorp": 75.0,
            "career_def_rtg": 106,
            "triple_doubles": 20,
            "forty_plus_point_games": 3
        },
        {
            "player_name": "James Harden",
            "seasons_played": 14,
            "games_played": 1010,
            "minutes_played": 35777,
            "field_goals_made": 7895,
            "field_goal_attempts": 17926,
            "field_goal_percentage": 44.0,
            "three_pointers_made": 3030,
            "three_pointer_attempts": 8424,
            "three_pointer_percentage": 36.0,
            "two_pointers_made": 4865,
            "two_pointer_attempts": 10502,
            "two_pointer_percentage": 46.3,
            "free_throws_made": 7165,
            "free_throw_attempts": 8311,
            "free_throw_percentage": 86.2,
            "offensive_rebounds": 718,
            "defensive_rebounds": 4017,
            "total_rebounds": 4735,
            "assists": 6808,
            "steals": 1393,
            "blocks": 477,
            "turnovers": 3745,
            "points": 25885,
            "all_star_appearances": 10,
            "all_nba_teams": 7,
            "mvp_awards": 1,
            "finals_mvp_awards": 0,
            "championships": 0,
            "career_per": 24.8,
            "career_ws": 156.0,
            "career_bpm": 6.8,
            # New Stats
            "true_shooting_percentage": 60.6,
            "effective_fg_percentage": 52.5,
            "offensive_bpm": 7.0,
            "defensive_bpm": 0.3,
            "vorp": 65.0,
            "career_def_rtg": 110,
            "triple_doubles": 74,
            "forty_plus_point_games": 101
        },
        {
            "player_name": "Kawhi Leonard",
            "seasons_played": 12,
            "games_played": 628,
            "minutes_played": 19800,
            "field_goals_made": 4658,
            "field_goal_attempts": 9355,
            "field_goal_percentage": 49.8,
            "three_pointers_made": 915,
            "three_pointer_attempts": 2365,
            "three_pointer_percentage": 38.7,
            "two_pointers_made": 3743,
            "two_pointer_attempts": 6990,
            "two_pointer_percentage": 53.6,
            "free_throws_made": 3099,
            "free_throw_attempts": 3710,
            "free_throw_percentage": 83.5,
            "offensive_rebounds": 695,
            "defensive_rebounds": 2835,
            "total_rebounds": 3530,
            "assists": 1715,
            "steals": 873,
            "blocks": 349,
            "turnovers": 905,
            # Correct approximate total points:
            "points": 11667,
            "all_star_appearances": 5,
            "all_nba_teams": 5,
            "mvp_awards": 0,
            "finals_mvp_awards": 2,
            "championships": 2,
            "career_per": 23.5,
            "career_ws": 85.4,
            "career_bpm": 5.8,
            # New Stats
            "true_shooting_percentage": 58.0,
            "effective_fg_percentage": 53.4,
            "offensive_bpm": 4.5,
            "defensive_bpm": 2.2,
            "vorp": 40.0,
            "career_def_rtg": 102,
            "triple_doubles": 5,
            "forty_plus_point_games": 12
        },
        {
            "player_name": "Patrick Ewing",
            "seasons_played": 17,
            "games_played": 1183,
            "minutes_played": 39396,
            "field_goals_made": 9945,
            "field_goal_attempts": 18624,
            "field_goal_percentage": 53.4,
            "three_pointers_made": 19,
            "three_pointer_attempts": 125,
            "three_pointer_percentage": 15.2,
            "two_pointers_made": 9926,
            "two_pointer_attempts": 18499,
            "two_pointer_percentage": 53.7,
            "free_throws_made": 5535,
            "free_throw_attempts": 7422,
            "free_throw_percentage": 74.0,
            "offensive_rebounds": 3266,
            "defensive_rebounds": 7464,
            "total_rebounds": 10730,
            "assists": 2025,
            "steals": 1121,
            "blocks": 2894,
            "turnovers": 2880,
            "points": 24815,
            "all_star_appearances": 11,
            "all_nba_teams": 7,
            "mvp_awards": 0,
            "finals_mvp_awards": 0,
            "championships": 0,
            "career_per": 21.0,
            "career_ws": 126.4,
            "career_bpm": 3.2,
            # New Stats
            "true_shooting_percentage": 55.1,
            "effective_fg_percentage": 51.8,
            "offensive_bpm": 3.0,
            "defensive_bpm": 2.0,
            "vorp": 50.0,
            "career_def_rtg": 102,
            "triple_doubles": 0,
            "forty_plus_point_games": 15
        },
        {
            "player_name": "Reggie Miller",
            "seasons_played": 18,
            "games_played": 1389,
            "minutes_played": 47000,
            "field_goals_made": 8094,
            "field_goal_attempts": 17279,
            "field_goal_percentage": 46.1,
            "three_pointers_made": 2560,
            "three_pointer_attempts": 6486,
            "three_pointer_percentage": 39.5,
            "two_pointers_made": 5534,
            "two_pointer_attempts": 10793,
            "two_pointer_percentage": 51.3,
            "free_throws_made": 6456,
            "free_throw_attempts": 7535,
            "free_throw_percentage": 85.8,
            "offensive_rebounds": 722,
            "defensive_rebounds": 3139,
            "total_rebounds": 3861,
            "assists": 4141,
            "steals": 1505,
            "blocks": 397,
            "turnovers": 1525,
            "points": 25279,
            "all_star_appearances": 5,
            "all_nba_teams": 3,
            "mvp_awards": 0,
            "finals_mvp_awards": 0,
            "championships": 0,
            "career_per": 18.4,
            "career_ws": 174.4,
            "career_bpm": 2.8,
            # New Stats
            "true_shooting_percentage": 61.4,
            "effective_fg_percentage": 54.0,
            "offensive_bpm": 3.0,
            "defensive_bpm": 0.0,
            "vorp": 50.0,
            "career_def_rtg": 107,
            "triple_doubles": 5,
            "forty_plus_point_games": 9
        }
    ]

    # Write out to CSV
    with open(filename, mode="w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=headers)
        writer.writeheader()
        for pdata in players_data:
            # Fill in any missing fields with a safe default (like 0)
            for h in headers:
                if h not in pdata:
                    pdata[h] = 0
            writer.writerow(pdata)

if __name__ == "__main__":
    create_basketball_dataset()
    print("basketball_dataset.csv has been created/updated with 30 players, each with 40 stats (32 core + 8 new).")
