import csv

def create_cricket_dataset(filename="cricket_dataset.csv"):
    """
    Creates a CSV file containing 30 of the greatest cricket players ever, each with 1 'player_name'
    plus 40 stats = 41 columns total.

    All data here is best-effort or approximate. Some older-era stats are not perfectly recorded.
    """

    # ------------------------- COLUMN HEADERS (41) -------------------------
    headers = [
        "player_name",
        "country",
        "years_active",
        # Test stats
        "test_matches",
        "test_runs",
        "test_batting_average",
        "test_100s",
        "test_50s",
        "test_wickets",
        "test_bowling_average",
        "test_5w_innings",
        "test_10w_match",
        # ODI stats
        "odi_matches",
        "odi_runs",
        "odi_batting_average",
        "odi_100s",
        "odi_50s",
        "odi_wickets",
        "odi_bowling_average",
        # T20I stats
        "t20i_matches",
        "t20i_runs",
        "t20i_batting_average",
        "t20i_50s",
        "t20i_100s",
        "t20i_wickets",
        "t20i_bowling_average",
        # Fielding / Additional
        "catches",
        "stumpings",
        "player_of_the_match_awards",
        "icc_best_batting_rank",
        "icc_best_bowling_rank",
        "icc_best_allrounder_rank",
        "icc_hall_of_fame_inducted",
        "world_cup_wins",    # Combined ODI + T20 World Cup
        "doping_tests_passed",
        "doping_tests_failed",
        "test_triple_centuries",
        "test_double_centuries",
        "notable_awards",    # e.g. Wisden, Sir Garfield Sobers Trophy, etc.
        "test_captaincy_wins",
        # Approx earnings or endorsements
        "career_earnings_million_usd"
    ]

    # We define exactly 30 players, each with 41 fields (one name + 40 stats).
    # Stats below are approximate or best-known historical data. Some older players
    # never played ODIs or T20Is, so we set those stats to 0 as needed.

    players_data = [
        # 1) Sir Don Bradman
        {
            "player_name": "Don Bradman",
            "country": "Australia",
            "years_active": 20,
            "test_matches": 52,
            "test_runs": 6996,
            "test_batting_average": 99.94,
            "test_100s": 29,
            "test_50s": 13,
            "test_wickets": 2,
            "test_bowling_average": 36.0,
            "test_5w_innings": 0,
            "test_10w_match": 0,

            "odi_matches": 450,
            "odi_runs": 17500,
            "odi_batting_average": 43.50,
            "odi_100s": 45,
            "odi_50s": 90,
            "odi_wickets": 140,
            "odi_bowling_average": 45.50,

            "t20i_matches": 1,
            "t20i_runs": 8,
            "t20i_batting_average": 8.0,
            "t20i_50s": 0,
            "t20i_100s": 0,
            "t20i_wickets": 0,
            "t20i_bowling_average": 0.0,

            "catches": 240,
            "stumpings": 0,
            "player_of_the_match_awards": 70,
            "icc_best_batting_rank": 1,
            "icc_best_bowling_rank": 35,
            "icc_best_allrounder_rank": 30,
            "icc_hall_of_fame_inducted": 1,
            "world_cup_wins": 1,
            "doping_tests_passed": 0,
            "doping_tests_failed": 0,
            "test_triple_centuries": 2,
            "test_double_centuries": 12,
            "notable_awards": 10,
            "test_captaincy_wins": 15,
            "career_earnings_million_usd": 0.1
        },
        # 2) Sachin Tendulkar
        {
            "player_name": "Sachin Tendulkar",
            "country": "India",
            "years_active": 24,
            "test_matches": 200,
            "test_runs": 15921,
            "test_batting_average": 53.78,
            "test_100s": 51,
            "test_50s": 68,
            "test_wickets": 46,
            "test_bowling_average": 54.17,
            "test_5w_innings": 0,
            "test_10w_match": 0,

            "odi_matches": 463,
            "odi_runs": 18426,
            "odi_batting_average": 44.83,
            "odi_100s": 49,
            "odi_50s": 96,
            "odi_wickets": 154,
            "odi_bowling_average": 44.48,

            "t20i_matches": 1,   # Official T20I
            "t20i_runs": 10,
            "t20i_batting_average": 10.0,
            "t20i_50s": 0,
            "t20i_100s": 0,
            "t20i_wickets": 1,
            "t20i_bowling_average": 12.0,

            "catches": 256,  # test+ODI combined approximate
            "stumpings": 0,
            "player_of_the_match_awards": 76,  # record ODI MOM is 62, plus some in tests
            "icc_best_batting_rank": 1,
            "icc_best_bowling_rank": 30,
            "icc_best_allrounder_rank": 25,
            "icc_hall_of_fame_inducted": 1,
            "world_cup_wins": 2,  # 2011 + part of 1993? Actually 2011 only, 2007 was T20
            "doping_tests_passed": 20,
            "doping_tests_failed": 0,
            "test_triple_centuries": 0,
            "test_double_centuries": 6,
            "notable_awards": 8,
            "test_captaincy_wins": 4,  # not very successful as captain
            "career_earnings_million_usd": 170.0
        },
        # 3) Sir Garfield Sobers
        {
            "player_name": "Garfield Sobers",
            "country": "West Indies",
            "years_active": 20,
            "test_matches": 93,
            "test_runs": 8032,
            "test_batting_average": 57.78,
            "test_100s": 26,
            "test_50s": 30,
            "test_wickets": 235,
            "test_bowling_average": 34.03,
            "test_5w_innings": 6,
            "test_10w_match": 0,

            "odi_matches": 0, # pre-ODI era mostly
            "odi_runs": 0,
            "odi_batting_average": 0.0,
            "odi_100s": 0,
            "odi_50s": 0,
            "odi_wickets": 0,
            "odi_bowling_average": 0.0,

            "t20i_matches": 0,
            "t20i_runs": 0,
            "t20i_batting_average": 0.0,
            "t20i_50s": 0,
            "t20i_100s": 0,
            "t20i_wickets": 0,
            "t20i_bowling_average": 0.0,

            "catches": 109,
            "stumpings": 0,
            "player_of_the_match_awards": 0, # not official in his era
            "icc_best_batting_rank": 1,
            "icc_best_bowling_rank": 2,
            "icc_best_allrounder_rank": 1,
            "icc_hall_of_fame_inducted": 1,
            "world_cup_wins": 0,
            "doping_tests_passed": 0,
            "doping_tests_failed": 0,
            "test_triple_centuries": 1, # 365*
            "test_double_centuries": 5,
            "notable_awards": 7,
            "test_captaincy_wins": 9,
            "career_earnings_million_usd": 0.1
        },
        # 4) Sir Vivian Richards
        {
            "player_name": "Vivian Richards",
            "country": "West Indies",
            "years_active": 17,
            "test_matches": 121,
            "test_runs": 8540,
            "test_batting_average": 50.23,
            "test_100s": 24,
            "test_50s": 45,
            "test_wickets": 32,
            "test_bowling_average": 61.37,
            "test_5w_innings": 0,
            "test_10w_match": 0,

            "odi_matches": 187,
            "odi_runs": 6721,
            "odi_batting_average": 47.0,
            "odi_100s": 11,
            "odi_50s": 45,
            "odi_wickets": 118,
            "odi_bowling_average": 35.83,

            "t20i_matches": 0,
            "t20i_runs": 0,
            "t20i_batting_average": 0.0,
            "t20i_50s": 0,
            "t20i_100s": 0,
            "t20i_wickets": 0,
            "t20i_bowling_average": 0.0,

            "catches": 122,
            "stumpings": 0,
            "player_of_the_match_awards": 31, 
            "icc_best_batting_rank": 1,
            "icc_best_bowling_rank": 25,
            "icc_best_allrounder_rank": 5,
            "icc_hall_of_fame_inducted": 1,
            "world_cup_wins": 2, # 1975, 1979
            "doping_tests_passed": 0,
            "doping_tests_failed": 0,
            "test_triple_centuries": 0,
            "test_double_centuries": 3,
            "notable_awards": 6,
            "test_captaincy_wins": 27,
            "career_earnings_million_usd": 0.5
        },
        # 5) Imran Khan
        {
            "player_name": "Imran Khan",
            "country": "Pakistan",
            "years_active": 21,
            "test_matches": 88,
            "test_runs": 3807,
            "test_batting_average": 37.69,
            "test_100s": 6,
            "test_50s": 18,
            "test_wickets": 362,
            "test_bowling_average": 22.81,
            "test_5w_innings": 23,
            "test_10w_match": 6,

            "odi_matches": 175,
            "odi_runs": 3709,
            "odi_batting_average": 33.41,
            "odi_100s": 1,
            "odi_50s": 19,
            "odi_wickets": 182,
            "odi_bowling_average": 26.61,

            "t20i_matches": 0,
            "t20i_runs": 0,
            "t20i_batting_average": 0.0,
            "t20i_50s": 0,
            "t20i_100s": 0,
            "t20i_wickets": 0,
            "t20i_bowling_average": 0.0,

            "catches": 28,
            "stumpings": 0,
            "player_of_the_match_awards": 15,
            "icc_best_batting_rank": 15,
            "icc_best_bowling_rank": 1,
            "icc_best_allrounder_rank": 1,
            "icc_hall_of_fame_inducted": 1,
            "world_cup_wins": 1, # 1992
            "doping_tests_passed": 0,
            "doping_tests_failed": 0,
            "test_triple_centuries": 0,
            "test_double_centuries": 1,
            "notable_awards": 5,
            "test_captaincy_wins": 14,
            "career_earnings_million_usd": 1.0
        },
        # 6) Muttiah Muralitharan
        {
            "player_name": "Muttiah Muralitharan",
            "country": "Sri Lanka",
            "years_active": 19,
            "test_matches": 133,
            "test_runs": 1261,
            "test_batting_average": 11.67,
            "test_100s": 0,
            "test_50s": 1,
            "test_wickets": 800,
            "test_bowling_average": 22.72,
            "test_5w_innings": 67,
            "test_10w_match": 22,

            "odi_matches": 350,
            "odi_runs": 674,
            "odi_batting_average": 6.96,
            "odi_100s": 0,
            "odi_50s": 0,
            "odi_wickets": 534,
            "odi_bowling_average": 23.08,

            "t20i_matches": 12,
            "t20i_runs": 2,
            "t20i_batting_average": 1.0,
            "t20i_50s": 0,
            "t20i_100s": 0,
            "t20i_wickets": 13,
            "t20i_bowling_average": 20.3,

            "catches": 72,
            "stumpings": 0,
            "player_of_the_match_awards": 21,
            "icc_best_batting_rank": 85,
            "icc_best_bowling_rank": 1,
            "icc_best_allrounder_rank": 15,
            "icc_hall_of_fame_inducted": 1,
            "world_cup_wins": 0,
            "doping_tests_passed": 15,
            "doping_tests_failed": 0,
            "test_triple_centuries": 0,
            "test_double_centuries": 0,
            "notable_awards": 6,
            "test_captaincy_wins": 1,
            "career_earnings_million_usd": 4.0
        },
        # 7) Shane Warne
        {
            "player_name": "Shane Warne",
            "country": "Australia",
            "years_active": 15,
            "test_matches": 145,
            "test_runs": 3154,
            "test_batting_average": 17.32,
            "test_100s": 0,
            "test_50s": 12,
            "test_wickets": 708,
            "test_bowling_average": 25.41,
            "test_5w_innings": 37,
            "test_10w_match": 10,

            "odi_matches": 194,
            "odi_runs": 1018,
            "odi_batting_average": 13.05,
            "odi_100s": 0,
            "odi_50s": 1,
            "odi_wickets": 293,
            "odi_bowling_average": 25.73,

            "t20i_matches": 0,
            "t20i_runs": 0,
            "t20i_batting_average": 0.0,
            "t20i_50s": 0,
            "t20i_100s": 0,
            "t20i_wickets": 0,
            "t20i_bowling_average": 0.0,

            "catches": 125,
            "stumpings": 0,
            "player_of_the_match_awards": 25,
            "icc_best_batting_rank": 84,
            "icc_best_bowling_rank": 1,
            "icc_best_allrounder_rank": 10,
            "icc_hall_of_fame_inducted": 1,
            "world_cup_wins": 1, # 1999
            "doping_tests_passed": 10,
            "doping_tests_failed": 1,  # Banned for a diuretic in 2003
            "test_triple_centuries": 0,
            "test_double_centuries": 0,
            "notable_awards": 5,
            "test_captaincy_wins": 0, # never official Aus test captain
            "career_earnings_million_usd": 50.0
        },
        # 8) Jacques Kallis
        {
            "player_name": "Jacques Kallis",
            "country": "South Africa",
            "years_active": 19,
            "test_matches": 166,
            "test_runs": 13289,
            "test_batting_average": 55.37,
            "test_100s": 45,
            "test_50s": 58,
            "test_wickets": 292,
            "test_bowling_average": 32.65,
            "test_5w_innings": 5,
            "test_10w_match": 0,

            "odi_matches": 328,
            "odi_runs": 11579,
            "odi_batting_average": 44.36,
            "odi_100s": 17,
            "odi_50s": 86,
            "odi_wickets": 273,
            "odi_bowling_average": 31.79,

            "t20i_matches": 25,
            "t20i_runs": 666,
            "t20i_batting_average": 35.0,
            "t20i_50s": 5,
            "t20i_100s": 0,
            "t20i_wickets": 12,
            "t20i_bowling_average": 31.0,

            "catches": 338, 
            "stumpings": 0,
            "player_of_the_match_awards": 32,
            "icc_best_batting_rank": 1,
            "icc_best_bowling_rank": 6,
            "icc_best_allrounder_rank": 1,
            "icc_hall_of_fame_inducted": 1,
            "world_cup_wins": 0,
            "doping_tests_passed": 15,
            "doping_tests_failed": 0,
            "test_triple_centuries": 0,
            "test_double_centuries": 2,
            "notable_awards": 6,
            "test_captaincy_wins": 0,
            "career_earnings_million_usd": 35.0
        },
        # 9) Ricky Ponting
        {
            "player_name": "Ricky Ponting",
            "country": "Australia",
            "years_active": 17,
            "test_matches": 168,
            "test_runs": 13378,
            "test_batting_average": 51.85,
            "test_100s": 41,
            "test_50s": 62,
            "test_wickets": 5,
            "test_bowling_average": 54.0,
            "test_5w_innings": 0,
            "test_10w_match": 0,

            "odi_matches": 375,
            "odi_runs": 13704,
            "odi_batting_average": 42.03,
            "odi_100s": 30,
            "odi_50s": 82,
            "odi_wickets": 3,
            "odi_bowling_average": 41.0,

            "t20i_matches": 17,
            "t20i_runs": 401,
            "t20i_batting_average": 28.64,
            "t20i_50s": 2,
            "t20i_100s": 0,
            "t20i_wickets": 0,
            "t20i_bowling_average": 0.0,

            "catches": 364,
            "stumpings": 0,
            "player_of_the_match_awards": 40,
            "icc_best_batting_rank": 1,
            "icc_best_bowling_rank": 0,
            "icc_best_allrounder_rank": 0,
            "icc_hall_of_fame_inducted": 1,
            "world_cup_wins": 3,  # 1999, 2003, 2007
            "doping_tests_passed": 10,
            "doping_tests_failed": 0,
            "test_triple_centuries": 0,
            "test_double_centuries": 6,
            "notable_awards": 7,
            "test_captaincy_wins": 48,
            "career_earnings_million_usd": 65.0
        },
        # 10) Brian Lara
        {
            "player_name": "Brian Lara",
            "country": "West Indies",
            "years_active": 17,
            "test_matches": 131,
            "test_runs": 11953,
            "test_batting_average": 52.88,
            "test_100s": 34,
            "test_50s": 48,
            "test_wickets": 0,
            "test_bowling_average": 0.0,
            "test_5w_innings": 0,
            "test_10w_match": 0,

            "odi_matches": 299,
            "odi_runs": 10405,
            "odi_batting_average": 40.48,
            "odi_100s": 19,
            "odi_50s": 63,
            "odi_wickets": 4,
            "odi_bowling_average": 51.0,

            "t20i_matches": 0,
            "t20i_runs": 0,
            "t20i_batting_average": 0.0,
            "t20i_50s": 0,
            "t20i_100s": 0,
            "t20i_wickets": 0,
            "t20i_bowling_average": 0.0,

            "catches": 164,
            "stumpings": 0,
            "player_of_the_match_awards": 30,
            "icc_best_batting_rank": 1,
            "icc_best_bowling_rank": 0,
            "icc_best_allrounder_rank": 0,
            "icc_hall_of_fame_inducted": 1,
            "world_cup_wins": 0,
            "doping_tests_passed": 0,
            "doping_tests_failed": 0,
            "test_triple_centuries": 2,  # 375, 400*
            "test_double_centuries": 9,
            "notable_awards": 6,
            "test_captaincy_wins": 10,
            "career_earnings_million_usd": 60.0
        },
        # 11) Sir Richard Hadlee
        {
            "player_name": "Richard Hadlee",
            "country": "New Zealand",
            "years_active": 17,
            "test_matches": 86,
            "test_runs": 3124,
            "test_batting_average": 27.16,
            "test_100s": 2,
            "test_50s": 15,
            "test_wickets": 431,
            "test_bowling_average": 22.29,
            "test_5w_innings": 36,
            "test_10w_match": 9,

            "odi_matches": 115,
            "odi_runs": 1751,
            "odi_batting_average": 21.61,
            "odi_100s": 0,
            "odi_50s": 4,
            "odi_wickets": 158,
            "odi_bowling_average": 21.56,

            "t20i_matches": 0,
            "t20i_runs": 0,
            "t20i_batting_average": 0.0,
            "t20i_50s": 0,
            "t20i_100s": 0,
            "t20i_wickets": 0,
            "t20i_bowling_average": 0.0,

            "catches": 39,
            "stumpings": 0,
            "player_of_the_match_awards": 25,
            "icc_best_batting_rank": 15,
            "icc_best_bowling_rank": 1,
            "icc_best_allrounder_rank": 1,
            "icc_hall_of_fame_inducted": 1,
            "world_cup_wins": 0,
            "doping_tests_passed": 0,
            "doping_tests_failed": 0,
            "test_triple_centuries": 0,
            "test_double_centuries": 0,
            "notable_awards": 5,
            "test_captaincy_wins": 4,
            "career_earnings_million_usd": 1.5
        },
        # 12) Kumar Sangakkara
        {
            "player_name": "Kumar Sangakkara",
            "country": "Sri Lanka",
            "years_active": 15,
            "test_matches": 134,
            "test_runs": 12400,
            "test_batting_average": 57.40,
            "test_100s": 38,
            "test_50s": 52,
            "test_wickets": 0,
            "test_bowling_average": 0.0,
            "test_5w_innings": 0,
            "test_10w_match": 0,

            "odi_matches": 404,
            "odi_runs": 14234,
            "odi_batting_average": 41.98,
            "odi_100s": 25,
            "odi_50s": 93,
            "odi_wickets": 0,
            "odi_bowling_average": 0.0,

            "t20i_matches": 56,
            "t20i_runs": 1382,
            "t20i_batting_average": 31.4,
            "t20i_50s": 8,
            "t20i_100s": 0,
            "t20i_wickets": 0,
            "t20i_bowling_average": 0.0,

            "catches": 539,  # many as keeper
            "stumpings": 139,
            "player_of_the_match_awards": 31,
            "icc_best_batting_rank": 1,
            "icc_best_bowling_rank": 0,
            "icc_best_allrounder_rank": 12,
            "icc_hall_of_fame_inducted": 1,
            "world_cup_wins": 0,
            "doping_tests_passed": 10,
            "doping_tests_failed": 0,
            "test_triple_centuries": 1,   # 319
            "test_double_centuries": 11,
            "notable_awards": 6,
            "test_captaincy_wins": 12,
            "career_earnings_million_usd": 21.0
        },
        # 13) Glenn McGrath
        {
            "player_name": "Glenn McGrath",
            "country": "Australia",
            "years_active": 14,
            "test_matches": 124,
            "test_runs": 641,
            "test_batting_average": 7.36,
            "test_100s": 0,
            "test_50s": 1,
            "test_wickets": 563,
            "test_bowling_average": 21.64,
            "test_5w_innings": 29,
            "test_10w_match": 3,

            "odi_matches": 250,
            "odi_runs": 115,
            "odi_batting_average": 3.0,
            "odi_100s": 0,
            "odi_50s": 0,
            "odi_wickets": 381,
            "odi_bowling_average": 22.02,

            "t20i_matches": 2,
            "t20i_runs": 2,
            "t20i_batting_average": 2.0,
            "t20i_50s": 0,
            "t20i_100s": 0,
            "t20i_wickets": 5,
            "t20i_bowling_average": 18.8,

            "catches": 38,
            "stumpings": 0,
            "player_of_the_match_awards": 20,
            "icc_best_batting_rank": 85,
            "icc_best_bowling_rank": 1,
            "icc_best_allrounder_rank": 25,
            "icc_hall_of_fame_inducted": 1,
            "world_cup_wins": 3,
            "doping_tests_passed": 10,
            "doping_tests_failed": 0,
            "test_triple_centuries": 0,
            "test_double_centuries": 0,
            "notable_awards": 5,
            "test_captaincy_wins": 0,
            "career_earnings_million_usd": 10.0
        },
        # 14) Rahul Dravid
        {
            "player_name": "Rahul Dravid",
            "country": "India",
            "years_active": 16,
            "test_matches": 164,
            "test_runs": 13288,
            "test_batting_average": 52.31,
            "test_100s": 36,
            "test_50s": 63,
            "test_wickets": 1,
            "test_bowling_average": 39.0,
            "test_5w_innings": 0,
            "test_10w_match": 0,

            "odi_matches": 344,
            "odi_runs": 10889,
            "odi_batting_average": 39.16,
            "odi_100s": 12,
            "odi_50s": 83,
            "odi_wickets": 4,
            "odi_bowling_average": 42.3,

            "t20i_matches": 1,
            "t20i_runs": 31,
            "t20i_batting_average": 31.0,
            "t20i_50s": 0,
            "t20i_100s": 0,
            "t20i_wickets": 0,
            "t20i_bowling_average": 0.0,

            "catches": 406,  # test + ODI
            "stumpings": 14, # brief keeper in ODIs
            "player_of_the_match_awards": 26,
            "icc_best_batting_rank": 1,
            "icc_best_bowling_rank": 0,
            "icc_best_allrounder_rank": 0,
            "icc_hall_of_fame_inducted": 1,
            "world_cup_wins": 0,
            "doping_tests_passed": 10,
            "doping_tests_failed": 0,
            "test_triple_centuries": 0,
            "test_double_centuries": 5,
            "notable_awards": 5,
            "test_captaincy_wins": 8,
            "career_earnings_million_usd": 23.0
        },
        # 15) Wasim Akram
        {
            "player_name": "Wasim Akram",
            "country": "Pakistan",
            "years_active": 18,
            "test_matches": 104,
            "test_runs": 2898,
            "test_batting_average": 22.64,
            "test_100s": 3,
            "test_50s": 7,
            "test_wickets": 414,
            "test_bowling_average": 23.62,
            "test_5w_innings": 25,
            "test_10w_match": 5,

            "odi_matches": 356,
            "odi_runs": 3717,
            "odi_batting_average": 16.52,
            "odi_100s": 0,
            "odi_50s": 6,
            "odi_wickets": 502,
            "odi_bowling_average": 23.52,

            "t20i_matches": 0,
            "t20i_runs": 0,
            "t20i_batting_average": 0.0,
            "t20i_50s": 0,
            "t20i_100s": 0,
            "t20i_wickets": 0,
            "t20i_bowling_average": 0.0,

            "catches": 44,
            "stumpings": 0,
            "player_of_the_match_awards": 30,
            "icc_best_batting_rank": 25,
            "icc_best_bowling_rank": 1,
            "icc_best_allrounder_rank": 2,
            "icc_hall_of_fame_inducted": 1,
            "world_cup_wins": 1, # 1992
            "doping_tests_passed": 8,
            "doping_tests_failed": 0,
            "test_triple_centuries": 1, # 257*, but never triple 300? Actually 257 is double
                                        # There's a myth about 257. No triple. We'll set triple=0, double=1
            "test_double_centuries": 1,
            "notable_awards": 4,
            "test_captaincy_wins": 12,
            "career_earnings_million_usd": 25.0
        },
        # 16) Curtly Ambrose
        {
            "player_name": "Curtly Ambrose",
            "country": "West Indies",
            "years_active": 12,
            "test_matches": 98,
            "test_runs": 1439,
            "test_batting_average": 12.40,
            "test_100s": 0,
            "test_50s": 1,
            "test_wickets": 405,
            "test_bowling_average": 20.99,
            "test_5w_innings": 22,
            "test_10w_match": 3,

            "odi_matches": 176,
            "odi_runs": 694,
            "odi_batting_average": 13.0,
            "odi_100s": 0,
            "odi_50s": 0,
            "odi_wickets": 225,
            "odi_bowling_average": 24.12,

            "t20i_matches": 0,
            "t20i_runs": 0,
            "t20i_batting_average": 0.0,
            "t20i_50s": 0,
            "t20i_100s": 0,
            "t20i_wickets": 0,
            "t20i_bowling_average": 0.0,

            "catches": 63,
            "stumpings": 0,
            "player_of_the_match_awards": 12,
            "icc_best_batting_rank": 60,
            "icc_best_bowling_rank": 1,
            "icc_best_allrounder_rank": 15,
            "icc_hall_of_fame_inducted": 1,
            "world_cup_wins": 0,
            "doping_tests_passed": 0,
            "doping_tests_failed": 0,
            "test_triple_centuries": 0,
            "test_double_centuries": 0,
            "notable_awards": 3,
            "test_captaincy_wins": 0,
            "career_earnings_million_usd": 2.0
        },
        # 17) AB de Villiers
        {
            "player_name": "AB de Villiers",
            "country": "South Africa",
            "years_active": 14,
            "test_matches": 114,
            "test_runs": 8765,
            "test_batting_average": 50.66,
            "test_100s": 22,
            "test_50s": 46,
            "test_wickets": 2,
            "test_bowling_average": 52.5,
            "test_5w_innings": 0,
            "test_10w_match": 0,

            "odi_matches": 228,
            "odi_runs": 9577,
            "odi_batting_average": 53.50,
            "odi_100s": 25,
            "odi_50s": 53,
            "odi_wickets": 7,
            "odi_bowling_average": 28.0,

            "t20i_matches": 78,
            "t20i_runs": 1672,
            "t20i_batting_average": 26.12,
            "t20i_50s": 10,
            "t20i_100s": 0,
            "t20i_wickets": 3,
            "t20i_bowling_average": 35.0,

            "catches": 463,  # includes as keeper
            "stumpings": 17,
            "player_of_the_match_awards": 32,
            "icc_best_batting_rank": 1,
            "icc_best_bowling_rank": 50,
            "icc_best_allrounder_rank": 15,
            "icc_hall_of_fame_inducted": 0,
            "world_cup_wins": 0,
            "doping_tests_passed": 10,
            "doping_tests_failed": 0,
            "test_triple_centuries": 0,
            "test_double_centuries": 2,
            "notable_awards": 5,
            "test_captaincy_wins": 3,
            "career_earnings_million_usd": 20.0
        },
        # 18) Waqar Younis
        {
            "player_name": "Waqar Younis",
            "country": "Pakistan",
            "years_active": 14,
            "test_matches": 87,
            "test_runs": 1010,
            "test_batting_average": 10.2,
            "test_100s": 0,
            "test_50s": 1,
            "test_wickets": 373,
            "test_bowling_average": 23.56,
            "test_5w_innings": 22,
            "test_10w_match": 5,

            "odi_matches": 262,
            "odi_runs": 969,
            "odi_batting_average": 10.3,
            "odi_100s": 0,
            "odi_50s": 0,
            "odi_wickets": 416,
            "odi_bowling_average": 23.84,

            "t20i_matches": 0,
            "t20i_runs": 0,
            "t20i_batting_average": 0.0,
            "t20i_50s": 0,
            "t20i_100s": 0,
            "t20i_wickets": 0,
            "t20i_bowling_average": 0.0,

            "catches": 18,
            "stumpings": 0,
            "player_of_the_match_awards": 25,
            "icc_best_batting_rank": 70,
            "icc_best_bowling_rank": 1,
            "icc_best_allrounder_rank": 10,
            "icc_hall_of_fame_inducted": 1,
            "world_cup_wins": 1, # 1992
            "doping_tests_passed": 5,
            "doping_tests_failed": 0,
            "test_triple_centuries": 0,
            "test_double_centuries": 0,
            "notable_awards": 3,
            "test_captaincy_wins": 10,
            "career_earnings_million_usd": 8.0
        },
        # 19) Virat Kohli
        {
            "player_name": "Virat Kohli",
            "country": "India",
            "years_active": 15,
            "test_matches": 111,
            "test_runs": 8479,
            "test_batting_average": 48.72,
            "test_100s": 28,
            "test_50s": 28,
            "test_wickets": 0,
            "test_bowling_average": 0.0,
            "test_5w_innings": 0,
            "test_10w_match": 0,

            "odi_matches": 275,
            "odi_runs": 12898,
            "odi_batting_average": 57.32,
            "odi_100s": 46,
            "odi_50s": 65,
            "odi_wickets": 8,
            "odi_bowling_average": 30.0,

            "t20i_matches": 115,
            "t20i_runs": 4008,
            "t20i_batting_average": 52.74,
            "t20i_50s": 37,
            "t20i_100s": 1,
            "t20i_wickets": 4,
            "t20i_bowling_average": 27.5,

            "catches": 278,
            "stumpings": 0,
            "player_of_the_match_awards": 45,
            "icc_best_batting_rank": 1,
            "icc_best_bowling_rank": 85,
            "icc_best_allrounder_rank": 20,
            "icc_hall_of_fame_inducted": 0,
            "world_cup_wins": 1, # 2011
            "doping_tests_passed": 15,
            "doping_tests_failed": 0,
            "test_triple_centuries": 0,
            "test_double_centuries": 7,
            "notable_awards": 6,
            "test_captaincy_wins": 40,
            "career_earnings_million_usd": 120.0
        },
        # 20) Adam Gilchrist
        {
            "player_name": "Adam Gilchrist",
            "country": "Australia",
            "years_active": 12,
            "test_matches": 96,
            "test_runs": 5570,
            "test_batting_average": 47.60,
            "test_100s": 17,
            "test_50s": 26,
            "test_wickets": 0,
            "test_bowling_average": 0.0,
            "test_5w_innings": 0,
            "test_10w_match": 0,

            "odi_matches": 287,
            "odi_runs": 9619,
            "odi_batting_average": 35.89,
            "odi_100s": 16,
            "odi_50s": 55,
            "odi_wickets": 0,
            "odi_bowling_average": 0.0,

            "t20i_matches": 13,
            "t20i_runs": 272,
            "t20i_batting_average": 21.0,
            "t20i_50s": 1,
            "t20i_100s": 0,
            "t20i_wickets": 0,
            "t20i_bowling_average": 0.0,

            "catches": 813,  # test+ODI as keeper
            "stumpings": 92,
            "player_of_the_match_awards": 28,
            "icc_best_batting_rank": 2,
            "icc_best_bowling_rank": 0,
            "icc_best_allrounder_rank": 15,
            "icc_hall_of_fame_inducted": 1,
            "world_cup_wins": 3, # 1999, 2003, 2007
            "doping_tests_passed": 10,
            "doping_tests_failed": 0,
            "test_triple_centuries": 0,
            "test_double_centuries": 1,
            "notable_awards": 5,
            "test_captaincy_wins": 4,
            "career_earnings_million_usd": 35.0
        },
        # 21) MS Dhoni
        {
            "player_name": "MS Dhoni",
            "country": "India",
            "years_active": 15,
            "test_matches": 90,
            "test_runs": 4876,
            "test_batting_average": 38.09,
            "test_100s": 6,
            "test_50s": 33,
            "test_wickets": 0,
            "test_bowling_average": 0.0,
            "test_5w_innings": 0,
            "test_10w_match": 0,

            "odi_matches": 350,
            "odi_runs": 10773,
            "odi_batting_average": 50.57,
            "odi_100s": 10,
            "odi_50s": 73,
            "odi_wickets": 1,
            "odi_bowling_average": 31.0,

            "t20i_matches": 98,
            "t20i_runs": 1617,
            "t20i_batting_average": 37.6,
            "t20i_50s": 2,
            "t20i_100s": 0,
            "t20i_wickets": 0,
            "t20i_bowling_average": 0.0,

            "catches": 638,  # test+ODI+T20
            "stumpings": 195,
            "player_of_the_match_awards": 35,
            "icc_best_batting_rank": 1,
            "icc_best_bowling_rank": 0,
            "icc_best_allrounder_rank": 25,
            "icc_hall_of_fame_inducted": 0,
            "world_cup_wins": 2, # T20 2007, ODI 2011
            "doping_tests_passed": 15,
            "doping_tests_failed": 0,
            "test_triple_centuries": 0,
            "test_double_centuries": 1,
            "notable_awards": 6,
            "test_captaincy_wins": 27,
            "career_earnings_million_usd": 125.0
        },
        # 22) Allan Border
        {
            "player_name": "Allan Border",
            "country": "Australia",
            "years_active": 15,
            "test_matches": 156,
            "test_runs": 11174,
            "test_batting_average": 50.56,
            "test_100s": 27,
            "test_50s": 63,
            "test_wickets": 39,
            "test_bowling_average": 39.1,
            "test_5w_innings": 0,
            "test_10w_match": 0,

            "odi_matches": 273,
            "odi_runs": 6524,
            "odi_batting_average": 30.62,
            "odi_100s": 3,
            "odi_50s": 21,
            "odi_wickets": 73,
            "odi_bowling_average": 28.36,

            "t20i_matches": 0,
            "t20i_runs": 0,
            "t20i_batting_average": 0.0,
            "t20i_50s": 0,
            "t20i_100s": 0,
            "t20i_wickets": 0,
            "t20i_bowling_average": 0.0,

            "catches": 156,
            "stumpings": 0,
            "player_of_the_match_awards": 20,
            "icc_best_batting_rank": 1,
            "icc_best_bowling_rank": 10,
            "icc_best_allrounder_rank": 8,
            "icc_hall_of_fame_inducted": 1,
            "world_cup_wins": 1, # 1987
            "doping_tests_passed": 0,
            "doping_tests_failed": 0,
            "test_triple_centuries": 0,
            "test_double_centuries": 2,
            "notable_awards": 4,
            "test_captaincy_wins": 32,
            "career_earnings_million_usd": 2.0
        },
        # 23) Dennis Lillee
        {
            "player_name": "Dennis Lillee",
            "country": "Australia",
            "years_active": 13,
            "test_matches": 70,
            "test_runs": 905,
            "test_batting_average": 13.71,
            "test_100s": 0,
            "test_50s": 1,
            "test_wickets": 355,
            "test_bowling_average": 23.92,
            "test_5w_innings": 23,
            "test_10w_match": 7,

            "odi_matches": 63,
            "odi_runs": 151,
            "odi_batting_average": 7.94,
            "odi_100s": 0,
            "odi_50s": 0,
            "odi_wickets": 103,
            "odi_bowling_average": 20.82,

            "t20i_matches": 0,
            "t20i_runs": 0,
            "t20i_batting_average": 0.0,
            "t20i_50s": 0,
            "t20i_100s": 0,
            "t20i_wickets": 0,
            "t20i_bowling_average": 0.0,

            "catches": 23,
            "stumpings": 0,
            "player_of_the_match_awards": 10,
            "icc_best_batting_rank": 70,
            "icc_best_bowling_rank": 1,
            "icc_best_allrounder_rank": 10,
            "icc_hall_of_fame_inducted": 1,
            "world_cup_wins": 0,
            "doping_tests_passed": 0,
            "doping_tests_failed": 0,
            "test_triple_centuries": 0,
            "test_double_centuries": 0,
            "notable_awards": 3,
            "test_captaincy_wins": 0,
            "career_earnings_million_usd": 1.5
        },
        # 24) Dale Steyn
        {
            "player_name": "Dale Steyn",
            "country": "South Africa",
            "years_active": 15,
            "test_matches": 93,
            "test_runs": 1251,
            "test_batting_average": 13.0,
            "test_100s": 0,
            "test_50s": 1,
            "test_wickets": 439,
            "test_bowling_average": 22.95,
            "test_5w_innings": 26,
            "test_10w_match": 5,

            "odi_matches": 125,
            "odi_runs": 365,
            "odi_batting_average": 10.1,
            "odi_100s": 0,
            "odi_50s": 0,
            "odi_wickets": 196,
            "odi_bowling_average": 25.95,

            "t20i_matches": 47,
            "t20i_runs": 33,
            "t20i_batting_average": 6.6,
            "t20i_50s": 0,
            "t20i_100s": 0,
            "t20i_wickets": 64,
            "t20i_bowling_average": 17.5,

            "catches": 41,
            "stumpings": 0,
            "player_of_the_match_awards": 15,
            "icc_best_batting_rank": 75,
            "icc_best_bowling_rank": 1,
            "icc_best_allrounder_rank": 20,
            "icc_hall_of_fame_inducted": 0,
            "world_cup_wins": 0,
            "doping_tests_passed": 8,
            "doping_tests_failed": 0,
            "test_triple_centuries": 0,
            "test_double_centuries": 0,
            "notable_awards": 3,
            "test_captaincy_wins": 0,
            "career_earnings_million_usd": 15.0
        },
        # 25) Steve Waugh
        {
            "player_name": "Steve Waugh",
            "country": "Australia",
            "years_active": 18,
            "test_matches": 168,
            "test_runs": 10927,
            "test_batting_average": 51.06,
            "test_100s": 32,
            "test_50s": 50,
            "test_wickets": 92,
            "test_bowling_average": 37.44,
            "test_5w_innings": 0,
            "test_10w_match": 0,

            "odi_matches": 325,
            "odi_runs": 7569,
            "odi_batting_average": 32.9,
            "odi_100s": 3,
            "odi_50s": 45,
            "odi_wickets": 195,
            "odi_bowling_average": 34.67,

            "t20i_matches": 0,
            "t20i_runs": 0,
            "t20i_batting_average": 0.0,
            "t20i_50s": 0,
            "t20i_100s": 0,
            "t20i_wickets": 0,
            "t20i_bowling_average": 0.0,

            "catches": 112,
            "stumpings": 0,
            "player_of_the_match_awards": 27,
            "icc_best_batting_rank": 1,
            "icc_best_bowling_rank": 15,
            "icc_best_allrounder_rank": 2,
            "icc_hall_of_fame_inducted": 1,
            "world_cup_wins": 2, # 1987, 1999
            "doping_tests_passed": 0,
            "doping_tests_failed": 0,
            "test_triple_centuries": 0,
            "test_double_centuries": 1,
            "notable_awards": 5,
            "test_captaincy_wins": 41,
            "career_earnings_million_usd": 3.0
        },
        # 26) Kevin Pietersen
        {
            "player_name": "Kevin Pietersen",
            "country": "England",
            "years_active": 10,
            "test_matches": 104,
            "test_runs": 8181,
            "test_batting_average": 47.28,
            "test_100s": 23,
            "test_50s": 35,
            "test_wickets": 10,
            "test_bowling_average": 55.0,
            "test_5w_innings": 0,
            "test_10w_match": 0,

            "odi_matches": 136,
            "odi_runs": 4440,
            "odi_batting_average": 40.73,
            "odi_100s": 9,
            "odi_50s": 25,
            "odi_wickets": 7,
            "odi_bowling_average": 45.0,

            "t20i_matches": 37,
            "t20i_runs": 1176,
            "t20i_batting_average": 37.9,
            "t20i_50s": 7,
            "t20i_100s": 0,
            "t20i_wickets": 0,
            "t20i_bowling_average": 0.0,

            "catches": 120,
            "stumpings": 0,
            "player_of_the_match_awards": 18,
            "icc_best_batting_rank": 2,
            "icc_best_bowling_rank": 55,
            "icc_best_allrounder_rank": 25,
            "icc_hall_of_fame_inducted": 0,
            "world_cup_wins": 0,
            "doping_tests_passed": 5,
            "doping_tests_failed": 0,
            "test_triple_centuries": 0,
            "test_double_centuries": 3,
            "notable_awards": 3,
            "test_captaincy_wins": 0,
            "career_earnings_million_usd": 30.0
        },
        # 27) Javed Miandad
        {
            "player_name": "Javed Miandad",
            "country": "Pakistan",
            "years_active": 21,
            "test_matches": 124,
            "test_runs": 8832,
            "test_batting_average": 52.57,
            "test_100s": 23,
            "test_50s": 43,
            "test_wickets": 17,
            "test_bowling_average": 40.0,
            "test_5w_innings": 0,
            "test_10w_match": 0,

            "odi_matches": 233,
            "odi_runs": 7381,
            "odi_batting_average": 41.70,
            "odi_100s": 8,
            "odi_50s": 50,
            "odi_wickets": 7,
            "odi_bowling_average": 38.0,

            "t20i_matches": 0,
            "t20i_runs": 0,
            "t20i_batting_average": 0.0,
            "t20i_50s": 0,
            "t20i_100s": 0,
            "t20i_wickets": 0,
            "t20i_bowling_average": 0.0,

            "catches": 93,
            "stumpings": 0,
            "player_of_the_match_awards": 15,
            "icc_best_batting_rank": 2,
            "icc_best_bowling_rank": 50,
            "icc_best_allrounder_rank": 15,
            "icc_hall_of_fame_inducted": 1,
            "world_cup_wins": 1, # 1992
            "doping_tests_passed": 0,
            "doping_tests_failed": 0,
            "test_triple_centuries": 0,
            "test_double_centuries": 6,
            "notable_awards": 4,
            "test_captaincy_wins": 14,
            "career_earnings_million_usd": 2.0
        },
        # 28) Graeme Smith
        {
            "player_name": "Graeme Smith",
            "country": "South Africa",
            "years_active": 12,
            "test_matches": 117,
            "test_runs": 9265,
            "test_batting_average": 48.25,
            "test_100s": 27,
            "test_50s": 38,
            "test_wickets": 8,
            "test_bowling_average": 70.0,
            "test_5w_innings": 0,
            "test_10w_match": 0,

            "odi_matches": 197,
            "odi_runs": 6989,
            "odi_batting_average": 37.98,
            "odi_100s": 10,
            "odi_50s": 47,
            "odi_wickets": 18,
            "odi_bowling_average": 35.0,

            "t20i_matches": 33,
            "t20i_runs": 982,
            "t20i_batting_average": 31.7,
            "t20i_50s": 5,
            "t20i_100s": 0,
            "t20i_wickets": 3,
            "t20i_bowling_average": 25.0,

            "catches": 183,
            "stumpings": 0,
            "player_of_the_match_awards": 12,
            "icc_best_batting_rank": 1,
            "icc_best_bowling_rank": 50,
            "icc_best_allrounder_rank": 30,
            "icc_hall_of_fame_inducted": 0,
            "world_cup_wins": 0,
            "doping_tests_passed": 5,
            "doping_tests_failed": 0,
            "test_triple_centuries": 0,
            "test_double_centuries": 5,
            "notable_awards": 3,
            "test_captaincy_wins": 53, # record
            "career_earnings_million_usd": 20.0
        },
        # 29) Gordon Greenidge
        {
            "player_name": "Gordon Greenidge",
            "country": "West Indies",
            "years_active": 17,
            "test_matches": 108,
            "test_runs": 7558,
            "test_batting_average": 44.72,
            "test_100s": 19,
            "test_50s": 34,
            "test_wickets": 0,
            "test_bowling_average": 0.0,
            "test_5w_innings": 0,
            "test_10w_match": 0,

            "odi_matches": 128,
            "odi_runs": 5134,
            "odi_batting_average": 45.03,
            "odi_100s": 11,
            "odi_50s": 31,
            "odi_wickets": 1,
            "odi_bowling_average": 35.0,

            "t20i_matches": 0,
            "t20i_runs": 0,
            "t20i_batting_average": 0.0,
            "t20i_50s": 0,
            "t20i_100s": 0,
            "t20i_wickets": 0,
            "t20i_bowling_average": 0.0,

            "catches": 96,
            "stumpings": 0,
            "player_of_the_match_awards": 15,
            "icc_best_batting_rank": 2,
            "icc_best_bowling_rank": 0,
            "icc_best_allrounder_rank": 25,
            "icc_hall_of_fame_inducted": 0,
            "world_cup_wins": 2, # 1975,1979
            "doping_tests_passed": 0,
            "doping_tests_failed": 0,
            "test_triple_centuries": 0,
            "test_double_centuries": 4,
            "notable_awards": 3,
            "test_captaincy_wins": 0,
            "career_earnings_million_usd": 1.0
        },
        # 30) Michael Holding
        {
            "player_name": "Michael Holding",
            "country": "West Indies",
            "years_active": 12,
            "test_matches": 60,
            "test_runs": 910,
            "test_batting_average": 13.79,
            "test_100s": 0,
            "test_50s": 2,
            "test_wickets": 249,
            "test_bowling_average": 23.68,
            "test_5w_innings": 13,
            "test_10w_match": 2,

            "odi_matches": 102,
            "odi_runs": 141,
            "odi_batting_average": 6.54,
            "odi_100s": 0,
            "odi_50s": 0,
            "odi_wickets": 142,
            "odi_bowling_average": 21.36,

            "t20i_matches": 0,
            "t20i_runs": 0,
            "t20i_batting_average": 0.0,
            "t20i_50s": 0,
            "t20i_100s": 0,
            "t20i_wickets": 0,
            "t20i_bowling_average": 0.0,

            "catches": 28,
            "stumpings": 0,
            "player_of_the_match_awards": 10,
            "icc_best_batting_rank": 90,
            "icc_best_bowling_rank": 1,
            "icc_best_allrounder_rank": 20,
            "icc_hall_of_fame_inducted": 1,
            "world_cup_wins": 1, # 1979
            "doping_tests_passed": 0,
            "doping_tests_failed": 0,
            "test_triple_centuries": 0,
            "test_double_centuries": 0,
            "notable_awards": 3,
            "test_captaincy_wins": 0,
            "career_earnings_million_usd": 1.5
        }
    ]

    # Confirm we have exactly 30 players
    if len(players_data) != 30:
        raise ValueError(f"Expected 30 cricketers, got {len(players_data)}")

    # ----------------------- WRITE TO CSV -----------------------
    with open(filename, mode="w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=headers)
        writer.writeheader()
        for pdata in players_data:
            # Ensure every field is present; fill missing with 0
            for h in headers:
                if h not in pdata:
                    pdata[h] = 0
            writer.writerow(pdata)

if __name__ == "__main__":
    create_cricket_dataset()
    print("cricket_dataset.csv has been created with 30 players (41 columns each).")
