import csv

def create_mlb_dataset(filename="mlb_dataset.csv"):
    """
    Creates a CSV file containing 30 MLB players with 40+ stats each.
    Stats are approximations, intended for demonstration and for building
    an 'MLB Index Score' later in Step 2.
    
    A single dataset includes both hitters and pitchers. 
    Pitching stats for hitters (and vice versa) are set to 0.
    """

    # Define the header (41 columns: player_name + 40 stats)
    headers = [
        "player_name",
        "position",
        "seasons_played",
        "games_played",
        "plate_appearances",
        "hits",
        "home_runs",
        "rbi",
        "runs",
        "stolen_bases",
        "batting_avg",
        "on_base_percentage",
        "slugging_percentage",
        "ops",
        "woba",
        "wrc_plus",
        "ops_plus",
        "total_bases",
        "strikeouts_batting",
        "walks_batting",
        "double_plays_grounded_into",
        "gold_gloves",
        "silver_sluggers",
        "mvp_awards",
        "all_star_appearances",
        "world_series_titles",
        "triple_crowns",
        "war",  # Overall WAR (includes pitching WAR for pitchers if relevant)
        "jaws",
        "def_runs_saved",
        # Pitching-specific stats (0 for most hitters)
        "era",
        "pitcher_wins",
        "pitcher_strikeouts",
        "pitcher_saves",
        "pitcher_whip",
        "cy_young_awards",
        "perfect_games",
        "no_hitters",
        # Postseason / Hall
        "career_postseason_war",
        "hall_of_fame"   # 1 if inducted, 0 if not
    ]

    # Each dict represents one player's career data (approx).
    # Mix of hitters & pitchers, with 40 stats per player.
    players_data = [
        {
            "player_name": "Babe Ruth",
            "position": "RF/SP",
            "seasons_played": 22,
            "games_played": 2503,
            "plate_appearances": 10622,
            "hits": 2873,
            "home_runs": 714,
            "rbi": 2214,
            "runs": 2174,
            "stolen_bases": 123,
            "batting_avg": 0.342,
            "on_base_percentage": 0.474,
            "slugging_percentage": 0.690,
            "ops": 1.164,
            "woba": 0.513,
            "wrc_plus": 197,
            "ops_plus": 206,
            "total_bases": 5793,
            "strikeouts_batting": 1330,
            "walks_batting": 2062,
            "double_plays_grounded_into": 90,
            "gold_gloves": 0,
            "silver_sluggers": 0,  # didn't exist in his era
            "mvp_awards": 1,       # official MVP only awarded after 1931
            "all_star_appearances": 2, # The All-Star game started in 1933, near end of his career
            "world_series_titles": 7,
            "triple_crowns": 1,  # 1916 as pitcher is arguable, but let's approximate for demonstration
            "war": 183.1,
            "jaws": 179.0,
            "def_runs_saved": 0,   # Stats not well tracked in his era
            "era": 2.28,           # As a pitcher (approx)
            "pitcher_wins": 94,
            "pitcher_strikeouts": 488,
            "pitcher_saves": 0,
            "pitcher_whip": 1.16,
            "cy_young_awards": 0,  # didn't exist
            "perfect_games": 0,
            "no_hitters": 0,
            "career_postseason_war": 3.6, # approximate
            "hall_of_fame": 1
        },
        {
            "player_name": "Willie Mays",
            "position": "CF",
            "seasons_played": 22,
            "games_played": 2992,
            "plate_appearances": 12496,
            "hits": 3283,
            "home_runs": 660,
            "rbi": 1903,
            "runs": 2062,
            "stolen_bases": 338,
            "batting_avg": 0.302,
            "on_base_percentage": 0.384,
            "slugging_percentage": 0.557,
            "ops": 0.941,
            "woba": 0.415,
            "wrc_plus": 154,
            "ops_plus": 156,
            "total_bases": 6066,
            "strikeouts_batting": 1526,
            "walks_batting": 1464,
            "double_plays_grounded_into": 240,
            "gold_gloves": 12,
            "silver_sluggers": 0,   # didn't exist until 1980
            "mvp_awards": 2,
            "all_star_appearances": 24,
            "world_series_titles": 1,
            "triple_crowns": 0,
            "war": 156.2,
            "jaws": 149.8,
            "def_runs_saved": 0,    # advanced metrics partial
            "era": 0,  # Mays was not a pitcher
            "pitcher_wins": 0,
            "pitcher_strikeouts": 0,
            "pitcher_saves": 0,
            "pitcher_whip": 0,
            "cy_young_awards": 0,
            "perfect_games": 0,
            "no_hitters": 0,
            "career_postseason_war": 1.5,
            "hall_of_fame": 1
        },
        {
            "player_name": "Barry Bonds",
            "position": "LF",
            "seasons_played": 22,
            "games_played": 2986,
            "plate_appearances": 12606,
            "hits": 2935,
            "home_runs": 762,
            "rbi": 1996,
            "runs": 2227,
            "stolen_bases": 514,
            "batting_avg": 0.298,
            "on_base_percentage": 0.444,
            "slugging_percentage": 0.607,
            "ops": 1.051,
            "woba": 0.435,
            "wrc_plus": 173,
            "ops_plus": 182,
            "total_bases": 5856,
            "strikeouts_batting": 1539,
            "walks_batting": 2558,  # all-time record
            "double_plays_grounded_into": 168,
            "gold_gloves": 8,
            "silver_sluggers": 12,
            "mvp_awards": 7,
            "all_star_appearances": 14,
            "world_series_titles": 0,
            "triple_crowns": 0,
            "war": 162.8,
            "jaws": 157.7,
            "def_runs_saved": 0,
            "era": 0,
            "pitcher_wins": 0,
            "pitcher_strikeouts": 0,
            "pitcher_saves": 0,
            "pitcher_whip": 0,
            "cy_young_awards": 0,
            "perfect_games": 0,
            "no_hitters": 0,
            "career_postseason_war": 3.0,
            "hall_of_fame": 0  # Not inducted (PED controversies)
        },
        {
            "player_name": "Hank Aaron",
            "position": "RF",
            "seasons_played": 23,
            "games_played": 3298,
            "plate_appearances": 13941,
            "hits": 3771,
            "home_runs": 755,
            "rbi": 2297,
            "runs": 2174,
            "stolen_bases": 240,
            "batting_avg": 0.305,
            "on_base_percentage": 0.374,
            "slugging_percentage": 0.555,
            "ops": 0.928,
            "woba": 0.405,
            "wrc_plus": 153,
            "ops_plus": 155,
            "total_bases": 6856,
            "strikeouts_batting": 1383,
            "walks_batting": 1402,
            "double_plays_grounded_into": 328,
            "gold_gloves": 3,
            "silver_sluggers": 0,
            "mvp_awards": 1,
            "all_star_appearances": 25,
            "world_series_titles": 1,
            "triple_crowns": 0,
            "war": 143.0,
            "jaws": 136.4,
            "def_runs_saved": 0,
            "era": 0,
            "pitcher_wins": 0,
            "pitcher_strikeouts": 0,
            "pitcher_saves": 0,
            "pitcher_whip": 0,
            "cy_young_awards": 0,
            "perfect_games": 0,
            "no_hitters": 0,
            "career_postseason_war": 2.5,
            "hall_of_fame": 1
        },
        {
            "player_name": "Ted Williams",
            "position": "LF",
            "seasons_played": 19,
            "games_played": 2292,
            "plate_appearances": 9788,
            "hits": 2654,
            "home_runs": 521,
            "rbi": 1839,
            "runs": 1798,
            "stolen_bases": 24,
            "batting_avg": 0.344,
            "on_base_percentage": 0.482,
            "slugging_percentage": 0.634,
            "ops": 1.116,
            "woba": 0.488,
            "wrc_plus": 188,
            "ops_plus": 190,
            "total_bases": 4884,
            "strikeouts_batting": 709,
            "walks_batting": 2021,
            "double_plays_grounded_into": 119,
            "gold_gloves": 0,   # didn't exist in his prime
            "silver_sluggers": 0,  # started 1980
            "mvp_awards": 2,
            "all_star_appearances": 19,
            "world_series_titles": 0,
            "triple_crowns": 2,
            "war": 122.0,
            "jaws": 120.1,
            "def_runs_saved": 0,
            "era": 0,
            "pitcher_wins": 0,
            "pitcher_strikeouts": 0,
            "pitcher_saves": 0,
            "pitcher_whip": 0,
            "cy_young_awards": 0,
            "perfect_games": 0,
            "no_hitters": 0,
            "career_postseason_war": 0.2,
            "hall_of_fame": 1
        },
        {
            "player_name": "Ty Cobb",
            "position": "CF",
            "seasons_played": 24,
            "games_played": 3035,
            "plate_appearances": 13099,
            "hits": 4189,
            "home_runs": 117,
            "rbi": 1938,
            "runs": 2246,
            "stolen_bases": 897,
            "batting_avg": 0.366,
            "on_base_percentage": 0.433,
            "slugging_percentage": 0.512,
            "ops": 0.945,
            "woba": 0.436,
            "wrc_plus": 170,
            "ops_plus": 168,
            "total_bases": 5854,
            "strikeouts_batting": 357,
            "walks_batting": 1249,
            "double_plays_grounded_into": 100, 
            "gold_gloves": 0,
            "silver_sluggers": 0,
            "mvp_awards": 1,
            "all_star_appearances": 0,  # started 1933, he retired 1928
            "world_series_titles": 0,
            "triple_crowns": 1,
            "war": 151.5,
            "jaws": 145.5,
            "def_runs_saved": 0,
            "era": 0,
            "pitcher_wins": 0,
            "pitcher_strikeouts": 0,
            "pitcher_saves": 0,
            "pitcher_whip": 0,
            "cy_young_awards": 0,
            "perfect_games": 0,
            "no_hitters": 0,
            "career_postseason_war": 0.1,
            "hall_of_fame": 1
        },
        {
            "player_name": "Stan Musial",
            "position": "1B/OF",
            "seasons_played": 22,
            "games_played": 3026,
            "plate_appearances": 12717,
            "hits": 3630,
            "home_runs": 475,
            "rbi": 1951,
            "runs": 1949,
            "stolen_bases": 78,
            "batting_avg": 0.331,
            "on_base_percentage": 0.417,
            "slugging_percentage": 0.559,
            "ops": 0.976,
            "woba": 0.435,
            "wrc_plus": 158,
            "ops_plus": 159,
            "total_bases": 6134,
            "strikeouts_batting": 696,
            "walks_batting": 1599,
            "double_plays_grounded_into": 186,
            "gold_gloves": 0, 
            "silver_sluggers": 0,
            "mvp_awards": 3,
            "all_star_appearances": 24,
            "world_series_titles": 3,
            "triple_crowns": 0,
            "war": 128.7,
            "jaws": 125.3,
            "def_runs_saved": 0,
            "era": 0,
            "pitcher_wins": 0,
            "pitcher_strikeouts": 0,
            "pitcher_saves": 0,
            "pitcher_whip": 0,
            "cy_young_awards": 0,
            "perfect_games": 0,
            "no_hitters": 0,
            "career_postseason_war": 1.2,
            "hall_of_fame": 1
        },
        {
            "player_name": "Mickey Mantle",
            "position": "CF",
            "seasons_played": 18,
            "games_played": 2401,
            "plate_appearances": 9909,
            "hits": 2415,
            "home_runs": 536,
            "rbi": 1509,
            "runs": 1677,
            "stolen_bases": 153,
            "batting_avg": 0.298,
            "on_base_percentage": 0.421,
            "slugging_percentage": 0.557,
            "ops": 0.977,
            "woba": 0.431,
            "wrc_plus": 170,
            "ops_plus": 172,
            "total_bases": 4511,
            "strikeouts_batting": 1710,
            "walks_batting": 1733,
            "double_plays_grounded_into": 113,
            "gold_gloves": 1,
            "silver_sluggers": 0,
            "mvp_awards": 3,
            "all_star_appearances": 20,
            "world_series_titles": 7,
            "triple_crowns": 1,
            "war": 110.2,
            "jaws": 104.2,
            "def_runs_saved": 0,
            "era": 0,
            "pitcher_wins": 0,
            "pitcher_strikeouts": 0,
            "pitcher_saves": 0,
            "pitcher_whip": 0,
            "cy_young_awards": 0,
            "perfect_games": 0,
            "no_hitters": 0,
            "career_postseason_war": 2.9,
            "hall_of_fame": 1
        },
        {
            "player_name": "Lou Gehrig",
            "position": "1B",
            "seasons_played": 17,
            "games_played": 2164,
            "plate_appearances": 9660,
            "hits": 2721,
            "home_runs": 493,
            "rbi": 1995,
            "runs": 1888,
            "stolen_bases": 102,
            "batting_avg": 0.340,
            "on_base_percentage": 0.447,
            "slugging_percentage": 0.632,
            "ops": 1.080,
            "woba": 0.464,
            "wrc_plus": 173,
            "ops_plus": 179,
            "total_bases": 5060,
            "strikeouts_batting": 790,
            "walks_batting": 1508,
            "double_plays_grounded_into": 105,
            "gold_gloves": 0,
            "silver_sluggers": 0,
            "mvp_awards": 2,
            "all_star_appearances": 7,   # All-Star started in 1933
            "world_series_titles": 6,
            "triple_crowns": 1,
            "war": 114.1,
            "jaws": 112.0,
            "def_runs_saved": 0,
            "era": 0,
            "pitcher_wins": 0,
            "pitcher_strikeouts": 0,
            "pitcher_saves": 0,
            "pitcher_whip": 0,
            "cy_young_awards": 0,
            "perfect_games": 0,
            "no_hitters": 0,
            "career_postseason_war": 2.4,
            "hall_of_fame": 1
        },
        {
            "player_name": "Walter Johnson",
            "position": "SP",
            "seasons_played": 21,
            "games_played": 802,
            "plate_appearances": 0,  # as a pitcher might have some, but we'll skip hitting details or set to 0
            "hits": 0,
            "home_runs": 0,
            "rbi": 0,
            "runs": 0,
            "stolen_bases": 0,
            "batting_avg": 0,
            "on_base_percentage": 0,
            "slugging_percentage": 0,
            "ops": 0,
            "woba": 0,
            "wrc_plus": 0,
            "ops_plus": 0,
            "total_bases": 0,
            "strikeouts_batting": 0,
            "walks_batting": 0,
            "double_plays_grounded_into": 0,
            "gold_gloves": 0,
            "silver_sluggers": 0,
            "mvp_awards": 2,  # did have early version of MVP
            "all_star_appearances": 0,  # started 1933, he retired 1927
            "world_series_titles": 1,
            "triple_crowns": 3,  # pitching triple crowns
            "war": 164.8,
            "jaws": 153.0,
            "def_runs_saved": 0,
            "era": 2.17,
            "pitcher_wins": 417,
            "pitcher_strikeouts": 3509,
            "pitcher_saves": 34,
            "pitcher_whip": 1.06,
            "cy_young_awards": 0,  # didn't exist
            "perfect_games": 0,
            "no_hitters": 1,  # credited with 1 (some historical debate)
            "career_postseason_war": 1.0,
            "hall_of_fame": 1
        },
        {
            "player_name": "Cy Young",
            "position": "SP",
            "seasons_played": 22,
            "games_played": 906,
            "plate_appearances": 0,
            "hits": 0,
            "home_runs": 0,
            "rbi": 0,
            "runs": 0,
            "stolen_bases": 0,
            "batting_avg": 0,
            "on_base_percentage": 0,
            "slugging_percentage": 0,
            "ops": 0,
            "woba": 0,
            "wrc_plus": 0,
            "ops_plus": 0,
            "total_bases": 0,
            "strikeouts_batting": 0,
            "walks_batting": 0,
            "double_plays_grounded_into": 0,
            "gold_gloves": 0,
            "silver_sluggers": 0,
            "mvp_awards": 0,
            "all_star_appearances": 0,  
            "world_series_titles": 1,  # near end of career 1903
            "triple_crowns": 1,
            "war": 165.7,
            "jaws": 153.8,
            "def_runs_saved": 0,
            "era": 2.63,
            "pitcher_wins": 511,
            "pitcher_strikeouts": 2803,
            "pitcher_saves": 17,
            "pitcher_whip": 1.13,
            "cy_young_awards": 0, # didn't exist
            "perfect_games": 1,   # in 1904
            "no_hitters": 3,
            "career_postseason_war": 0.0, # minimal postseason data
            "hall_of_fame": 1
        },
        {
            "player_name": "Roger Clemens",
            "position": "SP",
            "seasons_played": 24,
            "games_played": 709,
            "plate_appearances": 0,
            "hits": 0,
            "home_runs": 0,
            "rbi": 0,
            "runs": 0,
            "stolen_bases": 0,
            "batting_avg": 0,
            "on_base_percentage": 0,
            "slugging_percentage": 0,
            "ops": 0,
            "woba": 0,
            "wrc_plus": 0,
            "ops_plus": 0,
            "total_bases": 0,
            "strikeouts_batting": 0,
            "walks_batting": 0,
            "double_plays_grounded_into": 0,
            "gold_gloves": 0,
            "silver_sluggers": 0,
            "mvp_awards": 1, 
            "all_star_appearances": 11,
            "world_series_titles": 2,
            "triple_crowns": 2,  # pitching triple crowns
            "war": 139.2,
            "jaws": 102.7,
            "def_runs_saved": 0,
            "era": 3.12,
            "pitcher_wins": 354,
            "pitcher_strikeouts": 4672,
            "pitcher_saves": 0,
            "pitcher_whip": 1.17,
            "cy_young_awards": 7,
            "perfect_games": 0,
            "no_hitters": 0,
            "career_postseason_war": 2.2,
            "hall_of_fame": 0  # not inducted (PED controversies)
        },
        {
            "player_name": "Randy Johnson",
            "position": "SP",
            "seasons_played": 22,
            "games_played": 618,
            "plate_appearances": 0,
            "hits": 0,
            "home_runs": 0,
            "rbi": 0,
            "runs": 0,
            "stolen_bases": 0,
            "batting_avg": 0,
            "on_base_percentage": 0,
            "slugging_percentage": 0,
            "ops": 0,
            "woba": 0,
            "wrc_plus": 0,
            "ops_plus": 0,
            "total_bases": 0,
            "strikeouts_batting": 0,
            "walks_batting": 0,
            "double_plays_grounded_into": 0,
            "gold_gloves": 0,
            "silver_sluggers": 0,
            "mvp_awards": 0,
            "all_star_appearances": 10,
            "world_series_titles": 1,
            "triple_crowns": 1,
            "war": 104.3,
            "jaws": 81.5,
            "def_runs_saved": 0,
            "era": 3.29,
            "pitcher_wins": 303,
            "pitcher_strikeouts": 4875,
            "pitcher_saves": 2,
            "pitcher_whip": 1.17,
            "cy_young_awards": 5,
            "perfect_games": 1,
            "no_hitters": 1,
            "career_postseason_war": 1.8,
            "hall_of_fame": 1
        },
        {
            "player_name": "Greg Maddux",
            "position": "SP",
            "seasons_played": 23,
            "games_played": 744,
            "plate_appearances": 0,
            "hits": 0,
            "home_runs": 0,
            "rbi": 0,
            "runs": 0,
            "stolen_bases": 0,
            "batting_avg": 0,
            "on_base_percentage": 0,
            "slugging_percentage": 0,
            "ops": 0,
            "woba": 0,
            "wrc_plus": 0,
            "ops_plus": 0,
            "total_bases": 0,
            "strikeouts_batting": 0,
            "walks_batting": 0,
            "double_plays_grounded_into": 0,
            "gold_gloves": 18,  # pitchers can win GGs
            "silver_sluggers": 0,
            "mvp_awards": 0,
            "all_star_appearances": 8,
            "world_series_titles": 1,
            "triple_crowns": 0,
            "war": 106.6,
            "jaws": 81.1,
            "def_runs_saved": 0,
            "era": 3.16,
            "pitcher_wins": 355,
            "pitcher_strikeouts": 3371,
            "pitcher_saves": 0,
            "pitcher_whip": 1.14,
            "cy_young_awards": 4,
            "perfect_games": 0,
            "no_hitters": 0,
            "career_postseason_war": 2.4,
            "hall_of_fame": 1
        },
        {
            "player_name": "Pedro Martinez",
            "position": "SP",
            "seasons_played": 18,
            "games_played": 476,
            "plate_appearances": 0,
            "hits": 0,
            "home_runs": 0,
            "rbi": 0,
            "runs": 0,
            "stolen_bases": 0,
            "batting_avg": 0,
            "on_base_percentage": 0,
            "slugging_percentage": 0,
            "ops": 0,
            "woba": 0,
            "wrc_plus": 0,
            "ops_plus": 0,
            "total_bases": 0,
            "strikeouts_batting": 0,
            "walks_batting": 0,
            "double_plays_grounded_into": 0,
            "gold_gloves": 0,
            "silver_sluggers": 0,
            "mvp_awards": 0,
            "all_star_appearances": 8,
            "world_series_titles": 1,
            "triple_crowns": 1,
            "war": 86.1,
            "jaws": 66.9,
            "def_runs_saved": 0,
            "era": 2.93,
            "pitcher_wins": 219,
            "pitcher_strikeouts": 3154,
            "pitcher_saves": 3,
            "pitcher_whip": 1.05,
            "cy_young_awards": 3,
            "perfect_games": 0,
            "no_hitters": 0,
            "career_postseason_war": 1.5,
            "hall_of_fame": 1
        },
        {
            "player_name": "Christy Mathewson",
            "position": "SP",
            "seasons_played": 17,
            "games_played": 635,
            "plate_appearances": 0,
            "hits": 0,
            "home_runs": 0,
            "rbi": 0,
            "runs": 0,
            "stolen_bases": 0,
            "batting_avg": 0,
            "on_base_percentage": 0,
            "slugging_percentage": 0,
            "ops": 0,
            "woba": 0,
            "wrc_plus": 0,
            "ops_plus": 0,
            "total_bases": 0,
            "strikeouts_batting": 0,
            "walks_batting": 0,
            "double_plays_grounded_into": 0,
            "gold_gloves": 0,
            "silver_sluggers": 0,
            "mvp_awards": 0,
            "all_star_appearances": 0,  # retired 1916
            "world_series_titles": 1,
            "triple_crowns": 2,
            "war": 106.6,
            "jaws": 97.2,
            "def_runs_saved": 0,
            "era": 2.13,
            "pitcher_wins": 373,
            "pitcher_strikeouts": 2507,
            "pitcher_saves": 30,
            "pitcher_whip": 1.06,
            "cy_young_awards": 0,
            "perfect_games": 0,
            "no_hitters": 2,
            "career_postseason_war": 1.2,
            "hall_of_fame": 1
        },
        {
            "player_name": "Grover Cleveland Alexander",
            "position": "SP",
            "seasons_played": 20,
            "games_played": 696,
            "plate_appearances": 0,
            "hits": 0,
            "home_runs": 0,
            "rbi": 0,
            "runs": 0,
            "stolen_bases": 0,
            "batting_avg": 0,
            "on_base_percentage": 0,
            "slugging_percentage": 0,
            "ops": 0,
            "woba": 0,
            "wrc_plus": 0,
            "ops_plus": 0,
            "total_bases": 0,
            "strikeouts_batting": 0,
            "walks_batting": 0,
            "double_plays_grounded_into": 0,
            "gold_gloves": 0,
            "silver_sluggers": 0,
            "mvp_awards": 0,
            "all_star_appearances": 0,  
            "world_series_titles": 1,
            "triple_crowns": 3,
            "war": 119.0,
            "jaws": 106.8,
            "def_runs_saved": 0,
            "era": 2.56,
            "pitcher_wins": 373,
            "pitcher_strikeouts": 2198,
            "pitcher_saves": 32,
            "pitcher_whip": 1.12,
            "cy_young_awards": 0,
            "perfect_games": 0,
            "no_hitters": 0,
            "career_postseason_war": 1.0,
            "hall_of_fame": 1
        },
        {
            "player_name": "Sandy Koufax",
            "position": "SP",
            "seasons_played": 12,
            "games_played": 397,
            "plate_appearances": 0,
            "hits": 0,
            "home_runs": 0,
            "rbi": 0,
            "runs": 0,
            "stolen_bases": 0,
            "batting_avg": 0,
            "on_base_percentage": 0,
            "slugging_percentage": 0,
            "ops": 0,
            "woba": 0,
            "wrc_plus": 0,
            "ops_plus": 0,
            "total_bases": 0,
            "strikeouts_batting": 0,
            "walks_batting": 0,
            "double_plays_grounded_into": 0,
            "gold_gloves": 0,
            "silver_sluggers": 0,
            "mvp_awards": 1,
            "all_star_appearances": 7,
            "world_series_titles": 4,
            "triple_crowns": 3,
            "war": 53.2,
            "jaws": 57.4,
            "def_runs_saved": 0,
            "era": 2.76,
            "pitcher_wins": 165,
            "pitcher_strikeouts": 2396,
            "pitcher_saves": 2,
            "pitcher_whip": 1.10,
            "cy_young_awards": 3,
            "perfect_games": 1,
            "no_hitters": 4,
            "career_postseason_war": 1.3,
            "hall_of_fame": 1
        },
        {
            "player_name": "Nolan Ryan",
            "position": "SP",
            "seasons_played": 27,
            "games_played": 807,
            "plate_appearances": 0,
            "hits": 0,
            "home_runs": 0,
            "rbi": 0,
            "runs": 0,
            "stolen_bases": 0,
            "batting_avg": 0,
            "on_base_percentage": 0,
            "slugging_percentage": 0,
            "ops": 0,
            "woba": 0,
            "wrc_plus": 0,
            "ops_plus": 0,
            "total_bases": 0,
            "strikeouts_batting": 0,
            "walks_batting": 0,
            "double_plays_grounded_into": 0,
            "gold_gloves": 0,
            "silver_sluggers": 0,
            "mvp_awards": 0,
            "all_star_appearances": 8,
            "world_series_titles": 1,
            "triple_crowns": 0,
            "war": 81.3,
            "jaws": 73.4,
            "def_runs_saved": 0,
            "era": 3.19,
            "pitcher_wins": 324,
            "pitcher_strikeouts": 5714,
            "pitcher_saves": 3,
            "pitcher_whip": 1.25,
            "cy_young_awards": 0,
            "perfect_games": 0,
            "no_hitters": 7,
            "career_postseason_war": 1.0,
            "hall_of_fame": 1
        },
        {
            "player_name": "Derek Jeter",
            "position": "SS",
            "seasons_played": 20,
            "games_played": 2747,
            "plate_appearances": 12602,
            "hits": 3465,
            "home_runs": 260,
            "rbi": 1311,
            "runs": 1923,
            "stolen_bases": 358,
            "batting_avg": 0.310,
            "on_base_percentage": 0.377,
            "slugging_percentage": 0.440,
            "ops": 0.817,
            "woba": 0.359,
            "wrc_plus": 119,
            "ops_plus": 115,
            "total_bases": 4921,
            "strikeouts_batting": 1840,
            "walks_batting": 1082,
            "double_plays_grounded_into": 287,
            "gold_gloves": 5,
            "silver_sluggers": 5,
            "mvp_awards": 0,
            "all_star_appearances": 14,
            "world_series_titles": 5,
            "triple_crowns": 0,
            "war": 71.3,
            "jaws": 57.4,
            "def_runs_saved": -162,  # advanced metrics show negative
            "era": 0,
            "pitcher_wins": 0,
            "pitcher_strikeouts": 0,
            "pitcher_saves": 0,
            "pitcher_whip": 0,
            "cy_young_awards": 0,
            "perfect_games": 0,
            "no_hitters": 0,
            "career_postseason_war": 4.5,
            "hall_of_fame": 1
        },
        {
            "player_name": "Albert Pujols",
            "position": "1B",
            "seasons_played": 22,
            "games_played": 3080,
            "plate_appearances": 13405,
            "hits": 3384,
            "home_runs": 703,
            "rbi": 2218,
            "runs": 1914,
            "stolen_bases": 117,
            "batting_avg": 0.296,
            "on_base_percentage": 0.374,
            "slugging_percentage": 0.544,
            "ops": 0.918,
            "woba": 0.401,
            "wrc_plus": 144,
            "ops_plus": 144,
            "total_bases": 6141,
            "strikeouts_batting": 1404,
            "walks_batting": 1382,
            "double_plays_grounded_into": 426,
            "gold_gloves": 2,
            "silver_sluggers": 6,
            "mvp_awards": 3,
            "all_star_appearances": 11,
            "world_series_titles": 2,
            "triple_crowns": 0,
            "war": 101.6,
            "jaws": 91.1,
            "def_runs_saved": 0,
            "era": 0,
            "pitcher_wins": 0,
            "pitcher_strikeouts": 0,
            "pitcher_saves": 0,
            "pitcher_whip": 0,
            "cy_young_awards": 0,
            "perfect_games": 0,
            "no_hitters": 0,
            "career_postseason_war": 2.2,
            "hall_of_fame": 0  # Not yet eligible, but certain to be 1 eventually
        },
        {
            "player_name": "Mike Trout",
            "position": "CF",
            "seasons_played": 13,
            "games_played": 1473,
            "plate_appearances": 6517,
            "hits": 1543,
            "home_runs": 368,
            "rbi": 944,
            "runs": 1062,
            "stolen_bases": 206,
            "batting_avg": 0.300,
            "on_base_percentage": 0.414,
            "slugging_percentage": 0.585,
            "ops": 0.999,
            "woba": 0.420,
            "wrc_plus": 170,
            "ops_plus": 176,
            "total_bases": 3015,
            "strikeouts_batting": 1313,
            "walks_batting": 942,
            "double_plays_grounded_into": 100,
            "gold_gloves": 0,
            "silver_sluggers": 9,
            "mvp_awards": 3,
            "all_star_appearances": 10,
            "world_series_titles": 0,
            "triple_crowns": 0,
            "war": 82.4, # through ~2023
            "jaws": 68.0,
            "def_runs_saved": 0,
            "era": 0,
            "pitcher_wins": 0,
            "pitcher_strikeouts": 0,
            "pitcher_saves": 0,
            "pitcher_whip": 0,
            "cy_young_awards": 0,
            "perfect_games": 0,
            "no_hitters": 0,
            "career_postseason_war": 0.0,
            "hall_of_fame": 0  # active
        },
        {
            "player_name": "Jackie Robinson",
            "position": "2B",
            "seasons_played": 10,
            "games_played": 1382,
            "plate_appearances": 5804,
            "hits": 1563,
            "home_runs": 141,
            "rbi": 761,
            "runs": 947,
            "stolen_bases": 200,
            "batting_avg": 0.313,
            "on_base_percentage": 0.410,
            "slugging_percentage": 0.477,
            "ops": 0.887,
            "woba": 0.401,
            "wrc_plus": 132,
            "ops_plus": 132,
            "total_bases": 2022,
            "strikeouts_batting": 291,
            "walks_batting": 740,
            "double_plays_grounded_into": 73,
            "gold_gloves": 0,
            "silver_sluggers": 0,
            "mvp_awards": 1,
            "all_star_appearances": 6,
            "world_series_titles": 1,
            "triple_crowns": 0,
            "war": 61.7,
            "jaws": 57.2,
            "def_runs_saved": 0,
            "era": 0,
            "pitcher_wins": 0,
            "pitcher_strikeouts": 0,
            "pitcher_saves": 0,
            "pitcher_whip": 0,
            "cy_young_awards": 0,
            "perfect_games": 0,
            "no_hitters": 0,
            "career_postseason_war": 0.5,
            "hall_of_fame": 1
        },
        {
            "player_name": "Joe DiMaggio",
            "position": "CF",
            "seasons_played": 13,
            "games_played": 1736,
            "plate_appearances": 7673,
            "hits": 2214,
            "home_runs": 361,
            "rbi": 1537,
            "runs": 1390,
            "stolen_bases": 30,
            "batting_avg": 0.325,
            "on_base_percentage": 0.398,
            "slugging_percentage": 0.579,
            "ops": 0.977,
            "woba": 0.435,
            "wrc_plus": 155,
            "ops_plus": 155,
            "total_bases": 3694,
            "strikeouts_batting": 369,
            "walks_batting": 790,
            "double_plays_grounded_into": 120,
            "gold_gloves": 0,
            "silver_sluggers": 0,
            "mvp_awards": 3,
            "all_star_appearances": 13,
            "world_series_titles": 9,
            "triple_crowns": 0,
            "war": 79.2,
            "jaws": 74.0,
            "def_runs_saved": 0,
            "era": 0,
            "pitcher_wins": 0,
            "pitcher_strikeouts": 0,
            "pitcher_saves": 0,
            "pitcher_whip": 0,
            "cy_young_awards": 0,
            "perfect_games": 0,
            "no_hitters": 0,
            "career_postseason_war": 2.3,
            "hall_of_fame": 1
        },
        {
            "player_name": "Ken Griffey Jr.",
            "position": "CF",
            "seasons_played": 22,
            "games_played": 2671,
            "plate_appearances": 11304,
            "hits": 2781,
            "home_runs": 630,
            "rbi": 1836,
            "runs": 1662,
            "stolen_bases": 184,
            "batting_avg": 0.284,
            "on_base_percentage": 0.370,
            "slugging_percentage": 0.538,
            "ops": 0.907,
            "woba": 0.387,
            "wrc_plus": 136,
            "ops_plus": 136,
            "total_bases": 5271,
            "strikeouts_batting": 1779,
            "walks_batting": 1312,
            "double_plays_grounded_into": 183,
            "gold_gloves": 10,
            "silver_sluggers": 7,
            "mvp_awards": 1,
            "all_star_appearances": 13,
            "world_series_titles": 0,
            "triple_crowns": 0,
            "war": 83.8,
            "jaws": 70.6,
            "def_runs_saved": 0,
            "era": 0,
            "pitcher_wins": 0,
            "pitcher_strikeouts": 0,
            "pitcher_saves": 0,
            "pitcher_whip": 0,
            "cy_young_awards": 0,
            "perfect_games": 0,
            "no_hitters": 0,
            "career_postseason_war": 1.2,
            "hall_of_fame": 1
        },
        {
            "player_name": "Honus Wagner",
            "position": "SS",
            "seasons_played": 21,
            "games_played": 2792,
            "plate_appearances": 11748,
            "hits": 3415,
            "home_runs": 101,
            "rbi": 1732,
            "runs": 1769,
            "stolen_bases": 722,
            "batting_avg": 0.328,
            "on_base_percentage": 0.391,
            "slugging_percentage": 0.467,
            "ops": 0.858,
            "woba": 0.400,
            "wrc_plus": 147,
            "ops_plus": 151,
            "total_bases": 4261,
            "strikeouts_batting": 327,
            "walks_batting": 963,
            "double_plays_grounded_into": 0, # not tracked
            "gold_gloves": 0,
            "silver_sluggers": 0,
            "mvp_awards": 0,
            "all_star_appearances": 0, # pre-1933
            "world_series_titles": 1,
            "triple_crowns": 0,
            "war": 130.8,
            "jaws": 113.0,
            "def_runs_saved": 0,
            "era": 0,
            "pitcher_wins": 0,
            "pitcher_strikeouts": 0,
            "pitcher_saves": 0,
            "pitcher_whip": 0,
            "cy_young_awards": 0,
            "perfect_games": 0,
            "no_hitters": 0,
            "career_postseason_war": 0.7,
            "hall_of_fame": 1
        },
        {
            "player_name": "Tom Seaver",
            "position": "SP",
            "seasons_played": 20,
            "games_played": 656,
            "plate_appearances": 0,
            "hits": 0,
            "home_runs": 0,
            "rbi": 0,
            "runs": 0,
            "stolen_bases": 0,
            "batting_avg": 0,
            "on_base_percentage": 0,
            "slugging_percentage": 0,
            "ops": 0,
            "woba": 0,
            "wrc_plus": 0,
            "ops_plus": 0,
            "total_bases": 0,
            "strikeouts_batting": 0,
            "walks_batting": 0,
            "double_plays_grounded_into": 0,
            "gold_gloves": 0,
            "silver_sluggers": 0,
            "mvp_awards": 0,
            "all_star_appearances": 12,
            "world_series_titles": 1,
            "triple_crowns": 0,
            "war": 109.9,
            "jaws": 88.9,
            "def_runs_saved": 0,
            "era": 2.86,
            "pitcher_wins": 311,
            "pitcher_strikeouts": 3640,
            "pitcher_saves": 1,
            "pitcher_whip": 1.12,
            "cy_young_awards": 3,
            "perfect_games": 0,
            "no_hitters": 1,
            "career_postseason_war": 2.0,
            "hall_of_fame": 1
        },
        {
            "player_name": "Roberto Clemente",
            "position": "RF",
            "seasons_played": 18,
            "games_played": 2433,
            "plate_appearances": 9454,
            "hits": 3000,
            "home_runs": 240,
            "rbi": 1305,
            "runs": 1416,
            "stolen_bases": 83,
            "batting_avg": 0.317,
            "on_base_percentage": 0.359,
            "slugging_percentage": 0.475,
            "ops": 0.834,
            "woba": 0.366,
            "wrc_plus": 129,
            "ops_plus": 130,
            "total_bases": 4543,
            "strikeouts_batting": 1230,
            "walks_batting": 621,
            "double_plays_grounded_into": 200,
            "gold_gloves": 12,
            "silver_sluggers": 0,
            "mvp_awards": 1,
            "all_star_appearances": 15,
            "world_series_titles": 2,
            "triple_crowns": 0,
            "war": 94.8,
            "jaws": 80.6,
            "def_runs_saved": 0,
            "era": 0,
            "pitcher_wins": 0,
            "pitcher_strikeouts": 0,
            "pitcher_saves": 0,
            "pitcher_whip": 0,
            "cy_young_awards": 0,
            "perfect_games": 0,
            "no_hitters": 0,
            "career_postseason_war": 1.2,
            "hall_of_fame": 1
        },
        {
            "player_name": "Frank Robinson",
            "position": "OF/1B",
            "seasons_played": 21,
            "games_played": 2808,
            "plate_appearances": 11742,
            "hits": 2943,
            "home_runs": 586,
            "rbi": 1812,
            "runs": 1829,
            "stolen_bases": 204,
            "batting_avg": 0.294,
            "on_base_percentage": 0.389,
            "slugging_percentage": 0.537,
            "ops": 0.926,
            "woba": 0.406,
            "wrc_plus": 154,
            "ops_plus": 154,
            "total_bases": 5373,
            "strikeouts_batting": 1532,
            "walks_batting": 1420,
            "double_plays_grounded_into": 218,
            "gold_gloves": 1,
            "silver_sluggers": 0,
            "mvp_awards": 2,
            "all_star_appearances": 14,
            "world_series_titles": 2,
            "triple_crowns": 1,
            "war": 107.2,
            "jaws": 93.4,
            "def_runs_saved": 0,
            "era": 0,
            "pitcher_wins": 0,
            "pitcher_strikeouts": 0,
            "pitcher_saves": 0,
            "pitcher_whip": 0,
            "cy_young_awards": 0,
            "perfect_games": 0,
            "no_hitters": 0,
            "career_postseason_war": 1.3,
            "hall_of_fame": 1
        },
        {
            "player_name": "Johnny Bench",
            "position": "C",
            "seasons_played": 17,
            "games_played": 2158,
            "plate_appearances": 8674,
            "hits": 2048,
            "home_runs": 389,
            "rbi": 1376,
            "runs": 1091,
            "stolen_bases": 68,
            "batting_avg": 0.267,
            "on_base_percentage": 0.342,
            "slugging_percentage": 0.476,
            "ops": 0.818,
            "woba": 0.357,
            "wrc_plus": 126,
            "ops_plus": 126,
            "total_bases": 3604,
            "strikeouts_batting": 1278,
            "walks_batting": 891,
            "double_plays_grounded_into": 177,
            "gold_gloves": 10,
            "silver_sluggers": 0,
            "mvp_awards": 2,
            "all_star_appearances": 14,
            "world_series_titles": 2,
            "triple_crowns": 0,
            "war": 75.2,
            "jaws": 61.2,
            "def_runs_saved": 0,
            "era": 0,
            "pitcher_wins": 0,
            "pitcher_strikeouts": 0,
            "pitcher_saves": 0,
            "pitcher_whip": 0,
            "cy_young_awards": 0,
            "perfect_games": 0,
            "no_hitters": 0,
            "career_postseason_war": 2.0,
            "hall_of_fame": 1
        }
    ]

    # Write out to CSV
    with open(filename, mode="w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=headers)
        writer.writeheader()
        for pdata in players_data:
            # Ensure missing fields are set to 0 or safe defaults
            for h in headers:
                if h not in pdata:
                    pdata[h] = 0
            writer.writerow(pdata)


if __name__ == "__main__":
    create_mlb_dataset()
    print("mlb_dataset.csv has been created with 30 players and 41 columns of stats each.")
