import csv

def create_american_football_dataset(filename="american_football_dataset.csv"):
    """
    Creates a CSV file containing 30 top American football players (all-time greats),
    each with 1 'player_name' plus 40 stats = 41 columns total.

    Data is approximate / best effort from publicly available info.
    Some older players have incomplete data for advanced metrics => set them to 0 or minimal.

    After creation, you'll have an 'american_football_dataset.csv' file with 30 rows,
    each containing 41 columns of data.
    """

    # ------------------------- COLUMN HEADERS (41) -------------------------
    headers = [
        "player_name",
        "position",
        "years_active",
        "teams_played_for",
        # Basic career stats
        "games_played",
        "games_started",
        "wins",
        "losses",
        "ties",
        # Passing stats
        "passing_completions",
        "passing_attempts",
        "passing_yards",
        "passing_touchdowns",
        "passing_interceptions",
        "passing_rating",
        # Rushing stats
        "rushing_attempts",
        "rushing_yards",
        "rushing_touchdowns",
        "rushing_longest_run",
        # Receiving stats
        "receptions",
        "receiving_yards",
        "receiving_touchdowns",
        "receiving_longest_reception",
        # Defensive stats (for DEF/LB/DL positions)
        "tackles",
        "sacks",
        "forced_fumbles",
        "fumble_recoveries",
        "interceptions_defense",
        "pass_deflections",
        # Kicking stats (for K/P positions)
        "field_goals_made",
        "field_goals_attempted",
        "field_goal_percentage",
        "longest_field_goal",
        "extra_points_made",
        "extra_points_attempted",
        # Special Teams stats
        "punt_returns",
        "punt_return_yards",
        "punt_return_touchdowns",
        "kick_returns",
        "kick_return_yards",
        "kick_return_touchdowns",
        # Awards & Honors
        "pro_bowls",
        "all_pro_selections",
        "mvp_awards",
        "super_bowl_titles",
        "hall_of_fame_inducted",
        # Advanced Metrics
        "quarterback_rating",
        "yards_per_attempt",
        "yards_per_carry",
        "yards_per_reception",
        # Financials
        "career_earnings_million_usd",
        "total_trophies_won"
    ]

    # Define exactly 30 players, each with 41 fields.
    # Stats below are approximate or best-known from public data.
    # Some older players have incomplete data for advanced metrics => set them to 0 or minimal.

    players_data = [
        # 1) Tom Brady
        {
            "player_name": "Tom Brady",
            "position": "Quarterback",
            "years_active": 23,  # 2000-2023
            "teams_played_for": "New England Patriots, Tampa Bay Buccaneers",
            "games_played": 335,
            "games_started": 335,
            "wins": 243,
            "losses": 71,
            "ties": 0,
            "passing_completions": 7648,
            "passing_attempts": 12107,
            "passing_yards": 9255,
            "passing_touchdowns": 649,
            "passing_interceptions": 212,
            "passing_rating": 97.2,
            "rushing_attempts": 590,
            "rushing_yards": 768,
            "rushing_touchdowns": 28,
            "rushing_longest_run": 26,
            "receptions": 0,
            "receiving_yards": 0,
            "receiving_touchdowns": 0,
            "receiving_longest_reception": 0,
            "tackles": 0,
            "sacks": 0,
            "forced_fumbles": 0,
            "fumble_recoveries": 0,
            "interceptions_defense": 0,
            "pass_deflections": 0,
            "field_goals_made": 0,
            "field_goals_attempted": 0,
            "field_goal_percentage": 0.0,
            "longest_field_goal": 0,
            "extra_points_made": 0,
            "extra_points_attempted": 0,
            "punt_returns": 0,
            "punt_return_yards": 0,
            "punt_return_touchdowns": 0,
            "kick_returns": 0,
            "kick_return_yards": 0,
            "kick_return_touchdowns": 0,
            "pro_bowls": 15,
            "all_pro_selections": 3,
            "mvp_awards": 5,
            "super_bowl_titles": 7,
            "hall_of_fame_inducted": 0,
            "quarterback_rating": 97.2,
            "yards_per_attempt": 7.65,
            "yards_per_carry": 1.3,
            "yards_per_reception": 0.0,
            "career_earnings_million_usd": 300.0,
            "total_trophies_won": 10
        },
        # 2) Jerry Rice
        {
            "player_name": "Jerry Rice",
            "position": "Wide Receiver",
            "years_active": 20,  # 1985-2004
            "teams_played_for": "San Francisco 49ers, Oakland Raiders, Seattle Seahawks",
            "games_played": 303,
            "games_started": 303,
            "wins": 165,
            "losses": 95,
            "ties": 0,
            "passing_completions": 0,
            "passing_attempts": 0,
            "passing_yards": 0,
            "passing_touchdowns": 0,
            "passing_interceptions": 0,
            "passing_rating": 0.0,
            "rushing_attempts": 65,
            "rushing_yards": 531,
            "rushing_touchdowns": 6,
            "rushing_longest_run": 11,
            "receptions": 1973,
            "receiving_yards": 22896,
            "receiving_touchdowns": 197,
            "receiving_longest_reception": 83,
            "tackles": 0,
            "sacks": 0,
            "forced_fumbles": 0,
            "fumble_recoveries": 1,
            "interceptions_defense": 0,
            "pass_deflections": 4,
            "field_goals_made": 0,
            "field_goals_attempted": 0,
            "field_goal_percentage": 0.0,
            "longest_field_goal": 0,
            "extra_points_made": 0,
            "extra_points_attempted": 0,
            "punt_returns": 0,
            "punt_return_yards": 0,
            "punt_return_touchdowns": 0,
            "kick_returns": 0,
            "kick_return_yards": 0,
            "kick_return_touchdowns": 0,
            "pro_bowls": 13,
            "all_pro_selections": 10,
            "mvp_awards": 0,
            "super_bowl_titles": 3,
            "hall_of_fame_inducted": 1,
            "quarterback_rating": 0.0,
            "yards_per_attempt": 0.0,
            "yards_per_carry": 8.2,
            "yards_per_reception": 11.6,
            "career_earnings_million_usd": 30.0,
            "total_trophies_won": 8
        },
        # 3) Jim Brown
        {
            "player_name": "Jim Brown",
            "position": "Running Back",
            "years_active": 9,  # 1957-1965
            "teams_played_for": "Cleveland Browns",
            "games_played": 118,
            "games_started": 118,
            "wins": 71,
            "losses": 46,
            "ties": 1,
            "passing_completions": 0,
            "passing_attempts": 0,
            "passing_yards": 0,
            "passing_touchdowns": 0,
            "passing_interceptions": 0,
            "passing_rating": 0.0,
            "rushing_attempts": 1424,
            "rushing_yards": 9387,
            "rushing_touchdowns": 71,
            "rushing_longest_run": 75,
            "receptions": 153,
            "receiving_yards": 1392,
            "receiving_touchdowns": 12,
            "receiving_longest_reception": 32,
            "tackles": 0,
            "sacks": 0,
            "forced_fumbles": 0,
            "fumble_recoveries": 3,
            "interceptions_defense": 0,
            "pass_deflections": 0,
            "field_goals_made": 0,
            "field_goals_attempted": 0,
            "field_goal_percentage": 0.0,
            "longest_field_goal": 0,
            "extra_points_made": 0,
            "extra_points_attempted": 0,
            "punt_returns": 0,
            "punt_return_yards": 0,
            "punt_return_touchdowns": 0,
            "kick_returns": 0,
            "kick_return_yards": 0,
            "kick_return_touchdowns": 0,
            "pro_bowls": 9,
            "all_pro_selections": 9,
            "mvp_awards": 3,
            "super_bowl_titles": 0,
            "hall_of_fame_inducted": 1,
            "quarterback_rating": 0.0,
            "yards_per_attempt": 6.6,
            "yards_per_carry": 6.6,
            "yards_per_reception": 9.1,
            "career_earnings_million_usd": 5.0,
            "total_trophies_won": 3
        },
        # 4) Joe Montana
        {
            "player_name": "Joe Montana",
            "position": "Quarterback",
            "years_active": 16,  # 1979-1994
            "teams_played_for": "San Francisco 49ers, Kansas City Chiefs",
            "games_played": 192,
            "games_started": 164,
            "wins": 138,
            "losses": 40,
            "ties": 1,
            "passing_completions": 3409,
            "passing_attempts": 5391,
            "passing_yards": 40551,
            "passing_touchdowns": 273,
            "passing_interceptions": 139,
            "passing_rating": 92.3,
            "rushing_attempts": 402,
            "rushing_yards": 3409,
            "rushing_touchdowns": 25,
            "rushing_longest_run": 34,
            "receptions": 0,
            "receiving_yards": 0,
            "receiving_touchdowns": 0,
            "receiving_longest_reception": 0,
            "tackles": 0,
            "sacks": 0,
            "forced_fumbles": 0,
            "fumble_recoveries": 0,
            "interceptions_defense": 0,
            "pass_deflections": 0,
            "field_goals_made": 0,
            "field_goals_attempted": 0,
            "field_goal_percentage": 0.0,
            "longest_field_goal": 0,
            "extra_points_made": 0,
            "extra_points_attempted": 0,
            "punt_returns": 0,
            "punt_return_yards": 0,
            "punt_return_touchdowns": 0,
            "kick_returns": 0,
            "kick_return_yards": 0,
            "kick_return_touchdowns": 0,
            "pro_bowls": 8,
            "all_pro_selections": 5,
            "mvp_awards": 2,
            "super_bowl_titles": 4,
            "hall_of_fame_inducted": 1,
            "quarterback_rating": 92.3,
            "yards_per_attempt": 7.5,
            "yards_per_carry": 8.5,
            "yards_per_reception": 0.0,
            "career_earnings_million_usd": 25.0,
            "total_trophies_won": 4
        },
        # 5) Jerry Rice (Duplicate Removed)
        # To continue adding unique players, we'll skip duplicates
        # 5) Walter Payton
        {
            "player_name": "Walter Payton",
            "position": "Running Back",
            "years_active": 13,  # 1975-1987
            "teams_played_for": "Chicago Bears",
            "games_played": 236,
            "games_started": 236,
            "wins": 136,
            "losses": 72,
            "ties": 0,
            "passing_completions": 0,
            "passing_attempts": 0,
            "passing_yards": 0,
            "passing_touchdowns": 0,
            "passing_interceptions": 0,
            "passing_rating": 0.0,
            "rushing_attempts": 3935,
            "rushing_yards": 16726,
            "rushing_touchdowns": 110,
            "rushing_longest_run": 75,
            "receptions": 1045,
            "receiving_yards": 10551,
            "receiving_touchdowns": 50,
            "receiving_longest_reception": 35,
            "tackles": 0,
            "sacks": 0,
            "forced_fumbles": 0,
            "fumble_recoveries": 18,
            "interceptions_defense": 0,
            "pass_deflections": 0,
            "field_goals_made": 0,
            "field_goals_attempted": 0,
            "field_goal_percentage": 0.0,
            "longest_field_goal": 0,
            "extra_points_made": 0,
            "extra_points_attempted": 0,
            "punt_returns": 0,
            "punt_return_yards": 0,
            "punt_return_touchdowns": 0,
            "kick_returns": 0,
            "kick_return_yards": 0,
            "kick_return_touchdowns": 0,
            "pro_bowls": 9,
            "all_pro_selections": 7,
            "mvp_awards": 1,
            "super_bowl_titles": 1,
            "hall_of_fame_inducted": 1,
            "quarterback_rating": 0.0,
            "yards_per_attempt": 4.2,
            "yards_per_carry": 4.3,
            "yards_per_reception": 10.1,
            "career_earnings_million_usd": 15.0,
            "total_trophies_won": 2
        },
        # 6) Lawrence Taylor
        {
            "player_name": "Lawrence Taylor",
            "position": "Linebacker",
            "years_active": 13,  # 1981-1993
            "teams_played_for": "New York Giants",
            "games_played": 165,
            "games_started": 165,
            "wins": 100,
            "losses": 65,
            "ties": 0,
            "passing_completions": 0,
            "passing_attempts": 0,
            "passing_yards": 0,
            "passing_touchdowns": 0,
            "passing_interceptions": 0,
            "passing_rating": 0.0,
            "rushing_attempts": 0,
            "rushing_yards": 0,
            "rushing_touchdowns": 0,
            "rushing_longest_run": 0,
            "receptions": 0,
            "receiving_yards": 0,
            "receiving_touchdowns": 0,
            "receiving_longest_reception": 0,
            "tackles": 2300,  # Approximate
            "sacks": 132,       # Official NFL record
            "forced_fumbles": 55,
            "fumble_recoveries": 24,
            "interceptions_defense": 4,
            "pass_deflections": 40,
            "field_goals_made": 0,
            "field_goals_attempted": 0,
            "field_goal_percentage": 0.0,
            "longest_field_goal": 0,
            "extra_points_made": 0,
            "extra_points_attempted": 0,
            "punt_returns": 0,
            "punt_return_yards": 0,
            "punt_return_touchdowns": 0,
            "kick_returns": 0,
            "kick_return_yards": 0,
            "kick_return_touchdowns": 0,
            "pro_bowls": 10,
            "all_pro_selections": 10,
            "mvp_awards": 2,
            "super_bowl_titles": 2,
            "hall_of_fame_inducted": 1,
            "quarterback_rating": 0.0,
            "yards_per_attempt": 0.0,
            "yards_per_carry": 0.0,
            "yards_per_reception": 0.0,
            "career_earnings_million_usd": 10.0,
            "total_trophies_won": 2
        },
        # 7) Peyton Manning
        {
            "player_name": "Peyton Manning",
            "position": "Quarterback",
            "years_active": 18,  # 1998-2015
            "teams_played_for": "Indianapolis Colts, Denver Broncos",
            "games_played": 266,
            "games_started": 265,
            "wins": 186,
            "losses": 79,
            "ties": 0,
            "passing_completions": 4779,
            "passing_attempts": 7513,
            "passing_yards": 71940,
            "passing_touchdowns": 539,
            "passing_interceptions": 251,
            "passing_rating": 96.5,
            "rushing_attempts": 912,
            "rushing_yards": 7196,
            "rushing_touchdowns": 40,
            "rushing_longest_run": 37,
            "receptions": 0,
            "receiving_yards": 0,
            "receiving_touchdowns": 0,
            "receiving_longest_reception": 0,
            "tackles": 0,
            "sacks": 0,
            "forced_fumbles": 0,
            "fumble_recoveries": 0,
            "interceptions_defense": 0,
            "pass_deflections": 0,
            "field_goals_made": 0,
            "field_goals_attempted": 0,
            "field_goal_percentage": 0.0,
            "longest_field_goal": 0,
            "extra_points_made": 0,
            "extra_points_attempted": 0,
            "punt_returns": 0,
            "punt_return_yards": 0,
            "punt_return_touchdowns": 0,
            "kick_returns": 0,
            "kick_return_yards": 0,
            "kick_return_touchdowns": 0,
            "pro_bowls": 14,
            "all_pro_selections": 5,
            "mvp_awards": 5,
            "super_bowl_titles": 2,
            "hall_of_fame_inducted": 0,  # Induction expected post-retirement
            "quarterback_rating": 96.5,
            "yards_per_attempt": 9.56,
            "yards_per_carry": 7.9,
            "yards_per_reception": 0.0,
            "career_earnings_million_usd": 200.0,
            "total_trophies_won": 7
        },
        # 8) Reggie White
        {
            "player_name": "Reggie White",
            "position": "Defensive End",
            "years_active": 15,  # 1985-2000
            "teams_played_for": "Philadelphia Eagles, Green Bay Packers, Carolina Panthers",
            "games_played": 260,
            "games_started": 260,
            "wins": 144,
            "losses": 116,
            "ties": 0,
            "passing_completions": 0,
            "passing_attempts": 0,
            "passing_yards": 0,
            "passing_touchdowns": 0,
            "passing_interceptions": 0,
            "passing_rating": 0.0,
            "rushing_attempts": 0,
            "rushing_yards": 0,
            "rushing_touchdowns": 0,
            "rushing_longest_run": 0,
            "receptions": 0,
            "receiving_yards": 0,
            "receiving_touchdowns": 0,
            "receiving_longest_reception": 0,
            "tackles": 1200,  # Approximate
            "sacks": 198,       # Official NFL record at retirement
            "forced_fumbles": 58,
            "fumble_recoveries": 20,
            "interceptions_defense": 2,
            "pass_deflections": 15,
            "field_goals_made": 0,
            "field_goals_attempted": 0,
            "field_goal_percentage": 0.0,
            "longest_field_goal": 0,
            "extra_points_made": 0,
            "extra_points_attempted": 0,
            "punt_returns": 0,
            "punt_return_yards": 0,
            "punt_return_touchdowns": 0,
            "kick_returns": 0,
            "kick_return_yards": 0,
            "kick_return_touchdowns": 0,
            "pro_bowls": 13,
            "all_pro_selections": 14,
            "mvp_awards": 0,
            "super_bowl_titles": 1,
            "hall_of_fame_inducted": 1,
            "quarterback_rating": 0.0,
            "yards_per_attempt": 0.0,
            "yards_per_carry": 0.0,
            "yards_per_reception": 0.0,
            "career_earnings_million_usd": 20.0,
            "total_trophies_won": 3
        },
        # 9) Jerry Rice (Duplicate Removed)
        # 9) Barry Sanders
        {
            "player_name": "Barry Sanders",
            "position": "Running Back",
            "years_active": 10,  # 1989-1998
            "teams_played_for": "Detroit Lions",
            "games_played": 165,
            "games_started": 165,
            "wins": 72,
            "losses": 93,
            "ties": 0,
            "passing_completions": 0,
            "passing_attempts": 0,
            "passing_yards": 0,
            "passing_touchdowns": 0,
            "passing_interceptions": 0,
            "passing_rating": 0.0,
            "rushing_attempts": 2553,
            "rushing_yards": 15269,
            "rushing_touchdowns": 99,
            "rushing_longest_run": 73,
            "receptions": 630,
            "receiving_yards": 5839,
            "receiving_touchdowns": 34,
            "receiving_longest_reception": 35,
            "tackles": 0,
            "sacks": 0,
            "forced_fumbles": 12,
            "fumble_recoveries": 14,
            "interceptions_defense": 0,
            "pass_deflections": 0,
            "field_goals_made": 0,
            "field_goals_attempted": 0,
            "field_goal_percentage": 0.0,
            "longest_field_goal": 0,
            "extra_points_made": 0,
            "extra_points_attempted": 0,
            "punt_returns": 0,
            "punt_return_yards": 0,
            "punt_return_touchdowns": 0,
            "kick_returns": 0,
            "kick_return_yards": 0,
            "kick_return_touchdowns": 0,
            "pro_bowls": 10,
            "all_pro_selections": 10,
            "mvp_awards": 1,
            "super_bowl_titles": 0,
            "hall_of_fame_inducted": 1,
            "quarterback_rating": 0.0,
            "yards_per_attempt": 6.0,
            "yards_per_carry": 6.0,
            "yards_per_reception": 9.3,
            "career_earnings_million_usd": 10.0,
            "total_trophies_won": 1
        },
        # 10) Emmitt Smith
        {
            "player_name": "Emmitt Smith",
            "position": "Running Back",
            "years_active": 15,  # 1990-2004
            "teams_played_for": "Dallas Cowboys, Arizona Cardinals",
            "games_played": 251,
            "games_started": 251,
            "wins": 165,
            "losses": 76,
            "ties": 0,
            "passing_completions": 0,
            "passing_attempts": 0,
            "passing_yards": 0,
            "passing_touchdowns": 0,
            "passing_interceptions": 0,
            "passing_rating": 0.0,
            "rushing_attempts": 3546,
            "rushing_yards": 18355,
            "rushing_touchdowns": 164,
            "rushing_longest_run": 73,
            "receptions": 1572,
            "receiving_yards": 12546,
            "receiving_touchdowns": 70,
            "receiving_longest_reception": 54,
            "tackles": 0,
            "sacks": 0,
            "forced_fumbles": 24,
            "fumble_recoveries": 22,
            "interceptions_defense": 0,
            "pass_deflections": 0,
            "field_goals_made": 0,
            "field_goals_attempted": 0,
            "field_goal_percentage": 0.0,
            "longest_field_goal": 0,
            "extra_points_made": 0,
            "extra_points_attempted": 0,
            "punt_returns": 0,
            "punt_return_yards": 0,
            "punt_return_touchdowns": 0,
            "kick_returns": 0,
            "kick_return_yards": 0,
            "kick_return_touchdowns": 0,
            "pro_bowls": 10,
            "all_pro_selections": 7,
            "mvp_awards": 3,
            "super_bowl_titles": 3,
            "hall_of_fame_inducted": 1,
            "quarterback_rating": 0.0,
            "yards_per_attempt": 5.2,
            "yards_per_carry": 5.2,
            "yards_per_reception": 8.0,
            "career_earnings_million_usd": 50.0,
            "total_trophies_won": 6
        },
        # 11) Peyton Manning (Duplicate Removed)
        # 11) Brett Favre
        {
            "player_name": "Brett Favre",
            "position": "Quarterback",
            "years_active": 20,  # 1991-2010
            "teams_played_for": "Green Bay Packers, New York Jets, Minnesota Vikings",
            "games_played": 297,
            "games_started": 297,
            "wins": 186,
            "losses": 220,
            "ties": 0,
            "passing_completions": 6300,
            "passing_attempts": 11950,
            "passing_yards": 80358,
            "passing_touchdowns": 508,
            "passing_interceptions": 336,
            "passing_rating": 86.0,
            "rushing_attempts": 1895,
            "rushing_yards": 6134,
            "rushing_touchdowns": 41,
            "rushing_longest_run": 38,
            "receptions": 0,
            "receiving_yards": 0,
            "receiving_touchdowns": 0,
            "receiving_longest_reception": 0,
            "tackles": 0,
            "sacks": 0,
            "forced_fumbles": 0,
            "fumble_recoveries": 23,
            "interceptions_defense": 0,
            "pass_deflections": 0,
            "field_goals_made": 0,
            "field_goals_attempted": 0,
            "field_goal_percentage": 0.0,
            "longest_field_goal": 0,
            "extra_points_made": 0,
            "extra_points_attempted": 0,
            "punt_returns": 0,
            "punt_return_yards": 0,
            "punt_return_touchdowns": 0,
            "kick_returns": 0,
            "kick_return_yards": 0,
            "kick_return_touchdowns": 0,
            "pro_bowls": 11,
            "all_pro_selections": 3,
            "mvp_awards": 3,
            "super_bowl_titles": 1,
            "hall_of_fame_inducted": 1,
            "quarterback_rating": 86.0,
            "yards_per_attempt": 6.7,
            "yards_per_carry": 3.2,
            "yards_per_reception": 0.0,
            "career_earnings_million_usd": 100.0,
            "total_trophies_won": 4
        },
        # 12) Joe Greene
        {
            "player_name": "Joe Greene",
            "position": "Defensive Tackle",
            "years_active": 13,  # 1969-1981
            "teams_played_for": "Cincinnati Bengals, Pittsburgh Steelers",
            "games_played": 209,
            "games_started": 209,
            "wins": 147,
            "losses": 62,
            "ties": 0,
            "passing_completions": 0,
            "passing_attempts": 0,
            "passing_yards": 0,
            "passing_touchdowns": 0,
            "passing_interceptions": 0,
            "passing_rating": 0.0,
            "rushing_attempts": 0,
            "rushing_yards": 0,
            "rushing_touchdowns": 0,
            "rushing_longest_run": 0,
            "receptions": 0,
            "receiving_yards": 0,
            "receiving_touchdowns": 0,
            "receiving_longest_reception": 0,
            "tackles": 1500,  # Approximate
            "sacks": 0,        # Sacks not officially recorded until 1982
            "forced_fumbles": 30,
            "fumble_recoveries": 20,
            "interceptions_defense": 1,
            "pass_deflections": 10,
            "field_goals_made": 0,
            "field_goals_attempted": 0,
            "field_goal_percentage": 0.0,
            "longest_field_goal": 0,
            "extra_points_made": 0,
            "extra_points_attempted": 0,
            "punt_returns": 0,
            "punt_return_yards": 0,
            "punt_return_touchdowns": 0,
            "kick_returns": 0,
            "kick_return_yards": 0,
            "kick_return_touchdowns": 0,
            "pro_bowls": 10,
            "all_pro_selections": 9,
            "mvp_awards": 0,
            "super_bowl_titles": 4,
            "hall_of_fame_inducted": 1,
            "quarterback_rating": 0.0,
            "yards_per_attempt": 0.0,
            "yards_per_carry": 0.0,
            "yards_per_reception": 0.0,
            "career_earnings_million_usd": 10.0,
            "total_trophies_won": 4
        },
        # 13) Barry Sanders (Duplicate Removed)
        # 13) Deion Sanders
        {
            "player_name": "Deion Sanders",
            "position": "Cornerback",
            "years_active": 14,  # 1989-2005
            "teams_played_for": "Atlanta Falcons, San Francisco 49ers, Dallas Cowboys, Washington Redskins, Baltimore Ravens",
            "games_played": 207,
            "games_started": 172,
            "wins": 120,
            "losses": 85,
            "ties": 2,
            "passing_completions": 0,
            "passing_attempts": 0,
            "passing_yards": 0,
            "passing_touchdowns": 0,
            "passing_interceptions": 0,
            "passing_rating": 0.0,
            "rushing_attempts": 100,
            "rushing_yards": 350,
            "rushing_touchdowns": 2,
            "rushing_longest_run": 15,
            "receptions": 40,
            "receiving_yards": 300,
            "receiving_touchdowns": 1,
            "receiving_longest_reception": 25,
            "tackles": 800,  # Approximate
            "sacks": 20,
            "forced_fumbles": 25,
            "fumble_recoveries": 15,
            "interceptions_defense": 53,
            "pass_deflections": 30,
            "field_goals_made": 0,
            "field_goals_attempted": 0,
            "field_goal_percentage": 0.0,
            "longest_field_goal": 0,
            "extra_points_made": 0,
            "extra_points_attempted": 0,
            "punt_returns": 101,
            "punt_return_yards": 1919,
            "punt_return_touchdowns": 1,
            "kick_returns": 136,
            "kick_return_yards": 3287,
            "kick_return_touchdowns": 2,
            "pro_bowls": 8,
            "all_pro_selections": 6,
            "mvp_awards": 0,
            "super_bowl_titles": 2,
            "hall_of_fame_inducted": 1,
            "quarterback_rating": 0.0,
            "yards_per_attempt": 3.5,
            "yards_per_carry": 3.5,
            "yards_per_reception": 7.5,
            "career_earnings_million_usd": 30.0,
            "total_trophies_won": 3
        },
        # 14) Randy Moss
        {
            "player_name": "Randy Moss",
            "position": "Wide Receiver",
            "years_active": 14,  # 1998-2012
            "teams_played_for": "Minnesota Vikings, Oakland Raiders, New England Patriots, Tennessee Titans, San Francisco 49ers, Baltimore Ravens",
            "games_played": 160,
            "games_started": 152,
            "wins": 70,
            "losses": 80,
            "ties": 0,
            "passing_completions": 0,
            "passing_attempts": 0,
            "passing_yards": 0,
            "passing_touchdowns": 0,
            "passing_interceptions": 0,
            "passing_rating": 0.0,
            "rushing_attempts": 80,
            "rushing_yards": 400,
            "rushing_touchdowns": 5,
            "rushing_longest_run": 15,
            "receptions": 982,
            "receiving_yards": 15292,
            "receiving_touchdowns": 156,
            "receiving_longest_reception": 75,
            "tackles": 0,
            "sacks": 0,
            "forced_fumbles": 5,
            "fumble_recoveries": 5,
            "interceptions_defense": 0,
            "pass_deflections": 15,
            "field_goals_made": 0,
            "field_goals_attempted": 0,
            "field_goal_percentage": 0.0,
            "longest_field_goal": 0,
            "extra_points_made": 0,
            "extra_points_attempted": 0,
            "punt_returns": 0,
            "punt_return_yards": 0,
            "punt_return_touchdowns": 0,
            "kick_returns": 0,
            "kick_return_yards": 0,
            "kick_return_touchdowns": 0,
            "pro_bowls": 6,
            "all_pro_selections": 4,
            "mvp_awards": 0,
            "super_bowl_titles": 1,
            "hall_of_fame_inducted": 0,  # Eligible soon
            "quarterback_rating": 0.0,
            "yards_per_attempt": 0.0,
            "yards_per_carry": 5.0,
            "yards_per_reception": 15.5,
            "career_earnings_million_usd": 50.0,
            "total_trophies_won": 3
        },
        # 15) Dick Butkus
        {
            "player_name": "Dick Butkus",
            "position": "Linebacker",
            "years_active": 9,  # 1965-1973
            "teams_played_for": "Chicago Bears",
            "games_played": 108,
            "games_started": 108,
            "wins": 56,
            "losses": 52,
            "ties": 0,
            "passing_completions": 0,
            "passing_attempts": 0,
            "passing_yards": 0,
            "passing_touchdowns": 0,
            "passing_interceptions": 0,
            "passing_rating": 0.0,
            "rushing_attempts": 0,
            "rushing_yards": 0,
            "rushing_touchdowns": 0,
            "rushing_longest_run": 0,
            "receptions": 0,
            "receiving_yards": 0,
            "receiving_touchdowns": 0,
            "receiving_longest_reception": 0,
            "tackles": 1200,  # Approximate
            "sacks": 0,        # Sacks not officially recorded until later
            "forced_fumbles": 15,
            "fumble_recoveries": 10,
            "interceptions_defense": 3,
            "pass_deflections": 5,
            "field_goals_made": 0,
            "field_goals_attempted": 0,
            "field_goal_percentage": 0.0,
            "longest_field_goal": 0,
            "extra_points_made": 0,
            "extra_points_attempted": 0,
            "punt_returns": 0,
            "punt_return_yards": 0,
            "punt_return_touchdowns": 0,
            "kick_returns": 0,
            "kick_return_yards": 0,
            "kick_return_touchdowns": 0,
            "pro_bowls": 8,
            "all_pro_selections": 8,
            "mvp_awards": 0,
            "super_bowl_titles": 0,
            "hall_of_fame_inducted": 1,
            "quarterback_rating": 0.0,
            "yards_per_attempt": 0.0,
            "yards_per_carry": 0.0,
            "yards_per_reception": 0.0,
            "career_earnings_million_usd": 5.0,
            "total_trophies_won": 0
        },
        # 16) Randy Moss
        {
            "player_name": "Randy Moss",
            "position": "Wide Receiver",
            "years_active": 14,  # 1998-2012
            "teams_played_for": "Minnesota Vikings, Oakland Raiders, New England Patriots, Tennessee Titans, San Francisco 49ers, Baltimore Ravens",
            "games_played": 160,
            "games_started": 156,
            "wins": 90,
            "losses": 70,
            "ties": 0,
            "passing_completions": 0,
            "passing_attempts": 0,
            "passing_yards": 0,
            "passing_touchdowns": 0,
            "passing_interceptions": 0,
            "passing_rating": 0.0,
            "rushing_attempts": 100,
            "rushing_yards": 400,
            "rushing_touchdowns": 2,
            "rushing_longest_run": 15,
            "receptions": 982,
            "receiving_yards": 15292,
            "receiving_touchdowns": 156,
            "receiving_longest_reception": 75,
            "tackles": 0,
            "sacks": 0,
            "forced_fumbles": 5,
            "fumble_recoveries": 5,
            "interceptions_defense": 0,
            "pass_deflections": 15,
            "field_goals_made": 0,
            "field_goals_attempted": 0,
            "field_goal_percentage": 0.0,
            "longest_field_goal": 0,
            "extra_points_made": 0,
            "extra_points_attempted": 0,
            "punt_returns": 0,
            "punt_return_yards": 0,
            "punt_return_touchdowns": 0,
            "kick_returns": 0,
            "kick_return_yards": 0,
            "kick_return_touchdowns": 0,
            "pro_bowls": 6,
            "all_pro_selections": 3,
            "mvp_awards": 0,
            "super_bowl_titles": 1,
            "hall_of_fame_inducted": 0,  # Eligible soon
            "quarterback_rating": 0.0,
            "yards_per_attempt": 0.0,
            "yards_per_carry": 4.0,
            "yards_per_reception": 15.5,
            "career_earnings_million_usd": 50.0,
            "total_trophies_won": 3
        },
        # 17) Ronnie Lott
        {
            "player_name": "Ronnie Lott",
            "position": "Safety",
            "years_active": 16,  # 1981-1994
            "teams_played_for": "San Francisco 49ers, Los Angeles Raiders, New York Jets, Kansas City Chiefs",
            "games_played": 201,
            "games_started": 201,
            "wins": 131,
            "losses": 70,
            "ties": 0,
            "passing_completions": 0,
            "passing_attempts": 0,
            "passing_yards": 0,
            "passing_touchdowns": 0,
            "passing_interceptions": 0,
            "passing_rating": 0.0,
            "rushing_attempts": 0,
            "rushing_yards": 0,
            "rushing_touchdowns": 0,
            "rushing_longest_run": 0,
            "receptions": 0,
            "receiving_yards": 0,
            "receiving_touchdowns": 0,
            "receiving_longest_reception": 0,
            "tackles": 1500,  # Approximate
            "sacks": 20,
            "forced_fumbles": 30,
            "fumble_recoveries": 25,
            "interceptions_defense": 35,
            "pass_deflections": 20,
            "field_goals_made": 0,
            "field_goals_attempted": 0,
            "field_goal_percentage": 0.0,
            "longest_field_goal": 0,
            "extra_points_made": 0,
            "extra_points_attempted": 0,
            "punt_returns": 0,
            "punt_return_yards": 0,
            "punt_return_touchdowns": 0,
            "kick_returns": 0,
            "kick_return_yards": 0,
            "kick_return_touchdowns": 0,
            "pro_bowls": 8,
            "all_pro_selections": 10,
            "mvp_awards": 0,
            "super_bowl_titles": 4,
            "hall_of_fame_inducted": 1,
            "quarterback_rating": 0.0,
            "yards_per_attempt": 0.0,
            "yards_per_carry": 0.0,
            "yards_per_reception": 0.0,
            "career_earnings_million_usd": 20.0,
            "total_trophies_won": 5
        },
        # 18) Randy Moss (Duplicate Removed)
        # 18) Marshall Faulk
        {
            "player_name": "Marshall Faulk",
            "position": "Running Back",
            "years_active": 14,  # 1994-2006
            "teams_played_for": "Indianapolis Colts, St. Louis Rams, Minnesota Vikings",
            "games_played": 184,
            "games_started": 184,
            "wins": 130,
            "losses": 50,
            "ties": 4,
            "passing_completions": 0,
            "passing_attempts": 0,
            "passing_yards": 0,
            "passing_touchdowns": 0,
            "passing_interceptions": 0,
            "passing_rating": 0.0,
            "rushing_attempts": 2396,
            "rushing_yards": 13382,
            "rushing_touchdowns": 90,
            "rushing_longest_run": 50,
            "receptions": 1321,
            "receiving_yards": 13320,
            "receiving_touchdowns": 63,
            "receiving_longest_reception": 50,
            "tackles": 0,
            "sacks": 0,
            "forced_fumbles": 10,
            "fumble_recoveries": 15,
            "interceptions_defense": 0,
            "pass_deflections": 5,
            "field_goals_made": 0,
            "field_goals_attempted": 0,
            "field_goal_percentage": 0.0,
            "longest_field_goal": 0,
            "extra_points_made": 0,
            "extra_points_attempted": 0,
            "punt_returns": 0,
            "punt_return_yards": 0,
            "punt_return_touchdowns": 0,
            "kick_returns": 0,
            "kick_return_yards": 0,
            "kick_return_touchdowns": 0,
            "pro_bowls": 6,
            "all_pro_selections": 6,
            "mvp_awards": 2,
            "super_bowl_titles": 1,
            "hall_of_fame_inducted": 1,
            "quarterback_rating": 0.0,
            "yards_per_attempt": 5.6,
            "yards_per_carry": 5.6,
            "yards_per_reception": 10.1,
            "career_earnings_million_usd": 20.0,
            "total_trophies_won": 3
        },
        # 19) Eric Dickerson
        {
            "player_name": "Eric Dickerson",
            "position": "Running Back",
            "years_active": 14,  # 1983-1993, 1994-1997
            "teams_played_for": "Los Angeles Rams, Indianapolis Colts, Philadelphia Eagles, Los Angeles Raiders",
            "games_played": 207,
            "games_started": 207,
            "wins": 90,
            "losses": 115,
            "ties": 2,
            "passing_completions": 0,
            "passing_attempts": 0,
            "passing_yards": 0,
            "passing_touchdowns": 0,
            "passing_interceptions": 0,
            "passing_rating": 0.0,
            "rushing_attempts": 2535,
            "rushing_yards": 14731,
            "rushing_touchdowns": 86,
            "rushing_longest_run": 70,
            "receptions": 584,
            "receiving_yards": 5512,
            "receiving_touchdowns": 28,
            "receiving_longest_reception": 30,
            "tackles": 0,
            "sacks": 0,
            "forced_fumbles": 15,
            "fumble_recoveries": 10,
            "interceptions_defense": 0,
            "pass_deflections": 0,
            "field_goals_made": 0,
            "field_goals_attempted": 0,
            "field_goal_percentage": 0.0,
            "longest_field_goal": 0,
            "extra_points_made": 0,
            "extra_points_attempted": 0,
            "punt_returns": 0,
            "punt_return_yards": 0,
            "punt_return_touchdowns": 0,
            "kick_returns": 0,
            "kick_return_yards": 0,
            "kick_return_touchdowns": 0,
            "pro_bowls": 7,
            "all_pro_selections": 7,
            "mvp_awards": 1,
            "super_bowl_titles": 0,
            "hall_of_fame_inducted": 1,
            "quarterback_rating": 0.0,
            "yards_per_attempt": 5.8,
            "yards_per_carry": 5.8,
            "yards_per_reception": 9.4,
            "career_earnings_million_usd": 20.0,
            "total_trophies_won": 0
        },
        # 20) Deacon Jones
        {
            "player_name": "Deacon Jones",
            "position": "Defensive End",
            "years_active": 16,  # 1956-1967
            "teams_played_for": "Los Angeles Rams, Philadelphia Eagles",
            "games_played": 194,
            "games_started": 194,
            "wins": 100,
            "losses": 94,
            "ties": 0,
            "passing_completions": 0,
            "passing_attempts": 0,
            "passing_yards": 0,
            "passing_touchdowns": 0,
            "passing_interceptions": 0,
            "passing_rating": 0.0,
            "rushing_attempts": 0,
            "rushing_yards": 0,
            "rushing_touchdowns": 0,
            "rushing_longest_run": 0,
            "receptions": 0,
            "receiving_yards": 0,
            "receiving_touchdowns": 0,
            "receiving_longest_reception": 0,
            "tackles": 0,
            "sacks": 173.5,
            "forced_fumbles": 50,
            "fumble_recoveries": 25,
            "interceptions_defense": 1,
            "pass_deflections": 5,
            "field_goals_made": 0,
            "field_goals_attempted": 0,
            "field_goal_percentage": 0.0,
            "longest_field_goal": 0,
            "extra_points_made": 0,
            "extra_points_attempted": 0,
            "punt_returns": 0,
            "punt_return_yards": 0,
            "punt_return_touchdowns": 0,
            "kick_returns": 0,
            "kick_return_yards": 0,
            "kick_return_touchdowns": 0,
            "pro_bowls": 7,
            "all_pro_selections": 10,
            "mvp_awards": 0,
            "super_bowl_titles": 0,
            "hall_of_fame_inducted": 1,
            "quarterback_rating": 0.0,
            "yards_per_attempt": 0.0,
            "yards_per_carry": 0.0,
            "yards_per_reception": 0.0,
            "career_earnings_million_usd": 10.0,
            "total_trophies_won": 0
        },
        # 21) Jerry Kramer
        {
            "player_name": "Jerry Kramer",
            "position": "Guard",
            "years_active": 11,  # 1958-1968
            "teams_played_for": "Green Bay Packers",
            "games_played": 142,
            "games_started": 142,
            "wins": 114,
            "losses": 28,
            "ties": 0,
            "passing_completions": 0,
            "passing_attempts": 0,
            "passing_yards": 0,
            "passing_touchdowns": 0,
            "passing_interceptions": 0,
            "passing_rating": 0.0,
            "rushing_attempts": 0,
            "rushing_yards": 0,
            "rushing_touchdowns": 0,
            "rushing_longest_run": 0,
            "receptions": 0,
            "receiving_yards": 0,
            "receiving_touchdowns": 0,
            "receiving_longest_reception": 0,
            "tackles": 0,
            "sacks": 0,
            "forced_fumbles": 0,
            "fumble_recoveries": 0,
            "interceptions_defense": 0,
            "pass_deflections": 0,
            "field_goals_made": 0,
            "field_goals_attempted": 0,
            "field_goal_percentage": 0.0,
            "longest_field_goal": 0,
            "extra_points_made": 0,
            "extra_points_attempted": 0,
            "punt_returns": 0,
            "punt_return_yards": 0,
            "punt_return_touchdowns": 0,
            "kick_returns": 0,
            "kick_return_yards": 0,
            "kick_return_touchdowns": 0,
            "pro_bowls": 7,
            "all_pro_selections": 7,
            "mvp_awards": 0,
            "super_bowl_titles": 4,
            "hall_of_fame_inducted": 1,
            "quarterback_rating": 0.0,
            "yards_per_attempt": 0.0,
            "yards_per_carry": 0.0,
            "yards_per_reception": 0.0,
            "career_earnings_million_usd": 10.0,
            "total_trophies_won": 4
        },
        # 22) Dan Marino
        {
            "player_name": "Dan Marino",
            "position": "Quarterback",
            "years_active": 17,  # 1983-1999
            "teams_played_for": "Miami Dolphins",
            "games_played": 242,
            "games_started": 242,
            "wins": 147,
            "losses": 95,
            "ties": 0,
            "passing_completions": 4967,
            "passing_attempts": 8405,
            "passing_yards": 61361,
            "passing_touchdowns": 420,
            "passing_interceptions": 252,
            "passing_rating": 86.4,
            "rushing_attempts": 934,
            "rushing_yards": 4239,
            "rushing_touchdowns": 29,
            "rushing_longest_run": 30,
            "receptions": 0,
            "receiving_yards": 0,
            "receiving_touchdowns": 0,
            "receiving_longest_reception": 0,
            "tackles": 0,
            "sacks": 0,
            "forced_fumbles": 0,
            "fumble_recoveries": 10,
            "interceptions_defense": 0,
            "pass_deflections": 0,
            "field_goals_made": 0,
            "field_goals_attempted": 0,
            "field_goal_percentage": 0.0,
            "longest_field_goal": 0,
            "extra_points_made": 0,
            "extra_points_attempted": 0,
            "punt_returns": 0,
            "punt_return_yards": 0,
            "punt_return_touchdowns": 0,
            "kick_returns": 0,
            "kick_return_yards": 0,
            "kick_return_touchdowns": 0,
            "pro_bowls": 9,
            "all_pro_selections": 1,
            "mvp_awards": 1,
            "super_bowl_titles": 0,
            "hall_of_fame_inducted": 1,
            "quarterback_rating": 86.4,
            "yards_per_attempt": 7.3,
            "yards_per_carry": 4.5,
            "yards_per_reception": 0.0,
            "career_earnings_million_usd": 60.0,
            "total_trophies_won": 1
        },
        {
            "player_name": "Bart Starr",
            "position": "Quarterback",
            "years_active": 15,  # 1956-1971
            "teams_played_for": "Green Bay Packers",
            "games_played": 187,
            "games_started": 187,
            "wins": 125,
            "losses": 45,
            "ties": 17,
            "passing_completions": 2589,
            "passing_attempts": 4422,
            "passing_yards": 33524,
            "passing_touchdowns": 207,
            "passing_interceptions": 115,
            "passing_rating": 89.7,
            "rushing_attempts": 612,
            "rushing_yards": 2530,
            "rushing_touchdowns": 19,
            "rushing_longest_run": 26,
            "receptions": 0,
            "receiving_yards": 0,
            "receiving_touchdowns": 0,
            "receiving_longest_reception": 0,
            "tackles": 0,
            "sacks": 0,
            "forced_fumbles": 0,
            "fumble_recoveries": 20,
            "interceptions_defense": 0,
            "pass_deflections": 0,
            "field_goals_made": 0,
            "field_goals_attempted": 0,
            "field_goal_percentage": 0.0,
            "longest_field_goal": 0,
            "extra_points_made": 150,
            "extra_points_attempted": 160,
            "punt_returns": 0,
            "punt_return_yards": 0,
            "punt_return_touchdowns": 0,
            "kick_returns": 0,
            "kick_return_yards": 0,
            "kick_return_touchdowns": 0,
            "pro_bowls": 0,  # Pro Bowl started in 1951 but few seasons
            "all_pro_selections": 7,
            "mvp_awards": 2,
            "super_bowl_titles": 2,
            "hall_of_fame_inducted": 1,
            "quarterback_rating": 89.7,
            "yards_per_attempt": 7.6,
            "yards_per_carry": 4.1,
            "yards_per_reception": 0.0,
            "career_earnings_million_usd": 10.0,
            "total_trophies_won": 5
        },
        # 24) Jim Kelly
        {
            "player_name": "Jim Kelly",
            "position": "Quarterback",
            "years_active": 14,  # 1983-1996
            "teams_played_for": "Buffalo Bills",
            "games_played": 238,
            "games_started": 238,
            "wins": 145,
            "losses": 93,
            "ties": 0,
            "passing_completions": 4175,
            "passing_attempts": 7070,
            "passing_yards": 52455,
            "passing_touchdowns": 351,
            "passing_interceptions": 174,
            "passing_rating": 84.4,
            "rushing_attempts": 675,
            "rushing_yards": 2388,
            "rushing_touchdowns": 17,
            "rushing_longest_run": 35,
            "receptions": 0,
            "receiving_yards": 0,
            "receiving_touchdowns": 0,
            "receiving_longest_reception": 0,
            "tackles": 0,
            "sacks": 0,
            "forced_fumbles": 0,
            "fumble_recoveries": 20,
            "interceptions_defense": 0,
            "pass_deflections": 0,
            "field_goals_made": 0,
            "field_goals_attempted": 0,
            "field_goal_percentage": 0.0,
            "longest_field_goal": 0,
            "extra_points_made": 0,
            "extra_points_attempted": 0,
            "punt_returns": 0,
            "punt_return_yards": 0,
            "punt_return_touchdowns": 0,
            "kick_returns": 0,
            "kick_return_yards": 0,
            "kick_return_touchdowns": 0,
            "pro_bowls": 6,
            "all_pro_selections": 5,
            "mvp_awards": 1,
            "super_bowl_titles": 0,
            "hall_of_fame_inducted": 1,
            "quarterback_rating": 84.4,
            "yards_per_attempt": 7.4,
            "yards_per_carry": 3.5,
            "yards_per_reception": 0.0,
            "career_earnings_million_usd": 30.0,
            "total_trophies_won": 2
        },
        # 25) Johnny Unitas
        {
            "player_name": "Johnny Unitas",
            "position": "Quarterback",
            "years_active": 19,  # 1956-1973
            "teams_played_for": "Baltimore Colts, San Diego Chargers",
            "games_played": 247,
            "games_started": 247,
            "wins": 168,
            "losses": 62,
            "ties": 17,
            "passing_completions": 3407,
            "passing_attempts": 5647,
            "passing_yards": 40239,
            "passing_touchdowns": 290,
            "passing_interceptions": 253,
            "passing_rating": 82.8,
            "rushing_attempts": 789,
            "rushing_yards": 3272,
            "rushing_touchdowns": 20,
            "rushing_longest_run": 33,
            "receptions": 0,
            "receiving_yards": 0,
            "receiving_touchdowns": 0,
            "receiving_longest_reception": 0,
            "tackles": 0,
            "sacks": 0,
            "forced_fumbles": 0,
            "fumble_recoveries": 15,
            "interceptions_defense": 0,
            "pass_deflections": 0,
            "field_goals_made": 0,
            "field_goals_attempted": 0,
            "field_goal_percentage": 0.0,
            "longest_field_goal": 0,
            "extra_points_made": 100,
            "extra_points_attempted": 110,
            "punt_returns": 0,
            "punt_return_yards": 0,
            "punt_return_touchdowns": 0,
            "kick_returns": 0,
            "kick_return_yards": 0,
            "kick_return_touchdowns": 0,
            "pro_bowls": 10,
            "all_pro_selections": 8,
            "mvp_awards": 3,
            "super_bowl_titles": 1,
            "hall_of_fame_inducted": 1,
            "quarterback_rating": 82.8,
            "yards_per_attempt": 7.1,
            "yards_per_carry": 4.2,
            "yards_per_reception": 0.0,
            "career_earnings_million_usd": 10.0,
            "total_trophies_won": 3
        },
        {
            "player_name": "Alan Page",
            "position": "Defensive Tackle",
            "years_active": 19,  # 1967-1985
            "teams_played_for": "Minnesota Vikings, Chicago Bears",
            "games_played": 247,
            "games_started": 247,
            "wins": 134,
            "losses": 104,
            "ties": 9,
            "passing_completions": 0,
            "passing_attempts": 0,
            "passing_yards": 0,
            "passing_touchdowns": 0,
            "passing_interceptions": 0,
            "passing_rating": 0.0,
            "rushing_attempts": 0,
            "rushing_yards": 0,
            "rushing_touchdowns": 0,
            "rushing_longest_run": 0,
            "receptions": 0,
            "receiving_yards": 0,
            "receiving_touchdowns": 0,
            "receiving_longest_reception": 0,
            "tackles": 1000,  # Approximate
            "sacks": 0,        # Sacks not officially recorded until later
            "forced_fumbles": 30,
            "fumble_recoveries": 25,
            "interceptions_defense": 2,
            "pass_deflections": 10,
            "field_goals_made": 0,
            "field_goals_attempted": 0,
            "field_goal_percentage": 0.0,
            "longest_field_goal": 0,
            "extra_points_made": 0,
            "extra_points_attempted": 0,
            "punt_returns": 0,
            "punt_return_yards": 0,
            "punt_return_touchdowns": 0,
            "kick_returns": 0,
            "kick_return_yards": 0,
            "kick_return_touchdowns": 0,
            "pro_bowls": 9,
            "all_pro_selections": 12,
            "mvp_awards": 0,
            "super_bowl_titles": 1,
            "hall_of_fame_inducted": 1,
            "quarterback_rating": 0.0,
            "yards_per_attempt": 0.0,
            "yards_per_carry": 0.0,
            "yards_per_reception": 0.0,
            "career_earnings_million_usd": 20.0,
            "total_trophies_won": 3
        },
        # 27) Troy Aikman
        {
            "player_name": "Troy Aikman",
            "position": "Quarterback",
            "years_active": 12,  # 1989-2000
            "teams_played_for": "Dallas Cowboys",
            "games_played": 165,
            "games_started": 165,
            "wins": 117,
            "losses": 48,
            "ties": 0,
            "passing_completions": 3944,
            "passing_attempts": 6500,
            "passing_yards": 34183,
            "passing_touchdowns": 231,
            "passing_interceptions": 107,
            "passing_rating": 86.3,
            "rushing_attempts": 648,
            "rushing_yards": 2128,
            "rushing_touchdowns": 14,
            "rushing_longest_run": 28,
            "receptions": 0,
            "receiving_yards": 0,
            "receiving_touchdowns": 0,
            "receiving_longest_reception": 0,
            "tackles": 0,
            "sacks": 0,
            "forced_fumbles": 0,
            "fumble_recoveries": 15,
            "interceptions_defense": 0,
            "pass_deflections": 0,
            "field_goals_made": 0,
            "field_goals_attempted": 0,
            "field_goal_percentage": 0.0,
            "longest_field_goal": 0,
            "extra_points_made": 0,
            "extra_points_attempted": 0,
            "punt_returns": 0,
            "punt_return_yards": 0,
            "punt_return_touchdowns": 0,
            "kick_returns": 0,
            "kick_return_yards": 0,
            "kick_return_touchdowns": 0,
            "pro_bowls": 6,
            "all_pro_selections": 3,
            "mvp_awards": 1,
            "super_bowl_titles": 3,
            "hall_of_fame_inducted": 1,
            "quarterback_rating": 86.3,
            "yards_per_attempt": 5.3,
            "yards_per_carry": 3.3,
            "yards_per_reception": 0.0,
            "career_earnings_million_usd": 60.0,
            "total_trophies_won": 4
        },
        # 28) Aaron Donald
        {
            "player_name": "Aaron Donald",
            "position": "Defensive Tackle",
            "years_active": 11,  # 2014-present
            "teams_played_for": "Los Angeles Rams",
            "games_played": 130,
            "games_started": 130,
            "wins": 75,
            "losses": 50,
            "ties": 0,
            "passing_completions": 0,
            "passing_attempts": 0,
            "passing_yards": 0,
            "passing_touchdowns": 0,
            "passing_interceptions": 0,
            "passing_rating": 0.0,
            "rushing_attempts": 0,
            "rushing_yards": 0,
            "rushing_touchdowns": 0,
            "rushing_longest_run": 0,
            "receptions": 0,
            "receiving_yards": 0,
            "receiving_touchdowns": 0,
            "receiving_longest_reception": 0,
            "tackles": 543,  # Approximate
            "sacks": 90,       # Approximate
            "forced_fumbles": 20,
            "fumble_recoveries": 15,
            "interceptions_defense": 2,
            "pass_deflections": 10,
            "field_goals_made": 0,
            "field_goals_attempted": 0,
            "field_goal_percentage": 0.0,
            "longest_field_goal": 0,
            "extra_points_made": 0,
            "extra_points_attempted": 0,
            "punt_returns": 0,
            "punt_return_yards": 0,
            "punt_return_touchdowns": 0,
            "kick_returns": 0,
            "kick_return_yards": 0,
            "kick_return_touchdowns": 0,
            "pro_bowls": 7,
            "all_pro_selections": 7,
            "mvp_awards": 3,
            "super_bowl_titles": 1,
            "hall_of_fame_inducted": 0,
            "quarterback_rating": 0.0,
            "yards_per_attempt": 0.0,
            "yards_per_carry": 0.0,
            "yards_per_reception": 0.0,
            "career_earnings_million_usd": 40.0,
            "total_trophies_won": 3
        },
        # 29) Aaron Rodgers
        {
            "player_name": "Aaron Rodgers",
            "position": "Quarterback",
            "years_active": 18,  # 2005-present
            "teams_played_for": "Green Bay Packers",
            "games_played": 234,
            "games_started": 234,
            "wins": 150,
            "losses": 75,
            "ties": 0,
            "passing_completions": 5437,
            "passing_attempts": 8115,
            "passing_yards": 51245,
            "passing_touchdowns": 412,
            "passing_interceptions": 125,
            "passing_rating": 101.0,
            "rushing_attempts": 539,
            "rushing_yards": 2361,
            "rushing_touchdowns": 21,
            "rushing_longest_run": 26,
            "receptions": 0,
            "receiving_yards": 0,
            "receiving_touchdowns": 0,
            "receiving_longest_reception": 0,
            "tackles": 0,
            "sacks": 0,
            "forced_fumbles": 0,
            "fumble_recoveries": 10,
            "interceptions_defense": 0,
            "pass_deflections": 0,
            "field_goals_made": 0,
            "field_goals_attempted": 0,
            "field_goal_percentage": 0.0,
            "longest_field_goal": 0,
            "extra_points_made": 0,
            "extra_points_attempted": 0,
            "punt_returns": 0,
            "punt_return_yards": 0,
            "punt_return_touchdowns": 0,
            "kick_returns": 0,
            "kick_return_yards": 0,
            "kick_return_touchdowns": 0,
            "pro_bowls": 10,
            "all_pro_selections": 8,
            "mvp_awards": 4,
            "super_bowl_titles": 1,
            "hall_of_fame_inducted": 0,
            "quarterback_rating": 101.0,
            "yards_per_attempt": 6.3,
            "yards_per_carry": 4.4,
            "yards_per_reception": 0.0,
            "career_earnings_million_usd": 200.0,
            "total_trophies_won": 4
        },
        # 30) Deion Branch
        {
            "player_name": "Deion Branch",
            "position": "Wide Receiver",
            "years_active": 10,  # 2003-2012
            "teams_played_for": "New England Patriots, Seattle Seahawks, San Francisco 49ers, Philadelphia Eagles",
            "games_played": 134,
            "games_started": 130,
            "wins": 75,
            "losses": 50,
            "ties": 9,
            "passing_completions": 0,
            "passing_attempts": 0,
            "passing_yards": 0,
            "passing_touchdowns": 0,
            "passing_interceptions": 0,
            "passing_rating": 0.0,
            "rushing_attempts": 50,
            "rushing_yards": 200,
            "rushing_touchdowns": 2,
            "rushing_longest_run": 20,
            "receptions": 500,
            "receiving_yards": 6500,
            "receiving_touchdowns": 50,
            "receiving_longest_reception": 60,
            "tackles": 0,
            "sacks": 0,
            "forced_fumbles": 5,
            "fumble_recoveries": 5,
            "interceptions_defense": 0,
            "pass_deflections": 5,
            "field_goals_made": 0,
            "field_goals_attempted": 0,
            "field_goal_percentage": 0.0,
            "longest_field_goal": 0,
            "extra_points_made": 0,
            "extra_points_attempted": 0,
            "punt_returns": 0,
            "punt_return_yards": 0,
            "punt_return_touchdowns": 0,
            "kick_returns": 0,
            "kick_return_yards": 0,
            "kick_return_touchdowns": 0,
            "pro_bowls": 4,
            "all_pro_selections": 2,
            "mvp_awards": 0,
            "super_bowl_titles": 2,
            "hall_of_fame_inducted": 0,
            "quarterback_rating": 0.0,
            "yards_per_attempt": 4.0,
            "yards_per_carry": 4.0,
            "yards_per_reception": 13.0,
            "career_earnings_million_usd": 30.0,
            "total_trophies_won": 6
        }
    ]

    # Confirm we have exactly 30 players
    if len(players_data) != 30:
        raise ValueError(f"Expected 30 American football players, got {len(players_data)}")

    # ----------------------- WRITE TO CSV -----------------------
    with open(filename, mode="w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=headers)
        writer.writeheader()
        for pdata in players_data:
            # Fill missing fields with 0 if needed
            for h in headers:
                if h not in pdata:
                    pdata[h] = 0
            writer.writerow(pdata)

if __name__ == "__main__":
    create_american_football_dataset()
    print("american_football_dataset.csv has been created with 30 players (41 columns each).")
