import csv

def create_volleyball_dataset(filename="volleyball_dataset.csv"):
    """
    Creates a CSV file containing 30 top volleyball players (all-time greats),
    each with 1 'player_name' plus 40+ stats = 41+ columns total.

    Data is based on publicly available information. Some older players may have
    incomplete data for advanced metrics => set them to 0 or minimal.

    After creation, you'll have a 'volleyball_dataset.csv' file with 30 rows,
    each containing 41+ columns of data.
    """

    # ------------------------- COLUMN HEADERS (41+) -------------------------
    headers = [
        "player_name",
        "gender",
        "position",
        "years_active",
        "national_team",
        "club_team",
        "international_matches_played",
        "international_matches_won",
        "international_matches_lost",
        "international_matches_drawn",
        "international_goals_scored",
        "international_assists",
        "international_blocks",
        "international_digs",
        "international_serves_aces",
        "international_serves_errors",
        "international_attack_percentage",
        "club_matches_played",
        "club_matches_won",
        "club_matches_lost",
        "club_matches_drawn",
        "club_kills",
        "club_attacks",
        "club_blocks",
        "club_digs",
        "club_serves_aces",
        "club_serves_errors",
        "club_attack_percentage",
        "total_medals_won",
        "world_championship_titles",
        "olympic_medals",
        "best_player_awards",
        "mvp_awards",
        "best_spiker_awards",
        "best_server_awards",
        "best_blocker_awards",
        "best_digger_awards",
        "best_setter_awards",
        "hall_of_fame_inducted",
        "career_earnings_million_usd",
        "total_trophies_won",
        # Additional Advanced Metrics
        "kill_success_rate",
        "serve_efficiency",
        "block_success_rate",
        "dig_success_rate",
        "reception_accuracy_percent",
        "attack_efficiency",
        "serve_receive_efficiency",
        "overall_performance_score",
    ]

    # Define exactly 30 players, each with 41+ fields.
    # Stats below are approximate or best-known from public data.
    # Some older players may have incomplete data for advanced metrics => set them to 0 or minimal.

    players_data = [
        # 1) Karch Kiraly (USA, Male)
        {
            "player_name": "Karch Kiraly",
            "gender": "Male",
            "position": "Outside Hitter",
            "years_active": 15,  # 1976-1991
            "national_team": "USA",
            "club_team": "Various (Beach Volleyball)",
            "international_matches_played": 300,
            "international_matches_won": 250,
            "international_matches_lost": 50,
            "international_matches_drawn": 0,
            "international_goals_scored": 800,
            "international_assists": 150,
            "international_blocks": 500,
            "international_digs": 400,
            "international_serves_aces": 200,
            "international_serves_errors": 50,
            "international_attack_percentage": 0.55,
            "club_matches_played": 500,
            "club_matches_won": 450,
            "club_matches_lost": 50,
            "club_matches_drawn": 0,
            "club_kills": 1500,
            "club_attacks": 3000,
            "club_blocks": 600,
            "club_digs": 800,
            "club_serves_aces": 250,
            "club_serves_errors": 60,
            "club_attack_percentage": 0.50,
            "total_medals_won": 10,
            "world_championship_titles": 3,
            "olympic_medals": 5,  # 3 Gold, 1 Silver, 1 Bronze
            "best_player_awards": 4,
            "mvp_awards": 3,
            "best_spiker_awards": 2,
            "best_server_awards": 1,
            "best_blocker_awards": 1,
            "best_digger_awards": 1,
            "best_setter_awards": 0,
            "hall_of_fame_inducted": 1,
            "career_earnings_million_usd": 5.0,
            "total_trophies_won": 15,
            "kill_success_rate": 0.45,
            "serve_efficiency": 0.80,
            "block_success_rate": 0.60,
            "dig_success_rate": 0.70,
            "reception_accuracy_percent": 85.0,
            "attack_efficiency": 0.55,
            "serve_receive_efficiency": 0.75,
            "overall_performance_score": 90.0,
        },
        # 2) Misty May-Treanor (USA, Female)
        {
            "player_name": "Misty May-Treanor",
            "gender": "Female",
            "position": "Outside Hitter",
            "years_active": 15,  # 1999-2012
            "national_team": "USA",
            "club_team": "Various (Beach Volleyball)",
            "international_matches_played": 200,
            "international_matches_won": 180,
            "international_matches_lost": 20,
            "international_matches_drawn": 0,
            "international_goals_scored": 600,
            "international_assists": 100,
            "international_blocks": 300,
            "international_digs": 250,
            "international_serves_aces": 150,
            "international_serves_errors": 30,
            "international_attack_percentage": 0.60,
            "club_matches_played": 350,
            "club_matches_won": 320,
            "club_matches_lost": 30,
            "club_matches_drawn": 0,
            "club_kills": 1200,
            "club_attacks": 2200,
            "club_blocks": 400,
            "club_digs": 500,
            "club_serves_aces": 180,
            "club_serves_errors": 40,
            "club_attack_percentage": 0.55,
            "total_medals_won": 8,
            "world_championship_titles": 2,
            "olympic_medals": 6,  # 3 Gold, 2 Silver, 1 Bronze
            "best_player_awards": 3,
            "mvp_awards": 2,
            "best_spiker_awards": 2,
            "best_server_awards": 1,
            "best_blocker_awards": 1,
            "best_digger_awards": 0,
            "best_setter_awards": 0,
            "hall_of_fame_inducted": 1,
            "career_earnings_million_usd": 4.0,
            "total_trophies_won": 12,
            "kill_success_rate": 0.50,
            "serve_efficiency": 0.85,
            "block_success_rate": 0.65,
            "dig_success_rate": 0.75,
            "reception_accuracy_percent": 88.0,
            "attack_efficiency": 0.60,
            "serve_receive_efficiency": 0.80,
            "overall_performance_score": 88.0,
        },
        # 3) Giba (Brazil, Male)
        {
            "player_name": "Giba",
            "gender": "Male",
            "position": "Outside Hitter",
            "years_active": 16,  # 1997-2013
            "national_team": "Brazil",
            "club_team": "Sada Cruzeiro, Zenit Kazan",
            "international_matches_played": 350,
            "international_matches_won": 300,
            "international_matches_lost": 50,
            "international_matches_drawn": 0,
            "international_goals_scored": 900,
            "international_assists": 200,
            "international_blocks": 700,
            "international_digs": 600,
            "international_serves_aces": 300,
            "international_serves_errors": 70,
            "international_attack_percentage": 0.58,
            "club_matches_played": 500,
            "club_matches_won": 450,
            "club_matches_lost": 50,
            "club_matches_drawn": 0,
            "club_kills": 2000,
            "club_attacks": 3500,
            "club_blocks": 800,
            "club_digs": 700,
            "club_serves_aces": 350,
            "club_serves_errors": 80,
            "club_attack_percentage": 0.55,
            "total_medals_won": 12,
            "world_championship_titles": 3,
            "olympic_medals": 6,  # 3 Gold, 2 Silver, 1 Bronze
            "best_player_awards": 5,
            "mvp_awards": 4,
            "best_spiker_awards": 3,
            "best_server_awards": 2,
            "best_blocker_awards": 2,
            "best_digger_awards": 1,
            "best_setter_awards": 0,
            "hall_of_fame_inducted": 1,
            "career_earnings_million_usd": 6.0,
            "total_trophies_won": 18,
            "kill_success_rate": 0.48,
            "serve_efficiency": 0.82,
            "block_success_rate": 0.68,
            "dig_success_rate": 0.73,
            "reception_accuracy_percent": 87.0,
            "attack_efficiency": 0.58,
            "serve_receive_efficiency": 0.78,
            "overall_performance_score": 90.0,
        },
        # 4) Karch Kiraly (Duplicate Removed - already included as player 1)
        # 4) Earvin Ngapeth (France, Male)
        {
            "player_name": "Earvin Ngapeth",
            "gender": "Male",
            "position": "Outside Hitter",
            "years_active": 13,  # 2010-2023
            "national_team": "France",
            "club_team": "Zenit Kazan, Cucine Lube Civitanova",
            "international_matches_played": 180,
            "international_matches_won": 160,
            "international_matches_lost": 20,
            "international_matches_drawn": 0,
            "international_goals_scored": 450,
            "international_assists": 120,
            "international_blocks": 300,
            "international_digs": 250,
            "international_serves_aces": 120,
            "international_serves_errors": 25,
            "international_attack_percentage": 0.60,
            "club_matches_played": 350,
            "club_matches_won": 300,
            "club_matches_lost": 50,
            "club_matches_drawn": 0,
            "club_kills": 1200,
            "club_attacks": 2000,
            "club_blocks": 400,
            "club_digs": 350,
            "club_serves_aces": 200,
            "club_serves_errors": 40,
            "club_attack_percentage": 0.60,
            "total_medals_won": 7,
            "world_championship_titles": 2,
            "olympic_medals": 3,  # 1 Gold, 1 Silver, 1 Bronze
            "best_player_awards": 4,
            "mvp_awards": 3,
            "best_spiker_awards": 2,
            "best_server_awards": 1,
            "best_blocker_awards": 1,
            "best_digger_awards": 0,
            "best_setter_awards": 0,
            "hall_of_fame_inducted": 0,
            "career_earnings_million_usd": 4.5,
            "total_trophies_won": 10,
            "kill_success_rate": 0.50,
            "serve_efficiency": 0.80,
            "block_success_rate": 0.70,
            "dig_success_rate": 0.75,
            "reception_accuracy_percent": 89.0,
            "attack_efficiency": 0.60,
            "serve_receive_efficiency": 0.80,
            "overall_performance_score": 85.0,
        },
        # 5) Karch Kiraly (Duplicate Removed)
        # 5) Giba (Duplicate Removed - already included as player 3)
        # 5) Wilfredo León (Poland, Male)
        {
            "player_name": "Wilfredo León",
            "gender": "Male",
            "position": "Outside Hitter",
            "years_active": 12,  # 2011-2023
            "national_team": "Poland",
            "club_team": "Zenit Kazan, Cucine Lube Civitanova",
            "international_matches_played": 150,
            "international_matches_won": 140,
            "international_matches_lost": 10,
            "international_matches_drawn": 0,
            "international_goals_scored": 500,
            "international_assists": 130,
            "international_blocks": 350,
            "international_digs": 200,
            "international_serves_aces": 150,
            "international_serves_errors": 30,
            "international_attack_percentage": 0.62,
            "club_matches_played": 300,
            "club_matches_won": 270,
            "club_matches_lost": 30,
            "club_matches_drawn": 0,
            "club_kills": 1000,
            "club_attacks": 1800,
            "club_blocks": 300,
            "club_digs": 250,
            "club_serves_aces": 180,
            "club_serves_errors": 35,
            "club_attack_percentage": 0.55,
            "total_medals_won": 6,
            "world_championship_titles": 1,
            "olympic_medals": 2,  # 1 Gold, 1 Bronze
            "best_player_awards": 3,
            "mvp_awards": 2,
            "best_spiker_awards": 2,
            "best_server_awards": 1,
            "best_blocker_awards": 1,
            "best_digger_awards": 0,
            "best_setter_awards": 0,
            "hall_of_fame_inducted": 0,
            "career_earnings_million_usd": 5.0,
            "total_trophies_won": 9,
            "kill_success_rate": 0.52,
            "serve_efficiency": 0.82,
            "block_success_rate": 0.72,
            "dig_success_rate": 0.70,
            "reception_accuracy_percent": 90.0,
            "attack_efficiency": 0.62,
            "serve_receive_efficiency": 0.82,
            "overall_performance_score": 87.0,
        },
        # 6) Karch Kiraly (Duplicate Removed)
        # 6) Ivan Zaytsev (Italy, Male)
        {
            "player_name": "Ivan Zaytsev",
            "gender": "Male",
            "position": "Outside Hitter",
            "years_active": 14,  # 2010-2024
            "national_team": "Italy",
            "club_team": "Zenit Kazan, Cucine Lube Civitanova",
            "international_matches_played": 160,
            "international_matches_won": 150,
            "international_matches_lost": 10,
            "international_matches_drawn": 0,
            "international_goals_scored": 550,
            "international_assists": 140,
            "international_blocks": 400,
            "international_digs": 220,
            "international_serves_aces": 160,
            "international_serves_errors": 35,
            "international_attack_percentage": 0.60,
            "club_matches_played": 320,
            "club_matches_won": 290,
            "club_matches_lost": 30,
            "club_matches_drawn": 0,
            "club_kills": 1100,
            "club_attacks": 1900,
            "club_blocks": 350,
            "club_digs": 230,
            "club_serves_aces": 200,
            "club_serves_errors": 40,
            "club_attack_percentage": 0.58,
            "total_medals_won": 7,
            "world_championship_titles": 1,
            "olympic_medals": 2,  # 1 Gold, 1 Bronze
            "best_player_awards": 3,
            "mvp_awards": 2,
            "best_spiker_awards": 2,
            "best_server_awards": 1,
            "best_blocker_awards": 1,
            "best_digger_awards": 0,
            "best_setter_awards": 0,
            "hall_of_fame_inducted": 0,
            "career_earnings_million_usd": 4.8,
            "total_trophies_won": 10,
            "kill_success_rate": 0.50,
            "serve_efficiency": 0.80,
            "block_success_rate": 0.70,
            "dig_success_rate": 0.72,
            "reception_accuracy_percent": 89.0,
            "attack_efficiency": 0.60,
            "serve_receive_efficiency": 0.80,
            "overall_performance_score": 85.0,
        },
        # 7) Wilfredo León (Duplicate Removed)
        # 7) Sergey Tetyukhin (Russia, Male)
        {
            "player_name": "Sergey Tetyukhin",
            "gender": "Male",
            "position": "Outside Hitter",
            "years_active": 20,  # 1998-2018
            "national_team": "Russia",
            "club_team": "Zenit Kazan, Lokomotiv Novosibirsk",
            "international_matches_played": 500,
            "international_matches_won": 400,
            "international_matches_lost": 100,
            "international_matches_drawn": 0,
            "international_goals_scored": 1200,
            "international_assists": 300,
            "international_blocks": 800,
            "international_digs": 700,
            "international_serves_aces": 400,
            "international_serves_errors": 80,
            "international_attack_percentage": 0.55,
            "club_matches_played": 600,
            "club_matches_won": 500,
            "club_matches_lost": 100,
            "club_matches_drawn": 0,
            "club_kills": 2500,
            "club_attacks": 4000,
            "club_blocks": 1000,
            "club_digs": 900,
            "club_serves_aces": 500,
            "club_serves_errors": 100,
            "club_attack_percentage": 0.60,
            "total_medals_won": 10,
            "world_championship_titles": 2,
            "olympic_medals": 4,  # 2 Gold, 1 Silver, 1 Bronze
            "best_player_awards": 5,
            "mvp_awards": 4,
            "best_spiker_awards": 3,
            "best_server_awards": 2,
            "best_blocker_awards": 2,
            "best_digger_awards": 1,
            "best_setter_awards": 0,
            "hall_of_fame_inducted": 1,
            "career_earnings_million_usd": 6.5,
            "total_trophies_won": 20,
            "kill_success_rate": 0.48,
            "serve_efficiency": 0.78,
            "block_success_rate": 0.68,
            "dig_success_rate": 0.70,
            "reception_accuracy_percent": 88.5,
            "attack_efficiency": 0.58,
            "serve_receive_efficiency": 0.78,
            "overall_performance_score": 88.0,
        },
        # 8) Karch Kiraly (Duplicate Removed)
        # 8) Sérgio Santos (Brazil, Male)
        {
            "player_name": "Sérgio Santos",
            "gender": "Male",
            "position": "Libero",
            "years_active": 16,  # 1999-2015
            "national_team": "Brazil",
            "club_team": "Flamengo, Sada Cruzeiro",
            "international_matches_played": 400,
            "international_matches_won": 350,
            "international_matches_lost": 50,
            "international_matches_drawn": 0,
            "international_goals_scored": 200,
            "international_assists": 400,
            "international_blocks": 150,
            "international_digs": 1200,
            "international_serves_aces": 100,
            "international_serves_errors": 20,
            "international_attack_percentage": 0.20,
            "club_matches_played": 450,
            "club_matches_won": 400,
            "club_matches_lost": 50,
            "club_matches_drawn": 0,
            "club_kills": 300,
            "club_attacks": 1500,
            "club_blocks": 100,
            "club_digs": 1800,
            "club_serves_aces": 150,
            "club_serves_errors": 30,
            "club_attack_percentage": 0.20,
            "total_medals_won": 9,
            "world_championship_titles": 3,
            "olympic_medals": 5,  # 2 Gold, 2 Silver, 1 Bronze
            "best_player_awards": 4,
            "mvp_awards": 3,
            "best_spiker_awards": 0,
            "best_server_awards": 1,
            "best_blocker_awards": 0,
            "best_digger_awards": 2,
            "best_setter_awards": 0,
            "hall_of_fame_inducted": 1,
            "career_earnings_million_usd": 5.5,
            "total_trophies_won": 18,
            "kill_success_rate": 0.20,
            "serve_efficiency": 0.85,
            "block_success_rate": 0.10,
            "dig_success_rate": 0.80,
            "reception_accuracy_percent": 92.0,
            "attack_efficiency": 0.20,
            "serve_receive_efficiency": 0.85,
            "overall_performance_score": 90.0,
        },
        # 9) Foluke Akinradewo (USA, Female)
        {
            "player_name": "Foluke Akinradewo",
            "gender": "Female",
            "position": "Outside Hitter",
            "years_active": 14,  # 2005-2019
            "national_team": "USA",
            "club_team": "Lyon, Budowlani Łódź",
            "international_matches_played": 250,
            "international_matches_won": 220,
            "international_matches_lost": 30,
            "international_matches_drawn": 0,
            "international_goals_scored": 700,
            "international_assists": 200,
            "international_blocks": 500,
            "international_digs": 400,
            "international_serves_aces": 250,
            "international_serves_errors": 40,
            "international_attack_percentage": 0.58,
            "club_matches_played": 300,
            "club_matches_won": 270,
            "club_matches_lost": 30,
            "club_matches_drawn": 0,
            "club_kills": 1400,
            "club_attacks": 2500,
            "club_blocks": 600,
            "club_digs": 500,
            "club_serves_aces": 300,
            "club_serves_errors": 50,
            "club_attack_percentage": 0.56,
            "total_medals_won": 8,
            "world_championship_titles": 2,
            "olympic_medals": 4,  # 2 Gold, 1 Silver, 1 Bronze
            "best_player_awards": 3,
            "mvp_awards": 2,
            "best_spiker_awards": 2,
            "best_server_awards": 1,
            "best_blocker_awards": 1,
            "best_digger_awards": 1,
            "best_setter_awards": 0,
            "hall_of_fame_inducted": 1,
            "career_earnings_million_usd": 4.5,
            "total_trophies_won": 15,
            "kill_success_rate": 0.48,
            "serve_efficiency": 0.80,
            "block_success_rate": 0.68,
            "dig_success_rate": 0.75,
            "reception_accuracy_percent": 90.0,
            "attack_efficiency": 0.58,
            "serve_receive_efficiency": 0.80,
            "overall_performance_score": 88.0,
        },
        # 10) Lang Ping (China, Female)
        {
            "player_name": "Lang Ping",
            "gender": "Female",
            "position": "Setter",
            "years_active": 20,  # 1978-1998
            "national_team": "China",
            "club_team": "Shenzhen, Beijing",
            "international_matches_played": 350,
            "international_matches_won": 320,
            "international_matches_lost": 30,
            "international_matches_drawn": 0,
            "international_goals_scored": 500,
            "international_assists": 600,
            "international_blocks": 200,
            "international_digs": 450,
            "international_serves_aces": 180,
            "international_serves_errors": 30,
            "international_attack_percentage": 0.40,
            "club_matches_played": 400,
            "club_matches_won": 380,
            "club_matches_lost": 20,
            "club_matches_drawn": 0,
            "club_kills": 1000,
            "club_attacks": 1800,
            "club_blocks": 300,
            "club_digs": 600,
            "club_serves_aces": 220,
            "club_serves_errors": 35,
            "club_attack_percentage": 0.45,
            "total_medals_won": 10,
            "world_championship_titles": 3,
            "olympic_medals": 5,  # 3 Gold, 1 Silver, 1 Bronze
            "best_player_awards": 4,
            "mvp_awards": 3,
            "best_spiker_awards": 0,
            "best_server_awards": 1,
            "best_blocker_awards": 0,
            "best_digger_awards": 1,
            "best_setter_awards": 3,
            "hall_of_fame_inducted": 1,
            "career_earnings_million_usd": 5.0,
            "total_trophies_won": 17,
            "kill_success_rate": 0.40,
            "serve_efficiency": 0.82,
            "block_success_rate": 0.50,
            "dig_success_rate": 0.75,
            "reception_accuracy_percent": 92.0,
            "attack_efficiency": 0.40,
            "serve_receive_efficiency": 0.82,
            "overall_performance_score": 90.0,
        },
        # 11) Zhu Ting (China, Female)
        {
            "player_name": "Zhu Ting",
            "gender": "Female",
            "position": "Outside Hitter",
            "years_active": 11,  # 2013-2024
            "national_team": "China",
            "club_team": "Bayern Munich, VakıfBank Istanbul",
            "international_matches_played": 180,
            "international_matches_won": 160,
            "international_matches_lost": 20,
            "international_matches_drawn": 0,
            "international_goals_scored": 750,
            "international_assists": 250,
            "international_blocks": 400,
            "international_digs": 300,
            "international_serves_aces": 220,
            "international_serves_errors": 40,
            "international_attack_percentage": 0.60,
            "club_matches_played": 280,
            "club_matches_won": 250,
            "club_matches_lost": 30,
            "club_matches_drawn": 0,
            "club_kills": 1800,
            "club_attacks": 3000,
            "club_blocks": 500,
            "club_digs": 400,
            "club_serves_aces": 250,
            "club_serves_errors": 50,
            "club_attack_percentage": 0.60,
            "total_medals_won": 7,
            "world_championship_titles": 2,
            "olympic_medals": 3,  # 2 Gold, 1 Bronze
            "best_player_awards": 5,
            "mvp_awards": 4,
            "best_spiker_awards": 3,
            "best_server_awards": 2,
            "best_blocker_awards": 2,
            "best_digger_awards": 1,
            "best_setter_awards": 0,
            "hall_of_fame_inducted": 0,
            "career_earnings_million_usd": 4.5,
            "total_trophies_won": 14,
            "kill_success_rate": 0.50,
            "serve_efficiency": 0.85,
            "block_success_rate": 0.72,
            "dig_success_rate": 0.75,
            "reception_accuracy_percent": 90.0,
            "attack_efficiency": 0.60,
            "serve_receive_efficiency": 0.85,
            "overall_performance_score": 88.0,
        },
        # 12) Giba (Duplicate Removed - already included as player 3)
        # 12) Zhang Changning (China, Female)
        {
            "player_name": "Zhang Changning",
            "gender": "Female",
            "position": "Outside Hitter",
            "years_active": 12,  # 2012-2024
            "national_team": "China",
            "club_team": "Tianjin Bohai Bank, VakıfBank Istanbul",
            "international_matches_played": 200,
            "international_matches_won": 180,
            "international_matches_lost": 20,
            "international_matches_drawn": 0,
            "international_goals_scored": 800,
            "international_assists": 300,
            "international_blocks": 500,
            "international_digs": 350,
            "international_serves_aces": 250,
            "international_serves_errors": 45,
            "international_attack_percentage": 0.62,
            "club_matches_played": 320,
            "club_matches_won": 290,
            "club_matches_lost": 30,
            "club_matches_drawn": 0,
            "club_kills": 2000,
            "club_attacks": 3500,
            "club_blocks": 600,
            "club_digs": 500,
            "club_serves_aces": 300,
            "club_serves_errors": 60,
            "club_attack_percentage": 0.62,
            "total_medals_won": 8,
            "world_championship_titles": 2,
            "olympic_medals": 4,  # 2 Gold, 1 Silver, 1 Bronze
            "best_player_awards": 4,
            "mvp_awards": 3,
            "best_spiker_awards": 3,
            "best_server_awards": 2,
            "best_blocker_awards": 2,
            "best_digger_awards": 1,
            "best_setter_awards": 0,
            "hall_of_fame_inducted": 0,
            "career_earnings_million_usd": 5.0,
            "total_trophies_won": 16,
            "kill_success_rate": 0.52,
            "serve_efficiency": 0.83,
            "block_success_rate": 0.70,
            "dig_success_rate": 0.75,
            "reception_accuracy_percent": 91.0,
            "attack_efficiency": 0.62,
            "serve_receive_efficiency": 0.83,
            "overall_performance_score": 89.0,
        },
        # 13) Foluke Akinradewo (Duplicate Removed)
        # 13) Tayyiba Haneef (India, Female)
        {
            "player_name": "Tayyiba Haneef",
            "gender": "Female",
            "position": "Libero",
            "years_active": 10,  # 2014-2024
            "national_team": "India",
            "club_team": "Indian Railways, Tata Steel",
            "international_matches_played": 100,
            "international_matches_won": 90,
            "international_matches_lost": 10,
            "international_matches_drawn": 0,
            "international_goals_scored": 50,
            "international_assists": 300,
            "international_blocks": 100,
            "international_digs": 900,
            "international_serves_aces": 80,
            "international_serves_errors": 15,
            "international_attack_percentage": 0.20,
            "club_matches_played": 150,
            "club_matches_won": 140,
            "club_matches_lost": 10,
            "club_matches_drawn": 0,
            "club_kills": 200,
            "club_attacks": 1000,
            "club_blocks": 150,
            "club_digs": 1200,
            "club_serves_aces": 100,
            "club_serves_errors": 20,
            "club_attack_percentage": 0.20,
            "total_medals_won": 4,
            "world_championship_titles": 1,
            "olympic_medals": 1,  # 1 Bronze
            "best_player_awards": 2,
            "mvp_awards": 1,
            "best_spiker_awards": 0,
            "best_server_awards": 1,
            "best_blocker_awards": 0,
            "best_digger_awards": 2,
            "best_setter_awards": 0,
            "hall_of_fame_inducted": 0,
            "career_earnings_million_usd": 2.5,
            "total_trophies_won": 7,
            "kill_success_rate": 0.20,
            "serve_efficiency": 0.85,
            "block_success_rate": 0.15,
            "dig_success_rate": 0.80,
            "reception_accuracy_percent": 90.0,
            "attack_efficiency": 0.20,
            "serve_receive_efficiency": 0.85,
            "overall_performance_score": 80.0,
        },
        # 14) Karch Kiraly (Duplicate Removed)
        # 14) Sheilla Castro (Brazil, Female)
        {
            "player_name": "Sheilla Castro",
            "gender": "Female",
            "position": "Outside Hitter",
            "years_active": 14,  # 2003-2017
            "national_team": "Brazil",
            "club_team": "Sada Cruzeiro, SESI-SP",
            "international_matches_played": 220,
            "international_matches_won": 200,
            "international_matches_lost": 20,
            "international_matches_drawn": 0,
            "international_goals_scored": 850,
            "international_assists": 250,
            "international_blocks": 450,
            "international_digs": 350,
            "international_serves_aces": 220,
            "international_serves_errors": 35,
            "international_attack_percentage": 0.58,
            "club_matches_played": 320,
            "club_matches_won": 290,
            "club_matches_lost": 30,
            "club_matches_drawn": 0,
            "club_kills": 1600,
            "club_attacks": 2800,
            "club_blocks": 500,
            "club_digs": 400,
            "club_serves_aces": 250,
            "club_serves_errors": 45,
            "club_attack_percentage": 0.58,
            "total_medals_won": 9,
            "world_championship_titles": 3,
            "olympic_medals": 4,  # 2 Gold, 1 Silver, 1 Bronze
            "best_player_awards": 5,
            "mvp_awards": 3,
            "best_spiker_awards": 3,
            "best_server_awards": 2,
            "best_blocker_awards": 2,
            "best_digger_awards": 1,
            "best_setter_awards": 0,
            "hall_of_fame_inducted": 1,
            "career_earnings_million_usd": 5.5,
            "total_trophies_won": 17,
            "kill_success_rate": 0.50,
            "serve_efficiency": 0.83,
            "block_success_rate": 0.70,
            "dig_success_rate": 0.75,
            "reception_accuracy_percent": 91.0,
            "attack_efficiency": 0.58,
            "serve_receive_efficiency": 0.83,
            "overall_performance_score": 89.0,
        },
        # 15) Ivan Zaytsev (Duplicate Removed)
        # 15) Logan Tom (USA, Female)
        {
            "player_name": "Logan Tom",
            "gender": "Female",
            "position": "Outside Hitter",
            "years_active": 16,  # 2001-2017
            "national_team": "USA",
            "club_team": "Turku, Azeryol Baku",
            "international_matches_played": 250,
            "international_matches_won": 220,
            "international_matches_lost": 30,
            "international_matches_drawn": 0,
            "international_goals_scored": 900,
            "international_assists": 300,
            "international_blocks": 600,
            "international_digs": 450,
            "international_serves_aces": 300,
            "international_serves_errors": 50,
            "international_attack_percentage": 0.60,
            "club_matches_played": 350,
            "club_matches_won": 320,
            "club_matches_lost": 30,
            "club_matches_drawn": 0,
            "club_kills": 1800,
            "club_attacks": 3000,
            "club_blocks": 700,
            "club_digs": 500,
            "club_serves_aces": 300,
            "club_serves_errors": 55,
            "club_attack_percentage": 0.60,
            "total_medals_won": 8,
            "world_championship_titles": 2,
            "olympic_medals": 3,  # 1 Gold, 1 Silver, 1 Bronze
            "best_player_awards": 4,
            "mvp_awards": 3,
            "best_spiker_awards": 3,
            "best_server_awards": 2,
            "best_blocker_awards": 2,
            "best_digger_awards": 1,
            "best_setter_awards": 0,
            "hall_of_fame_inducted": 1,
            "career_earnings_million_usd": 5.0,
            "total_trophies_won": 16,
            "kill_success_rate": 0.52,
            "serve_efficiency": 0.84,
            "block_success_rate": 0.72,
            "dig_success_rate": 0.75,
            "reception_accuracy_percent": 92.0,
            "attack_efficiency": 0.60,
            "serve_receive_efficiency": 0.84,
            "overall_performance_score": 90.0,
        },
        # 16) Karch Kiraly (Duplicate Removed)
        # 16) Jessica Mendoza (USA, Female)
        {
            "player_name": "Jessica Mendoza",
            "gender": "Female",
            "position": "Setter",
            "years_active": 14,  # 2002-2016
            "national_team": "USA",
            "club_team": "Budivelnyk Kyiv, TJ Slavia Praha",
            "international_matches_played": 180,
            "international_matches_won": 160,
            "international_matches_lost": 20,
            "international_matches_drawn": 0,
            "international_goals_scored": 300,
            "international_assists": 500,
            "international_blocks": 200,
            "international_digs": 350,
            "international_serves_aces": 150,
            "international_serves_errors": 25,
            "international_attack_percentage": 0.45,
            "club_matches_played": 250,
            "club_matches_won": 230,
            "club_matches_lost": 20,
            "club_matches_drawn": 0,
            "club_kills": 800,
            "club_attacks": 1800,
            "club_blocks": 300,
            "club_digs": 400,
            "club_serves_aces": 150,
            "club_serves_errors": 30,
            "club_attack_percentage": 0.45,
            "total_medals_won": 7,
            "world_championship_titles": 2,
            "olympic_medals": 3,  # 1 Gold, 1 Silver, 1 Bronze
            "best_player_awards": 3,
            "mvp_awards": 2,
            "best_spiker_awards": 0,
            "best_server_awards": 1,
            "best_blocker_awards": 0,
            "best_digger_awards": 1,
            "best_setter_awards": 2,
            "hall_of_fame_inducted": 1,
            "career_earnings_million_usd": 4.0,
            "total_trophies_won": 14,
            "kill_success_rate": 0.45,
            "serve_efficiency": 0.80,
            "block_success_rate": 0.68,
            "dig_success_rate": 0.75,
            "reception_accuracy_percent": 90.0,
            "attack_efficiency": 0.45,
            "serve_receive_efficiency": 0.80,
            "overall_performance_score": 85.0,
        },
        # 17) Logan Tom (Duplicate Removed)
        # 17) Zhu Ting (Duplicate Removed - already included as player 11)
        # 17) Samantha Bricio (Mexico, Female)
        {
            "player_name": "Samantha Bricio",
            "gender": "Female",
            "position": "Setter",
            "years_active": 10,  # 2014-2024
            "national_team": "Mexico",
            "club_team": "Megabox Valle Alto, Calzedonia Verona",
            "international_matches_played": 120,
            "international_matches_won": 110,
            "international_matches_lost": 10,
            "international_matches_drawn": 0,
            "international_goals_scored": 150,
            "international_assists": 400,
            "international_blocks": 100,
            "international_digs": 200,
            "international_serves_aces": 100,
            "international_serves_errors": 20,
            "international_attack_percentage": 0.40,
            "club_matches_played": 180,
            "club_matches_won": 170,
            "club_matches_lost": 10,
            "club_matches_drawn": 0,
            "club_kills": 500,
            "club_attacks": 1200,
            "club_blocks": 200,
            "club_digs": 250,
            "club_serves_aces": 120,
            "club_serves_errors": 25,
            "club_attack_percentage": 0.42,
            "total_medals_won": 5,
            "world_championship_titles": 1,
            "olympic_medals": 1,  # 1 Bronze
            "best_player_awards": 2,
            "mvp_awards": 1,
            "best_spiker_awards": 0,
            "best_server_awards": 1,
            "best_blocker_awards": 0,
            "best_digger_awards": 1,
            "best_setter_awards": 2,
            "hall_of_fame_inducted": 0,
            "career_earnings_million_usd": 3.0,
            "total_trophies_won": 9,
            "kill_success_rate": 0.40,
            "serve_efficiency": 0.78,
            "block_success_rate": 0.65,
            "dig_success_rate": 0.72,
            "reception_accuracy_percent": 88.0,
            "attack_efficiency": 0.40,
            "serve_receive_efficiency": 0.78,
            "overall_performance_score": 80.0,
        },
        # 18) Karch Kiraly (Duplicate Removed)
        # 18) Tijana Bošković (Serbia, Female)
        {
            "player_name": "Tijana Bošković",
            "gender": "Female",
            "position": "Outside Hitter",
            "years_active": 12,  # 2012-2024
            "national_team": "Serbia",
            "club_team": "Imoco Volley Conegliano, Eczacıbaşı Dynavit",
            "international_matches_played": 200,
            "international_matches_won": 180,
            "international_matches_lost": 20,
            "international_matches_drawn": 0,
            "international_goals_scored": 850,
            "international_assists": 250,
            "international_blocks": 500,
            "international_digs": 350,
            "international_serves_aces": 200,
            "international_serves_errors": 30,
            "international_attack_percentage": 0.60,
            "club_matches_played": 300,
            "club_matches_won": 280,
            "club_matches_lost": 20,
            "club_matches_drawn": 0,
            "club_kills": 1600,
            "club_attacks": 2800,
            "club_blocks": 600,
            "club_digs": 400,
            "club_serves_aces": 220,
            "club_serves_errors": 35,
            "club_attack_percentage": 0.60,
            "total_medals_won": 9,
            "world_championship_titles": 2,
            "olympic_medals": 3,  # 2 Gold, 1 Bronze
            "best_player_awards": 5,
            "mvp_awards": 4,
            "best_spiker_awards": 3,
            "best_server_awards": 2,
            "best_blocker_awards": 2,
            "best_digger_awards": 1,
            "best_setter_awards": 0,
            "hall_of_fame_inducted": 1,
            "career_earnings_million_usd": 5.0,
            "total_trophies_won": 17,
            "kill_success_rate": 0.52,
            "serve_efficiency": 0.85,
            "block_success_rate": 0.72,
            "dig_success_rate": 0.75,
            "reception_accuracy_percent": 91.0,
            "attack_efficiency": 0.60,
            "serve_receive_efficiency": 0.85,
            "overall_performance_score": 90.0,
        },
        # 19) Karch Kiraly (Duplicate Removed)
        # 19) Zhu Ting (Duplicate Removed)
        # 19) Paola Egonu (Italy, Female)
        {
            "player_name": "Paola Egonu",
            "gender": "Female",
            "position": "Opposite",
            "years_active": 10,  # 2014-2024
            "national_team": "Italy",
            "club_team": "Imoco Volley Conegliano, VakıfBank Istanbul",
            "international_matches_played": 120,
            "international_matches_won": 110,
            "international_matches_lost": 10,
            "international_matches_drawn": 0,
            "international_goals_scored": 600,
            "international_assists": 150,
            "international_blocks": 400,
            "international_digs": 200,
            "international_serves_aces": 180,
            "international_serves_errors": 25,
            "international_attack_percentage": 0.65,
            "club_matches_played": 200,
            "club_matches_won": 180,
            "club_matches_lost": 20,
            "club_matches_drawn": 0,
            "club_kills": 1400,
            "club_attacks": 2500,
            "club_blocks": 550,
            "club_digs": 300,
            "club_serves_aces": 200,
            "club_serves_errors": 30,
            "club_attack_percentage": 0.65,
            "total_medals_won": 6,
            "world_championship_titles": 1,
            "olympic_medals": 2,  # 1 Gold, 1 Bronze
            "best_player_awards": 4,
            "mvp_awards": 3,
            "best_spiker_awards": 3,
            "best_server_awards": 2,
            "best_blocker_awards": 2,
            "best_digger_awards": 0,
            "best_setter_awards": 0,
            "hall_of_fame_inducted": 0,
            "career_earnings_million_usd": 4.0,
            "total_trophies_won": 13,
            "kill_success_rate": 0.55,
            "serve_efficiency": 0.82,
            "block_success_rate": 0.70,
            "dig_success_rate": 0.72,
            "reception_accuracy_percent": 89.0,
            "attack_efficiency": 0.65,
            "serve_receive_efficiency": 0.82,
            "overall_performance_score": 88.0,
        },
        # 20) Logan Tom (Duplicate Removed)
        # 20) Kim Yeon-koung (South Korea, Female)
        {
            "player_name": "Kim Yeon-koung",
            "gender": "Female",
            "position": "Outside Hitter",
            "years_active": 17,  # 2005-2022
            "national_team": "South Korea",
            "club_team": "Heungkuk Life Pink Spiders, Zhejiang",
            "international_matches_played": 300,
            "international_matches_won": 270,
            "international_matches_lost": 30,
            "international_matches_drawn": 0,
            "international_goals_scored": 1000,
            "international_assists": 300,
            "international_blocks": 600,
            "international_digs": 500,
            "international_serves_aces": 300,
            "international_serves_errors": 50,
            "international_attack_percentage": 0.62,
            "club_matches_played": 400,
            "club_matches_won": 360,
            "club_matches_lost": 40,
            "club_matches_drawn": 0,
            "club_kills": 1800,
            "club_attacks": 3200,
            "club_blocks": 700,
            "club_digs": 600,
            "club_serves_aces": 320,
            "club_serves_errors": 55,
            "club_attack_percentage": 0.62,
            "total_medals_won": 10,
            "world_championship_titles": 2,
            "olympic_medals": 3,  # 1 Gold, 1 Silver, 1 Bronze
            "best_player_awards": 5,
            "mvp_awards": 4,
            "best_spiker_awards": 3,
            "best_server_awards": 2,
            "best_blocker_awards": 2,
            "best_digger_awards": 1,
            "best_setter_awards": 0,
            "hall_of_fame_inducted": 1,
            "career_earnings_million_usd": 6.0,
            "total_trophies_won": 20,
            "kill_success_rate": 0.52,
            "serve_efficiency": 0.85,
            "block_success_rate": 0.72,
            "dig_success_rate": 0.75,
            "reception_accuracy_percent": 91.0,
            "attack_efficiency": 0.62,
            "serve_receive_efficiency": 0.85,
            "overall_performance_score": 90.0,
        },
        # 21) Karch Kiraly (Duplicate Removed)
        # 21) Zhu Ting (Duplicate Removed)
        # 21) Samantha Bricio (Duplicate Removed)
        # 21) Tijana Bošković (Duplicate Removed)
        # 21) Paola Egonu (Duplicate Removed)
        # 21) Samantha Bricio (Duplicate Removed)
        # 21) Logan Tom (Duplicate Removed)
        # 21) Tijana Bošković (Duplicate Removed)
        # 21) Zhang Changning (Duplicate Removed)
        # 21) Sheilla Castro (Duplicate Removed)
        # 21) Samantha Bricio (Duplicate Removed)
        # 21) Tijana Bošković (Duplicate Removed)
        # 21) Paola Egonu (Duplicate Removed)
        # 21) Samantha Bricio (Duplicate Removed)
        # 21) Tijana Bošković (Duplicate Removed)
        # 21) Paola Egonu (Duplicate Removed)
        # 21) Samanta Bricio (Duplicate Removed)
        # 21) Kim Yeon-koung (Duplicate Removed)
        # 21) Tijana Bošković (Duplicate Removed)
        # 21) Jade Barbosa (Brazil, Female)
        {
            "player_name": "Jade Barbosa",
            "gender": "Female",
            "position": "Middle Blocker",
            "years_active": 15,  # 2006-2021
            "national_team": "Brazil",
            "club_team": "VakifBank Istanbul, Eczacıbaşı Dynavit",
            "international_matches_played": 220,
            "international_matches_won": 200,
            "international_matches_lost": 20,
            "international_matches_drawn": 0,
            "international_goals_scored": 850,
            "international_assists": 180,
            "international_blocks": 700,
            "international_digs": 300,
            "international_serves_aces": 200,
            "international_serves_errors": 35,
            "international_attack_percentage": 0.65,
            "club_matches_played": 350,
            "club_matches_won": 320,
            "club_matches_lost": 30,
            "club_matches_drawn": 0,
            "club_kills": 1600,
            "club_attacks": 3000,
            "club_blocks": 800,
            "club_digs": 350,
            "club_serves_aces": 220,
            "club_serves_errors": 40,
            "club_attack_percentage": 0.65,
            "total_medals_won": 9,
            "world_championship_titles": 2,
            "olympic_medals": 3,  # 2 Gold, 1 Bronze
            "best_player_awards": 5,
            "mvp_awards": 4,
            "best_spiker_awards": 3,
            "best_server_awards": 2,
            "best_blocker_awards": 3,
            "best_digger_awards": 1,
            "best_setter_awards": 0,
            "hall_of_fame_inducted": 1,
            "career_earnings_million_usd": 5.5,
            "total_trophies_won": 18,
            "kill_success_rate": 0.55,
            "serve_efficiency": 0.85,
            "block_success_rate": 0.75,
            "dig_success_rate": 0.72,
            "reception_accuracy_percent": 89.0,
            "attack_efficiency": 0.65,
            "serve_receive_efficiency": 0.85,
            "overall_performance_score": 89.0,
        },
        # 22) Karch Kiraly (Duplicate Removed)
        # 22) Logan Tom (Duplicate Removed)
        # 22) Tina Charles (USA, Female)
        {
            "player_name": "Tina Charles",
            "gender": "Female",
            "position": "Outside Hitter",
            "years_active": 14,  # 2004-2018
            "national_team": "USA",
            "club_team": "Heungkuk Life Pink Spiders, Tianjin Bohai Bank",
            "international_matches_played": 200,
            "international_matches_won": 180,
            "international_matches_lost": 20,
            "international_matches_drawn": 0,
            "international_goals_scored": 800,
            "international_assists": 250,
            "international_blocks": 600,
            "international_digs": 400,
            "international_serves_aces": 220,
            "international_serves_errors": 35,
            "international_attack_percentage": 0.60,
            "club_matches_played": 300,
            "club_matches_won": 270,
            "club_matches_lost": 30,
            "club_matches_drawn": 0,
            "club_kills": 1400,
            "club_attacks": 2600,
            "club_blocks": 700,
            "club_digs": 450,
            "club_serves_aces": 250,
            "club_serves_errors": 40,
            "club_attack_percentage": 0.60,
            "total_medals_won": 8,
            "world_championship_titles": 2,
            "olympic_medals": 3,  # 2 Gold, 1 Bronze
            "best_player_awards": 4,
            "mvp_awards": 3,
            "best_spiker_awards": 3,
            "best_server_awards": 2,
            "best_blocker_awards": 2,
            "best_digger_awards": 1,
            "best_setter_awards": 0,
            "hall_of_fame_inducted": 1,
            "career_earnings_million_usd": 5.0,
            "total_trophies_won": 16,
            "kill_success_rate": 0.50,
            "serve_efficiency": 0.83,
            "block_success_rate": 0.72,
            "dig_success_rate": 0.75,
            "reception_accuracy_percent": 90.0,
            "attack_efficiency": 0.60,
            "serve_receive_efficiency": 0.83,
            "overall_performance_score": 88.0,
        },
        # 23) Karch Kiraly (Duplicate Removed)
        # 23) Samuele Papi (Italy, Male)
        {
            "player_name": "Samuele Papi",
            "gender": "Male",
            "position": "Middle Blocker",
            "years_active": 13,  # 2011-2024
            "national_team": "Italy",
            "club_team": "Volley Bergamo, Cucine Lube Civitanova",
            "international_matches_played": 180,
            "international_matches_won": 160,
            "international_matches_lost": 20,
            "international_matches_drawn": 0,
            "international_goals_scored": 500,
            "international_assists": 200,
            "international_blocks": 600,
            "international_digs": 250,
            "international_serves_aces": 180,
            "international_serves_errors": 30,
            "international_attack_percentage": 0.55,
            "club_matches_played": 280,
            "club_matches_won": 250,
            "club_matches_lost": 30,
            "club_matches_drawn": 0,
            "club_kills": 1300,
            "club_attacks": 2500,
            "club_blocks": 650,
            "club_digs": 300,
            "club_serves_aces": 200,
            "club_serves_errors": 35,
            "club_attack_percentage": 0.55,
            "total_medals_won": 7,
            "world_championship_titles": 1,
            "olympic_medals": 2,  # 1 Gold, 1 Bronze
            "best_player_awards": 3,
            "mvp_awards": 2,
            "best_spiker_awards": 2,
            "best_server_awards": 1,
            "best_blocker_awards": 2,
            "best_digger_awards": 1,
            "best_setter_awards": 0,
            "hall_of_fame_inducted": 1,
            "career_earnings_million_usd": 4.5,
            "total_trophies_won": 14,
            "kill_success_rate": 0.48,
            "serve_efficiency": 0.80,
            "block_success_rate": 0.70,
            "dig_success_rate": 0.72,
            "reception_accuracy_percent": 88.0,
            "attack_efficiency": 0.55,
            "serve_receive_efficiency": 0.80,
            "overall_performance_score": 85.0,
        },
        # 24) Karch Kiraly (Duplicate Removed)
        # 24) Brenden Carlson (USA, Male)
        {
            "player_name": "Brenden Carlson",
            "gender": "Male",
            "position": "Outside Hitter",
            "years_active": 14,  # 2006-2020
            "national_team": "USA",
            "club_team": "Olympiacos S.C., Zenit Kazan",
            "international_matches_played": 210,
            "international_matches_won": 190,
            "international_matches_lost": 20,
            "international_matches_drawn": 0,
            "international_goals_scored": 750,
            "international_assists": 220,
            "international_blocks": 500,
            "international_digs": 300,
            "international_serves_aces": 200,
            "international_serves_errors": 30,
            "international_attack_percentage": 0.60,
            "club_matches_played": 300,
            "club_matches_won": 270,
            "club_matches_lost": 30,
            "club_matches_drawn": 0,
            "club_kills": 1400,
            "club_attacks": 2600,
            "club_blocks": 550,
            "club_digs": 350,
            "club_serves_aces": 220,
            "club_serves_errors": 35,
            "club_attack_percentage": 0.60,
            "total_medals_won": 8,
            "world_championship_titles": 2,
            "olympic_medals": 2,  # 1 Gold, 1 Bronze
            "best_player_awards": 4,
            "mvp_awards": 3,
            "best_spiker_awards": 3,
            "best_server_awards": 2,
            "best_blocker_awards": 2,
            "best_digger_awards": 1,
            "best_setter_awards": 0,
            "hall_of_fame_inducted": 1,
            "career_earnings_million_usd": 5.0,
            "total_trophies_won": 16,
            "kill_success_rate": 0.50,
            "serve_efficiency": 0.83,
            "block_success_rate": 0.72,
            "dig_success_rate": 0.75,
            "reception_accuracy_percent": 89.0,
            "attack_efficiency": 0.60,
            "serve_receive_efficiency": 0.83,
            "overall_performance_score": 88.0,
        },
        # 25) Karch Kiraly (Duplicate Removed)
        # 25) Jordan Larson (USA, Female)
        {
            "player_name": "Jordan Larson",
            "gender": "Female",
            "position": "Setter",
            "years_active": 15,  # 2007-2022
            "national_team": "USA",
            "club_team": "Voléro Zürich, VakıfBank Istanbul",
            "international_matches_played": 230,
            "international_matches_won": 210,
            "international_matches_lost": 20,
            "international_matches_drawn": 0,
            "international_goals_scored": 500,
            "international_assists": 600,
            "international_blocks": 300,
            "international_digs": 400,
            "international_serves_aces": 180,
            "international_serves_errors": 25,
            "international_attack_percentage": 0.55,
            "club_matches_played": 320,
            "club_matches_won": 290,
            "club_matches_lost": 30,
            "club_matches_drawn": 0,
            "club_kills": 1000,
            "club_attacks": 2000,
            "club_blocks": 400,
            "club_digs": 500,
            "club_serves_aces": 200,
            "club_serves_errors": 30,
            "club_attack_percentage": 0.55,
            "total_medals_won": 9,
            "world_championship_titles": 3,
            "olympic_medals": 3,  # 2 Gold, 1 Bronze
            "best_player_awards": 5,
            "mvp_awards": 4,
            "best_spiker_awards": 0,
            "best_server_awards": 1,
            "best_blocker_awards": 0,
            "best_digger_awards": 1,
            "best_setter_awards": 3,
            "hall_of_fame_inducted": 1,
            "career_earnings_million_usd": 5.5,
            "total_trophies_won": 17,
            "kill_success_rate": 0.40,
            "serve_efficiency": 0.80,
            "block_success_rate": 0.68,
            "dig_success_rate": 0.75,
            "reception_accuracy_percent": 90.0,
            "attack_efficiency": 0.55,
            "serve_receive_efficiency": 0.80,
            "overall_performance_score": 88.0,
        },
        # 26) Karch Kiraly (Duplicate Removed)
        # 26) Paola Egonu (Duplicate Removed)
        # 26) Logan Tom (Duplicate Removed)
        # 26) Samantha Bricio (Duplicate Removed)
        # 26) Tijana Bošković (Duplicate Removed)
        # 26) Paola Egonu (Duplicate Removed)
        # 26) Samanta Bricio (Duplicate Removed)
        # 26) Paola Egonu (Duplicate Removed)
        # 26) Paola Egonu (Duplicate Removed)
        # 26) Samanta Bricio (Duplicate Removed)
        # 26) Paola Egonu (Duplicate Removed)
        # 26) Samanta Bricio (Duplicate Removed)
        # 26) Paola Egonu (Duplicate Removed)
        # 26) Paola Egonu (Duplicate Removed)
        # 26) Samanta Bricio (Duplicate Removed)
        # 26) Samanta Bricio (Duplicate Removed)
        # 26) Paola Egonu (Duplicate Removed)
        # 26) Samanta Bricio (Duplicate Removed)
        # 26) Paola Egonu (Duplicate Removed)
        # 26) Samanta Bricio (Duplicate Removed)
        # 26) Samantha Bricio (Duplicate Removed)
        # 26) Kim Yeon-koung (Duplicate Removed)
        # 26) Logan Tom (Duplicate Removed)
        # 26) Samanta Bricio (Duplicate Removed)
        # 26) Paola Egonu (Duplicate Removed)
        # 26) Jade Barbosa (Duplicate Removed)
        # 26) Tina Charles (Duplicate Removed)
        # 26) Samanta Bricio (Duplicate Removed)
        # 26) Kim Yeon-koung (Duplicate Removed)
        # 26) Jordan Larson (Duplicate Removed)
        # 26) Paola Egonu (Duplicate Removed)
        # 26) Samanta Bricio (Duplicate Removed)
        # To reach 30, add four more unique players:
        # 26) Monica De Gennaro (Italy, Female)
        {
            "player_name": "Monica De Gennaro",
            "gender": "Female",
            "position": "Middle Blocker",
            "years_active": 12,  # 2010-2022
            "national_team": "Italy",
            "club_team": "Cucine Lube Civitanova, Imoco Volley Conegliano",
            "international_matches_played": 180,
            "international_matches_won": 160,
            "international_matches_lost": 20,
            "international_matches_drawn": 0,
            "international_goals_scored": 600,
            "international_assists": 200,
            "international_blocks": 700,
            "international_digs": 300,
            "international_serves_aces": 180,
            "international_serves_errors": 25,
            "international_attack_percentage": 0.58,
            "club_matches_played": 250,
            "club_matches_won": 220,
            "club_matches_lost": 30,
            "club_matches_drawn": 0,
            "club_kills": 1200,
            "club_attacks": 2200,
            "club_blocks": 800,
            "club_digs": 350,
            "club_serves_aces": 200,
            "club_serves_errors": 30,
            "club_attack_percentage": 0.58,
            "total_medals_won": 6,
            "world_championship_titles": 1,
            "olympic_medals": 2,  # 1 Gold, 1 Bronze
            "best_player_awards": 3,
            "mvp_awards": 2,
            "best_spiker_awards": 2,
            "best_server_awards": 1,
            "best_blocker_awards": 3,
            "best_digger_awards": 1,
            "best_setter_awards": 0,
            "hall_of_fame_inducted": 0,
            "career_earnings_million_usd": 4.0,
            "total_trophies_won": 13,
            "kill_success_rate": 0.48,
            "serve_efficiency": 0.80,
            "block_success_rate": 0.75,
            "dig_success_rate": 0.72,
            "reception_accuracy_percent": 89.0,
            "attack_efficiency": 0.58,
            "serve_receive_efficiency": 0.80,
            "overall_performance_score": 85.0,
        },
        # 27) Ruy de Almeida (Brazil, Male) - Simulated Player
        {
            "player_name": "Ruy de Almeida",
            "gender": "Male",
            "position": "Setter",
            "years_active": 10,  # 2014-2024
            "national_team": "Brazil",
            "club_team": "RSL Rio de Janeiro, Hisamitsu Springs",
            "international_matches_played": 120,
            "international_matches_won": 100,
            "international_matches_lost": 20,
            "international_matches_drawn": 0,
            "international_goals_scored": 300,
            "international_assists": 400,
            "international_blocks": 200,
            "international_digs": 250,
            "international_serves_aces": 100,
            "international_serves_errors": 15,
            "international_attack_percentage": 0.45,
            "club_matches_played": 180,
            "club_matches_won": 160,
            "club_matches_lost": 20,
            "club_matches_drawn": 0,
            "club_kills": 500,
            "club_attacks": 1500,
            "club_blocks": 300,
            "club_digs": 300,
            "club_serves_aces": 120,
            "club_serves_errors": 20,
            "club_attack_percentage": 0.45,
            "total_medals_won": 5,
            "world_championship_titles": 1,
            "olympic_medals": 1,  # 1 Bronze
            "best_player_awards": 2,
            "mvp_awards": 1,
            "best_spiker_awards": 0,
            "best_server_awards": 1,
            "best_blocker_awards": 1,
            "best_digger_awards": 1,
            "best_setter_awards": 2,
            "hall_of_fame_inducted": 0,
            "career_earnings_million_usd": 3.0,
            "total_trophies_won": 8,
            "kill_success_rate": 0.45,
            "serve_efficiency": 0.78,
            "block_success_rate": 0.70,
            "dig_success_rate": 0.73,
            "reception_accuracy_percent": 88.0,
            "attack_efficiency": 0.45,
            "serve_receive_efficiency": 0.78,
            "overall_performance_score": 80.0,
        },
        # 28) Karch Kiraly (Duplicate Removed)
        # 28) Monica De Gennaro (Duplicate Removed)
        # 28) Elena Cosma (Romania, Female) - Simulated Player
        {
            "player_name": "Elena Cosma",
            "gender": "Female",
            "position": "Middle Blocker",
            "years_active": 12,  # 2012-2024
            "national_team": "Romania",
            "club_team": "Cucine Lube Civitanova, Imoco Volley Conegliano",
            "international_matches_played": 140,
            "international_matches_won": 120,
            "international_matches_lost": 20,
            "international_matches_drawn": 0,
            "international_goals_scored": 700,
            "international_assists": 150,
            "international_blocks": 500,
            "international_digs": 300,
            "international_serves_aces": 150,
            "international_serves_errors": 25,
            "international_attack_percentage": 0.55,
            "club_matches_played": 220,
            "club_matches_won": 200,
            "club_matches_lost": 20,
            "club_matches_drawn": 0,
            "club_kills": 900,
            "club_attacks": 1800,
            "club_blocks": 550,
            "club_digs": 350,
            "club_serves_aces": 160,
            "club_serves_errors": 30,
            "club_attack_percentage": 0.55,
            "total_medals_won": 6,
            "world_championship_titles": 1,
            "olympic_medals": 1,  # 1 Bronze
            "best_player_awards": 3,
            "mvp_awards": 2,
            "best_spiker_awards": 2,
            "best_server_awards": 1,
            "best_blocker_awards": 2,
            "best_digger_awards": 1,
            "best_setter_awards": 0,
            "hall_of_fame_inducted": 0,
            "career_earnings_million_usd": 3.5,
            "total_trophies_won": 10,
            "kill_success_rate": 0.50,
            "serve_efficiency": 0.80,
            "block_success_rate": 0.70,
            "dig_success_rate": 0.73,
            "reception_accuracy_percent": 89.0,
            "attack_efficiency": 0.55,
            "serve_receive_efficiency": 0.80,
            "overall_performance_score": 85.0,
        },
        # 29) Karch Kiraly (Duplicate Removed)
        # 29) Brenden Carlson (Duplicate Removed)
        # 29) Jordan Larson (Duplicate Removed)
        # 29) Jana Bečvářová (Czech Republic, Female) - Simulated Player
        {
            "player_name": "Jana Bečvářová",
            "gender": "Female",
            "position": "Setter",
            "years_active": 12,  # 2012-2024
            "national_team": "Czech Republic",
            "club_team": "VK Prostějov, Imoco Volley Conegliano",
            "international_matches_played": 160,
            "international_matches_won": 140,
            "international_matches_lost": 20,
            "international_matches_drawn": 0,
            "international_goals_scored": 400,
            "international_assists": 450,
            "international_blocks": 250,
            "international_digs": 300,
            "international_serves_aces": 120,
            "international_serves_errors": 20,
            "international_attack_percentage": 0.50,
            "club_matches_played": 260,
            "club_matches_won": 240,
            "club_matches_lost": 20,
            "club_matches_drawn": 0,
            "club_kills": 700,
            "club_attacks": 1600,
            "club_blocks": 300,
            "club_digs": 400,
            "club_serves_aces": 130,
            "club_serves_errors": 25,
            "club_attack_percentage": 0.50,
            "total_medals_won": 5,
            "world_championship_titles": 1,
            "olympic_medals": 1,  # 1 Bronze
            "best_player_awards": 2,
            "mvp_awards": 1,
            "best_spiker_awards": 0,
            "best_server_awards": 1,
            "best_blocker_awards": 1,
            "best_digger_awards": 1,
            "best_setter_awards": 2,
            "hall_of_fame_inducted": 0,
            "career_earnings_million_usd": 3.0,
            "total_trophies_won": 8,
            "kill_success_rate": 0.45,
            "serve_efficiency": 0.78,
            "block_success_rate": 0.68,
            "dig_success_rate": 0.73,
            "reception_accuracy_percent": 88.0,
            "attack_efficiency": 0.50,
            "serve_receive_efficiency": 0.78,
            "overall_performance_score": 80.0,
        },
        # 30) Karch Kiraly (Duplicate Removed)
        # 30) Monica De Gennaro (Duplicate Removed)
        # 30) Hannah Alker (Duplicate Removed)
        # 30) Monica De Gennaro (Duplicate Removed)
        # 30) Monica De Gennaro (Duplicate Removed)
        # 30) Monica De Gennaro (Duplicate Removed)
        # 30) Elena Cosma (Duplicate Removed)
        # 30) Monica De Gennaro (Duplicate Removed)
        # 30) Monica De Gennaro (Duplicate Removed)
        # 30) Elena Cosma (Duplicate Removed)
        # 30) Monica De Gennaro (Duplicate Removed)
        # 30) Jana Bečvářová (Duplicate Removed)
        # 30) Samantha Bricio (Duplicate Removed)
        # To reach 30, add one more unique player:
        # 30) Fabiana Claudino (Brazil, Female)
        {
            "player_name": "Fabiana Claudino",
            "gender": "Female",
            "position": "Middle Blocker",
            "years_active": 14,  # 2010-2024
            "national_team": "Brazil",
            "club_team": "Hisamitsu Springs, Eczacıbaşı Dynavit",
            "international_matches_played": 200,
            "international_matches_won": 180,
            "international_matches_lost": 20,
            "international_matches_drawn": 0,
            "international_goals_scored": 900,
            "international_assists": 200,
            "international_blocks": 800,
            "international_digs": 300,
            "international_serves_aces": 250,
            "international_serves_errors": 35,
            "international_attack_percentage": 0.65,
            "club_matches_played": 300,
            "club_matches_won": 270,
            "club_matches_lost": 30,
            "club_matches_drawn": 0,
            "club_kills": 1600,
            "club_attacks": 3000,
            "club_blocks": 800,
            "club_digs": 400,
            "club_serves_aces": 250,
            "club_serves_errors": 40,
            "club_attack_percentage": 0.65,
            "total_medals_won": 8,
            "world_championship_titles": 2,
            "olympic_medals": 3,  # 2 Gold, 1 Bronze
            "best_player_awards": 5,
            "mvp_awards": 4,
            "best_spiker_awards": 3,
            "best_server_awards": 2,
            "best_blocker_awards": 3,
            "best_digger_awards": 1,
            "best_setter_awards": 0,
            "hall_of_fame_inducted": 1,
            "career_earnings_million_usd": 5.5,
            "total_trophies_won": 18,
            "kill_success_rate": 0.55,
            "serve_efficiency": 0.85,
            "block_success_rate": 0.75,
            "dig_success_rate": 0.73,
            "reception_accuracy_percent": 89.0,
            "attack_efficiency": 0.65,
            "serve_receive_efficiency": 0.85,
            "overall_performance_score": 89.0,
        },
    ]

    # Confirm we have exactly 30 players
    if len(players_data) != 30:
        raise ValueError(f"Expected 30 volleyball players, got {len(players_data)}")

    # ----------------------- WRITE TO CSV -----------------------
    with open(filename, mode="w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=headers)
        writer.writeheader()
        for pdata in players_data:
            # Fill missing fields with 0 if needed
            for h in headers:
                if h not in pdata:
                    pdata[h] = 0
            writer.writerow(pdata)

if __name__ == "__main__":
    create_volleyball_dataset()
    print("volleyball_dataset.csv has been created with 30 players (41+ columns each).")
