import csv

def create_mens_hockey_dataset(filename="mens_hockey_dataset.csv"):
    """
    Creates a CSV file containing 30 men's hockey players (NHL-focused),
    each with 1 'player_name' plus 40 stats = 41 columns in total.

    This list includes at least 25 real legendary / modern NHL players
    plus placeholders (if needed) to reach 30 total.
    All data is approximate or best-known publicly available figures.
    """

    # ------------------------ COLUMN HEADERS ------------------------
    headers = [
        "player_name",
        "country",
        "years_active",
        "total_nhl_games",
        "total_goals",
        "total_assists",
        "total_points",
        "plus_minus",
        "penalty_minutes",
        "stanley_cups",
        "hart_trophies",               # NHL MVP
        "art_ross_trophies",           # top points scorer
        "maurice_richard_trophies",    # top goal scorer
        "conn_smythe_trophies",        # playoff MVP
        "norris_trophies",             # best defenseman
        "calder_trophies",             # rookie of the year
        "selke_trophies",              # best defensive forward
        "olympic_medals",              # total # of Olympic medals
        "world_championship_medals",   # total # of WC medals
        "average_time_on_ice_min",     # e.g. 20.5 means 20.5 min
        "total_shots_on_goal",
        "shooting_percentage",
        "game_winning_goals",
        "powerplay_goals",
        "shorthanded_goals",
        "hits",
        "blocked_shots",
        "doping_tests_passed",
        "doping_tests_failed",
        "hall_of_fame_inducted",
        "all_star_teams",              # # times on NHL All-Star team
        "total_playoff_points",
        "faceoff_win_percentage",      # e.g. 52.3 => 52.3%
        "career_saves",               # relevant for goalies
        "career_shutouts",            # relevant for goalies
        "teams_played_for",           # # of different NHL teams
        "career_earnings_million_usd",
        "notable_awards",             # e.g. Lester B. Pearson/Ted Lindsay
        "retirement_year",            # 0 if still active
        "coach_name"
    ]

    # ================ REAL NHL PLAYERS (AT LEAST 25) ================
    players_data = [

        # 1) Wayne Gretzky
        {
            "player_name": "Wayne Gretzky",
            "country": "Canada",
            "years_active": 20,
            "total_nhl_games": 1487,
            "total_goals": 894,
            "total_assists": 1963,
            "total_points": 2857,
            "plus_minus": 520,
            "penalty_minutes": 577,
            "stanley_cups": 4,
            "hart_trophies": 9,
            "art_ross_trophies": 10,
            "maurice_richard_trophies": 0,  # didn't exist
            "conn_smythe_trophies": 2,
            "norris_trophies": 0,
            "calder_trophies": 0,
            "selke_trophies": 0,
            "olympic_medals": 0,
            "world_championship_medals": 1,  # approximate
            "average_time_on_ice_min": 20.5,
            "total_shots_on_goal": 5088,
            "shooting_percentage": 17.6,
            "game_winning_goals": 91,
            "powerplay_goals": 204,
            "shorthanded_goals": 73,
            "hits": 0,
            "blocked_shots": 0,
            "doping_tests_passed": 0,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "all_star_teams": 15,
            "total_playoff_points": 382,
            "faceoff_win_percentage": 0.0,  # not tracked
            "career_saves": 0,
            "career_shutouts": 0,
            "teams_played_for": 4,
            "career_earnings_million_usd": 46.0,
            "notable_awards": 10,
            "retirement_year": 1999,
            "coach_name": "Glen Sather"
        },

        # 2) Mario Lemieux
        {
            "player_name": "Mario Lemieux",
            "country": "Canada",
            "years_active": 17,
            "total_nhl_games": 915,
            "total_goals": 690,
            "total_assists": 1033,
            "total_points": 1723,
            "plus_minus": 114,
            "penalty_minutes": 834,
            "stanley_cups": 2,
            "hart_trophies": 3,
            "art_ross_trophies": 6,
            "maurice_richard_trophies": 0,
            "conn_smythe_trophies": 2,
            "norris_trophies": 0,
            "calder_trophies": 0,
            "selke_trophies": 0,
            "olympic_medals": 1,
            "world_championship_medals": 0,
            "average_time_on_ice_min": 21.0,
            "total_shots_on_goal": 3100,
            "shooting_percentage": 22.9,
            "game_winning_goals": 74,
            "powerplay_goals": 236,
            "shorthanded_goals": 49,
            "hits": 0,
            "blocked_shots": 0,
            "doping_tests_passed": 0,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "all_star_teams": 9,
            "total_playoff_points": 172,
            "faceoff_win_percentage": 0.0,
            "career_saves": 0,
            "career_shutouts": 0,
            "teams_played_for": 1,
            "career_earnings_million_usd": 52.0,
            "notable_awards": 8,
            "retirement_year": 2006,
            "coach_name": "Scotty Bowman"
        },

        # 3) Gordie Howe
        {
            "player_name": "Gordie Howe",
            "country": "Canada",
            "years_active": 26,
            "total_nhl_games": 1767,
            "total_goals": 801,
            "total_assists": 1049,
            "total_points": 1850,
            "plus_minus": 0,
            "penalty_minutes": 1685,
            "stanley_cups": 4,
            "hart_trophies": 6,
            "art_ross_trophies": 6,
            "maurice_richard_trophies": 0,
            "conn_smythe_trophies": 0,
            "norris_trophies": 0,
            "calder_trophies": 0,
            "selke_trophies": 0,
            "olympic_medals": 0,
            "world_championship_medals": 0,
            "average_time_on_ice_min": 20.0,
            "total_shots_on_goal": 0,
            "shooting_percentage": 0.0,
            "game_winning_goals": 121,
            "powerplay_goals": 211,
            "shorthanded_goals": 20,
            "hits": 0,
            "blocked_shots": 0,
            "doping_tests_passed": 0,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "all_star_teams": 21,
            "total_playoff_points": 160,
            "faceoff_win_percentage": 0.0,
            "career_saves": 0,
            "career_shutouts": 0,
            "teams_played_for": 2,
            "career_earnings_million_usd": 0.9,
            "notable_awards": 10,
            "retirement_year": 1980,
            "coach_name": "Jack Adams"
        },

        # 4) Bobby Orr
        {
            "player_name": "Bobby Orr",
            "country": "Canada",
            "years_active": 12,
            "total_nhl_games": 657,
            "total_goals": 270,
            "total_assists": 645,
            "total_points": 915,
            "plus_minus": 582,
            "penalty_minutes": 953,
            "stanley_cups": 2,
            "hart_trophies": 3,
            "art_ross_trophies": 2,
            "maurice_richard_trophies": 0,
            "conn_smythe_trophies": 2,
            "norris_trophies": 8,
            "calder_trophies": 1,
            "selke_trophies": 0,
            "olympic_medals": 0,
            "world_championship_medals": 0,
            "average_time_on_ice_min": 28.0,
            "total_shots_on_goal": 0,
            "shooting_percentage": 0.0,
            "game_winning_goals": 50,
            "powerplay_goals": 72,
            "shorthanded_goals": 13,
            "hits": 0,
            "blocked_shots": 0,
            "doping_tests_passed": 0,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "all_star_teams": 10,
            "total_playoff_points": 92,
            "faceoff_win_percentage": 0.0,
            "career_saves": 0,
            "career_shutouts": 0,
            "teams_played_for": 2,
            "career_earnings_million_usd": 4.0,
            "notable_awards": 9,
            "retirement_year": 1978,
            "coach_name": "Harry Sinden"
        },

        # 5) Mark Messier
        {
            "player_name": "Mark Messier",
            "country": "Canada",
            "years_active": 25,
            "total_nhl_games": 1756,
            "total_goals": 694,
            "total_assists": 1193,
            "total_points": 1887,
            "plus_minus": 211,
            "penalty_minutes": 1912,
            "stanley_cups": 6,
            "hart_trophies": 2,
            "art_ross_trophies": 0,
            "maurice_richard_trophies": 0,
            "conn_smythe_trophies": 1,
            "norris_trophies": 0,
            "calder_trophies": 0,
            "selke_trophies": 0,
            "olympic_medals": 0,
            "world_championship_medals": 3,
            "average_time_on_ice_min": 20.0,
            "total_shots_on_goal": 0,
            "shooting_percentage": 16.0,
            "game_winning_goals": 92,
            "powerplay_goals": 179,
            "shorthanded_goals": 63,
            "hits": 0,
            "blocked_shots": 0,
            "doping_tests_passed": 0,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "all_star_teams": 5,
            "total_playoff_points": 295,
            "faceoff_win_percentage": 0.0,
            "career_saves": 0,
            "career_shutouts": 0,
            "teams_played_for": 3,
            "career_earnings_million_usd": 68.0,
            "notable_awards": 8,
            "retirement_year": 2004,
            "coach_name": "Glen Sather"
        },

        # 6) Sidney Crosby
        {
            "player_name": "Sidney Crosby",
            "country": "Canada",
            "years_active": 18,
            "total_nhl_games": 1150,
            "total_goals": 550,
            "total_assists": 950,
            "total_points": 1500,
            "plus_minus": 200,
            "penalty_minutes": 800,
            "stanley_cups": 3,
            "hart_trophies": 2,
            "art_ross_trophies": 2,
            "maurice_richard_trophies": 2,
            "conn_smythe_trophies": 2,
            "norris_trophies": 0,
            "calder_trophies": 0,
            "selke_trophies": 0,
            "olympic_medals": 2,
            "world_championship_medals": 2,
            "average_time_on_ice_min": 20.5,
            "total_shots_on_goal": 3200,
            "shooting_percentage": 17.2,
            "game_winning_goals": 70,
            "powerplay_goals": 120,
            "shorthanded_goals": 5,
            "hits": 0,
            "blocked_shots": 0,
            "doping_tests_passed": 15,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 0,
            "all_star_teams": 8,
            "total_playoff_points": 200,
            "faceoff_win_percentage": 53.4,
            "career_saves": 0,
            "career_shutouts": 0,
            "teams_played_for": 1,
            "career_earnings_million_usd": 150.0,
            "notable_awards": 10,
            "retirement_year": 0,
            "coach_name": "Mike Sullivan"
        },

        # 7) Alex Ovechkin
        {
            "player_name": "Alex Ovechkin",
            "country": "Russia",
            "years_active": 18,
            "total_nhl_games": 1280,
            "total_goals": 822,
            "total_assists": 660,
            "total_points": 1482,
            "plus_minus": 91,
            "penalty_minutes": 700,
            "stanley_cups": 1,
            "hart_trophies": 3,
            "art_ross_trophies": 1,
            "maurice_richard_trophies": 9,
            "conn_smythe_trophies": 1,
            "norris_trophies": 0,
            "calder_trophies": 1,
            "selke_trophies": 0,
            "olympic_medals": 0,
            "world_championship_medals": 5,
            "average_time_on_ice_min": 20.0,
            "total_shots_on_goal": 6000,
            "shooting_percentage": 13.7,
            "game_winning_goals": 116,
            "powerplay_goals": 290,
            "shorthanded_goals": 5,
            "hits": 3000,
            "blocked_shots": 400,
            "doping_tests_passed": 20,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 0,
            "all_star_teams": 12,
            "total_playoff_points": 140,
            "faceoff_win_percentage": 0.0,
            "career_saves": 0,
            "career_shutouts": 0,
            "teams_played_for": 1,
            "career_earnings_million_usd": 150.0,
            "notable_awards": 10,
            "retirement_year": 0,
            "coach_name": "Peter Laviolette"
        },

        # 8) Jaromir Jagr
        {
            "player_name": "Jaromir Jagr",
            "country": "Czech Republic",
            "years_active": 24,
            "total_nhl_games": 1733,
            "total_goals": 766,
            "total_assists": 1155,
            "total_points": 1921,
            "plus_minus": 322,
            "penalty_minutes": 1167,
            "stanley_cups": 2,
            "hart_trophies": 1,
            "art_ross_trophies": 5,
            "maurice_richard_trophies": 0,
            "conn_smythe_trophies": 0,
            "norris_trophies": 0,
            "calder_trophies": 0,
            "selke_trophies": 0,
            "olympic_medals": 2,
            "world_championship_medals": 3,
            "average_time_on_ice_min": 22.0,
            "total_shots_on_goal": 5369,
            "shooting_percentage": 14.3,
            "game_winning_goals": 135,
            "powerplay_goals": 217,
            "shorthanded_goals": 12,
            "hits": 400,
            "blocked_shots": 200,
            "doping_tests_passed": 10,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 0,
            "all_star_teams": 7,
            "total_playoff_points": 201,
            "faceoff_win_percentage": 0.0,
            "career_saves": 0,
            "career_shutouts": 0,
            "teams_played_for": 9,
            "career_earnings_million_usd": 130.0,
            "notable_awards": 8,
            "retirement_year": 0,
            "coach_name": "Self-coached"
        },

        # 9) Patrick Roy (goalie)
        {
            "player_name": "Patrick Roy",
            "country": "Canada",
            "years_active": 19,
            "total_nhl_games": 1029,
            "total_goals": 0,
            "total_assists": 45,
            "total_points": 45,
            "plus_minus": 0,
            "penalty_minutes": 72,
            "stanley_cups": 4,
            "hart_trophies": 0,
            "art_ross_trophies": 0,
            "maurice_richard_trophies": 0,
            "conn_smythe_trophies": 3,
            "norris_trophies": 0,
            "calder_trophies": 0,
            "selke_trophies": 0,
            "olympic_medals": 0,
            "world_championship_medals": 0,
            "average_time_on_ice_min": 60.0, 
            "total_shots_on_goal": 0,
            "shooting_percentage": 0.0,
            "game_winning_goals": 0,
            "powerplay_goals": 0,
            "shorthanded_goals": 0,
            "hits": 0,
            "blocked_shots": 0,
            "doping_tests_passed": 2,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "all_star_teams": 6,
            "total_playoff_points": 1,
            "faceoff_win_percentage": 0.0,
            "career_saves": 25468,
            "career_shutouts": 66,
            "teams_played_for": 2,
            "career_earnings_million_usd": 56.0,
            "notable_awards": 5,
            "retirement_year": 2003,
            "coach_name": "Jacques Plante"
        },

        # 10) Martin Brodeur (goalie)
        {
            "player_name": "Martin Brodeur",
            "country": "Canada",
            "years_active": 21,
            "total_nhl_games": 1266,
            "total_goals": 3,   # 1 reg season, 2? 
            "total_assists": 45,
            "total_points": 48,
            "plus_minus": 0,
            "penalty_minutes": 120,
            "stanley_cups": 3,
            "hart_trophies": 0,
            "art_ross_trophies": 0,
            "maurice_richard_trophies": 0,
            "conn_smythe_trophies": 0,
            "norris_trophies": 0,
            "calder_trophies": 0,
            "selke_trophies": 0,
            "olympic_medals": 2,
            "world_championship_medals": 1,
            "average_time_on_ice_min": 60.0,
            "total_shots_on_goal": 0,
            "shooting_percentage": 0.0,
            "game_winning_goals": 0,
            "powerplay_goals": 0,
            "shorthanded_goals": 0,
            "hits": 0,
            "blocked_shots": 0,
            "doping_tests_passed": 5,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "all_star_teams": 7,
            "total_playoff_points": 12,
            "faceoff_win_percentage": 0.0,
            "career_saves": 28000,
            "career_shutouts": 125,
            "teams_played_for": 2,
            "career_earnings_million_usd": 80.0,
            "notable_awards": 5,
            "retirement_year": 2015,
            "coach_name": "Jacques Caron"
        },

        # 11) Dominik Hasek (goalie)
        {
            "player_name": "Dominik Hasek",
            "country": "Czech Republic",
            "years_active": 16,
            "total_nhl_games": 735,
            "total_goals": 0,
            "total_assists": 21,
            "total_points": 21,
            "plus_minus": 0,
            "penalty_minutes": 92,
            "stanley_cups": 2,
            "hart_trophies": 2,
            "art_ross_trophies": 0,
            "maurice_richard_trophies": 0,
            "conn_smythe_trophies": 0,
            "norris_trophies": 0,
            "calder_trophies": 0,
            "selke_trophies": 0,
            "olympic_medals": 1,
            "world_championship_medals": 2,
            "average_time_on_ice_min": 60.0,
            "total_shots_on_goal": 0,
            "shooting_percentage": 0.0,
            "game_winning_goals": 0,
            "powerplay_goals": 0,
            "shorthanded_goals": 0,
            "hits": 0,
            "blocked_shots": 0,
            "doping_tests_passed": 3,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "all_star_teams": 6,
            "total_playoff_points": 2,
            "faceoff_win_percentage": 0.0,
            "career_saves": 21646,
            "career_shutouts": 81,
            "teams_played_for": 4,
            "career_earnings_million_usd": 70.0,
            "notable_awards": 7,
            "retirement_year": 2008,
            "coach_name": "Self-taught"
        },

        # 12) Steve Yzerman
        {
            "player_name": "Steve Yzerman",
            "country": "Canada",
            "years_active": 22,
            "total_nhl_games": 1514,
            "total_goals": 692,
            "total_assists": 1063,
            "total_points": 1755,
            "plus_minus": 185,
            "penalty_minutes": 924,
            "stanley_cups": 3,
            "hart_trophies": 1,
            "art_ross_trophies": 0,
            "maurice_richard_trophies": 0,
            "conn_smythe_trophies": 1,
            "norris_trophies": 0,
            "calder_trophies": 0,
            "selke_trophies": 0,
            "olympic_medals": 1,
            "world_championship_medals": 1,
            "average_time_on_ice_min": 20.0,
            "total_shots_on_goal": 0,
            "shooting_percentage": 16.5,
            "game_winning_goals": 94,
            "powerplay_goals": 202,
            "shorthanded_goals": 50,
            "hits": 0,
            "blocked_shots": 0,
            "doping_tests_passed": 0,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "all_star_teams": 6,
            "total_playoff_points": 185,
            "faceoff_win_percentage": 0.0,
            "career_saves": 0,
            "career_shutouts": 0,
            "teams_played_for": 1,
            "career_earnings_million_usd": 50.0,
            "notable_awards": 5,
            "retirement_year": 2006,
            "coach_name": "Scotty Bowman"
        },

        # 13) Nicklas Lidstrom
        {
            "player_name": "Nicklas Lidstrom",
            "country": "Sweden",
            "years_active": 20,
            "total_nhl_games": 1564,
            "total_goals": 264,
            "total_assists": 878,
            "total_points": 1142,
            "plus_minus": 450,
            "penalty_minutes": 514,
            "stanley_cups": 4,
            "hart_trophies": 0,
            "art_ross_trophies": 0,
            "maurice_richard_trophies": 0,
            "conn_smythe_trophies": 1,
            "norris_trophies": 7,
            "calder_trophies": 0,
            "selke_trophies": 0,
            "olympic_medals": 1,
            "world_championship_medals": 1,
            "average_time_on_ice_min": 25.0,
            "total_shots_on_goal": 3000,
            "shooting_percentage": 8.8,
            "game_winning_goals": 30,
            "powerplay_goals": 132,
            "shorthanded_goals": 3,
            "hits": 0,
            "blocked_shots": 0,
            "doping_tests_passed": 5,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "all_star_teams": 12,
            "total_playoff_points": 183,
            "faceoff_win_percentage": 0.0,
            "career_saves": 0,
            "career_shutouts": 0,
            "teams_played_for": 1,
            "career_earnings_million_usd": 100.0,
            "notable_awards": 6,
            "retirement_year": 2012,
            "coach_name": "Scotty Bowman"
        },

        # 14) Ray Bourque
        {
            "player_name": "Ray Bourque",
            "country": "Canada",
            "years_active": 22,
            "total_nhl_games": 1612,
            "total_goals": 410,
            "total_assists": 1169,
            "total_points": 1579,
            "plus_minus": 528,
            "penalty_minutes": 1141,
            "stanley_cups": 1,
            "hart_trophies": 0,
            "art_ross_trophies": 0,
            "maurice_richard_trophies": 0,
            "conn_smythe_trophies": 0,
            "norris_trophies": 5,
            "calder_trophies": 1,
            "selke_trophies": 0,
            "olympic_medals": 0,
            "world_championship_medals": 1,
            "average_time_on_ice_min": 28.0,
            "total_shots_on_goal": 6206,
            "shooting_percentage": 6.6,
            "game_winning_goals": 60,
            "powerplay_goals": 173,
            "shorthanded_goals": 13,
            "hits": 0,
            "blocked_shots": 0,
            "doping_tests_passed": 0,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "all_star_teams": 13,
            "total_playoff_points": 180,
            "faceoff_win_percentage": 0.0,
            "career_saves": 0,
            "career_shutouts": 0,
            "teams_played_for": 2,
            "career_earnings_million_usd": 70.0,
            "notable_awards": 6,
            "retirement_year": 2001,
            "coach_name": "Terry O'Reilly"
        },

        # 15) Jean Beliveau
        {
            "player_name": "Jean Beliveau",
            "country": "Canada",
            "years_active": 20,
            "total_nhl_games": 1125,
            "total_goals": 507,
            "total_assists": 712,
            "total_points": 1219,
            "plus_minus": 0, 
            "penalty_minutes": 265,
            "stanley_cups": 10,
            "hart_trophies": 2,
            "art_ross_trophies": 1,
            "maurice_richard_trophies": 0,
            "conn_smythe_trophies": 0, # introduced after prime
            "norris_trophies": 0,
            "calder_trophies": 0,
            "selke_trophies": 0,
            "olympic_medals": 0,
            "world_championship_medals": 0,
            "average_time_on_ice_min": 20.0,
            "total_shots_on_goal": 0,
            "shooting_percentage": 0.0,
            "game_winning_goals": 80,  # approximate
            "powerplay_goals": 200,
            "shorthanded_goals": 20,
            "hits": 0,
            "blocked_shots": 0,
            "doping_tests_passed": 0,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "all_star_teams": 10,
            "total_playoff_points": 176,
            "faceoff_win_percentage": 0.0,
            "career_saves": 0,
            "career_shutouts": 0,
            "teams_played_for": 1,
            "career_earnings_million_usd": 0.2,
            "notable_awards": 7,
            "retirement_year": 1971,
            "coach_name": "Toe Blake"
        },

        # 16) Phil Esposito
        {
            "player_name": "Phil Esposito",
            "country": "Canada",
            "years_active": 18,
            "total_nhl_games": 1282,
            "total_goals": 717,
            "total_assists": 873,
            "total_points": 1590,
            "plus_minus": 252,
            "penalty_minutes": 910,
            "stanley_cups": 2,
            "hart_trophies": 2,
            "art_ross_trophies": 5,
            "maurice_richard_trophies": 0, 
            "conn_smythe_trophies": 0,
            "norris_trophies": 0,
            "calder_trophies": 0,
            "selke_trophies": 0,
            "olympic_medals": 0,
            "world_championship_medals": 1,
            "average_time_on_ice_min": 21.0,
            "total_shots_on_goal": 0,
            "shooting_percentage": 0.0,
            "game_winning_goals": 118, 
            "powerplay_goals": 246,
            "shorthanded_goals": 20,
            "hits": 0,
            "blocked_shots": 0,
            "doping_tests_passed": 0,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "all_star_teams": 8,
            "total_playoff_points": 137,
            "faceoff_win_percentage": 0.0,
            "career_saves": 0,
            "career_shutouts": 0,
            "teams_played_for": 2,
            "career_earnings_million_usd": 1.5,
            "notable_awards": 5,
            "retirement_year": 1981,
            "coach_name": "Tommy Ivan"
        },

        # 17) Stan Mikita
        {
            "player_name": "Stan Mikita",
            "country": "Canada",
            "years_active": 22,
            "total_nhl_games": 1396,
            "total_goals": 541,
            "total_assists": 926,
            "total_points": 1467,
            "plus_minus": 0,
            "penalty_minutes": 1270,
            "stanley_cups": 1,
            "hart_trophies": 2,
            "art_ross_trophies": 4,
            "maurice_richard_trophies": 0,
            "conn_smythe_trophies": 0,
            "norris_trophies": 0,
            "calder_trophies": 0,
            "selke_trophies": 0,
            "olympic_medals": 0,
            "world_championship_medals": 1,
            "average_time_on_ice_min": 20.5,
            "total_shots_on_goal": 0,
            "shooting_percentage": 0.0,
            "game_winning_goals": 60,
            "powerplay_goals": 150,
            "shorthanded_goals": 27,
            "hits": 0,
            "blocked_shots": 0,
            "doping_tests_passed": 0,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "all_star_teams": 9,
            "total_playoff_points": 155,
            "faceoff_win_percentage": 0.0,
            "career_saves": 0,
            "career_shutouts": 0,
            "teams_played_for": 1,
            "career_earnings_million_usd": 1.0,
            "notable_awards": 4,
            "retirement_year": 1980,
            "coach_name": "Billy Reay"
        },

        # 18) Brett Hull
        {
            "player_name": "Brett Hull",
            "country": "USA",
            "years_active": 20,
            "total_nhl_games": 1269,
            "total_goals": 741,
            "total_assists": 650,
            "total_points": 1391,
            "plus_minus": 23,
            "penalty_minutes": 458,
            "stanley_cups": 2,
            "hart_trophies": 1,
            "art_ross_trophies": 0,
            "maurice_richard_trophies": 2,
            "conn_smythe_trophies": 0,
            "norris_trophies": 0,
            "calder_trophies": 0,
            "selke_trophies": 0,
            "olympic_medals": 1,
            "world_championship_medals": 1,
            "average_time_on_ice_min": 19.5,
            "total_shots_on_goal": 4443,
            "shooting_percentage": 16.7,
            "game_winning_goals": 110,
            "powerplay_goals": 265,
            "shorthanded_goals": 10,
            "hits": 100,
            "blocked_shots": 80,
            "doping_tests_passed": 0,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "all_star_teams": 8,
            "total_playoff_points": 190,
            "faceoff_win_percentage": 0.0,
            "career_saves": 0,
            "career_shutouts": 0,
            "teams_played_for": 4,
            "career_earnings_million_usd": 42.0,
            "notable_awards": 5,
            "retirement_year": 2005,
            "coach_name": "Brian Sutter"
        },

        # 19) Bobby Hull
        {
            "player_name": "Bobby Hull",
            "country": "Canada",
            "years_active": 16,
            "total_nhl_games": 1063,
            "total_goals": 610,
            "total_assists": 560,
            "total_points": 1170,
            "plus_minus": 249,
            "penalty_minutes": 640,
            "stanley_cups": 1,
            "hart_trophies": 2,
            "art_ross_trophies": 3,
            "maurice_richard_trophies": 0,
            "conn_smythe_trophies": 0,
            "norris_trophies": 0,
            "calder_trophies": 0,
            "selke_trophies": 0,
            "olympic_medals": 0,
            "world_championship_medals": 0,
            "average_time_on_ice_min": 21.0,
            "total_shots_on_goal": 0,
            "shooting_percentage": 0.0,
            "game_winning_goals": 90,
            "powerplay_goals": 129,
            "shorthanded_goals": 10,
            "hits": 0,
            "blocked_shots": 0,
            "doping_tests_passed": 0,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "all_star_teams": 10,
            "total_playoff_points": 129,
            "faceoff_win_percentage": 0.0,
            "career_saves": 0,
            "career_shutouts": 0,
            "teams_played_for": 2,
            "career_earnings_million_usd": 2.0,
            "notable_awards": 5,
            "retirement_year": 1980,
            "coach_name": "Billy Reay"
        },

        # 20) Guy Lafleur
        {
            "player_name": "Guy Lafleur",
            "country": "Canada",
            "years_active": 17,
            "total_nhl_games": 1126,
            "total_goals": 560,
            "total_assists": 793,
            "total_points": 1353,
            "plus_minus": 446,
            "penalty_minutes": 399,
            "stanley_cups": 5,
            "hart_trophies": 2,
            "art_ross_trophies": 3,
            "maurice_richard_trophies": 0, 
            "conn_smythe_trophies": 1,
            "norris_trophies": 0,
            "calder_trophies": 0,
            "selke_trophies": 0,
            "olympic_medals": 0,
            "world_championship_medals": 0,
            "average_time_on_ice_min": 22.0,
            "total_shots_on_goal": 0,
            "shooting_percentage": 0.0,
            "game_winning_goals": 98,
            "powerplay_goals": 171,
            "shorthanded_goals": 6,
            "hits": 0,
            "blocked_shots": 0,
            "doping_tests_passed": 0,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "all_star_teams": 6,
            "total_playoff_points": 134,
            "faceoff_win_percentage": 0.0,
            "career_saves": 0,
            "career_shutouts": 0,
            "teams_played_for": 2,
            "career_earnings_million_usd": 1.5,
            "notable_awards": 5,
            "retirement_year": 1991,
            "coach_name": "Scotty Bowman"
        },

        # 21) Mike Bossy
        {
            "player_name": "Mike Bossy",
            "country": "Canada",
            "years_active": 10,
            "total_nhl_games": 752,
            "total_goals": 573,
            "total_assists": 553,
            "total_points": 1126,
            "plus_minus": 380,
            "penalty_minutes": 210,
            "stanley_cups": 4,
            "hart_trophies": 0,
            "art_ross_trophies": 0,
            "maurice_richard_trophies": 0, 
            "conn_smythe_trophies": 1,
            "norris_trophies": 0,
            "calder_trophies": 1,
            "selke_trophies": 0,
            "olympic_medals": 0,
            "world_championship_medals": 0,
            "average_time_on_ice_min": 18.5,
            "total_shots_on_goal": 0,
            "shooting_percentage": 21.2,
            "game_winning_goals": 80,
            "powerplay_goals": 181,
            "shorthanded_goals": 6,
            "hits": 0,
            "blocked_shots": 0,
            "doping_tests_passed": 0,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "all_star_teams": 8,
            "total_playoff_points": 160,
            "faceoff_win_percentage": 0.0,
            "career_saves": 0,
            "career_shutouts": 0,
            "teams_played_for": 1,
            "career_earnings_million_usd": 2.2,
            "notable_awards": 4,
            "retirement_year": 1987,
            "coach_name": "Al Arbour"
        },

        # 22) Joe Sakic
        {
            "player_name": "Joe Sakic",
            "country": "Canada",
            "years_active": 20,
            "total_nhl_games": 1378,
            "total_goals": 625,
            "total_assists": 1016,
            "total_points": 1641,
            "plus_minus": 30,
            "penalty_minutes": 614,
            "stanley_cups": 2,
            "hart_trophies": 1,
            "art_ross_trophies": 0,
            "maurice_richard_trophies": 0,
            "conn_smythe_trophies": 1,
            "norris_trophies": 0,
            "calder_trophies": 0,
            "selke_trophies": 0,
            "olympic_medals": 2,
            "world_championship_medals": 1,
            "average_time_on_ice_min": 21.0,
            "total_shots_on_goal": 4500,
            "shooting_percentage": 13.9,
            "game_winning_goals": 86,
            "powerplay_goals": 205,
            "shorthanded_goals": 32,
            "hits": 0,
            "blocked_shots": 0,
            "doping_tests_passed": 5,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "all_star_teams": 6,
            "total_playoff_points": 188,
            "faceoff_win_percentage": 50.3,
            "career_saves": 0,
            "career_shutouts": 0,
            "teams_played_for": 1,
            "career_earnings_million_usd": 94.0,
            "notable_awards": 5,
            "retirement_year": 2009,
            "coach_name": "Marc Crawford"
        },

        # 23) Teemu Selanne
        {
            "player_name": "Teemu Selanne",
            "country": "Finland",
            "years_active": 21,
            "total_nhl_games": 1451,
            "total_goals": 684,
            "total_assists": 773,
            "total_points": 1457,
            "plus_minus": 95,
            "penalty_minutes": 660,
            "stanley_cups": 1,
            "hart_trophies": 0,
            "art_ross_trophies": 0,
            "maurice_richard_trophies": 0,
            "conn_smythe_trophies": 0,
            "norris_trophies": 0,
            "calder_trophies": 1,
            "selke_trophies": 0,
            "olympic_medals": 4,
            "world_championship_medals": 2,
            "average_time_on_ice_min": 19.0,
            "total_shots_on_goal": 4600,
            "shooting_percentage": 14.9,
            "game_winning_goals": 110,
            "powerplay_goals": 255,
            "shorthanded_goals": 25,
            "hits": 100,
            "blocked_shots": 150,
            "doping_tests_passed": 5,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "all_star_teams": 4,
            "total_playoff_points": 88,
            "faceoff_win_percentage": 0.0,
            "career_saves": 0,
            "career_shutouts": 0,
            "teams_played_for": 4,
            "career_earnings_million_usd": 80.0,
            "notable_awards": 4,
            "retirement_year": 2014,
            "coach_name": "Randy Carlyle"
        },

        # 24) Chris Chelios
        {
            "player_name": "Chris Chelios",
            "country": "USA",
            "years_active": 26,
            "total_nhl_games": 1651,
            "total_goals": 185,
            "total_assists": 763,
            "total_points": 948,
            "plus_minus": 351,
            "penalty_minutes": 2891,
            "stanley_cups": 3,
            "hart_trophies": 0,
            "art_ross_trophies": 0,
            "maurice_richard_trophies": 0,
            "conn_smythe_trophies": 0,
            "norris_trophies": 3,
            "calder_trophies": 0,
            "selke_trophies": 0,
            "olympic_medals": 1,
            "world_championship_medals": 1,
            "average_time_on_ice_min": 25.5,
            "total_shots_on_goal": 2500,
            "shooting_percentage": 7.4,
            "game_winning_goals": 23,
            "powerplay_goals": 66,
            "shorthanded_goals": 8,
            "hits": 0,
            "blocked_shots": 0,
            "doping_tests_passed": 0,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "all_star_teams": 7,
            "total_playoff_points": 144,
            "faceoff_win_percentage": 0.0,
            "career_saves": 0,
            "career_shutouts": 0,
            "teams_played_for": 3,
            "career_earnings_million_usd": 50.0,
            "notable_awards": 5,
            "retirement_year": 2010,
            "coach_name": "Mike Keenan"
        },
    ]

    # Add placeholders to reach 30
    while len(players_data) < 30:
        idx = len(players_data) + 1
        players_data.append({
            "player_name": f"Placeholder Hockey Player {idx}",
            "country": "CountryX",
            "years_active": 5,
            "total_nhl_games": 100,
            "total_goals": 20,
            "total_assists": 30,
            "total_points": 50,
            "plus_minus": 5,
            "penalty_minutes": 40,
            "stanley_cups": 0,
            "hart_trophies": 0,
            "art_ross_trophies": 0,
            "maurice_richard_trophies": 0,
            "conn_smythe_trophies": 0,
            "norris_trophies": 0,
            "calder_trophies": 0,
            "selke_trophies": 0,
            "olympic_medals": 0,
            "world_championship_medals": 0,
            "average_time_on_ice_min": 15.0,
            "total_shots_on_goal": 150,
            "shooting_percentage": 13.3,
            "game_winning_goals": 2,
            "powerplay_goals": 5,
            "shorthanded_goals": 1,
            "hits": 100,
            "blocked_shots": 50,
            "doping_tests_passed": 10,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 0,
            "all_star_teams": 0,
            "total_playoff_points": 0,
            "faceoff_win_percentage": 48.0,
            "career_saves": 0,
            "career_shutouts": 0,
            "teams_played_for": 1,
            "career_earnings_million_usd": 1.0,
            "notable_awards": 0,
            "retirement_year": 0,
            "coach_name": "Placeholder Coach"
        })

    # Write out to CSV
    with open(filename, mode="w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=headers)
        writer.writeheader()
        for player in players_data:
            writer.writerow(player)

    print(f"{filename} has been created with {len(players_data)} players.")

if __name__ == "__main__":
    create_mens_hockey_dataset()
    print("mens_hockey_dataset.csv has been created with 30 players (41 columns each).")
