import csv

def create_womens_boxing_dataset(filename="womens_boxing_dataset.csv"):
    """
    Creates a CSV file containing 30 women's boxers (player_name + 40 stats = 41 columns).
    Stats are best-effort approximations, intended for demonstration and for building
    a 'Women's Boxing Index Score' in Step 2.
    """

    # Define the header (41 columns total)
    headers = [
        "player_name",
        "country",
        "weight_class",
        "stance",
        "years_active",
        "total_fights",
        "wins",
        "losses",
        "draws",
        "kos",  # knockout wins
        "ko_percentage",
        "world_titles_held",       # total # of recognized belts ever held
        "undisputed_titles",       # # of times undisputed champion
        "lineal_titles",           # # of lineal championships
        "ring_magazine_titles",    # # times recognized by The Ring
        "peak_p4p_ranking",        # best pound-for-pound rank
        "signature_win",           # # of widely recognized signature wins
        "major_upset_wins",        # # fights won as underdog
        "title_defenses",          # total # times defended any belt
        "unified_title_defenses",  # # times defended unified or undisputed
        "avg_punches_landed_per_round",
        "avg_punches_thrown_per_round",
        "knockdowns_scored",
        "knockdowns_received",
        "height_cm",
        "reach_cm",
        "age_at_debut",
        "fights_in_hometown",
        "doping_tests_passed",
        "doping_tests_failed",
        "hall_of_fame_inducted",
        "major_awards",            # e.g. BWAA fighter of the year, etc.
        "years_as_champion",       # total # of years held a recognized belt
        "notable_rivalries",       # # of big rivalry fights
        "avg_attendance_events",    # approximate average attendance
        "ppv_buys_millions",        # approximate total PPV buys
        "longest_win_streak",
        "earliest_round_ko",       # earliest round in which she KO'd an opponent
        "career_earnings_million_usd",
        "retirement_year",          # 0 if still active
        "trainer_name"
    ]

    # A list of the top 30 female boxers, each dict has 41 fields.
    # The data below is best-effort from public knowledge or approximations.
    players_data = [
        {
            "player_name": "Katie Taylor",
            "country": "Ireland",
            "weight_class": "Lightweight",
            "stance": "Orthodox",
            "years_active": 7,
            "total_fights": 23,
            "wins": 23,
            "losses": 0,
            "draws": 0,
            "kos": 6,
            "ko_percentage": 26.1,
            "world_titles_held": 4,
            "undisputed_titles": 2,  
            "lineal_titles": 1,
            "ring_magazine_titles": 1,
            "peak_p4p_ranking": 1,
            "signature_win": 3,
            "major_upset_wins": 1,
            "title_defenses": 14,
            "unified_title_defenses": 6,
            "avg_punches_landed_per_round": 14.2,
            "avg_punches_thrown_per_round": 45.0,
            "knockdowns_scored": 4,
            "knockdowns_received": 0,
            "height_cm": 165,
            "reach_cm": 66,
            "age_at_debut": 30,
            "fights_in_hometown": 2,
            "doping_tests_passed": 40,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 0,
            "major_awards": 3,  # e.g. BWAA Female fighter of the year, etc.
            "years_as_champion": 5,
            "notable_rivalries": 2,
            "avg_attendance_events": 8000,
            "ppv_buys_millions": 0.6,
            "longest_win_streak": 23,
            "earliest_round_ko": 1,
            "career_earnings_million_usd": 5.0,
            "retirement_year": 0,  # still active
            "trainer_name": "Ross Enamait"
        },
        {
            "player_name": "Claressa Shields",
            "country": "USA",
            "weight_class": "Middleweight",
            "stance": "Orthodox",
            "years_active": 6,
            "total_fights": 14,
            "wins": 14,
            "losses": 0,
            "draws": 0,
            "kos": 2,
            "ko_percentage": 14.3,
            "world_titles_held": 7,  
            "undisputed_titles": 3,  
            "lineal_titles": 1,
            "ring_magazine_titles": 1,
            "peak_p4p_ranking": 1,
            "signature_win": 4,
            "major_upset_wins": 1,
            "title_defenses": 12,
            "unified_title_defenses": 5,
            "avg_punches_landed_per_round": 15.0,
            "avg_punches_thrown_per_round": 48.0,
            "knockdowns_scored": 5,
            "knockdowns_received": 0,
            "height_cm": 173,
            "reach_cm": 68,
            "age_at_debut": 21,
            "fights_in_hometown": 3,
            "doping_tests_passed": 35,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 0,
            "major_awards": 4,  
            "years_as_champion": 5,
            "notable_rivalries": 2,
            "avg_attendance_events": 4000,
            "ppv_buys_millions": 0.3,
            "longest_win_streak": 14,
            "earliest_round_ko": 1,
            "career_earnings_million_usd": 3.5,
            "retirement_year": 0,
            "trainer_name": "John David Jackson"
        },
        {
            "player_name": "Amanda Serrano",
            "country": "Puerto Rico",
            "weight_class": "Featherweight",
            "stance": "Southpaw",
            "years_active": 13,
            "total_fights": 47,
            "wins": 44,
            "losses": 2,
            "draws": 1,
            "kos": 30,
            "ko_percentage": 63.8,
            "world_titles_held": 9,
            "undisputed_titles": 1,
            "lineal_titles": 1,
            "ring_magazine_titles": 1,
            "peak_p4p_ranking": 2,
            "signature_win": 5,
            "major_upset_wins": 1,
            "title_defenses": 15,
            "unified_title_defenses": 3,
            "avg_punches_landed_per_round": 16.5,
            "avg_punches_thrown_per_round": 52.0,
            "knockdowns_scored": 12,
            "knockdowns_received": 1,
            "height_cm": 166,
            "reach_cm": 65,
            "age_at_debut": 21,
            "fights_in_hometown": 7,
            "doping_tests_passed": 60,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 0,
            "major_awards": 2,
            "years_as_champion": 7,
            "notable_rivalries": 2,
            "avg_attendance_events": 6000,
            "ppv_buys_millions": 0.4,
            "longest_win_streak": 16,
            "earliest_round_ko": 1,
            "career_earnings_million_usd": 2.2,
            "retirement_year": 0,
            "trainer_name": "Jordan Maldonado"
        },
        {
            "player_name": "Laila Ali",
            "country": "USA",
            "weight_class": "Super Middleweight",
            "stance": "Orthodox",
            "years_active": 8,
            "total_fights": 24,
            "wins": 24,
            "losses": 0,
            "draws": 0,
            "kos": 21,
            "ko_percentage": 87.5,
            "world_titles_held": 5,
            "undisputed_titles": 0,
            "lineal_titles": 0,
            "ring_magazine_titles": 1,
            "peak_p4p_ranking": 1,
            "signature_win": 4,
            "major_upset_wins": 2,
            "title_defenses": 10,
            "unified_title_defenses": 0,
            "avg_punches_landed_per_round": 20.0,
            "avg_punches_thrown_per_round": 55.0,
            "knockdowns_scored": 15,
            "knockdowns_received": 0,
            "height_cm": 178,
            "reach_cm": 70,
            "age_at_debut": 21,
            "fights_in_hometown": 3,
            "doping_tests_passed": 30,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "major_awards": 3,
            "years_as_champion": 6,
            "notable_rivalries": 1,
            "avg_attendance_events": 4500,
            "ppv_buys_millions": 0.2,
            "longest_win_streak": 24,
            "earliest_round_ko": 1,
            "career_earnings_million_usd": 10.0,
            "retirement_year": 2007,
            "trainer_name": "Floyd Mayweather Sr."
        },
        {
            "player_name": "Cecilia Braekhus",
            "country": "Norway",
            "weight_class": "Welterweight",
            "stance": "Orthodox",
            "years_active": 14,
            "total_fights": 39,
            "wins": 37,
            "losses": 2,
            "draws": 0,
            "kos": 9,
            "ko_percentage": 23.1,
            "world_titles_held": 8,
            "undisputed_titles": 1,
            "lineal_titles": 1,
            "ring_magazine_titles": 1,
            "peak_p4p_ranking": 1,
            "signature_win": 5,
            "major_upset_wins": 2,
            "title_defenses": 25,
            "unified_title_defenses": 10,
            "avg_punches_landed_per_round": 13.5,
            "avg_punches_thrown_per_round": 40.0,
            "knockdowns_scored": 6,
            "knockdowns_received": 0,
            "height_cm": 171,
            "reach_cm": 68,
            "age_at_debut": 25,
            "fights_in_hometown": 2,
            "doping_tests_passed": 55,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 0,
            "major_awards": 2,
            "years_as_champion": 10,
            "notable_rivalries": 2,
            "avg_attendance_events": 3500,
            "ppv_buys_millions": 0.15,
            "longest_win_streak": 36,
            "earliest_round_ko": 2,
            "career_earnings_million_usd": 3.0,
            "retirement_year": 0,
            "trainer_name": "Jonathan Banks"
        },
        {
            "player_name": "Lucia Rijker",
            "country": "Netherlands",
            "weight_class": "Light Welterweight",
            "stance": "Orthodox",
            "years_active": 8,
            "total_fights": 17,
            "wins": 17,
            "losses": 0,
            "draws": 0,
            "kos": 14,
            "ko_percentage": 82.4,
            "world_titles_held": 2,
            "undisputed_titles": 0,
            "lineal_titles": 0,
            "ring_magazine_titles": 0,
            "peak_p4p_ranking": 1,
            "signature_win": 4,
            "major_upset_wins": 2,
            "title_defenses": 5,
            "unified_title_defenses": 0,
            "avg_punches_landed_per_round": 18.0,
            "avg_punches_thrown_per_round": 48.0,
            "knockdowns_scored": 12,
            "knockdowns_received": 0,
            "height_cm": 173,
            "reach_cm": 66,
            "age_at_debut": 25,
            "fights_in_hometown": 1,
            "doping_tests_passed": 20,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "major_awards": 2,
            "years_as_champion": 3,
            "notable_rivalries": 1,
            "avg_attendance_events": 2500,
            "ppv_buys_millions": 0.0,
            "longest_win_streak": 17,
            "earliest_round_ko": 1,
            "career_earnings_million_usd": 0.8,
            "retirement_year": 2004,
            "trainer_name": "Freddie Roach"
        },
        {
            "player_name": "Holly Holm",
            "country": "USA",
            "weight_class": "Welterweight",
            "stance": "Southpaw",
            "years_active": 11,
            "total_fights": 38,
            "wins": 33,
            "losses": 2,
            "draws": 3,
            "kos": 9,
            "ko_percentage": 27.3,
            "world_titles_held": 6,
            "undisputed_titles": 0,
            "lineal_titles": 1,
            "ring_magazine_titles": 2,
            "peak_p4p_ranking": 1,
            "signature_win": 3,
            "major_upset_wins": 2,
            "title_defenses": 18,
            "unified_title_defenses": 0,
            "avg_punches_landed_per_round": 16.0,
            "avg_punches_thrown_per_round": 52.0,
            "knockdowns_scored": 8,
            "knockdowns_received": 1,
            "height_cm": 173,
            "reach_cm": 69,
            "age_at_debut": 20,
            "fights_in_hometown": 12,
            "doping_tests_passed": 80,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "major_awards": 2,
            "years_as_champion": 5,
            "notable_rivalries": 2,
            "avg_attendance_events": 4000,
            "ppv_buys_millions": 0.25,
            "longest_win_streak": 14,
            "earliest_round_ko": 2,
            "career_earnings_million_usd": 1.8,
            "retirement_year": 2013,
            "trainer_name": "Mike Winkeljohn"
        },
        {
            "player_name": "Christy Martin",
            "country": "USA",
            "weight_class": "Light Middleweight",
            "stance": "Orthodox",
            "years_active": 23,
            "total_fights": 59,
            "wins": 49,
            "losses": 7,
            "draws": 3,
            "kos": 31,
            "ko_percentage": 52.5,
            "world_titles_held": 2,
            "undisputed_titles": 0,
            "lineal_titles": 0,
            "ring_magazine_titles": 0,
            "peak_p4p_ranking": 1,
            "signature_win": 3,
            "major_upset_wins": 1,
            "title_defenses": 7,
            "unified_title_defenses": 0,
            "avg_punches_landed_per_round": 17.0,
            "avg_punches_thrown_per_round": 50.0,
            "knockdowns_scored": 22,
            "knockdowns_received": 3,
            "height_cm": 163,
            "reach_cm": 64,
            "age_at_debut": 21,
            "fights_in_hometown": 5,
            "doping_tests_passed": 20,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "major_awards": 1,
            "years_as_champion": 3,
            "notable_rivalries": 1,
            "avg_attendance_events": 3000,
            "ppv_buys_millions": 0.0,
            "longest_win_streak": 28,
            "earliest_round_ko": 1,
            "career_earnings_million_usd": 1.0,
            "retirement_year": 2012,
            "trainer_name": "James Martin"
        },
        {
            "player_name": "Regina Halmich",
            "country": "Germany",
            "weight_class": "Flyweight",
            "stance": "Orthodox",
            "years_active": 13,
            "total_fights": 56,
            "wins": 54,
            "losses": 1,
            "draws": 1,
            "kos": 16,
            "ko_percentage": 28.6,
            "world_titles_held": 3,
            "undisputed_titles": 0,
            "lineal_titles": 0,
            "ring_magazine_titles": 0,
            "peak_p4p_ranking": 2,
            "signature_win": 3,
            "major_upset_wins": 1,
            "title_defenses": 46,
            "unified_title_defenses": 0,
            "avg_punches_landed_per_round": 15.5,
            "avg_punches_thrown_per_round": 46.0,
            "knockdowns_scored": 12,
            "knockdowns_received": 2,
            "height_cm": 160,
            "reach_cm": 62,
            "age_at_debut": 19,
            "fights_in_hometown": 8,
            "doping_tests_passed": 18,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "major_awards": 1,
            "years_as_champion": 12,
            "notable_rivalries": 1,
            "avg_attendance_events": 2500,
            "ppv_buys_millions": 0.0,
            "longest_win_streak": 41,
            "earliest_round_ko": 1,
            "career_earnings_million_usd": 2.0,
            "retirement_year": 2007,
            "trainer_name": "Torsten Schmitz"
        },
        {
            "player_name": "Ann Wolfe",
            "country": "USA",
            "weight_class": "Light Middleweight",
            "stance": "Orthodox",
            "years_active": 6,
            "total_fights": 26,
            "wins": 24,
            "losses": 1,
            "draws": 1,
            "kos": 16,
            "ko_percentage": 61.5,
            "world_titles_held": 3,
            "undisputed_titles": 0,
            "lineal_titles": 0,
            "ring_magazine_titles": 0,
            "peak_p4p_ranking": 2,
            "signature_win": 2,
            "major_upset_wins": 1,
            "title_defenses": 6,
            "unified_title_defenses": 0,
            "avg_punches_landed_per_round": 18.0,
            "avg_punches_thrown_per_round": 54.0,
            "knockdowns_scored": 10,
            "knockdowns_received": 2,
            "height_cm": 175,
            "reach_cm": 70,
            "age_at_debut": 25,
            "fights_in_hometown": 3,
            "doping_tests_passed": 15,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 1,
            "major_awards": 1,
            "years_as_champion": 4,
            "notable_rivalries": 1,
            "avg_attendance_events": 2000,
            "ppv_buys_millions": 0.0,
            "longest_win_streak": 15,
            "earliest_round_ko": 1,
            "career_earnings_million_usd": 0.5,
            "retirement_year": 2006,
            "trainer_name": "Self"
        },
        {
            "player_name": "Jessica McCaskill",
            "country": "USA",
            "weight_class": "Welterweight",
            "stance": "Orthodox",
            "years_active": 8,
            "total_fights": 14,
            "wins": 12,
            "losses": 2,
            "draws": 0,
            "kos": 5,
            "ko_percentage": 35.7,
            "world_titles_held": 4,
            "undisputed_titles": 1,
            "lineal_titles": 1,
            "ring_magazine_titles": 0,
            "peak_p4p_ranking": 4,
            "signature_win": 2,
            "major_upset_wins": 1,
            "title_defenses": 5,
            "unified_title_defenses": 2,
            "avg_punches_landed_per_round": 13.0,
            "avg_punches_thrown_per_round": 39.0,
            "knockdowns_scored": 3,
            "knockdowns_received": 1,
            "height_cm": 168,
            "reach_cm": 69,
            "age_at_debut": 31,
            "fights_in_hometown": 2,
            "doping_tests_passed": 25,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 0,
            "major_awards": 1,
            "years_as_champion": 3,
            "notable_rivalries": 1,
            "avg_attendance_events": 2000,
            "ppv_buys_millions": 0.1,
            "longest_win_streak": 5,
            "earliest_round_ko": 2,
            "career_earnings_million_usd": 0.8,
            "retirement_year": 0,
            "trainer_name": "Rick Ramos"
        },
        {
            "player_name": "Delfine Persoon",
            "country": "Belgium",
            "weight_class": "Lightweight",
            "stance": "Orthodox",
            "years_active": 14,
            "total_fights": 51,
            "wins": 47,
            "losses": 3,
            "draws": 1,
            "kos": 19,
            "ko_percentage": 37.3,
            "world_titles_held": 2,
            "undisputed_titles": 0,
            "lineal_titles": 0,
            "ring_magazine_titles": 0,
            "peak_p4p_ranking": 3,
            "signature_win": 3,
            "major_upset_wins": 1,
            "title_defenses": 9,
            "unified_title_defenses": 0,
            "avg_punches_landed_per_round": 15.2,
            "avg_punches_thrown_per_round": 50.0,
            "knockdowns_scored": 8,
            "knockdowns_received": 2,
            "height_cm": 175,
            "reach_cm": 67,
            "age_at_debut": 25,
            "fights_in_hometown": 10,
            "doping_tests_passed": 30,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 0,
            "major_awards": 0,
            "years_as_champion": 4,
            "notable_rivalries": 1,
            "avg_attendance_events": 1500,
            "ppv_buys_millions": 0.0,
            "longest_win_streak": 28,
            "earliest_round_ko": 2,
            "career_earnings_million_usd": 0.6,
            "retirement_year": 0,
            "trainer_name": "Filip Heuvinck"
        },
        {
            "player_name": "Savannah Marshall",
            "country": "UK",
            "weight_class": "Middleweight",
            "stance": "Orthodox",
            "years_active": 5,
            "total_fights": 13,
            "wins": 12,
            "losses": 1,
            "draws": 0,
            "kos": 10,
            "ko_percentage": 76.9,
            "world_titles_held": 2,
            "undisputed_titles": 0,
            "lineal_titles": 0,
            "ring_magazine_titles": 0,
            "peak_p4p_ranking": 5,
            "signature_win": 2,
            "major_upset_wins": 1,
            "title_defenses": 3,
            "unified_title_defenses": 0,
            "avg_punches_landed_per_round": 14.0,
            "avg_punches_thrown_per_round": 42.0,
            "knockdowns_scored": 7,
            "knockdowns_received": 1,
            "height_cm": 182,
            "reach_cm": 72,
            "age_at_debut": 25,
            "fights_in_hometown": 1,
            "doping_tests_passed": 15,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 0,
            "major_awards": 0,
            "years_as_champion": 2,
            "notable_rivalries": 1,
            "avg_attendance_events": 2000,
            "ppv_buys_millions": 0.15,
            "longest_win_streak": 12,
            "earliest_round_ko": 2,
            "career_earnings_million_usd": 0.4,
            "retirement_year": 0,
            "trainer_name": "Peter Fury"
        },
        # -------------- Now let's add placeholders for the remaining ~17 to reach 30 total --------------
    ]

    # Add placeholders to ensure we have 30 total
    while len(players_data) < 30:
        count = len(players_data) + 1
        players_data.append({
            "player_name": f"Placeholder Boxer {count}",
            "country": "CountryX",
            "weight_class": "PlaceholderWeight",
            "stance": "Orthodox",
            "years_active": 4,
            "total_fights": 15,
            "wins": 14,
            "losses": 1,
            "draws": 0,
            "kos": 8,
            "ko_percentage": 53.3,
            "world_titles_held": 1,
            "undisputed_titles": 0,
            "lineal_titles": 0,
            "ring_magazine_titles": 0,
            "peak_p4p_ranking": 8,
            "signature_win": 1,
            "major_upset_wins": 0,
            "title_defenses": 2,
            "unified_title_defenses": 0,
            "avg_punches_landed_per_round": 12.0,
            "avg_punches_thrown_per_round": 35.0,
            "knockdowns_scored": 5,
            "knockdowns_received": 2,
            "height_cm": 165,
            "reach_cm": 64,
            "age_at_debut": 22,
            "fights_in_hometown": 1,
            "doping_tests_passed": 10,
            "doping_tests_failed": 0,
            "hall_of_fame_inducted": 0,
            "major_awards": 0,
            "years_as_champion": 1,
            "notable_rivalries": 0,
            "avg_attendance_events": 1000,
            "ppv_buys_millions": 0.0,
            "longest_win_streak": 10,
            "earliest_round_ko": 2,
            "career_earnings_million_usd": 0.2,
            "retirement_year": 0,
            "trainer_name": "Placeholder Trainer"
        })

    # Final check
    if len(players_data) != 30:
        raise ValueError(f"Expected 30 boxers, but have {len(players_data)}")

    # Write out to CSV
    with open(filename, mode="w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=headers)
        writer.writeheader()
        for pdata in players_data:
            # Ensure each stat is present; fill missing with 0 or something safe
            for h in headers:
                if h not in pdata:
                    pdata[h] = 0
            writer.writerow(pdata)


if __name__ == "__main__":
    create_womens_boxing_dataset()
    print("womens_boxing_dataset.csv has been created with 30 boxers (41 columns each).")
