import csv

def create_rugby_dataset(filename="rugby_dataset.csv"):
    """
    Creates a CSV file containing 30 Rugby players and 40+ stats each.
    Stats are approximations or representative figures, intended for
    demonstration and for building a 'Rugby Index Score' later.
    """

    # Define the header (41 columns: player_name + 40 stats)
    headers = [
        "player_name",
        "position",
        "test_caps",
        "total_points_scored",
        "tries_scored",
        "conversions",
        "penalty_goals",
        "drop_goals",
        "total_meters_carried",
        "defenders_beaten",
        "clean_breaks",
        "offloads",
        "passes",
        "handling_errors",
        "tackles_made",
        "tackle_success_percent",
        "turnovers_won",
        "turnovers_conceded",
        "lineouts_won",
        "lineouts_stolen",
        "scrums_won",
        "scrums_lost",
        "rucks_completed",
        "ruck_success_percent",
        "pick_and_go_meters",
        "tries_saved",
        "tries_assisted",
        "total_appearances_club",
        "total_points_club",
        "club_championships_won",
        "international_rugby_championships",
        "world_cup_titles",
        "international_player_of_year_awards",
        "man_of_the_match_awards",
        "red_cards",
        "yellow_cards",
        "captained_matches",
        "match_winning_kicks",
        "average_kick_distance",
        "career_length_years"
    ]

    # The data for each player is approximate. Modify as needed.
    players_data = [
        {
            "player_name": "Jonah Lomu",
            "position": "Wing",
            "test_caps": 63,
            "total_points_scored": 185,
            "tries_scored": 37,
            "conversions": 0,
            "penalty_goals": 0,
            "drop_goals": 0,
            "total_meters_carried": 4300,
            "defenders_beaten": 210,
            "clean_breaks": 165,
            "offloads": 55,
            "passes": 250,
            "handling_errors": 48,
            "tackles_made": 130,
            "tackle_success_percent": 82.0,
            "turnovers_won": 10,
            "turnovers_conceded": 25,
            "lineouts_won": 2,
            "lineouts_stolen": 0,
            "scrums_won": 0,
            "scrums_lost": 0,
            "rucks_completed": 160,
            "ruck_success_percent": 90.0,
            "pick_and_go_meters": 50,
            "tries_saved": 5,
            "tries_assisted": 10,
            "total_appearances_club": 100,
            "total_points_club": 350,
            "club_championships_won": 1,
            "international_rugby_championships": 2,  # e.g., Tri Nations, Rugby Championship, etc.
            "world_cup_titles": 0,
            "international_player_of_year_awards": 0,
            "man_of_the_match_awards": 12,
            "red_cards": 0,
            "yellow_cards": 3,
            "captained_matches": 0,
            "match_winning_kicks": 0,
            "average_kick_distance": 0,
            "career_length_years": 9
        },
        {
            "player_name": "Richie McCaw",
            "position": "Flanker",
            "test_caps": 148,
            "total_points_scored": 135,
            "tries_scored": 27,
            "conversions": 0,
            "penalty_goals": 0,
            "drop_goals": 0,
            "total_meters_carried": 3100,
            "defenders_beaten": 115,
            "clean_breaks": 40,
            "offloads": 60,
            "passes": 1200,
            "handling_errors": 55,
            "tackles_made": 1800,
            "tackle_success_percent": 91.2,
            "turnovers_won": 220,
            "turnovers_conceded": 65,
            "lineouts_won": 45,
            "lineouts_stolen": 18,
            "scrums_won": 0,
            "scrums_lost": 0,
            "rucks_completed": 1450,
            "ruck_success_percent": 92.5,
            "pick_and_go_meters": 135,
            "tries_saved": 17,
            "tries_assisted": 12,
            "total_appearances_club": 220,
            "total_points_club": 180,
            "club_championships_won": 5,
            "international_rugby_championships": 7,
            "world_cup_titles": 2,
            "international_player_of_year_awards": 3,
            "man_of_the_match_awards": 25,
            "red_cards": 0,
            "yellow_cards": 6,
            "captained_matches": 111,
            "match_winning_kicks": 0,
            "average_kick_distance": 0,
            "career_length_years": 15
        },
        {
            "player_name": "Dan Carter",
            "position": "Fly-Half",
            "test_caps": 112,
            "total_points_scored": 1598,
            "tries_scored": 29,
            "conversions": 293,
            "penalty_goals": 281,
            "drop_goals": 8,
            "total_meters_carried": 2850,
            "defenders_beaten": 85,
            "clean_breaks": 62,
            "offloads": 45,
            "passes": 2100,
            "handling_errors": 40,
            "tackles_made": 650,
            "tackle_success_percent": 86.5,
            "turnovers_won": 25,
            "turnovers_conceded": 45,
            "lineouts_won": 0,
            "lineouts_stolen": 0,
            "scrums_won": 0,
            "scrums_lost": 0,
            "rucks_completed": 700,
            "ruck_success_percent": 88.0,
            "pick_and_go_meters": 30,
            "tries_saved": 8,
            "tries_assisted": 35,
            "total_appearances_club": 180,
            "total_points_club": 1420,
            "club_championships_won": 4,
            "international_rugby_championships": 6,
            "world_cup_titles": 2,
            "international_player_of_year_awards": 3,
            "man_of_the_match_awards": 20,
            "red_cards": 0,
            "yellow_cards": 5,
            "captained_matches": 5,
            "match_winning_kicks": 14,
            "average_kick_distance": 45,
            "career_length_years": 12
        },
        {
            "player_name": "Brian O'Driscoll",
            "position": "Centre",
            "test_caps": 133,
            "total_points_scored": 245,
            "tries_scored": 46,
            "conversions": 0,
            "penalty_goals": 0,
            "drop_goals": 5,
            "total_meters_carried": 4100,
            "defenders_beaten": 210,
            "clean_breaks": 145,
            "offloads": 80,
            "passes": 2050,
            "handling_errors": 65,
            "tackles_made": 1250,
            "tackle_success_percent": 89.4,
            "turnovers_won": 110,
            "turnovers_conceded": 60,
            "lineouts_won": 5,
            "lineouts_stolen": 1,
            "scrums_won": 0,
            "scrums_lost": 0,
            "rucks_completed": 1200,
            "ruck_success_percent": 90.0,
            "pick_and_go_meters": 75,
            "tries_saved": 20,
            "tries_assisted": 22,
            "total_appearances_club": 230,
            "total_points_club": 520,
            "club_championships_won": 3,
            "international_rugby_championships": 4,
            "world_cup_titles": 0,
            "international_player_of_year_awards": 1,
            "man_of_the_match_awards": 22,
            "red_cards": 0,
            "yellow_cards": 4,
            "captained_matches": 84,
            "match_winning_kicks": 0,
            "average_kick_distance": 0,
            "career_length_years": 15
        },
        {
            "player_name": "Martin Johnson",
            "position": "Lock",
            "test_caps": 84,
            "total_points_scored": 10,
            "tries_scored": 2,
            "conversions": 0,
            "penalty_goals": 0,
            "drop_goals": 0,
            "total_meters_carried": 800,
            "defenders_beaten": 30,
            "clean_breaks": 8,
            "offloads": 20,
            "passes": 450,
            "handling_errors": 25,
            "tackles_made": 950,
            "tackle_success_percent": 89.0,
            "turnovers_won": 95,
            "turnovers_conceded": 40,
            "lineouts_won": 275,
            "lineouts_stolen": 60,
            "scrums_won": 0,
            "scrums_lost": 0,
            "rucks_completed": 850,
            "ruck_success_percent": 88.0,
            "pick_and_go_meters": 40,
            "tries_saved": 10,
            "tries_assisted": 2,
            "total_appearances_club": 290,
            "total_points_club": 60,
            "club_championships_won": 4,
            "international_rugby_championships": 2,
            "world_cup_titles": 1,
            "international_player_of_year_awards": 0,
            "man_of_the_match_awards": 5,
            "red_cards": 1,
            "yellow_cards": 6,
            "captained_matches": 50,
            "match_winning_kicks": 0,
            "average_kick_distance": 0,
            "career_length_years": 14
        },
        {
            "player_name": "Gareth Edwards",
            "position": "Scrum-Half",
            "test_caps": 53,
            "total_points_scored": 44,
            "tries_scored": 20,
            "conversions": 0,
            "penalty_goals": 0,
            "drop_goals": 1,
            "total_meters_carried": 1600,
            "defenders_beaten": 70,
            "clean_breaks": 40,
            "offloads": 25,
            "passes": 1200,
            "handling_errors": 22,
            "tackles_made": 300,
            "tackle_success_percent": 85.0,
            "turnovers_won": 40,
            "turnovers_conceded": 20,
            "lineouts_won": 0,
            "lineouts_stolen": 0,
            "scrums_won": 0,
            "scrums_lost": 0,
            "rucks_completed": 280,
            "ruck_success_percent": 85.0,
            "pick_and_go_meters": 25,
            "tries_saved": 3,
            "tries_assisted": 15,
            "total_appearances_club": 210,
            "total_points_club": 130,
            "club_championships_won": 3,
            "international_rugby_championships": 5,
            "world_cup_titles": 0,
            "international_player_of_year_awards": 0,
            "man_of_the_match_awards": 8,
            "red_cards": 0,
            "yellow_cards": 2,
            "captained_matches": 10,
            "match_winning_kicks": 0,
            "average_kick_distance": 0,
            "career_length_years": 12
        },
        {
            "player_name": "Jonny Wilkinson",
            "position": "Fly-Half",
            "test_caps": 91,
            "total_points_scored": 1179,
            "tries_scored": 6,
            "conversions": 169,
            "penalty_goals": 239,
            "drop_goals": 29,
            "total_meters_carried": 2100,
            "defenders_beaten": 55,
            "clean_breaks": 20,
            "offloads": 15,
            "passes": 1600,
            "handling_errors": 33,
            "tackles_made": 640,
            "tackle_success_percent": 87.5,
            "turnovers_won": 35,
            "turnovers_conceded": 40,
            "lineouts_won": 0,
            "lineouts_stolen": 0,
            "scrums_won": 0,
            "scrums_lost": 0,
            "rucks_completed": 550,
            "ruck_success_percent": 86.0,
            "pick_and_go_meters": 40,
            "tries_saved": 6,
            "tries_assisted": 30,
            "total_appearances_club": 210,
            "total_points_club": 1500,
            "club_championships_won": 3,
            "international_rugby_championships": 2,
            "world_cup_titles": 1,
            "international_player_of_year_awards": 1,
            "man_of_the_match_awards": 12,
            "red_cards": 0,
            "yellow_cards": 2,
            "captained_matches": 4,
            "match_winning_kicks": 18,
            "average_kick_distance": 43,
            "career_length_years": 14
        },
        {
            "player_name": "David Campese",
            "position": "Wing",
            "test_caps": 101,
            "total_points_scored": 315,
            "tries_scored": 64,
            "conversions": 0,
            "penalty_goals": 0,
            "drop_goals": 0,
            "total_meters_carried": 4200,
            "defenders_beaten": 190,
            "clean_breaks": 170,
            "offloads": 60,
            "passes": 450,
            "handling_errors": 40,
            "tackles_made": 200,
            "tackle_success_percent": 78.5,
            "turnovers_won": 20,
            "turnovers_conceded": 30,
            "lineouts_won": 0,
            "lineouts_stolen": 0,
            "scrums_won": 0,
            "scrums_lost": 0,
            "rucks_completed": 350,
            "ruck_success_percent": 82.0,
            "pick_and_go_meters": 55,
            "tries_saved": 8,
            "tries_assisted": 18,
            "total_appearances_club": 170,
            "total_points_club": 420,
            "club_championships_won": 2,
            "international_rugby_championships": 3,
            "world_cup_titles": 1,
            "international_player_of_year_awards": 0,
            "man_of_the_match_awards": 15,
            "red_cards": 0,
            "yellow_cards": 2,
            "captained_matches": 0,
            "match_winning_kicks": 0,
            "average_kick_distance": 0,
            "career_length_years": 13
        },
        {
            "player_name": "Sean Fitzpatrick",
            "position": "Hooker",
            "test_caps": 92,
            "total_points_scored": 50,
            "tries_scored": 12,
            "conversions": 0,
            "penalty_goals": 0,
            "drop_goals": 0,
            "total_meters_carried": 1250,
            "defenders_beaten": 40,
            "clean_breaks": 12,
            "offloads": 18,
            "passes": 600,
            "handling_errors": 28,
            "tackles_made": 950,
            "tackle_success_percent": 90.0,
            "turnovers_won": 80,
            "turnovers_conceded": 35,
            "lineouts_won": 30,
            "lineouts_stolen": 15,
            "scrums_won": 0,
            "scrums_lost": 0,
            "rucks_completed": 800,
            "ruck_success_percent": 90.0,
            "pick_and_go_meters": 40,
            "tries_saved": 5,
            "tries_assisted": 10,
            "total_appearances_club": 220,
            "total_points_club": 110,
            "club_championships_won": 4,
            "international_rugby_championships": 5,
            "world_cup_titles": 1,
            "international_player_of_year_awards": 0,
            "man_of_the_match_awards": 8,
            "red_cards": 0,
            "yellow_cards": 3,
            "captained_matches": 62,
            "match_winning_kicks": 0,
            "average_kick_distance": 0,
            "career_length_years": 12
        },
        {
            "player_name": "John Eales",
            "position": "Lock",
            "test_caps": 86,
            "total_points_scored": 173,
            "tries_scored": 2,
            "conversions": 31,
            "penalty_goals": 34,
            "drop_goals": 0,
            "total_meters_carried": 950,
            "defenders_beaten": 28,
            "clean_breaks": 5,
            "offloads": 10,
            "passes": 500,
            "handling_errors": 22,
            "tackles_made": 900,
            "tackle_success_percent": 88.0,
            "turnovers_won": 70,
            "turnovers_conceded": 35,
            "lineouts_won": 210,
            "lineouts_stolen": 40,
            "scrums_won": 0,
            "scrums_lost": 0,
            "rucks_completed": 650,
            "ruck_success_percent": 87.0,
            "pick_and_go_meters": 35,
            "tries_saved": 5,
            "tries_assisted": 3,
            "total_appearances_club": 130,
            "total_points_club": 270,
            "club_championships_won": 3,
            "international_rugby_championships": 2,
            "world_cup_titles": 2,
            "international_player_of_year_awards": 0,
            "man_of_the_match_awards": 6,
            "red_cards": 0,
            "yellow_cards": 2,
            "captained_matches": 55,
            "match_winning_kicks": 5,
            "average_kick_distance": 30,
            "career_length_years": 11
        },
        {
            "player_name": "Joost van der Westhuizen",
            "position": "Scrum-Half",
            "test_caps": 89,
            "total_points_scored": 190,
            "tries_scored": 38,
            "conversions": 0,
            "penalty_goals": 0,
            "drop_goals": 2,
            "total_meters_carried": 2300,
            "defenders_beaten": 88,
            "clean_breaks": 45,
            "offloads": 34,
            "passes": 1400,
            "handling_errors": 38,
            "tackles_made": 650,
            "tackle_success_percent": 86.0,
            "turnovers_won": 55,
            "turnovers_conceded": 40,
            "lineouts_won": 0,
            "lineouts_stolen": 0,
            "scrums_won": 0,
            "scrums_lost": 0,
            "rucks_completed": 580,
            "ruck_success_percent": 85.0,
            "pick_and_go_meters": 40,
            "tries_saved": 10,
            "tries_assisted": 25,
            "total_appearances_club": 160,
            "total_points_club": 310,
            "club_championships_won": 2,
            "international_rugby_championships": 1,
            "world_cup_titles": 1,
            "international_player_of_year_awards": 0,
            "man_of_the_match_awards": 11,
            "red_cards": 0,
            "yellow_cards": 3,
            "captained_matches": 10,
            "match_winning_kicks": 0,
            "average_kick_distance": 0,
            "career_length_years": 10
        },
        {
            "player_name": "Mils Muliaina",
            "position": "Fullback",
            "test_caps": 100,
            "total_points_scored": 125,
            "tries_scored": 33,
            "conversions": 0,
            "penalty_goals": 0,
            "drop_goals": 0,
            "total_meters_carried": 3600,
            "defenders_beaten": 140,
            "clean_breaks": 75,
            "offloads": 42,
            "passes": 850,
            "handling_errors": 30,
            "tackles_made": 650,
            "tackle_success_percent": 87.0,
            "turnovers_won": 30,
            "turnovers_conceded": 35,
            "lineouts_won": 5,
            "lineouts_stolen": 1,
            "scrums_won": 0,
            "scrums_lost": 0,
            "rucks_completed": 590,
            "ruck_success_percent": 88.0,
            "pick_and_go_meters": 40,
            "tries_saved": 10,
            "tries_assisted": 15,
            "total_appearances_club": 140,
            "total_points_club": 240,
            "club_championships_won": 2,
            "international_rugby_championships": 4,
            "world_cup_titles": 1,
            "international_player_of_year_awards": 0,
            "man_of_the_match_awards": 6,
            "red_cards": 0,
            "yellow_cards": 3,
            "captained_matches": 4,
            "match_winning_kicks": 0,
            "average_kick_distance": 0,
            "career_length_years": 10
        },
        {
            "player_name": "Christian Cullen",
            "position": "Fullback",
            "test_caps": 58,
            "total_points_scored": 190,
            "tries_scored": 46,
            "conversions": 0,
            "penalty_goals": 0,
            "drop_goals": 0,
            "total_meters_carried": 3100,
            "defenders_beaten": 160,
            "clean_breaks": 90,
            "offloads": 32,
            "passes": 620,
            "handling_errors": 35,
            "tackles_made": 290,
            "tackle_success_percent": 80.0,
            "turnovers_won": 25,
            "turnovers_conceded": 28,
            "lineouts_won": 2,
            "lineouts_stolen": 0,
            "scrums_won": 0,
            "scrums_lost": 0,
            "rucks_completed": 320,
            "ruck_success_percent": 84.0,
            "pick_and_go_meters": 30,
            "tries_saved": 5,
            "tries_assisted": 18,
            "total_appearances_club": 120,
            "total_points_club": 280,
            "club_championships_won": 2,
            "international_rugby_championships": 3,
            "world_cup_titles": 0,
            "international_player_of_year_awards": 0,
            "man_of_the_match_awards": 8,
            "red_cards": 0,
            "yellow_cards": 2,
            "captained_matches": 0,
            "match_winning_kicks": 0,
            "average_kick_distance": 0,
            "career_length_years": 8
        },
        {
            "player_name": "Lawrence Dallaglio",
            "position": "Number 8",
            "test_caps": 85,
            "total_points_scored": 85,
            "tries_scored": 16,
            "conversions": 0,
            "penalty_goals": 0,
            "drop_goals": 0,
            "total_meters_carried": 2700,
            "defenders_beaten": 90,
            "clean_breaks": 35,
            "offloads": 40,
            "passes": 750,
            "handling_errors": 28,
            "tackles_made": 830,
            "tackle_success_percent": 88.0,
            "turnovers_won": 100,
            "turnovers_conceded": 45,
            "lineouts_won": 110,
            "lineouts_stolen": 15,
            "scrums_won": 0,
            "scrums_lost": 0,
            "rucks_completed": 680,
            "ruck_success_percent": 89.0,
            "pick_and_go_meters": 80,
            "tries_saved": 12,
            "tries_assisted": 9,
            "total_appearances_club": 300,
            "total_points_club": 260,
            "club_championships_won": 4,
            "international_rugby_championships": 1,
            "world_cup_titles": 1,
            "international_player_of_year_awards": 0,
            "man_of_the_match_awards": 10,
            "red_cards": 0,
            "yellow_cards": 4,
            "captained_matches": 22,
            "match_winning_kicks": 0,
            "average_kick_distance": 0,
            "career_length_years": 13
        },
        {
            "player_name": "Schalk Burger",
            "position": "Flanker",
            "test_caps": 86,
            "total_points_scored": 70,
            "tries_scored": 14,
            "conversions": 0,
            "penalty_goals": 0,
            "drop_goals": 0,
            "total_meters_carried": 2100,
            "defenders_beaten": 65,
            "clean_breaks": 20,
            "offloads": 55,
            "passes": 550,
            "handling_errors": 45,
            "tackles_made": 1200,
            "tackle_success_percent": 88.0,
            "turnovers_won": 140,
            "turnovers_conceded": 50,
            "lineouts_won": 65,
            "lineouts_stolen": 10,
            "scrums_won": 0,
            "scrums_lost": 0,
            "rucks_completed": 980,
            "ruck_success_percent": 90.0,
            "pick_and_go_meters": 60,
            "tries_saved": 10,
            "tries_assisted": 6,
            "total_appearances_club": 200,
            "total_points_club": 100,
            "club_championships_won": 3,
            "international_rugby_championships": 3,
            "world_cup_titles": 1,
            "international_player_of_year_awards": 1,
            "man_of_the_match_awards": 15,
            "red_cards": 1,
            "yellow_cards": 7,
            "captained_matches": 5,
            "match_winning_kicks": 0,
            "average_kick_distance": 0,
            "career_length_years": 14
        },
        {
            "player_name": "Kieran Read",
            "position": "Number 8",
            "test_caps": 127,
            "total_points_scored": 130,
            "tries_scored": 26,
            "conversions": 0,
            "penalty_goals": 0,
            "drop_goals": 0,
            "total_meters_carried": 3600,
            "defenders_beaten": 130,
            "clean_breaks": 45,
            "offloads": 70,
            "passes": 950,
            "handling_errors": 40,
            "tackles_made": 1200,
            "tackle_success_percent": 90.0,
            "turnovers_won": 150,
            "turnovers_conceded": 60,
            "lineouts_won": 220,
            "lineouts_stolen": 40,
            "scrums_won": 0,
            "scrums_lost": 0,
            "rucks_completed": 1100,
            "ruck_success_percent": 92.0,
            "pick_and_go_meters": 110,
            "tries_saved": 15,
            "tries_assisted": 20,
            "total_appearances_club": 210,
            "total_points_club": 240,
            "club_championships_won": 4,
            "international_rugby_championships": 6,
            "world_cup_titles": 2,
            "international_player_of_year_awards": 2,
            "man_of_the_match_awards": 18,
            "red_cards": 0,
            "yellow_cards": 4,
            "captained_matches": 52,
            "match_winning_kicks": 0,
            "average_kick_distance": 0,
            "career_length_years": 13
        },
        {
            "player_name": "Ma'a Nonu",
            "position": "Centre",
            "test_caps": 103,
            "total_points_scored": 155,
            "tries_scored": 31,
            "conversions": 0,
            "penalty_goals": 0,
            "drop_goals": 0,
            "total_meters_carried": 3300,
            "defenders_beaten": 180,
            "clean_breaks": 95,
            "offloads": 75,
            "passes": 1050,
            "handling_errors": 48,
            "tackles_made": 720,
            "tackle_success_percent": 85.5,
            "turnovers_won": 85,
            "turnovers_conceded": 70,
            "lineouts_won": 10,
            "lineouts_stolen": 1,
            "scrums_won": 0,
            "scrums_lost": 0,
            "rucks_completed": 800,
            "ruck_success_percent": 89.0,
            "pick_and_go_meters": 60,
            "tries_saved": 7,
            "tries_assisted": 25,
            "total_appearances_club": 190,
            "total_points_club": 350,
            "club_championships_won": 3,
            "international_rugby_championships": 5,
            "world_cup_titles": 2,
            "international_player_of_year_awards": 0,
            "man_of_the_match_awards": 12,
            "red_cards": 1,
            "yellow_cards": 5,
            "captained_matches": 3,
            "match_winning_kicks": 0,
            "average_kick_distance": 0,
            "career_length_years": 14
        },
        {
            "player_name": "Michael Jones",
            "position": "Flanker",
            "test_caps": 55,
            "total_points_scored": 56,
            "tries_scored": 14,
            "conversions": 0,
            "penalty_goals": 0,
            "drop_goals": 0,
            "total_meters_carried": 1100,
            "defenders_beaten": 40,
            "clean_breaks": 15,
            "offloads": 20,
            "passes": 360,
            "handling_errors": 10,
            "tackles_made": 400,
            "tackle_success_percent": 92.0,
            "turnovers_won": 70,
            "turnovers_conceded": 15,
            "lineouts_won": 25,
            "lineouts_stolen": 5,
            "scrums_won": 0,
            "scrums_lost": 0,
            "rucks_completed": 320,
            "ruck_success_percent": 90.0,
            "pick_and_go_meters": 45,
            "tries_saved": 6,
            "tries_assisted": 5,
            "total_appearances_club": 90,
            "total_points_club": 120,
            "club_championships_won": 2,
            "international_rugby_championships": 3,
            "world_cup_titles": 1,
            "international_player_of_year_awards": 0,
            "man_of_the_match_awards": 5,
            "red_cards": 0,
            "yellow_cards": 1,
            "captained_matches": 3,
            "match_winning_kicks": 0,
            "average_kick_distance": 0,
            "career_length_years": 8
        },
        {
            "player_name": "Tim Horan",
            "position": "Centre",
            "test_caps": 80,
            "total_points_scored": 161,
            "tries_scored": 30,
            "conversions": 3,
            "penalty_goals": 5,
            "drop_goals": 0,
            "total_meters_carried": 2500,
            "defenders_beaten": 100,
            "clean_breaks": 60,
            "offloads": 40,
            "passes": 750,
            "handling_errors": 32,
            "tackles_made": 530,
            "tackle_success_percent": 84.0,
            "turnovers_won": 45,
            "turnovers_conceded": 40,
            "lineouts_won": 5,
            "lineouts_stolen": 0,
            "scrums_won": 0,
            "scrums_lost": 0,
            "rucks_completed": 500,
            "ruck_success_percent": 85.0,
            "pick_and_go_meters": 50,
            "tries_saved": 5,
            "tries_assisted": 18,
            "total_appearances_club": 120,
            "total_points_club": 400,
            "club_championships_won": 2,
            "international_rugby_championships": 2,
            "world_cup_titles": 2,
            "international_player_of_year_awards": 1,
            "man_of_the_match_awards": 9,
            "red_cards": 0,
            "yellow_cards": 2,
            "captained_matches": 4,
            "match_winning_kicks": 1,
            "average_kick_distance": 25,
            "career_length_years": 10
        },
        {
            "player_name": "George Gregan",
            "position": "Scrum-Half",
            "test_caps": 139,
            "total_points_scored": 99,
            "tries_scored": 17,
            "conversions": 0,
            "penalty_goals": 0,
            "drop_goals": 1,
            "total_meters_carried": 2000,
            "defenders_beaten": 60,
            "clean_breaks": 25,
            "offloads": 30,
            "passes": 3450,
            "handling_errors": 65,
            "tackles_made": 950,
            "tackle_success_percent": 86.0,
            "turnovers_won": 70,
            "turnovers_conceded": 60,
            "lineouts_won": 0,
            "lineouts_stolen": 0,
            "scrums_won": 0,
            "scrums_lost": 0,
            "rucks_completed": 900,
            "ruck_success_percent": 88.0,
            "pick_and_go_meters": 60,
            "tries_saved": 8,
            "tries_assisted": 28,
            "total_appearances_club": 160,
            "total_points_club": 260,
            "club_championships_won": 3,
            "international_rugby_championships": 3,
            "world_cup_titles": 1,
            "international_player_of_year_awards": 0,
            "man_of_the_match_awards": 10,
            "red_cards": 0,
            "yellow_cards": 3,
            "captained_matches": 59,
            "match_winning_kicks": 0,
            "average_kick_distance": 0,
            "career_length_years": 13
        },
        {
            "player_name": "Jonathan Davies",
            "position": "Centre",
            "test_caps": 94,
            "total_points_scored": 110,
            "tries_scored": 24,
            "conversions": 0,
            "penalty_goals": 0,
            "drop_goals": 2,
            "total_meters_carried": 2900,
            "defenders_beaten": 120,
            "clean_breaks": 68,
            "offloads": 44,
            "passes": 1350,
            "handling_errors": 37,
            "tackles_made": 820,
            "tackle_success_percent": 87.5,
            "turnovers_won": 60,
            "turnovers_conceded": 55,
            "lineouts_won": 8,
            "lineouts_stolen": 1,
            "scrums_won": 0,
            "scrums_lost": 0,
            "rucks_completed": 700,
            "ruck_success_percent": 88.0,
            "pick_and_go_meters": 65,
            "tries_saved": 8,
            "tries_assisted": 20,
            "total_appearances_club": 150,
            "total_points_club": 350,
            "club_championships_won": 3,
            "international_rugby_championships": 1,
            "world_cup_titles": 0,
            "international_player_of_year_awards": 0,
            "man_of_the_match_awards": 12,
            "red_cards": 0,
            "yellow_cards": 2,
            "captained_matches": 10,
            "match_winning_kicks": 0,
            "average_kick_distance": 0,
            "career_length_years": 11
        },
        {
            "player_name": "Thierry Dusautoir",
            "position": "Flanker",
            "test_caps": 80,
            "total_points_scored": 25,
            "tries_scored": 5,
            "conversions": 0,
            "penalty_goals": 0,
            "drop_goals": 0,
            "total_meters_carried": 1400,
            "defenders_beaten": 40,
            "clean_breaks": 10,
            "offloads": 15,
            "passes": 600,
            "handling_errors": 20,
            "tackles_made": 1200,
            "tackle_success_percent": 92.5,
            "turnovers_won": 125,
            "turnovers_conceded": 35,
            "lineouts_won": 28,
            "lineouts_stolen": 6,
            "scrums_won": 0,
            "scrums_lost": 0,
            "rucks_completed": 820,
            "ruck_success_percent": 91.0,
            "pick_and_go_meters": 35,
            "tries_saved": 6,
            "tries_assisted": 4,
            "total_appearances_club": 180,
            "total_points_club": 80,
            "club_championships_won": 2,
            "international_rugby_championships": 1,
            "world_cup_titles": 0,
            "international_player_of_year_awards": 1,
            "man_of_the_match_awards": 10,
            "red_cards": 0,
            "yellow_cards": 5,
            "captained_matches": 35,
            "match_winning_kicks": 0,
            "average_kick_distance": 0,
            "career_length_years": 10
        },
        {
            "player_name": "Francois Pienaar",
            "position": "Flanker",
            "test_caps": 29,
            "total_points_scored": 15,
            "tries_scored": 3,
            "conversions": 0,
            "penalty_goals": 0,
            "drop_goals": 0,
            "total_meters_carried": 420,
            "defenders_beaten": 18,
            "clean_breaks": 5,
            "offloads": 10,
            "passes": 340,
            "handling_errors": 12,
            "tackles_made": 280,
            "tackle_success_percent": 88.0,
            "turnovers_won": 30,
            "turnovers_conceded": 10,
            "lineouts_won": 15,
            "lineouts_stolen": 2,
            "scrums_won": 0,
            "scrums_lost": 0,
            "rucks_completed": 260,
            "ruck_success_percent": 88.5,
            "pick_and_go_meters": 20,
            "tries_saved": 4,
            "tries_assisted": 2,
            "total_appearances_club": 90,
            "total_points_club": 35,
            "club_championships_won": 2,
            "international_rugby_championships": 0,
            "world_cup_titles": 1,
            "international_player_of_year_awards": 0,
            "man_of_the_match_awards": 2,
            "red_cards": 0,
            "yellow_cards": 1,
            "captained_matches": 29,
            "match_winning_kicks": 0,
            "average_kick_distance": 0,
            "career_length_years": 5
        },
        {
            "player_name": "Percy Montgomery",
            "position": "Fullback",
            "test_caps": 102,
            "total_points_scored": 893,
            "tries_scored": 25,
            "conversions": 153,
            "penalty_goals": 148,
            "drop_goals": 2,
            "total_meters_carried": 3100,
            "defenders_beaten": 100,
            "clean_breaks": 55,
            "offloads": 30,
            "passes": 780,
            "handling_errors": 36,
            "tackles_made": 500,
            "tackle_success_percent": 82.5,
            "turnovers_won": 25,
            "turnovers_conceded": 38,
            "lineouts_won": 4,
            "lineouts_stolen": 0,
            "scrums_won": 0,
            "scrums_lost": 0,
            "rucks_completed": 480,
            "ruck_success_percent": 85.0,
            "pick_and_go_meters": 30,
            "tries_saved": 10,
            "tries_assisted": 20,
            "total_appearances_club": 160,
            "total_points_club": 540,
            "club_championships_won": 3,
            "international_rugby_championships": 2,
            "world_cup_titles": 1,
            "international_player_of_year_awards": 0,
            "man_of_the_match_awards": 8,
            "red_cards": 0,
            "yellow_cards": 3,
            "captained_matches": 4,
            "match_winning_kicks": 5,
            "average_kick_distance": 48,
            "career_length_years": 12
        },
        {
            "player_name": "Ronan O'Gara",
            "position": "Fly-Half",
            "test_caps": 128,
            "total_points_scored": 1083,
            "tries_scored": 16,
            "conversions": 176,
            "penalty_goals": 159,
            "drop_goals": 15,
            "total_meters_carried": 1450,
            "defenders_beaten": 44,
            "clean_breaks": 16,
            "offloads": 22,
            "passes": 2100,
            "handling_errors": 38,
            "tackles_made": 420,
            "tackle_success_percent": 78.0,
            "turnovers_won": 20,
            "turnovers_conceded": 65,
            "lineouts_won": 0,
            "lineouts_stolen": 0,
            "scrums_won": 0,
            "scrums_lost": 0,
            "rucks_completed": 600,
            "ruck_success_percent": 84.0,
            "pick_and_go_meters": 20,
            "tries_saved": 5,
            "tries_assisted": 18,
            "total_appearances_club": 230,
            "total_points_club": 1500,
            "club_championships_won": 3,
            "international_rugby_championships": 2,
            "world_cup_titles": 0,
            "international_player_of_year_awards": 0,
            "man_of_the_match_awards": 10,
            "red_cards": 0,
            "yellow_cards": 5,
            "captained_matches": 3,
            "match_winning_kicks": 12,
            "average_kick_distance": 42,
            "career_length_years": 13
        },
        {
            "player_name": "John Smit",
            "position": "Hooker",
            "test_caps": 111,
            "total_points_scored": 50,
            "tries_scored": 9,
            "conversions": 0,
            "penalty_goals": 0,
            "drop_goals": 0,
            "total_meters_carried": 900,
            "defenders_beaten": 35,
            "clean_breaks": 10,
            "offloads": 18,
            "passes": 700,
            "handling_errors": 30,
            "tackles_made": 1100,
            "tackle_success_percent": 88.5,
            "turnovers_won": 75,
            "turnovers_conceded": 35,
            "lineouts_won": 28,
            "lineouts_stolen": 7,
            "scrums_won": 0,
            "scrums_lost": 0,
            "rucks_completed": 750,
            "ruck_success_percent": 90.0,
            "pick_and_go_meters": 25,
            "tries_saved": 3,
            "tries_assisted": 6,
            "total_appearances_club": 180,
            "total_points_club": 90,
            "club_championships_won": 4,
            "international_rugby_championships": 3,
            "world_cup_titles": 1,
            "international_player_of_year_awards": 0,
            "man_of_the_match_awards": 8,
            "red_cards": 0,
            "yellow_cards": 4,
            "captained_matches": 83,
            "match_winning_kicks": 0,
            "average_kick_distance": 0,
            "career_length_years": 12
        },
        {
            "player_name": "Jean de Villiers",
            "position": "Centre",
            "test_caps": 109,
            "total_points_scored": 135,
            "tries_scored": 27,
            "conversions": 0,
            "penalty_goals": 0,
            "drop_goals": 0,
            "total_meters_carried": 2900,
            "defenders_beaten": 110,
            "clean_breaks": 60,
            "offloads": 50,
            "passes": 1400,
            "handling_errors": 40,
            "tackles_made": 780,
            "tackle_success_percent": 85.0,
            "turnovers_won": 70,
            "turnovers_conceded": 50,
            "lineouts_won": 10,
            "lineouts_stolen": 2,
            "scrums_won": 0,
            "scrums_lost": 0,
            "rucks_completed": 900,
            "ruck_success_percent": 88.0,
            "pick_and_go_meters": 50,
            "tries_saved": 7,
            "tries_assisted": 20,
            "total_appearances_club": 220,
            "total_points_club": 290,
            "club_championships_won": 3,
            "international_rugby_championships": 3,
            "world_cup_titles": 1,
            "international_player_of_year_awards": 0,
            "man_of_the_match_awards": 10,
            "red_cards": 0,
            "yellow_cards": 4,
            "captained_matches": 37,
            "match_winning_kicks": 0,
            "average_kick_distance": 0,
            "career_length_years": 13
        },
        {
            "player_name": "George Smith",
            "position": "Flanker",
            "test_caps": 111,
            "total_points_scored": 75,
            "tries_scored": 15,
            "conversions": 0,
            "penalty_goals": 0,
            "drop_goals": 0,
            "total_meters_carried": 1700,
            "defenders_beaten": 90,
            "clean_breaks": 35,
            "offloads": 65,
            "passes": 950,
            "handling_errors": 38,
            "tackles_made": 1400,
            "tackle_success_percent": 89.5,
            "turnovers_won": 180,
            "turnovers_conceded": 55,
            "lineouts_won": 40,
            "lineouts_stolen": 10,
            "scrums_won": 0,
            "scrums_lost": 0,
            "rucks_completed": 980,
            "ruck_success_percent": 90.0,
            "pick_and_go_meters": 40,
            "tries_saved": 8,
            "tries_assisted": 9,
            "total_appearances_club": 250,
            "total_points_club": 120,
            "club_championships_won": 3,
            "international_rugby_championships": 2,
            "world_cup_titles": 0,
            "international_player_of_year_awards": 1,
            "man_of_the_match_awards": 15,
            "red_cards": 0,
            "yellow_cards": 6,
            "captained_matches": 7,
            "match_winning_kicks": 0,
            "average_kick_distance": 0,
            "career_length_years": 15
        },
        {
            "player_name": "Stirling Mortlock",
            "position": "Centre",
            "test_caps": 80,
            "total_points_scored": 489,
            "tries_scored": 29,
            "conversions": 37,
            "penalty_goals": 51,
            "drop_goals": 2,
            "total_meters_carried": 2300,
            "defenders_beaten": 120,
            "clean_breaks": 65,
            "offloads": 30,
            "passes": 640,
            "handling_errors": 34,
            "tackles_made": 520,
            "tackle_success_percent": 84.0,
            "turnovers_won": 40,
            "turnovers_conceded": 50,
            "lineouts_won": 5,
            "lineouts_stolen": 0,
            "scrums_won": 0,
            "scrums_lost": 0,
            "rucks_completed": 490,
            "ruck_success_percent": 85.0,
            "pick_and_go_meters": 45,
            "tries_saved": 4,
            "tries_assisted": 15,
            "total_appearances_club": 170,
            "total_points_club": 860,
            "club_championships_won": 2,
            "international_rugby_championships": 2,
            "world_cup_titles": 0,
            "international_player_of_year_awards": 0,
            "man_of_the_match_awards": 10,
            "red_cards": 0,
            "yellow_cards": 4,
            "captained_matches": 20,
            "match_winning_kicks": 5,
            "average_kick_distance": 40,
            "career_length_years": 11
        },
        {
            "player_name": "Tana Umaga",
            "position": "Centre",
            "test_caps": 74,
            "total_points_scored": 180,
            "tries_scored": 36,
            "conversions": 0,
            "penalty_goals": 0,
            "drop_goals": 0,
            "total_meters_carried": 2900,
            "defenders_beaten": 130,
            "clean_breaks": 70,
            "offloads": 50,
            "passes": 820,
            "handling_errors": 28,
            "tackles_made": 510,
            "tackle_success_percent": 86.0,
            "turnovers_won": 60,
            "turnovers_conceded": 45,
            "lineouts_won": 6,
            "lineouts_stolen": 1,
            "scrums_won": 0,
            "scrums_lost": 0,
            "rucks_completed": 520,
            "ruck_success_percent": 88.0,
            "pick_and_go_meters": 45,
            "tries_saved": 8,
            "tries_assisted": 18,
            "total_appearances_club": 160,
            "total_points_club": 310,
            "club_championships_won": 3,
            "international_rugby_championships": 4,
            "world_cup_titles": 0,
            "international_player_of_year_awards": 0,
            "man_of_the_match_awards": 11,
            "red_cards": 0,
            "yellow_cards": 2,
            "captained_matches": 21,
            "match_winning_kicks": 0,
            "average_kick_distance": 0,
            "career_length_years": 10
        }
    ]

    # We've listed 30 players with ~40 stats each. If you see fewer than 30, add more accordingly.

    # Write out to CSV
    with open(filename, mode="w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=headers)
        writer.writeheader()
        for pdata in players_data:
            # Ensure every header field is present; if missing, fill with a default
            for h in headers:
                if h not in pdata:
                    pdata[h] = 0
            writer.writerow(pdata)

if __name__ == "__main__":
    create_rugby_dataset()
    print("rugby_dataset.csv has been created with 30 players, each containing 40+ stats.")
